Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-12, with the labels that each got.

#5505 Design System Storybook: Typography theming naming updates
  assets/src/design-system/components/button/index.js
  assets/src/design-system/components/typography/text/index.js
  assets/src/design-system/theme/typography.js
Labels: Group: Design System, Pod: Pea, cla: yes

#5497 Design System: Banner font size updates
  assets/src/design-system/components/banner/index.js
Labels: Group: Design System, Pod: Pea, cla: yes

#5048 Editor: support for custom meta boxes
  assets/src/dashboard/style.css
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/layout/layout.js
  assets/src/edit-story/app/story/effects/test/useSaveMetaBoxes.js
  assets/src/edit-story/app/story/effects/useSaveMetaBoxes.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/components/header/buttons/update.js
  assets/src/edit-story/integrations/wordpress/components/metaBoxes/index.js
  assets/src/edit-story/integrations/wordpress/components/metaBoxes/metaBoxesArea.js
  assets/src/edit-story/style.css
  includes/Database_Upgrader.php
  includes/Experiments.php
  includes/Meta_Boxes.php
  includes/Plugin.php
  includes/Story_Post_Type.php
  includes/namespace.php
  includes/templates/admin/dashboard.php
  includes/templates/admin/edit-story.php
  includes/templates/admin/error-no-js.php
  includes/uninstall.php
  phpcs.xml.dist
  tests/e2e/config/bootstrap.js
  tests/e2e/plugins/demo.php
  tests/e2e/plugins/web-stories-meta-box.php
  tests/e2e/specs/dashboard/noJS.js
  tests/e2e/specs/editor/metaBoxes.js
  tests/e2e/specs/editor/noJS.js
  tests/phpunit/tests/Meta_Boxes.php
  tests/phpunit/tests/REST_API/Embed_Controller.php
  tests/phpunit/tests/REST_API/Link_Controller.php
  tests/phpunit/tests/REST_API/Status_Check_Controller.php
  tests/phpunit/tests/REST_API/Stories_Autosaves_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5510 Blocks: React isSecondary prop warning for DOM element
  tests/e2e/config/bootstrap.js
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, WP 5.3, cla: yes

#5506 Embed block previewing not working WordPress 5.3
  assets/src/story-embed-block/block/edit.css
  assets/src/story-embed-block/block/edit.js
  assets/src/story-embed-block/block/embedPlaceholder.js
  package.json
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Bug, WP 5.3, cla: yes

#5496 Embed block missing component ToolbarGroup in WP 5.3
  assets/src/story-embed-block/block/embedControls.js
Labels: Group: Blocks, Pod: WP & Infra, Type: Bug, WP 5.3, cla: yes

#5417 Pre-Publish: Update text strings for links, images, and videos.
  assets/src/edit-story/app/prepublish/constants.js
  assets/src/edit-story/app/prepublish/warning/accessibility.js
  assets/src/edit-story/app/prepublish/warning/test/accessibility.js
Labels: Group: Pre-Publish Panel, Group: Workspace, Type: Bug, cla: yes

#5415 Update UI for In-Use Fonts for Text Sets
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/panes/text/textSets/textSets.js
Labels: Elements: Text, Group: Workspace, Type: Bug, cla: yes

#5375 Updated advanced dropdown search behavior
  assets/src/edit-story/components/form/advancedDropDown/dropDown.js
  assets/src/edit-story/components/form/advancedDropDown/list/list.js
  assets/src/edit-story/components/form/advancedDropDown/test/dropDown.js
  assets/src/edit-story/components/form/advancedDropDown/utils.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/karma/inspectorTabs.karma.js
  assets/src/edit-story/components/panels/karma/textStyle.karma.js
  assets/src/edit-story/components/panels/textStyle/fontPicker.js
  assets/src/edit-story/karma/textStyle.cuj.karma.js
  includes/data/stories/demo.json
Labels: Pod: Prometheus, cla: yes

#5551 Improve border-radius preview
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/elementBorder/utils.js
  assets/src/edit-story/elements/media/display.js
  assets/src/edit-story/elements/media/editCropMoveable.js
  assets/src/edit-story/elements/media/editPanMoveable.js
  assets/src/edit-story/elements/shape/display.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/display.js
Labels: cla: yes

#5553 E2E Tests: Make the ignore more broad
  tests/e2e/config/bootstrap.js
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#5507 Fix demo content not working in WordPress 5.3
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/story/effects/test/useLoadStory.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/karma/fixture/fixture.js
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/templates/admin/edit-story.php
Labels: Group: WordPress, Group: Workspace, Pod: WP & Infra, Type: Bug, cla: yes

#5352 PHP: Stories class
  includes/Interfaces/Renderer.php
  includes/Model/Story.php
  includes/Stories_Renderer/Carousel_Renderer.php
  includes/Stories_Renderer/Generic_Renderer.php
  includes/Stories_Renderer/Renderer.php
  includes/Story_Query.php
  includes/assets/stories.css
  tests/phpunit/includes/Test_Renderer.php
  tests/phpunit/tests/Stories_Renderer/Carousel_Renderer.php
  tests/phpunit/tests/Stories_Renderer/Generic_Renderer.php
  tests/phpunit/tests/Stories_Renderer/Renderer.php
  tests/phpunit/tests/Story_Query.php
Labels: cla: yes

#5550 Fix embed block tests on WordPress 5.3
  .github/workflows/continuous-integration-e2e.yml
  tests/e2e/specs/wordpress/embedBlock.js
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Infrastructure, cla: yes

#5566 Animations: Page Duplication Support
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/elements/test/index.js
Labels: Group: Animations, Pod: Pea, Type: Bug, cla: yes

#5555 Pre-publish: Remove duplicate low image resolution check
  assets/src/edit-story/app/prepublish/warning/index.js
Labels: cla: yes

#5527 Animation Panel: Active "Scale" animations should display "Scale" as active dropdown value
  assets/src/animation/constants.js
Labels: Group: Animations, Pod: Pea, Type: Bug, cla: yes

#5516 Make video poster generation more robust
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
Labels: Elements: Video, Group: WordPress, Type: Bug, cla: yes

#5508 Alert icon should always have 100% opacity
  assets/src/edit-story/components/tabview/index.js
Labels: cla: yes

#5360 Text Style: Reset font weight to regular on font family change
  assets/src/edit-story/components/panels/karma/textStyle.karma.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/components/panels/textStyle/fontPicker.js
  assets/src/edit-story/components/panels/textStyle/getClosestFontWeight.js
  assets/src/edit-story/components/panels/textStyle/test/getClosestFontWeight.js
  assets/src/edit-story/components/panels/textStyle/useRichTextFormatting.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
Labels: cla: yes

#5333 Use dialog to warn users about lack of upload permissions
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/local/missingUploadPermissionDialog.js
  assets/src/edit-story/components/library/panes/media/local/stories/missingUploadPermissionDialog.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
Labels: Group: Media, Type: Enhancement, cla: yes

#5563 Enable browser spell checking
  assets/src/edit-story/components/richText/editor.js
Labels: Elements: Text, Type: Enhancement, cla: yes

#5539 Prepublish checklist: remove text contrast warning for now
  assets/src/edit-story/app/prepublish/warning/index.js
Labels: Group: Pre-Publish Panel, Pod: Pea, Type: Enhancement, cla: yes

#5557 Prepublish Checklist: Story Excerpt/Description warning text update
  assets/src/edit-story/app/prepublish/constants.js
  assets/src/edit-story/app/prepublish/test/__snapshots__/getPrepublishErrors.js.snap
  assets/src/edit-story/components/inspector/document/excerpt.js
  assets/src/edit-story/components/inspector/document/test/excerpt.js
Labels: Bug Bash: 1.2, Group: Pre-Publish Panel, Pod: Pea, Type: Enhancement, cla: yes

#5518 Fixed autosave to run while user is working
  assets/src/edit-story/components/autoSaveHandler/index.js
  assets/src/edit-story/components/autoSaveHandler/test/autoSaveHandler.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#5305 Dashboard: Organize error message static text
  assets/src/dashboard/app/api/test/useSettingsApi.js
  assets/src/dashboard/app/api/useMediaApi.js
  assets/src/dashboard/app/api/useSettingsApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/reducer/test/media.js
  assets/src/dashboard/app/reducer/test/settings.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/reducer/test/templates.js
  assets/src/dashboard/app/textContent/index.js
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/templateDetails/index.js
Labels: Group: Dashboard, Pod: Pea, Type: Code Quality, cla: yes

#5570 Animation Panel: Effect dropdown a11y
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/effectChooserDropdown.js
  assets/src/edit-story/components/panels/animation/effectPanel.js
  assets/src/edit-story/components/panels/animation/panel.js
  assets/src/edit-story/components/panels/animation/utils/isNullOrUndefinedOrEmptyString.js
Labels: Accessibility, Bug Bash: 1.2, Group: Animations, P0, Pod: Pea, cla: yes

#5594 Animation Panel: Direction picker keyboard functionality
  assets/src/edit-story/components/panels/animation/directionRadioInput.js
Labels: Accessibility, Group: Animations, Pod: Pea, cla: yes

#5549 Pre-publish Checklist: Panel width causing content shift
  assets/src/edit-story/components/inspector/prepublish/checklistTab.js
Labels: Group: Pre-Publish Panel, Pod: Pea, cla: yes

#5592 Animations: Update page advancement calculation
  assets/src/edit-story/output/page.js
Labels: cla: yes

#5537 Animation: Play animation on input change
  assets/src/edit-story/components/panels/animation/panel.js
  assets/src/edit-story/components/panels/karma/animation.karma.js
Labels: Group: Animations, Pod: Pea, cla: yes

#5586 Animation: Update effect chooser active state style & persist between selections
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/effectChooserDropdown.js
  assets/src/edit-story/components/panels/animation/panel.js
  assets/src/edit-story/components/panels/karma/animation.karma.js
Labels: cla: yes

#5574 Animation: Update the UI of the Scale Animation to use a visual direction picker
  assets/src/animation/constants.js
  assets/src/animation/effects/zoom/animationProps.js
  assets/src/animation/effects/zoom/index.js
  assets/src/animation/effects/zoom/stories/index.js
  assets/src/edit-story/components/panels/animation/directionRadioInput.js
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/effectInput.js
  assets/src/edit-story/components/panels/animation/stories/directionRadioInput.js
  assets/src/edit-story/components/panels/animation/test/directionRadioInput.js
  assets/src/edit-story/components/panels/animation/test/effectChooser.js
Labels: Group: Animations, cla: yes

#5587 Animation: Update Pulse Preset
  assets/src/animation/effects/pulse/animationProps.js
  assets/src/animation/effects/pulse/index.js
  assets/src/animation/parts/pulse/index.js
  assets/src/animation/parts/pulse/test/index.js
Labels: Group: Animations, Pod: Pea, Type: Enhancement, cla: yes

#5548 Pre-Publish Checklist: Add indicator for pre-publish checklist warnings
  assets/src/edit-story/components/header/buttons/publish.js
  assets/src/edit-story/components/header/buttons/styles.js
  assets/src/edit-story/components/header/buttons/update.js
Labels: cla: yes

#5542 Remove inner and center border
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/elementBorder/index.js
  assets/src/edit-story/components/elementBorder/utils.js
  assets/src/edit-story/components/panels/border/panel.js
  assets/src/edit-story/components/panels/border/position.js
  assets/src/edit-story/components/panels/border/shared.js
  assets/src/edit-story/components/panels/karma/border.karma.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/media/display.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/editCropMoveable.js
  assets/src/edit-story/elements/media/editPanMoveable.js
  assets/src/edit-story/elements/media/imageDisplay.js
  assets/src/edit-story/elements/shape/display.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/test/page.js
Labels: cla: yes

#5604 Fix deprecation warning for embed block on WordPress 5.6
  assets/src/story-embed-block/block/embedControls.js
Labels: Group: Blocks, Group: WordPress, P0, Pod: WP & Infra, Type: Bug, Type: Infrastructure, cla: yes

#5605 Run PHP unit tests against WordPress 5.6
  .github/workflows/continuous-integration-unit-php.yml
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5571 E2E Tests: Reduce percy snapshot flakiness
  tests/e2e/specs/dashboard/integrations/sitekit.js
  tests/e2e/specs/editor/media/insertMovVideo.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5572 Improve generated video poster file name
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
Labels: Group: Media, Type: Enhancement, cla: yes

#5573 Poster generation: Set video as the poster's parent
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  includes/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5602 Animation: Update BG Zoom
  assets/src/animation/effects/backgroundZoom/animationProps.js
  assets/src/animation/effects/backgroundZoom/index.js
  assets/src/edit-story/components/panels/animation/directionRadioInput.js
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/effectPanel.js
  assets/src/edit-story/components/panels/animation/panel.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#5603 Animation: Updated Rotation Effect Inputs to Match Latest Designs
  assets/src/animation/effects/rotateIn/animationProps.js
  assets/src/animation/effects/rotateIn/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#5595 Remove duplicate video element size on page check
  assets/src/edit-story/app/prepublish/guidance/index.js
  assets/src/edit-story/app/prepublish/guidance/media.js
Labels: Group: Pre-Publish Panel, Pod: Pea, Type: Enhancement, cla: yes

#5598 Animations: Add Tooltip to Disabled Options
  assets/src/edit-story/components/panels/animation/directionRadioInput.js
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/effectChooserDropdown.js
  assets/src/edit-story/components/panels/animation/effectInput.js
  assets/src/edit-story/components/panels/animation/effectPanel.js
  assets/src/edit-story/components/panels/animation/panel.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#5332 Video: Combine "title" and "assistive text" fields
  assets/src/edit-story/app/prepublish/constants.js
  assets/src/edit-story/app/prepublish/warning/accessibility.js
  assets/src/edit-story/app/prepublish/warning/index.js
  assets/src/edit-story/app/prepublish/warning/test/accessibility.js
  assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js
  assets/src/edit-story/components/library/test/mediaEditDialog.js
  assets/src/edit-story/components/panels/test/videoAccessibility.js
  assets/src/edit-story/components/panels/videoAccessibility.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/output.js
Labels: Accessibility, Elements: Video, Type: Bug, cla: yes

#5362 Story progress bar not aligned with top of content
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/utils/styles.js
Labels: AMP Output, Type: Enhancement, cla: yes

#5561 Embed block: fix embedding stories with plain permalinks
  assets/src/story-embed-block/block/edit.js
  includes/REST_API/Embed_Controller.php
  phpcs.xml.dist
  tests/phpstan/stubs/wpdotcom.php
  tests/phpunit/tests/Discovery.php
  tests/phpunit/tests/REST_API/Embed_Controller.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5618 Fix popup location on RTL layouts
  assets/src/edit-story/components/popup/index.js
Labels: Group: Animations, Group: Design Panel, Group: Fonts, Type: Bug, cla: yes

#5606 CI: Run PHP unit tests on PHP 8
  .github/workflows/continuous-integration-unit-php.yml
  composer.json
  composer.lock
  patches/composer.patch
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5622 AMP: Update AMP plugin to version 2.0.8
  composer.json
  composer.lock
  web-stories.php
Labels: AMP Output, Dependencies, Pod: WP & Infra, Type: Infrastructure, cla: yes

#5584 Animations: Enable Animations.
  .storybook/preview.js
  assets/src/animation/components/provider.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/karma/animation.karma.js
  assets/src/edit-story/output/page.js
  includes/Experiments.php
  tests/phpunit/tests/Experiments.php
Labels: Group: Animations, Pod: Pea, Type: Enhancement, cla: yes

#5585 Pre-Publish Checklist: Enable Pre-Publish Checklist.
  .storybook/stories/playground/index.js
  assets/src/edit-story/components/header/buttons/publish.js
  assets/src/edit-story/components/header/karma/publish.karma.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
  includes/Experiments.php
Labels: Group: Pre-Publish Panel, Type: Enhancement, cla: yes

#5642 Bump version to 1.2 and update readme.txt
  package-lock.json
  readme.txt
  web-stories.php
Labels: cla: yes

#5667 Fix database version
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug

#5635 Video posters: use taxonomy instead of post meta
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/uploader/useUploader.js
  includes/Database_Upgrader.php
  includes/Media.php
  includes/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/Database_Upgrader.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5636 Media: Only run `filter_poster_attachments` for the editor
  includes/Media.php
  includes/REST_API/Stories_Media_Controller.php
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5503 Animation Panel: Give dropdown context with label
  assets/src/edit-story/components/panels/animation/effectChooser.js
Labels: Bug Bash: 1.2, Group: Animations, Pod: Pea, Type: Bug, cla: yes

#5637 Use taxonomy query instead of meta query.
  includes/Media.php
  includes/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/Media.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5672 Design System: Buttons updated to match latest figma colors
  assets/src/design-system/components/button/index.js
  assets/src/design-system/theme/colors.js
Labels: Group: Design System, Pod: Pea, cla: yes

#5680 Embed block: story without title requires two clicks to embed
  assets/src/story-embed-block/block/edit.js
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5597 Karma: ensure Google Fonts are loaded for tests and snapshots
  assets/src/dashboard/karma/fixture.js
  assets/src/edit-story/karma/fixture/fixture.js
  karma-dashboard.config.cjs
  karma-edit-story.config.cjs
  karma/fixture/client_with_context.html
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#5640 Remove web_stories_is_poster attachment meta
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  includes/Database_Upgrader.php
  includes/Media.php
  tests/phpunit/tests/Database_Upgrader.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5678 Update UI for Border and Corner Radius panels
  assets/src/edit-story/components/panels/border/borderWidth.js
  assets/src/edit-story/components/panels/borderRadius/panel.js
  assets/src/edit-story/components/panels/karma/border.karma.js
  assets/src/edit-story/components/panels/karma/borderRadius.karma.js
  assets/src/edit-story/icons/border_lock_line.svg
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/union.svg
  assets/src/edit-story/karma/fixture/containers/designPanel/border.js
  assets/src/edit-story/karma/fixture/containers/designPanel/borderRadius.js
Labels: Group: Borders, Type: Enhancement, cla: yes

#5671 Bug: Fix Close Toggle Action for Animation Drop Down
  assets/src/edit-story/components/panels/animation/effectChooserDropdown.js
Labels: Group: Animations, Type: Bug, cla: yes

#5641 Animation: Effect Chooser Left/Right Arrow Navigation Support
  assets/src/edit-story/components/panels/animation/effectChooser.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#5682 Frontend: HTML markers not always replaced
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: AMP Output, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5673 Added status check dialog
  assets/src/edit-story/components/statusCheck/statusCheck.js
  assets/src/edit-story/components/statusCheck/statusCheckFailed.js
  assets/src/edit-story/components/statusCheck/stories/statusCheckFailed.js
  assets/src/edit-story/components/statusCheck/test/statusCheck.js
  includes/Experiments.php
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/editor/statusCheck.js
Labels: Group: Workspace, Pod: Prometheus, Type: Enhancement, cla: yes

#5693 E2E Tests: fix status check test
  tests/e2e/specs/editor/statusCheck.js
Labels: Group: Status Check, Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#5615 Animation Panel: Effect direction input indexed for clockwise keyboard navigation
  assets/src/edit-story/components/panels/animation/directionRadioInput.js
Labels: Accessibility, Group: Animations, Pod: Pea, Type: Enhancement, cla: yes

#5512 Use Moveable in Library for Media
  assets/src/edit-story/app/layout/layout.js
  assets/src/edit-story/components/canvas/karma/backgroundCopyPaste.karma.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/canvas/utils/useSnapping.js
  assets/src/edit-story/components/library/panes/media/common/innerElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/shared/libraryMoveable.js
  assets/src/edit-story/components/library/test/mediaElement.js
  assets/src/edit-story/components/overlay/withOverlay.js
  assets/src/edit-story/components/panels/design/textStyle/karma/textStyle.other.karma.js
  assets/src/edit-story/components/workspace/index.js
  assets/src/edit-story/elements/video/karma/autoplay.karma.js
Labels: Type: Enhancement, cla: yes

#5712 E2E test: Improve Story From Template screenshot
  tests/e2e/specs/dashboard/templates/useTemplate.js
Labels: cla: yes

#5632 Animations: Fix animation inheriting parent transform
  assets/src/animation/effects/drop/index.js
  assets/src/animation/effects/flyIn/index.js
  assets/src/animation/effects/rotateIn/index.js
  assets/src/animation/effects/twirlIn/index.js
  assets/src/animation/effects/whooshIn/index.js
  assets/src/animation/parts/move/index.js
  assets/src/animation/parts/spin/index.js
  assets/src/animation/utils/getGlobalSpace.js
  assets/src/animation/utils/index.js
  assets/src/animation/utils/test/getGlobalSpace.js
Labels: Group: Animations, Pod: Pea, Type: Bug, cla: yes

#5674 Bug: Persist Delay and Duration between Effect Chooser Direction Changes
  assets/src/edit-story/components/panels/design/animation/animation.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#5317 Blocks: Usage difficulties due to theme styling
  assets/src/story-embed-block/block/edit.css
  includes/assets/embed.css
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5717 Update storybook packages
  .storybook/main.cjs
  package-lock.json
  package.json
Labels: Dependencies, JavaScript, cla: yes

#5676 Create "Release Plugin" issue template
  .github/ISSUE_TEMPLATE/release-plugin.md
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#5721 Fix editor shrinking unexpectedly when scrolling Media
  assets/src/edit-story/components/library/panes/shared/libraryMoveable.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#5725 Prepare 1.2.1 release
  includes/Database_Upgrader.php
  includes/Media.php
  readme.txt
  web-stories.php
Labels: Release, Skip Changelog, cla: yes

#5726 Fix CDN URL for stable releases
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5614 Use Moveable in Shapes library
  assets/src/edit-story/components/canvas/canvasElementDropzone.js
  assets/src/edit-story/components/library/karma/shapes/shapes.karma.js
  assets/src/edit-story/components/library/panes/shapes/shapePreview.js
  assets/src/edit-story/components/library/panes/shared/libraryMoveable.js
  assets/src/edit-story/components/library/test/shapes/shapePreview.js
Labels: Elements: Shape, Type: Enhancement, cla: yes

#5729 CI: Cancel previous workflows
  .github/workflows/cancel-previous-workflows.yml
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5732 Design System: DropDown Base Structure
  assets/src/design-system/components/dropDown/index.js
  assets/src/design-system/components/dropDown/stories/index.js
  assets/src/design-system/components/dropDown/stories/sampleData.js
  assets/src/design-system/components/dropDown/test/useDropDown.js
  assets/src/design-system/components/dropDown/test/utils.js
  assets/src/design-system/components/dropDown/types.js
  assets/src/design-system/components/dropDown/useDropDown.js
  assets/src/design-system/components/dropDown/utils.js
  assets/src/design-system/storybookUtils/darkThemeProvider.js
  assets/src/design-system/storybookUtils/index.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#5733 Design System: DropDown Select Button
  assets/src/design-system/components/dropDown/index.js
  assets/src/design-system/components/dropDown/select/index.js
  assets/src/design-system/components/dropDown/test/dropDown.js
  assets/src/design-system/components/dropDown/test/select.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#5751 CI: Do not run Percy for draft PRs
  .github/workflows/continuous-integration-e2e.yml
  .github/workflows/continuous-integration-karma-edit-story.yml
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#5716 Update WP npm packages
  .github/workflows/continuous-integration-e2e.yml
  assets/src/edit-story/components/statusCheck/statusCheckFailed.js
  package-lock.json
  package.json
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/editor/__snapshots__/publishingFlow.js.snap
  tests/e2e/specs/editor/publishingFlow.js
  tests/e2e/specs/wordpress/embedBlock.js
  tests/e2e/utils/index.js
  tests/e2e/utils/insertBlock.js
Labels: Dependencies, JavaScript, cla: yes

#5736 Karma: Add Copy and Paste tests
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  assets/src/edit-story/components/panels/design/animation/animation.js
  assets/src/edit-story/karma/copyAndPaste.cuj.karma.js
Labels: Group: Copy/Paste, Skip Changelog, Type: Infrastructure, cla: yes

#5599 Design System Storybook: Tooltip follow up
  assets/src/design-system/components/tooltip/stories/index.js
Labels: Group: Design System, Pod: Pea, Skip Changelog, Type: Enhancement, cla: yes

#5734 Design System: DropDown Keyboard Utils
  assets/src/design-system/components/keyboard/context.js
  assets/src/design-system/components/keyboard/index.js
  assets/src/design-system/components/keyboard/keys.js
  assets/src/design-system/components/keyboard/prettifyShortcut.js
  assets/src/design-system/components/keyboard/test/index.js
  assets/src/design-system/components/keyboard/test/prettifyShortcut.js
  assets/src/design-system/utils/context.js
  assets/src/design-system/utils/useBatchingCallback.js
Labels: Group: Design System, Pod: Pea, Skip Changelog, Type: Enhancement, cla: yes

#5766 AMP Optimization: Reduce debug noise
  includes/AMP/Optimization.php
  tests/phpunit/tests/AMP/Meta_Sanitizer.php
  tests/phpunit/tests/AMP/Optimization.php
  tests/phpunit/tests/AMP/Story_Sanitizer.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: AMP Output, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5782 Experiments: fix checks for experiments enabled by default
  includes/Experiments.php
  tests/phpunit/tests/Experiments.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5342 Design Panel: Improve accessibility for panel headers
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/panel/simplePanel.js
  assets/src/edit-story/components/panels/panel/test/simplePanel.js
  assets/src/edit-story/karma/fixture/containers/designPanel/textStyle.js
Labels: Accessibility, Group: Design Panel, cla: yes

#5697 Karma: Suppress useLayoutEffect warnings in tests
  assets/src/edit-story/output/utils/getStoryMarkup.js
  karma-dashboard.config.cjs
  karma-edit-story.config.cjs
  karma/fixture/init.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5701 Pre-Publish: Handle both resource and element alt texts for pre-publish check.
  assets/src/edit-story/app/prepublish/warning/accessibility.js
  assets/src/edit-story/app/prepublish/warning/test/accessibility.js
Labels: Group: Pre-Publish Panel, Type: Bug, cla: yes

#5773 E2E Tests: reduce number of Percy snapshots
  tests/e2e/specs/dashboard/dashboard.js
  tests/e2e/specs/dashboard/integrations/sitekit.js
  tests/e2e/specs/dashboard/noJS.js
  tests/e2e/specs/dashboard/templates/useTemplate.js
  tests/e2e/specs/editor/authorUser.js
  tests/e2e/specs/editor/editor.js
  tests/e2e/specs/editor/media/insertMediaFromDialog.js
  tests/e2e/specs/editor/media/insertMediaFromLibrary.js
  tests/e2e/specs/editor/media/insertMovVideo.js
  tests/e2e/specs/editor/media/insertWebMVideo.js
  tests/e2e/specs/editor/metaBoxes.js
  tests/e2e/specs/editor/noJS.js
  tests/e2e/specs/wordpress/adminMenu.js
  tests/e2e/specs/wordpress/getStartedStory.js
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#5738 Design System: Menu for DropDown
  assets/src/design-system/components/dropDown/constants.js
  assets/src/design-system/components/dropDown/index.js
  assets/src/design-system/components/dropDown/menu/components.js
  assets/src/design-system/components/dropDown/menu/defaultListItem.js
  assets/src/design-system/components/dropDown/menu/emptyList.js
  assets/src/design-system/components/dropDown/menu/groupLabel.js
  assets/src/design-system/components/dropDown/menu/index.js
  assets/src/design-system/components/dropDown/menu/list.js
  assets/src/design-system/components/dropDown/menu/listGroupings.js
  assets/src/design-system/components/dropDown/menu/useDropDownMenu.js
  assets/src/design-system/components/dropDown/select/index.js
  assets/src/design-system/components/dropDown/stories/index.js
  assets/src/design-system/components/dropDown/test/dropDown.js
  assets/src/design-system/components/dropDown/test/menu.js
  assets/src/design-system/components/dropDown/test/select.js
  assets/src/design-system/components/dropDown/test/useDropDownMenu.js
  assets/src/design-system/components/dropDown/test/utils.js
  assets/src/design-system/components/dropDown/utils.js
  assets/src/design-system/utils/isNullOrUndefinedOrEmptyString.js
  assets/src/design-system/utils/useFocusOut.js
Labels: Group: Design System, Pod: Pea, Skip Changelog, cla: yes

#5504 Design System Storybook: Banner responsive tweaks
  assets/src/design-system/components/banner/index.js
Labels: Group: Design System, Pod: Pea, cla: yes

#5783 Library: Remove Animations Pane
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/library/panes/animation/animation.svg
  assets/src/edit-story/components/library/panes/animation/animationIcon.js
  assets/src/edit-story/components/library/panes/animation/animationPane.js
  assets/src/edit-story/components/library/panes/animation/index.js
  assets/src/edit-story/components/library/panes/animation/paneId.js
  includes/Experiments.php
Labels: Group: Animations, Group: Library, Type: Code Quality, cla: yes

#5103 SVG: Implement initial server-side support
  bin/local-env/install-wordpress.sh
  composer.json
  composer.lock
  includes/Experiments.php
  includes/Plugin.php
  includes/SVG.php
  phpcs.xml.dist
  scoper.inc.php
  tests/e2e/assets/arrow.svg
  tests/e2e/assets/close.svg
  tests/e2e/assets/video-play.svg
  tests/e2e/specs/editor/media/svg.js
  tests/e2e/utils/index.js
  tests/e2e/utils/uploadFile.js
  tests/phpunit/data/add-invalid.svg
  tests/phpunit/data/add.svg
  tests/phpunit/data/animated.svg
  tests/phpunit/data/video-play.svg
  tests/phpunit/tests/SVG.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5765 Animations: Prevent malformed HTML output
  assets/src/animation/outputs/animationOutput.js
  includes/KSES.php
  tests/phpunit/tests/KSES.php
Labels: Group: Animations, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5809 Design System: DropDown a11y updates
  assets/src/design-system/components/dropDown/index.js
  assets/src/design-system/components/dropDown/menu/index.js
  assets/src/design-system/components/dropDown/menu/list.js
  assets/src/design-system/components/dropDown/menu/listGroupings.js
  assets/src/design-system/components/dropDown/select/index.js
  assets/src/design-system/components/dropDown/stories/index.js
  assets/src/design-system/components/dropDown/test/dropDown.js
  assets/src/design-system/components/dropDown/test/select.js
  assets/src/design-system/components/popup/index.js
Labels: Accessibility, Group: Design System, Pod: Pea, cla: yes

#5812 Design System: DropDown Minor Adjustments for Props
  assets/src/design-system/components/dropDown/index.js
  assets/src/design-system/components/dropDown/select/components.js
  assets/src/design-system/components/dropDown/stories/index.js
  assets/src/design-system/components/index.js
  assets/src/design-system/components/popup/index.js
Labels: Group: Dashboard, Group: Design System, Pod: Pea, Type: Code Quality, cla: yes
