Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-02, with the labels that each got.

#168 Explicitly add package to package.json
  package.json
Labels: cla: yes

#182 Refactors RangeInput and adds Storybook dark background
  .storybook/main.js
  assets/src/edit-story/components/button/stories/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/rangeInput/index.js
  assets/src/edit-story/components/rangeInput/stories/index.js
  assets/src/edit-story/elements/image/scalePanel.js
  package-lock.json
  package.json
Labels: cla: yes

#183 Upgrades react-moveable
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/movable/moveStyle.js
  package-lock.json
  package.json
Labels: cla: yes

#163 Begin adding some PHP tests
  includes/Fonts.php
  includes/REST_API/Fonts_Controller.php
  phpunit.xml.dist
  tests/phpunit/tests/Fonts.php
  tests/phpunit/tests/Media.php
  tests/phpunit/tests/REST_API/Fonts_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
Labels: Type: Infrastructure, cla: yes

#169 Remove unnecessary eslint-disable comments
  .eslintrc
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/utils/useDoubleClick.js
Labels: cla: yes

#181 Accurate colors/fonts on the design panel
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/inspector/inspectorTabs.js
  assets/src/edit-story/components/panels/panel/handle.js
  assets/src/edit-story/components/panels/panel/title.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/theme.js
  package-lock.json
  package.json
Labels: cla: yes

#199 Properly add API key as env var
  .github/workflows/update-google-fonts.yml
Labels: cla: yes

#213 Misc fixes: dedupe version calculation and avoid rendering page menu before the page is available
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/migration/dataVersion.js
  assets/src/edit-story/migration/index.js
  assets/src/edit-story/migration/migrate.js
Labels: cla: yes

#235 Remove pre-push hook
  package.json
Labels: cla: yes

#226 Shuffle dependencies around
  package-lock.json
  package.json
Labels: cla: yes

#195 Upload file hook
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/uploader/index.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
  assets/src/edit-story/utils/useUploadVideoFrame.js
  includes/Story_Post_Type.php
Labels: cla: yes

#243 Use finally everywhere.
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
  assets/src/edit-story/components/library/libraryProvider.js
Labels: cla: yes

#166 Add custom implementation of cleanForSlug function
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/utils/cleanForSlug.js
  assets/src/edit-story/utils/test/cleanForSlug.js
  package-lock.json
  package.json
Labels: cla: yes

#137 Save/output/preview templates with units and wrappers.
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/index.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
  assets/src/edit-story/components/transform/context.js
  assets/src/edit-story/components/transform/index.js
  assets/src/edit-story/components/transform/transformProvider.js
  assets/src/edit-story/components/transform/useTransform.js
  assets/src/edit-story/components/transform/useTransformHandler.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/image/output.js
  assets/src/edit-story/elements/image/preview.js
  assets/src/edit-story/elements/image/save.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/square/index.js
  assets/src/edit-story/elements/square/output.js
  assets/src/edit-story/elements/square/preview.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/preview.js
  assets/src/edit-story/elements/text/save.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/elements/video/preview.js
  assets/src/edit-story/elements/video/save.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/index.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/units/index.js
  assets/src/edit-story/utils/getPercentageFromPixels.js
  includes/templates/single-web-story.php
Labels: cla: yes

#249 Lint Markdown files
  .distignore
  .markdownlintignore
  .travis.yml
  README.md
  docs/getting-started.md
  package.json
Labels: Type: Enhancement, Type: Infrastructure, cla: yes

#245 Use eslint-plugin-header for license headers
  .eslintrc
  assets/src/edit-story/components/panels/background.js
  assets/src/edit-story/components/panels/videoPoster.js
  assets/src/edit-story/types.js
  assets/src/edit-story/units/dimensions.js
  assets/src/edit-story/units/index.js
  assets/src/edit-story/units/unitsProvider.js
  assets/src/edit-story/units/useUnits.js
  assets/src/edit-story/utils/getFirstFrameOfVideo.js
  assets/src/edit-story/utils/useResizeEffect.js
  assets/src/edit-story/utils/useUploadVideoFrame.js
  package-lock.json
  package.json
Labels: Type: Enhancement, cla: yes

#246 Prototype of clipping masks
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/mask.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/square/index.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/masks/.eslintrc
  assets/src/edit-story/masks/index.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/types.js
Labels: cla: yes

#210 Move media to be global state provider.
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/media/actions/useCompleteMedia.js
  assets/src/edit-story/app/media/actions/useLoadMedia.js
  assets/src/edit-story/app/media/actions/useReloadMedia.js
  assets/src/edit-story/app/media/actions/useResetMedia.js
  assets/src/edit-story/app/media/context.js
  assets/src/edit-story/app/media/index.js
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/useMedia.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/library/mediaLibrary.js
  assets/src/edit-story/utils/useUploadVideoFrame.js
Labels: cla: yes

#289 Add back missing dependency
  .eslintrc
  assets/src/edit-story/app/story/effects/useLoadStory.js
  package-lock.json
  package.json
Labels: Type: Bug, Type: Infrastructure, cla: yes

#288 Update build tooling deps and simplify stylelint config
  .stylelintrc
  package-lock.json
  package.json
Labels: Dependencies, Type: Infrastructure, cla: yes

#300 Actually leverage variable analysis sniffs
  includes/REST_API/Fonts_Controller.php
  phpcs.xml
Labels: PHP, Type: Infrastructure, cla: yes

#157 Various styling tweaks for storybook
  .storybook/stories/playground/index.js
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/library/tabs/index.js
  assets/src/edit-story/components/modal/index.js
  assets/src/edit-story/style.css
  assets/src/edit-story/theme.js
Labels: Type: Bug, Type: Task, cla: yes

#244 Use svgr for SVGs
  .distignore
  .svgo.yml
  assets/src/edit-story/components/button/icons/grid_view.svg
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/library/tabs/index.js
  assets/src/edit-story/components/library/tabs/links.svg
  assets/src/edit-story/components/library/tabs/media.svg
  assets/src/edit-story/components/library/tabs/shapes.svg
  assets/src/edit-story/components/library/tabs/text.svg
  assets/src/edit-story/components/panels/panel/title.js
  assets/src/edit-story/elements/background/index.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/square/index.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/video/index.js
  babel.config.js
  package-lock.json
  package.json
  webpack.config.js
Labels: Type: Enhancement, Type: Infrastructure, cla: yes

#302 Update storybook & husky dependencies
  package-lock.json
  package.json
Labels: Dependencies, cla: yes

#308 Change the remainder of backgroundElementId checks and fix deltaX movable
  assets/src/edit-story/app/story/useStoryReducer/reducers/arrangeElement.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/deleteElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
Labels: cla: yes

#314 Fix storybook webpack config
  .storybook/main.js
Labels: Type: Infrastructure, cla: yes

#315 Use regex for svgo’s currentColor replacement
  .svgo.yml
Labels: Type: Bug, Type: Infrastructure, cla: yes

#316 Use different indent size for PHP code
  .editorconfig
Labels: Type: Infrastructure, cla: yes

#330 Fix line breaks restore and keyboard shortcuts for text editor
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/output.js
Labels: cla: yes

#329 Adjust x/y of a cropped element
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/editCropMovable.js
  assets/src/edit-story/utils/calcRotatedResizeOffset.js
Labels: cla: yes

#281 Implement reorderable layers by mouse
  assets/src/edit-story/components/panels/layer/context.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/panels/layer/layerList.js
  assets/src/edit-story/components/panels/layer/panel.js
  assets/src/edit-story/components/panels/layer/provider.js
  assets/src/edit-story/components/panels/layer/separator.js
  assets/src/edit-story/components/panels/layer/useLayerReordering.js
  assets/src/edit-story/components/panels/layer/useLayerSelection.js
  assets/src/edit-story/components/panels/layer/useLayers.js
  package-lock.json
  package.json
Labels: cla: yes

#336 Update some dev dependencies
  package-lock.json
  package.json
Labels: Dependencies, JavaScript, cla: yes

#175 Drag and drop ( Media library )
  assets/src/edit-story/components/library/dropzone/icons/upload.svg
  assets/src/edit-story/components/library/dropzone/index.js
  assets/src/edit-story/components/library/mediaLibrary.js
  includes/Story_Post_Type.php
Labels: UX Needed, cla: yes

#340 Add imgbot config file
  .distignore
  .imgbotconfig
  .prettierrc
Labels: Type: Infrastructure, cla: yes

#341 Generate poster image only on creation of element
  assets/src/edit-story/app/media/actions/useUploadVideoFrame.js
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/utils/getFirstFrameOfVideo.js
  assets/src/edit-story/components/library/libraryContent.js
  assets/src/edit-story/components/library/mediaLibrary.js
  assets/src/edit-story/elements/video/display.js
Labels: cla: yes

#334 Run static analysis using PHPStan on CI
  .distignore
  .prettierrc
  .travis.yml
  composer.lock
  includes/REST_API/Fonts_Controller.php
  includes/Story_Post_Type.php
  phpstan.neon.dist
  tests/phpstan/bootstrap.php
Labels: cla: yes

#362 Fix some potential PHP warnings and errors
  includes/Story_Post_Type.php
Labels: PHP, Type: Bug, cla: yes

#352 Fix history bug
  assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js
  assets/src/edit-story/app/story/useStoryReducer/test/restore.js
Labels: cla: yes

#348 Clean up build folder before each build
  package-lock.json
  package.json
  webpack.config.js
Labels: Type: Infrastructure, cla: yes

#304 Revive issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Type: Task, cla: yes

#366 Add missing issue template header
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: cla: yes

#320 Prototype keyboard handlers for canvas
  assets/src/edit-story/app/history/historyProvider.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/arrangeElement.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/useCanvasKeys.js
  assets/src/edit-story/components/inspector/inspectorLayout.js
  assets/src/edit-story/components/keyboard/context.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/keyboard/keys.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/elements/text/frame.js
  package-lock.json
  package.json
Labels: cla: yes

#343 Text resize implementation
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/panels/font.js
  assets/src/edit-story/components/panels/utils/removeUnsetValues.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/square/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/text/updateForResizeEvent.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/utils/calculateFitTextFontSize.js
  assets/src/edit-story/utils/getAdjustedElementDimensions.js
  assets/src/edit-story/utils/textMeasurements.js
Labels: cla: yes

#367 Fix multi-select bug including background element
  assets/src/edit-story/app/story/useStoryReducer/reducers/selectElement.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/toggleElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/addElementToSelection.js
  assets/src/edit-story/app/story/useStoryReducer/test/toggleElementInSelection.js
Labels: cla: yes

#345 RangeSlider for Gridview
  assets/src/edit-story/components/canvas/gridview/index.js
Labels: cla: yes

#325 Configure Release Drafter GitHub action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Type: Infrastructure, cla: yes

#382 Update dependencies
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/elements/index.js
  package-lock.json
  package.json
Labels: Type: Infrastructure, cla: yes

#388 Fix Release Drafter config
  .github/workflows/release-drafter.yml
Labels: Type: Infrastructure, cla: yes

#364 Disable guidelines for background and fill elements
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
Labels: cla: yes

#387 Add bundle size check GitHub action
  .github/workflows/bundle-size.yml
Labels: Type: Infrastructure, cla: yes

#390 Bump uuid package
  package-lock.json
  package.json
Labels: Type: Infrastructure, cla: yes

#375 Move deps around in package.json
  package-lock.json
  package.json
Labels: Type: Infrastructure, cla: yes

#391 Tweaks to Release Drafter config
  .github/release-drafter.yml
Labels: Type: Infrastructure, cla: yes

#393 Fix text domain in background panel
  assets/src/edit-story/components/panels/background.js
Labels: Type: Bug, cla: yes

#406 Pass text resize direction directly instead of estimating and remove max font size
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/elements/text/updateForResizeEvent.js
  assets/src/edit-story/utils/textMeasurements.js
Labels: cla: yes

#409 Re-format GitHub templates to prevent issues with pre-commit hooks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Type: Infrastructure, cla: yes

#350 Bump PHPStan level to catch more potential issues
  includes/Fonts.php
  includes/Media.php
  includes/REST_API/Fonts_Controller.php
  includes/Story_Post_Type.php
  phpstan.neon.dist
  tests/phpstan/bootstrap.php
Labels: Type: Infrastructure, cla: yes

#180 Custom color picker
  assets/src/edit-story/components/button/icons/close.svg
  assets/src/edit-story/components/button/icons/eyedropper.svg
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/button/stories/index.js
  assets/src/edit-story/components/colorPicker/editableHexPreview.js
  assets/src/edit-story/components/colorPicker/index.js
  assets/src/edit-story/components/colorPicker/pointer.js
  assets/src/edit-story/components/colorPicker/stories/index.js
  assets/src/edit-story/theme.js
  package-lock.json
  package.json
Labels: Type: Enhancement, cla: yes

#383 New page background panel
  .distignore
  __mocks__/colorthief.js
  __mocks__/svgrMock.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/panels/actions.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/noSelection.js
  assets/src/edit-story/components/panels/pageBackground.js
  assets/src/edit-story/components/panels/panel/content.js
  assets/src/edit-story/components/panels/test/pageBackground.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/theme.js
  package-lock.json
  package.json
  tests/js/jest.config.js
Labels: Group: Editing, Type: Enhancement, cla: yes

#420 Open the preview in the same tab
  assets/src/edit-story/components/header/buttons.js
Labels: Type: Enhancement, cla: yes

#379 Set up code owners
  .github/CODEOWNERS
Labels: Type: Infrastructure, cla: yes

#410 Add and configure eslint-plugin-testing-library
  .eslintrc
  package-lock.json
  package.json
Labels: Type: Infrastructure, cla: yes

#426 Updating inspector components to new colors
  assets/src/edit-story/components/inspector/inspectorLayout.js
  assets/src/edit-story/components/inspector/inspectorTabs.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/panels/layer/panel.js
  assets/src/edit-story/components/panels/noSelection.js
  assets/src/edit-story/components/panels/panel/content.js
  assets/src/edit-story/components/panels/panel/handle.js
  assets/src/edit-story/components/panels/panel/title.js
  assets/src/edit-story/elements/text/layer.js
  assets/src/edit-story/theme.js
Labels: Group: Editing, Type: Enhancement, cla: yes

#335 Implement Background Display Options
  assets/src/edit-story/components/panels/backgroundDisplay.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/test/backgroundDisplay.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/output/page.js
  package-lock.json
  package.json
Labels: Type: Enhancement, cla: yes

#428 Feature/dropzone 2
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/canvas/draggablePage.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/dropzone/canvasDropZone.js
  assets/src/edit-story/components/dropzone/canvasOverlay.js
  assets/src/edit-story/components/dropzone/dropZone.js
  assets/src/edit-story/components/dropzone/dropZoneProvider.js
  assets/src/edit-story/components/dropzone/index.js
  assets/src/edit-story/components/dropzone/mediaDropZone.js
  assets/src/edit-story/components/dropzone/shared/index.js
  assets/src/edit-story/components/library/mediaLibrary.js
Labels: cla: yes

#427 Fix position of Movable handle
  assets/src/edit-story/components/movable/moveStyle.js
Labels: Type: Bug, cla: yes
