Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-07, with the labels that each got.

#2716 3P Media: Use react-photo-gallery
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/library/panes/media/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/providerType.js
  assets/src/edit-story/components/library/panes/media/stories/mediaGallery.js
  package-lock.json
  package.json
Labels: Group: 3P Media, Group: Media, Type: Enhancement, cla: yes

#2883 Dashboard: Prevent scroll to top on pagination
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Bug, cla: yes

#2889 Templates: Fix beauty template image
  assets/images/templates/beauty/beauty_page8_figure.jpg
  assets/images/templates/beauty/beauty_page8_figure.png
  assets/src/dashboard/templates/raw/beauty.json
Labels: Group: Templates, Type: Bug, cla: yes

#2890 Version 1.0.0-beta.1
  web-stories.php
Labels: Skip Changelog, Type: Task, cla: yes

#2832 Beta micro site
  beta/assets/arrow.png
  beta/assets/ftue.jpg
  beta/assets/google.svg
  beta/assets/hero_dashboard.jpg
  beta/assets/hero_editor.jpg
  beta/assets/templates/1.png
  beta/assets/templates/2.png
  beta/assets/templates/3.png
  beta/assets/templates/4.png
  beta/assets/templates/5.png
  beta/assets/templates/6.png
  beta/assets/templates/7.png
  beta/assets/templates/8.png
  beta/assets/tips/Group-5215-1.jpg
  beta/assets/tips/Group-5216-3.jpg
  beta/assets/tips/Group-5227-1.png
  beta/assets/tips/Rectangle-1352-1.jpg
  beta/assets/tips/ic-Safe-Mode.png
  beta/assets/tips/image-23.jpg
  beta/assets/tips/image-25.jpg
  beta/assets/tips/image-26.jpg
  beta/assets/tips/image-31.jpg
  beta/assets/tips/tip1.mp4
  beta/assets/tips/tip2.mp4
  beta/assets/tips/tip3.mp4
  beta/assets/tips/tip5.mp4
  beta/assets/wysiwyg.mp4
  beta/index.html
  beta/tips.html
  index.md
Labels: Type: Enhancement, cla: yes

#2753 Add 'Enter' key as a trigger to enter edit mode
  assets/src/edit-story/components/canvas/useCanvasKeys.js
  assets/src/edit-story/elements/text/karma/edit.karma.js
Labels: Accessibility, Elements: Image, Elements: Video, Type: Enhancement, cla: yes

#2865 Style Presets: fix color swatch styling on Firefox
  assets/src/edit-story/components/panels/stylePreset/presets.js
Labels: Browser Issues, Group: Presets, Type: Bug, cla: yes

#2887 Karma: use a single webpack bundle for all tests
  .eslintrc
  assets/src/dashboard/karma-tests.cjs
  assets/src/edit-story/elements/video/karma/autoplay.karma.js
  assets/src/edit-story/elements/video/karma/elementMinSizeAndPlayback.karma.js
  assets/src/edit-story/karma-tests.cjs
  karma-dashboard.config.cjs
  karma-edit-story.config.cjs
  package.json
Labels: Type: Infrastructure, cla: yes

#2850 Add tests for Discovery class
  tests/phpunit/tests/Discovery.php
  tests/phpunit/tests/Story_Renderer.php
Labels: Group: WordPress, Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#2857 Add tests for Story_Post_Type class
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#2849 Admin class: add tests
  tests/phpunit/tests/Admin.php
Labels: Group: WordPress, Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#2905 Fix aria-label typo ("Dupliccate" -> "Duplicate")
  assets/src/edit-story/components/canvas/pagemenu/index.js
Labels: cla: yes

#2590 Workspace: Dark UI for Font Picker
  assets/src/edit-story/components/fontPicker/pickerContainer.js
  assets/src/edit-story/theme.js
Labels: cla: yes

#2892 Fix detecting contenteditable for copy-paste
  assets/src/edit-story/utils/nativeCopyPasteExpected.js
  assets/src/edit-story/utils/test/nativeCopyPasteExpected.js
Labels: Elements: Text, Group: Copy/Paste, Type: Bug, cla: yes

#2810 Install jest-axe
  package-lock.json
  package.json
  tests/js/jest.setup.js
Labels: Accessibility, Pod: WP & Infra, Type: Infrastructure, cla: yes

#2903 Dashboard: fix inconsistency in the admin menu
  includes/Dashboard.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#2895 Expand tests for Story_Post_Type class
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#2906 Ensure raw story title is used for prefilling post title
  includes/Admin.php
  tests/phpunit/tests/Admin.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#2932 Ignore .DS_Store files from dist bundle
  .distignore
Labels: Type: Bug, Type: Infrastructure, cla: yes

#2936 Fix prop types warning for font preview
  assets/src/edit-story/components/library/text/fontPreview.js
Labels: Skip Changelog, Type: Code Quality, cla: yes

#2827 Pull out common parts of local/reducer.js to media/common/reducer.js
  assets/src/edit-story/app/media/common/reducer.js
  assets/src/edit-story/app/media/local/reducer.js
Labels: Group: Media, Type: Code Quality, cla: yes

#2833 Rename 'pagingNum' -> 'pageToken' for consistency between local / media3p
  assets/src/edit-story/app/media/actions.js
  assets/src/edit-story/app/media/common/reducer.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
Labels: Group: Media, Type: Code Quality, cla: yes

#2958 Fix autoloading for Tests namespace
  composer.json
  tests/phpunit/bootstrap.php
Labels: Pod: WP & Infra, Type: Code Quality, cla: yes

#2925 Media: Fix video poster extraction on Firefox and drag/paste on Safari
  assets/src/edit-story/app/media/utils/getFirstFrameOfVideo.js
Labels: Browser Issues, Elements: Video, Group: Media, Type: Bug, cla: yes

#3004 Add first version of ApiProvider
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/media/media3p/api/apiFetcher.js
  assets/src/edit-story/app/media/media3p/api/context.js
  assets/src/edit-story/app/media/media3p/api/index.js
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/apiFetcher.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/media3p/api/useMedia3pApi.js
Labels: cla: yes

#2965 Fix fonts controller limit
  includes/REST_API/Fonts_Controller.php
Labels: cla: yes

#2933 Dashboard: Preload first page of stories
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/useStoryApi.js
  includes/Dashboard.php
  includes/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
Labels: Group: Dashboard, Group: WordPress, Type: Enhancement, Type: Performance, cla: yes

#2834 Update pageToken to have opaque semantics in common/reducer.js
  assets/src/edit-story/app/media/actions.js
  assets/src/edit-story/app/media/common/reducer.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
Labels: Group: Media, Type: Code Quality, cla: yes

#2891 Write tests for existing local media reducer
  assets/src/edit-story/app/media/common/test/reducer.js
  assets/src/edit-story/app/media/local/test/reducer.js
  assets/src/edit-story/app/media/useMediaReducer.js
Labels: Group: Media, Pod: Media I/O, Type: Code Quality, cla: yes

#2893 Pull media action functions out to common
  assets/src/edit-story/app/media/common/actions.js
  assets/src/edit-story/app/media/common/test/reducer.js
  assets/src/edit-story/app/media/local/actions.js
  assets/src/edit-story/app/media/local/test/reducer.js
  assets/src/edit-story/app/media/useMediaReducer.js
Labels: cla: yes

#2894 Add provider discriminator to common/reducer.js and actions
  assets/src/edit-story/app/media/common/actions.js
  assets/src/edit-story/app/media/common/test/reducer.js
  assets/src/edit-story/app/media/local/actions.js
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/local/test/reducer.js
Labels: Group: Media, Pod: Media I/O, Type: Code Quality, cla: yes

#2956 Add useMedia3p and useMedia3pProvider context consumer hooks
  assets/src/edit-story/app/media/media3p/test/reducer.js
  assets/src/edit-story/app/media/media3p/test/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/test/useMedia3p.js
  assets/src/edit-story/app/media/media3p/useMedia3p.js
Labels: Group: Media, Pod: Media I/O, Type: Code Quality, cla: yes

#2959 Remove 'local' provider specific attributes from fetchMediaSuccess
  assets/src/edit-story/app/media/common/actions.js
Labels: Group: Media, Pod: Media I/O, Type: Code Quality, cla: yes

#2949 Dashboard: Update dialog relevant styles to match editor
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/dialog/index.js
  assets/src/dashboard/components/dialog/stories/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#3005 Add JSDoc comments for media state management
  assets/src/edit-story/app/media/common/reducer.js
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
  assets/src/edit-story/app/media/local/useLocalMedia.js
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/useMedia3p.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
  assets/src/edit-story/app/media/useMedia.js
Labels: cla: yes

#3035 add correct format for "sizes"
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
Labels: cla: yes

#2960 Emit warnings for missing JSDoc comments
  .eslintrc
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/components/keyboard/test/index.test.js
  package-lock.json
  package.json
  tests/e2e/config/bootstrap.js
  tests/e2e/utils/previewStory.js
  tests/js/matchers/toBeValidAMP.js
  tests/js/matchers/toBeValidAMPStoryElement.js
  tests/js/matchers/toBeValidAMPStoryPage.js
  tests/js/matchers/utils.js
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#3030 Templates: Added links to DIY, Fashion, and Fitness
  assets/src/dashboard/templates/raw/diy.json
  assets/src/dashboard/templates/raw/fashion.json
  assets/src/dashboard/templates/raw/fitness.json
Labels: Group: Templates, Type: Enhancement, cla: yes

#2882 Dashboard: My Stories View Karma Tests
  assets/src/dashboard/app/views/exploreTemplates/header/stories/index.js
  assets/src/dashboard/app/views/exploreTemplates/karma/exploreTemplates.karma.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/myStories/header/stories/index.js
  assets/src/dashboard/app/views/myStories/karma/myStores.karma.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGallery/stories/index.js
  assets/src/dashboard/components/toggleButtonGroup/index.js
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/dashboard/dataUtils/formattedTemplatesArray.js
  assets/src/dashboard/dataUtils/formattedUsersObject.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/dashboard/karma/fixture.js
  assets/src/dashboard/storybookUtils/index.js
  karma/fixture/events.js
  package.json
Labels: Pod: Dashboard & Templates, cla: yes

#2976 Dashboard: Settings view context foundation (Google Analytics)
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/useSettingsApi.js
  assets/src/dashboard/app/api/useSettingsApi.js
  assets/src/dashboard/app/reducer/settings.js
  assets/src/dashboard/app/reducer/test/settings.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/reducer/test/templates.js
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/stories/index.js
  assets/src/dashboard/app/views/editorSettings/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#3061 3P Media: Add Attribution to resources
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/app/media/utils/index.js
Labels: Group: 3P Media, Pod: Media I/O, Type: Enhancement, cla: yes

#2957 3P Media: Add media fetch side effect
  assets/src/edit-story/app/media/media3p/test/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
Labels: Group: Media, Pod: Media I/O, Type: Enhancement, cla: yes

#3037 Combine local and media3p actions for useMediaReducer
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/test/useMediaReducer.js
  assets/src/edit-story/app/media/useMediaReducer.js
Labels: Group: 3P Media, Group: Media, Pod: Media I/O, Type: Code Quality, cla: yes

#2962 Warn if running plugin from source
  includes/namespace.php
  tests/phpstan/bootstrap.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3094 Fix/Simplify `replace_editor` filter
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#2855 Add foundation for plugin activation notice
  assets/src/activation-notice/app/index.js
  assets/src/activation-notice/index.js
  assets/src/activation-notice/theme.js
  includes/Activation_Flag.php
  includes/Activation_Notice.php
  includes/Plugin.php
  includes/Story_Post_Type.php
  includes/templates/admin/activation-notice.php
  tests/phpunit/tests/Activation_Flag.php
  tests/phpunit/tests/Activation_Notice.php
  webpack.config.cjs
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3085 Dashboard: Settings view context foundation (Publisher Logos)
  assets/src/dashboard/app/api/useSettingsApi.js
  assets/src/dashboard/app/reducer/settings.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/stories/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#3095 Build Tool: Update version number in plugin header for pre-releases
  bin/utils/test/updateVersionNumbers.js
  bin/utils/updateVersionNumbers.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#3018 Dashboard: Updated Wellbeing template, improved blob imports
  assets/src/dashboard/templates/raw/wellbeing.json
  assets/src/edit-story/masks/index.js
Labels: Group: Templates, Pod: Dashboard & Templates, cla: yes

#2913 Dashboard: Updated Cooking template to use shapes instead of images when possible.
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/templates/raw/cooking.json
  assets/src/edit-story/masks/index.js
Labels: Pod: Dashboard & Templates, cla: yes

#3110 Set global post when replacing editor
  includes/Story_Post_Type.php
Labels: cla: yes

#3117 Move local mediaPane code so that we have media3p and local at the sa…
  assets/src/edit-story/components/library/panes/index.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/stories/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/stories/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/stories/test-image.jpg
  assets/src/edit-story/components/library/panes/media/common/stories/test-poster.png
  assets/src/edit-story/components/library/panes/media/common/stories/test-video.mp4
  assets/src/edit-story/components/library/panes/media/local/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/local/dropDownMenu.js
  assets/src/edit-story/components/library/panes/media/local/index.js
  assets/src/edit-story/components/library/panes/media/local/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/local/mediaTab.js
  assets/src/edit-story/components/library/panes/media/local/paneId.js
  assets/src/edit-story/components/library/panes/media/local/stories/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/local/stories/mediaEditDialog.js
  assets/src/edit-story/components/library/panes/media/local/stories/test-image.jpg
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/providerType.js
  assets/src/edit-story/components/library/test/deleteDialog.js
  assets/src/edit-story/components/library/test/mediaEditDialog.js
Labels: cla: yes

#3033 Media Library: use pointer cursor more consistently
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/shared.js
Labels: Group: Media, Pod: Media I/O, Type: Enhancement, cla: yes

#3091 Media Library: Debounce search requests
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
Labels: Group: Media, Type: Bug, cla: yes

#3089 Properly map media3p urls to the "sizes" format expected by the app
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
Labels: Group: 3P Media, Pod: Media I/O, Skip Changelog, Type: Enhancement, cla: yes

#3006 Render media resources in Media3pPane from media3p state
  assets/src/edit-story/app/media/media3p/api/apiFetcher.js
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/apiFetcher.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
Labels: Group: 3P Media, Skip Changelog, Type: Enhancement, cla: yes

#3118 Use upload icon for the upload tab
  assets/src/edit-story/components/library/panes/media/local/mediaTab.js
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/upload.svg
Labels: cla: yes

#3120 Factor out common styles and add dummy search bar and categories section
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/providerTab.js
Labels: cla: yes

#3122 fix artifact caused by scrollbar
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
Labels: cla: yes

#3123 Add some logic to insert media3p images when you click them
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
Labels: cla: yes

#3059 Dashboard: File Upload UI Component
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/stories/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/fileUpload/index.js
  assets/src/dashboard/components/fileUpload/stories/index.js
  assets/src/dashboard/components/fileUpload/test/fileUpload.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/constants/components.js
  assets/src/dashboard/icons/index.js
  assets/src/dashboard/icons/upload.svg
  assets/src/dashboard/utils/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#3129 Add E2E test for “Use template” feature
  includes/Story_Post_Type.php
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/dashboard/templates/useTemplate.js
Labels: Group: Dashboard, Group: WordPress, Pod: WP & Infra, Skip Changelog, cla: yes

#3128 Build Workflow: Prevent nested ZIP files
  .github/workflows/continuous-integration-build.yml
Labels: Group: WordPress, Pod: WP & Infra, Skip Changelog, Type: Bug, Type: Infrastructure, cla: yes

#3111 Dashboard: First half of Travel template animated
  assets/src/dashboard/templates/raw/travel.json
Labels: Group: Animations, Group: Templates, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#3144 Dashboard: Second half of Travel template animations complete
  assets/src/dashboard/templates/raw/travel.json
  includes/Dashboard.php
Labels: cla: yes

#2835 Media Library: row-based gallery
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
Labels: Group: Media, Type: Enhancement, cla: yes

#3159 Add pagination support for media3p results
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
Labels: cla: yes

#3113 Workspace: Keyboard navigation in Grid View
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/gridview/useGridViewKeys.js
  assets/src/edit-story/components/canvas/karma/grideView.karma.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
Labels: cla: yes

#3036 CUJ Coverage using Karma reporter
  .eslintrc
  .github/workflows/continuous-integration-karma-dashboard.yml
  .github/workflows/continuous-integration-karma-edit-story.yml
  assets/src/edit-story/karma/media.cuj.karma.js
  assets/src/edit-story/karma/text.cuj.karma.js
  karma-dashboard.config.cjs
  karma-edit-story.config.cjs
  karma/karma-cuj-reporter/.eslintrc
  karma/karma-cuj-reporter/README.md
  karma/karma-cuj-reporter/index.cjs
  package.json
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#3158 Moved ProviderType to /common instead of /media3p
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/providerType.js
  assets/src/edit-story/components/library/panes/media/common/stories/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
Labels: Group: Media, Type: Code Quality, cla: yes

#3183 Fix flakey test by adding await to fixture.events.click()
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: cla: yes

#3161 3P Media: Add search capabilities
  .github/workflows/continuous-integration-karma-edit-story.yml
  assets/src/edit-story/app/media/common/reducer.js
  assets/src/edit-story/app/media/common/test/reducer.js
  assets/src/edit-story/app/media/media3p/actions.js
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/test/reducer.js
  assets/src/edit-story/app/media/media3p/test/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/test/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/types.js
  assets/src/edit-story/app/media/media3p/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/karma-tests.cjs
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3125 Change the text wrapping for text display.
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/updateForResizeEvent.js
  assets/src/edit-story/utils/textMeasurements.js
Labels: cla: yes

#3019 Dashboard: Reduced loops into a single reduce for story fetching
  assets/src/dashboard/app/api/test/useStoryApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/serializers/stories.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/components/previewPage.js
  assets/src/dashboard/components/previewPageElements.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#3038 Links: improve error detection for invalid URLs
  includes/REST_API/Link_Controller.php
  tests/phpunit/tests/REST_API/Link_Controller.php
Labels: Group: Links, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#2718 Added integration tests for inline text formatting
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/form/color/color.js
  assets/src/edit-story/components/inspector/inspectorLayout.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/textStyle/color.js
  assets/src/edit-story/components/richText/karma/_utils.js
  assets/src/edit-story/components/richText/karma/inlineSelection.karma.js
  assets/src/edit-story/components/richText/karma/inlineStyleOverride.karma.js
  assets/src/edit-story/components/richText/karma/itf.karma.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
  assets/src/edit-story/components/richText/karma/singleSelection.karma.js
  assets/src/edit-story/components/richText/useSelectionManipulation.js
  assets/src/edit-story/karma/fixture/containers/canvas.js
  assets/src/edit-story/karma/fixture/containers/common/color.js
  assets/src/edit-story/karma/fixture/containers/common/index.js
  assets/src/edit-story/karma/fixture/containers/common/select.js
  assets/src/edit-story/karma/fixture/containers/common/toggle.js
  assets/src/edit-story/karma/fixture/containers/container.js
  assets/src/edit-story/karma/fixture/containers/designPanel/abstractPanel.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/textStyle.js
  assets/src/edit-story/karma/fixture/containers/editor.js
  assets/src/edit-story/karma/fixture/containers/inspector.js
  assets/src/edit-story/karma/fixture/containers/library.js
Labels: Skip Changelog, Type: Enhancement, cla: yes

#3181 Use PaginatedMediaGallery in Upload tab
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
Labels: Group: Media, Type: Code Quality, cla: yes

#3207 Fixed typo that caused ... icon to not show up for videos
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
Labels: cla: yes

#3209 Comment out flakey media3p tests temporarily
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: cla: yes

#3199 Set react-modal app element in karma tests
  assets/src/dashboard/karma/fixture.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#3108 Keep test suite in sync with WP files when testing trunk/nightlies
  bin/install-wp-tests.sh
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#3178 Dashboard: Added animations to DIY template
  assets/src/dashboard/templates/raw/diy.json
  includes/Dashboard.php
Labels: cla: yes

#3220 Dashboard: Added base animations to Wellbeing template
  assets/src/dashboard/templates/raw/wellbeing.json
Labels: cla: yes

#3226 fix search and pagination
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
Labels: cla: yes

#3098 Add foundation for Google Analytics Tracking ID setting
  includes/Dashboard.php
  includes/Plugin.php
  includes/Settings.php
  tests/phpunit/tests/Settings.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#3087 Dashboard: Display Scheduled Stories
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/views/myStories/header/test/header.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/cardGridItem/test/cardTitle.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/utils/test/useDashboardResultsLabel.js
  includes/Dashboard.php
  includes/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#3246 use a different action name for local and media3p SET_SEARCH_TERM
  assets/src/edit-story/app/media/local/actions.js
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/local/types.js
  assets/src/edit-story/app/media/media3p/actions.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/types.js
Labels: cla: yes

#3250 add a test to verify that the searchTerm states don't pollute each other
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/test/reducer.js
Labels: cla: yes

#3251 ApiFetcher to support listCategories fetching
  assets/src/edit-story/app/media/media3p/api/apiFetcher.js
  assets/src/edit-story/app/media/media3p/api/test/apiFetcher.js
Labels: cla: yes

#3208 3P Media: Add opt-in incremental search
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/library/common/searchInput.js
  assets/src/edit-story/components/library/common/test/searchInput.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/flags.js
  includes/Story_Post_Type.php
Labels: Group: 3P Media, Group: Media, Type: Enhancement, cla: yes

#2530 Display recently used fonts
  assets/src/edit-story/app/font/fontProvider.js
  assets/src/edit-story/components/fontPicker/pickerContainer.js
  assets/src/edit-story/components/fontPicker/scrollList.js
  assets/src/edit-story/components/fontPicker/test/fontPicker.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/font.js
Labels: Group: Fonts, Type: Enhancement, cla: yes

#3279 Remove unnecessary function export
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/test/reducer.js
Labels: cla: yes

#3296 Change "Remove as background" to "Detach from background"
  assets/src/edit-story/components/panels/backgroundSizePosition.js
Labels: Type: Bug, cla: yes

#3299 Embed Block: use built in string type for url attribute
  includes/Embed_Block.php
Labels: Group: WordPress, Type: Bug, cla: yes

#3302 Dashboad: CUJ karma test for WordPress list view
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
Labels: Group: Dashboard, Skip Changelog, Type: Infrastructure, cla: yes

#2699 Text edit mode + Moveable resizing/rotation
  .github/CODEOWNERS
  .storybook/preview.js
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/karma/multiSelectionMovable.karma.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable.js
  assets/src/edit-story/components/canvas/selection.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable.js
  assets/src/edit-story/components/canvas/test/multiSelectionMoveable.js
  assets/src/edit-story/components/canvas/test/singleSelectionMoveable.js
  assets/src/edit-story/components/moveable/cropStyle.js
  assets/src/edit-story/components/moveable/index.js
  assets/src/edit-story/components/moveable/moveStyle.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/editCropMoveable.js
  assets/src/edit-story/elements/media/editPanMoveable.js
  assets/src/edit-story/elements/media/index.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/karma/elementTransform.cuj.karma.js
Labels: Elements: Text, Group: Selection, Type: Enhancement, cla: yes

#3227 Use the 'scroll' event to load more media results
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: Group: Media, Type: Enhancement, cla: yes

#3328 Remove empty doc blocks
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable.js
  assets/src/edit-story/components/canvas/selection.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/editCropMoveable.js
  assets/src/edit-story/elements/media/editPanMoveable.js
Labels: Type: Code Quality, cla: yes

#3237 Correctly stop further execution when autoloader is missing
  includes/namespace.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#3213 Story Post Type: Change namespace of REST API endpoint
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/dashboard/karma/fixture.js
  includes/Dashboard.php
  includes/REST_API/Stories_Autosaves_Controller.php
  includes/REST_API/Stories_Base_Controller.php
  includes/Story_Post_Type.php
  includes/templates/admin/edit-story.php
  tests/phpunit/tests/REST_API/Stories_Autosaves_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#3214 Fix link protocol handling
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/karma/link.cuj.karma.js
Labels: cla: yes

#3260 Add Stories RSS feed link to HTML head
  includes/Discovery.php
  tests/phpunit/tests/Discovery.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3268 Templates: Cooking Base Animations
  assets/src/dashboard/templates/raw/cooking.json
Labels: Group: Animations, Group: Templates, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#3242 Dashboard: Explore Templates karma tests
  assets/src/dashboard/app/views/exploreTemplates/karma/exploreTemplates.karma.js
  assets/src/dashboard/dataUtils/formattedTemplatesArray.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/dashboard/karma/fixture.js
Labels: Group: Dashboard, Group: Templates, Skip Changelog, Type: Infrastructure, cla: yes

#3224 Dashboard: Updated Travel template's page 7 layout
  assets/src/dashboard/templates/raw/travel.json
Labels: Group: Templates, Type: Enhancement, cla: yes

#3318 Remove 'defaultProvider' and rename 'common' to 'pagination'
  assets/src/edit-story/app/media/local/actions.js
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/local/test/reducer.js
  assets/src/edit-story/app/media/media3p/actions.js
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/pagination/actions.js
  assets/src/edit-story/app/media/pagination/reducer.js
  assets/src/edit-story/app/media/pagination/test/reducer.js
  assets/src/edit-story/app/media/pagination/types.js
Labels: Group: 3P Media, Group: Media, Type: Code Quality, cla: yes

#3322 Adding a Pill styled component.
  assets/src/edit-story/components/library/panes/media/media3p/categoryPill.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/stories/categoryPill.js
  assets/src/edit-story/components/library/panes/media/media3p/stories/media3pCategories.js
Labels: Skip Changelog, Type: Enhancement, cla: yes

#3376 Embed Block: Fix attribute type in block.json
  assets/src/story-embed-block/block/block.json
Labels: Group: WordPress, Type: Bug, cla: yes

#3112 Templates: Fitness Base Animations
  assets/src/dashboard/templates/raw/fitness.json
Labels: Group: Templates, Type: Enhancement, cla: yes

#3285 Media Library: add keyboard navigation
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/useRovingTabIndex.js
  assets/src/edit-story/components/library/panes/media/local/dropDownMenu.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: Accessibility, Group: 3P Media, Group: Media, Type: Enhancement, cla: yes

#3374 3P Media: Category can expand and collapse
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/button/stories/index.js
  assets/src/edit-story/components/library/panes/media/media3p/categoryPill.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/stories/media3pCategories.js
  assets/src/edit-story/icons/arrow_down.svg
  assets/src/edit-story/icons/index.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3359 Load categories together with media in MediaPane
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
Labels: Group: Media, Skip Changelog, Type: Enhancement, cla: yes

#3360 Support category selection redux setup
  assets/src/edit-story/app/media/media3p/categories/actions.js
  assets/src/edit-story/app/media/media3p/categories/reducer.js
  assets/src/edit-story/app/media/media3p/categories/test/reducer.js
  assets/src/edit-story/app/media/media3p/categories/types.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
Labels: Group: Media, Type: Code Quality, cla: yes

#3361 Display categories from state
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/stories/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pCategories.js
Labels: Group: 3P Media, Skip Changelog, Type: Enhancement, cla: yes

#3396 Fade in images and videos in the gallery
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
Labels: cla: yes

#3058 Templates: Beauty Base Animations & Links
  assets/src/dashboard/templates/raw/beauty.json
Labels: Group: Templates, Type: Enhancement, cla: yes

#3316 Dashboard: Typeahead results to scroll & preserve current selection
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/typeaheadSearch.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadInput/stories/index.js
  assets/src/dashboard/components/typeaheadOptions/index.js
  assets/src/dashboard/components/typeaheadOptions/stories/index.js
  assets/src/dashboard/components/typeaheadOptions/test/typeaheadOptions.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#3394 Dashboard: Update document title on route changes
  assets/src/dashboard/app/index.js
  assets/src/dashboard/constants/index.js
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/dashboard/documentTitle.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#3397 Fetch Media for selected category
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/media3p/categories/actions.js
  assets/src/edit-story/app/media/media3p/categories/reducer.js
  assets/src/edit-story/app/media/media3p/categories/test/reducer.js
  assets/src/edit-story/app/media/media3p/test/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/stories/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pCategories.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3347 Dashboard: Typeahead options overlap in Safari
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadOptions/index.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#3264 Integration: Add Stories to Jetpack XML Sitemap
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: Integration, Group: WordPress, Type: Enhancement, cla: yes

#3407 Add Publisher Logos to Settings endpoint
  includes/Dashboard.php
  includes/Database_Upgrader.php
  includes/REST_API/Stories_Controller.php
  includes/Settings.php
  includes/Story_Post_Type.php
  includes/Traits/Publisher.php
  tests/phpunit/tests/Database_Upgrader.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
  tests/phpunit/tests/Story_Renderer.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3375 Readme: add block to list of tags
  readme.txt
Labels: Skip Changelog, Type: Task, cla: yes

#3196 Performance: Preload media REST API request in editor
  .github/workflows/continuous-integration-karma-dashboard.yml
  .github/workflows/continuous-integration-karma-edit-story.yml
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
  assets/src/edit-story/components/library/test/_utils/index.js
  assets/src/edit-story/components/library/test/_utils/mediaResponseWithPdfAndImage.json
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/utils/keyboardOnlyOutline.js
  includes/Dashboard.php
  includes/Plugin.php
  includes/REST_API/Stories_Media_Controller.php
  includes/Story_Post_Type.php
  includes/templates/admin/edit-story.php
  karma/karma-puppeteer-client/client.js
  tests/phpunit/tests/Media.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
Labels: Group: Media, Group: WordPress, Type: Enhancement, cla: yes

#3437 Improve default analytics configuration
  includes/Analytics.php
  includes/Plugin.php
  includes/Story_Post_Type.php
  includes/Story_Renderer.php
  tests/phpunit/tests/Analytics.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3458 Make a11y test less flaky by mocking just 1 page.
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: cla: yes

#3459 Hide empty categories when not loading.
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pCategories.js
Labels: cla: yes

#3460 switch media3p mediaFetching tests to use portrait images
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: cla: yes

#3463 update scrollto to not be flakey
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: cla: yes

#3464 update scrollto to not be flakey in local tests
  assets/src/edit-story/components/library/panes/media/local/karma/mediaFetching.karma.js
Labels: cla: yes

#3433 Media: modify getThumbnailUrl to receive a minimum width
  assets/src/edit-story/app/media/utils/getThumbnailUrl.js
  assets/src/edit-story/app/media/utils/test/getThumbnailUrl.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js
Labels: Group: Media, Skip Changelog, Type: Enhancement, cla: yes

#3430 Remove useMedia3p hook
  assets/src/edit-story/app/media/media3p/test/useMedia3p.js
  assets/src/edit-story/app/media/media3p/useMedia3p.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/test/_utils/mediaResponseWithPdfAndImage.json
Labels: Group: 3P Media, Type: Code Quality, cla: yes

#3419 Dashboard: Karma integration test for Template Details View
  assets/src/dashboard/app/views/templateDetails/components.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/dataUtils/formattedTemplatesArray.js
Labels: cla: yes

#3247 Dashboard: Date formatting util to handle relative date display
  assets/src/date/getDateObjectWithTimezone.js
  assets/src/date/getRelativeDisplayDate.js
  assets/src/date/getTimeFromNow.js
  assets/src/date/index.js
  assets/src/date/isToday.js
  assets/src/date/isYesterday.js
  assets/src/date/test/getDateObjectWithTimezone.js
  assets/src/date/test/getRelativeDisplayDate.js
  assets/src/date/test/getTimeFromNow.js
  assets/src/date/test/isToday.js
  assets/src/date/test/isYesterday.js
  package-lock.json
  package.json
Labels: cla: yes

#3425 Dashboard: Feature flag & initial structuring for template previews
  assets/src/dashboard/app/views/exploreTemplates/content/stories/index.js
  assets/src/dashboard/app/views/exploreTemplates/index.js
  assets/src/dashboard/app/views/exploreTemplates/karma/exploreTemplates.karma.js
  assets/src/dashboard/app/views/shared/stories/templateGridView.js
  assets/src/dashboard/app/views/shared/templateGridView.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/types.js
  assets/src/dashboard/utils/useTemplateView.js
  includes/Dashboard.php
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#3408 Dashboard: Fixed bug that caused some animations to not play
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/components/storyAnimation/provider.js
Labels: cla: yes

#3474 (De-) Select category UI
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pCategories.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3499 Replaced support link with feedback form
  beta/index.html
Labels: cla: yes

#3487 Dashboard: Added Fade In animation effect
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/effects/fadeIn/index.js
  assets/src/dashboard/animations/effects/fadeIn/stories/index.js
  assets/src/dashboard/animations/parts/blinkOn/stories/index.js
  assets/src/dashboard/animations/parts/bounce/stories/index.js
  assets/src/dashboard/animations/parts/fade/stories/index.js
  assets/src/dashboard/animations/parts/flip/stories/index.js
  assets/src/dashboard/animations/parts/floatOn/stories/index.js
  assets/src/dashboard/animations/parts/index.js
  assets/src/dashboard/animations/parts/move/stories/index.js
  assets/src/dashboard/animations/parts/spin/stories/index.js
  assets/src/dashboard/animations/parts/zoom/stories/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3241 Dashboard: Changed Wellbeing template title's font-weight to light
  assets/src/dashboard/templates/raw/wellbeing.json
Labels: Group: Templates, Type: Enhancement, cla: yes

#3417 Dashboard: Refactor My Stories karma tests to use fixture.renderHook
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/dashboard/karma/apiProviderFixture.js
Labels: Group: Dashboard, Type: Code Quality, cla: yes

#3503 Added unit tests for media element
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/local/dropDownMenu.js
  assets/src/edit-story/components/library/test/mediaElement.js
Labels: Group: Media, Skip Changelog, Type: Infrastructure, cla: yes

#3522 Add registerUsage call to apiFetcher
  assets/src/edit-story/app/media/media3p/api/apiFetcher.js
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/apiFetcher.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
Labels: Group: 3P Media, Skip Changelog, Type: Enhancement, cla: yes

#3502 3P Media Error Handling
  assets/src/edit-story/app/media/media3p/test/useFetchCategoriesEffect.js
  assets/src/edit-story/app/media/media3p/test/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useFetchCategoriesEffect.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/app/snackbar/snackbarProvider.js
Labels: Group: 3P Media, Pod: Media I/O, Type: Enhancement, cla: yes

#3525 Trigger register usage call on image insertion
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
Labels: Group: Media, Pod: Media I/O, Skip Changelog, Type: Enhancement, cla: yes

#3236 Workspace: Add key events for bold, underline, and italics.
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/useRichTextFormatting.js
Labels: cla: yes

#3547 Add Unsplash attribution at the bottom left
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/icons/unsplash_logo_full.svg
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3578 Removed role=grid in MediaGallery
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
Labels: cla: yes

#3567 Animations: Add Pulse animation effect and part
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/effects/pulse/index.js
  assets/src/dashboard/animations/effects/pulse/stories/index.js
  assets/src/dashboard/animations/parts/index.js
  assets/src/dashboard/animations/parts/pulse/index.js
  assets/src/dashboard/animations/parts/pulse/stories/index.js
  assets/src/dashboard/animations/parts/pulse/test/index.js
  assets/src/dashboard/animations/parts/test/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes
