Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-04, with the labels that each got.

#684 Add text highlight mode for text background
  assets/src/edit-story/components/form/toggleButton.js
  assets/src/edit-story/components/panels/textStyle/color.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/icons/fill_filled_icon.svg
  assets/src/edit-story/icons/fill_highlighted_icon.svg
  assets/src/edit-story/icons/fill_none_icon.svg
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0012_setBackgroundTextMode.js
  assets/src/edit-story/migration/migrations/v0012_setBackgroundTextMode.js
  assets/src/edit-story/types.js
  assets/src/edit-story/utils/textMeasurements.js
Labels: Type: Enhancement, cla: yes

#924 Fixed behavior for selected elements
  .stylelintrc
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/movable/moveStyle.js
  assets/src/edit-story/masks/output.js
Labels: cla: yes

#918 Use native aspect-ratio format for grid layers
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/test/output.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/utils/styles.js
Labels: cla: yes

#888 Add save story error message
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
Labels: Needs Cherry-Picking, Type: Enhancement, cla: yes

#875 Fix forms events in Firefox
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/inspector/design/designPanel.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#551 Added scroll behavior to layer panel when reordering by mouse
  assets/src/edit-story/components/panels/layer/layerList.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/reorderable/reorderable.js
  assets/src/edit-story/components/reorderable/reorderableScroller.js
  assets/src/edit-story/components/reorderable/reorderableSeparator.js
  assets/src/edit-story/components/reorderable/useReordering.js
  assets/src/edit-story/components/reorderable/useScroll.js
Labels: Group: Editing, Type: Enhancement, cla: yes

#929 Fix multiple warnings and proptype issues
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/types.js
Labels: cla: yes

#836 Update URL when publishing post.
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/test/buttons.js
  assets/src/edit-story/utils/useRefreshPostEditURL.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#928 Fix deployment
  package-lock.json
  package.json
Labels: Type: Infrastructure, cla: yes

#930 Fix Document panel crashing
  assets/src/edit-story/components/reorderable/useScroll.js
Labels: Type: Bug, cla: yes

#934 Change placeholder text for pre-publish panel
  assets/src/edit-story/components/inspector/prepublish/prepublishInspector.js
Labels: Type: Enhancement, cla: yes

#937 Fix spinner / progress bar when saving
  assets/src/edit-story/components/circularProgress/index.js
  assets/src/edit-story/components/circularProgress/stories/index.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/test/buttons.js
  package-lock.json
  package.json
Labels: Type: Bug, cla: yes

#939 Fix storybook hierarchy
  assets/src/edit-story/components/button/stories/index.js
  assets/src/edit-story/components/colorPicker/stories/index.js
  assets/src/edit-story/components/form/dropDown/stories/index.js
  assets/src/edit-story/components/form/stories/radioGroup.js
  assets/src/edit-story/components/form/stories/switch.js
  assets/src/edit-story/components/modal/stories/index.js
  assets/src/edit-story/components/rangeInput/stories/index.js
  assets/src/edit-story/components/switch/stories/index.js
  assets/src/edit-story/components/tooltip/stories/index.js
Labels: Type: Infrastructure, cla: yes

#941 Update react-moveable and disable snap digits again
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  package-lock.json
  package.json
Labels: Dependencies, cla: yes

#926 Finished initial pass on Dashboard My Stories Page UI Grid View
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGrid/test/card-grid.js
  assets/src/dashboard/components/cardGridItem/card-preview.js
  assets/src/dashboard/components/cardGridItem/card-title.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/cardGridItem/test/card-grid-item.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/constants.js
  assets/src/dashboard/icons/grid.svg
  assets/src/dashboard/icons/list.svg
  assets/src/dashboard/icons/playArrow.svg
  assets/src/dashboard/theme.js
Labels: cla: yes

#912 Add Snackbar for Invalid Links.
  assets/src/edit-story/components/panels/link/index.js
  includes/REST_API/Link_Controller.php
  tests/phpunit/tests/REST_API/Link_Controller.php
Labels: Type: Bug, Type: Enhancement, cla: yes

#927 Update font weights names, select nearest font weights changing font family
  assets/src/edit-story/app/font/fontProvider.js
  assets/src/edit-story/components/panels/textStyle/font.js
Labels: cla: yes

#837 Use Thumbnails in media library.
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/app/media/utils/getResourceFromAttachment.js
  assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js
  assets/src/edit-story/app/media/utils/getResourceFromUploadAPI.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  includes/Media.php
Labels: Media, Type: Enhancement, cla: yes

#907 Fix Firefox alignment issues on numeric fields.
  assets/src/edit-story/components/form/numeric.js
Labels: Type: Bug, cla: yes

#808 Set default bg mode and color for new texts
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textTab.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#813 Fetch all authors from REST API and make dropdown scrollable
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
Labels: Needs Cherry-Picking, cla: yes

#919 Dashboard: My Stories Search (part 1)
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/myStoriesSearch.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadOptions/index.js
  assets/src/dashboard/components/typeaheadOptions/stories/index.js
  assets/src/dashboard/components/typeaheadOptions/test/typeaheadOptions.js
  assets/src/dashboard/components/typography.js
Labels: Type: Enhancement, cla: yes

#940 Enable publish/unpublish buttons
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/test/buttons.js
  includes/Story_Post_Type.php
Labels: Type: Bug, cla: yes

#955 Fixes a couple of bugs surrounding text edit component and colors.
  assets/src/edit-story/elements/text/edit.js
Labels: cla: yes

#957 Fix Save Story.
  assets/src/edit-story/app/story/actions/useSaveStory.js
Labels: Type: Bug, cla: yes

#966 Fully clear out inline styles after all transforms are complete + tests
  assets/src/edit-story/components/canvas/test/_utils.js
  assets/src/edit-story/elements/media/display.js
  assets/src/edit-story/elements/media/test/display.test.js
Labels: cla: yes

#963 Ignore background color when text mode is set to transparent bg
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/output.js
Labels: Group: Editing, cla: yes

#938 Detect moving distance for entering Text edit mode.
  assets/src/edit-story/elements/text/frame.js
Labels: cla: yes

#946 Custom scrollbars to match with rest of editor
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/constants.js
Labels: Type: Enhancement, cla: yes

#974 Fix loading message
  assets/src/edit-story/style.css
Labels: cla: yes

#970 Simplify upload overlay
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
  assets/src/edit-story/components/library/libraryUploadDropTarget.js
  assets/src/edit-story/components/uploadDropTarget/index.js
  assets/src/edit-story/components/uploadDropTarget/message.js
  assets/src/edit-story/components/uploadDropTarget/overlay.js
Labels: Type: Enhancement, cla: yes

#988 AMP Validation: Fix `font-fallback` inline style appearing for text elements
  assets/src/edit-story/elements/text/util.js
Labels: Type: Bug, cla: yes

#968 Flush output buffers before rendering story
  includes/Story_Post_Type.php
  includes/templates/single-web-story.php
Labels: Type: Bug, cla: yes

#753 Color presets: version 1
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/colorPicker/colorPicker.js
  assets/src/edit-story/components/form/color/color.js
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/inspector/design/designInspector.js
  assets/src/edit-story/components/panels/colorPreset.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/shapeStyle.js
  assets/src/edit-story/components/panels/stylePreset/colorPresetActions.js
  assets/src/edit-story/components/panels/stylePreset/index.js
  assets/src/edit-story/components/panels/stylePreset/test/colorPresetActions.js
  assets/src/edit-story/components/panels/stylePreset/test/stylePreset.js
  assets/src/edit-story/components/panels/stylePreset/test/utils.js
  assets/src/edit-story/components/panels/stylePreset/utils.js
  assets/src/edit-story/components/panels/test/colorPreset.js
  assets/src/edit-story/components/panels/textStyle/color.js
  assets/src/edit-story/components/panels/utils/getColorPickerActions.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/icons/remove.svg
  assets/src/edit-story/theme.js
  includes/REST_API/Stories_Controller.php
  package-lock.json
Labels: Type: Enhancement, cla: yes

#954 Dashboard: My Stories Search (part 2 - updating heading, clean up files)
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/myStoriesSearch.js
  assets/src/dashboard/app/views/myStories/noResults.js
  assets/src/dashboard/app/views/myStories/pageHeading.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadOptions/index.js
  assets/src/dashboard/components/typography.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#982 Added ability to preview stories from dashboard
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/font/fontProvider.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/cardGridItem/card-preview.js
  assets/src/dashboard/components/previewPage.js
  assets/src/dashboard/constants.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/usePagePreviewSize.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  includes/Dashboard.php
Labels: cla: yes

#996 Saner text defaults
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textTab.js
  assets/src/edit-story/elements/text/index.js
Labels: cla: yes

#986 Use portal for Calendar
  assets/src/edit-story/components/form/dateTime/index.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/popup/index.js
  assets/src/edit-story/components/popup/test/popup.js
Labels: Type: Enhancement, cla: yes

#977 Hide admin notices on editor and dashboard screens
  assets/src/dashboard/style.css
  assets/src/edit-story/style.css
Labels: Type: Bug, cla: yes

#998 Fix missing createInterpolateElement import
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/panels/backgroundDisplay/dialogContent.js
  assets/src/edit-story/components/panels/link/dialogContent.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#1003 Fix getting image src.
  includes/Story_Post_Type.php
Labels: Needs Cherry-Picking, cla: yes

#987 Resize elements by edges
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/movable/moveStyle.js
Labels: Needs Cherry-Picking, Type: Enhancement, cla: yes

#894 Update all elements with same videoId when generate video poster
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducer.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/index.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateVideoElementsByVideoId.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/utils.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateVideoElementsByVideoId.js
  assets/src/edit-story/app/story/useStoryReducer/types.js
Labels: Type: Bug, cla: yes

#1013 Video spacing
  assets/src/edit-story/components/library/panes/media/mediaElement.js
Labels: Type: Bug, cla: yes

#1015 Fix console error on hover play
  assets/src/edit-story/components/library/panes/media/mediaElement.js
Labels: Type: Bug, cla: yes

#1036 Dashboard: No Stories Default Display
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/pageHeading.js
  assets/src/dashboard/app/views/myStories/storyGridView.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/types.js
Labels: cla: yes

#895 Fix Toggle space and Rotation Angle exceeding 360
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/test/sizePosition.js
Labels: Type: Bug, cla: yes

#1047 Ensure that every path ends with a closepath function
  assets/src/edit-story/masks/index.js
  assets/src/edit-story/masks/test/index.js
Labels: cla: yes

#1012 Dashboard: Disable incomplete links for dashboard
  assets/src/dashboard/constants.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#975 Disable functionality that has not been implemented yet.
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/library/common/searchInput.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/text/textPane.js
Labels: Type: Enhancement, cla: yes

#1025 Page advancement fixes
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/test/page.js
Labels: Type: Bug, cla: yes

#995 Dashboard: Add support for opening story in editor
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/storyGridView.js
  assets/src/dashboard/components/cardGridItem/card-preview.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  includes/Dashboard.php
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#1069 Add support for webm
  includes/Story_Post_Type.php
Labels: Needs Cherry-Picking, Type: Enhancement, cla: yes

#1078 Dashboard: responsive tweaks for grid
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/theme.js
Labels: Type: Enhancement, cla: yes

#1049 Color picker styling improvements
  assets/src/edit-story/components/colorPicker/colorPicker.js
  assets/src/edit-story/components/colorPicker/currentColorPicker.js
  assets/src/edit-story/components/colorPicker/editablePreview.js
  assets/src/edit-story/components/colorPicker/gradientPicker.js
  assets/src/edit-story/components/colorPicker/header.js
  assets/src/edit-story/components/panels/stylePreset/colorPresetActions.js
  assets/src/edit-story/components/sidebar/provider.js
Labels: Type: Enhancement, cla: yes

#1046 Added template json for Travel template
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/font/fontProvider.js
  assets/src/dashboard/templates/data/travel.json
  assets/src/dashboard/templates/stories/travel.js
Labels: cla: yes

#852 Fix exiting edit mode by clicking anywhere
  assets/src/edit-story/components/canvas/editLayer.js
Labels: Type: Bug, cla: yes

#1087 Added contextual menu to stories in dashboard
  assets/src/dashboard/app/views/myStories/storyGridView.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardItemMenu.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/popover-menu/index.js
  assets/src/dashboard/constants.js
  assets/src/dashboard/icons/moreVertical.svg
Labels: cla: yes

#1095 Fix auto-advance-after when there are only images
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/output/utils/getLongestMediaElement.js
  assets/src/edit-story/output/utils/test/getLongestMediaElement.js
Labels: Type: Bug, cla: yes

#1091 Dashboard: Responsive Style Updates
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/pageHeading.js
  assets/src/dashboard/app/views/myStories/storyGridView.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/cardItemMenu.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/navigationBar.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typography.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/style.css
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/usePagePreviewSize.js
Labels: Type: Enhancement, cla: yes

#1079 Support caretPositionFromPoint for FF
  assets/src/edit-story/utils/getCaretCharacterOffsetWithin.js
Labels: Type: Bug, cla: yes

#1037 Fix poster on drop upload
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/useMediaReducer/actions.js
  assets/src/edit-story/app/media/useMediaReducer/reducer.js
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/app/media/utils/getResourceFromAttachment.js
  assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js
  assets/src/edit-story/app/media/utils/getResourceFromUploadAPI.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducer.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/index.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElementsByResourceId.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateElementsByResourceId.js
  assets/src/edit-story/app/story/useStoryReducer/types.js
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/elements/image/test/output.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/test/output.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0013_videoIdToId.js
  assets/src/edit-story/migration/migrations/v0013_videoIdToId.js
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/types.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#1098 Quote font names
  assets/src/edit-story/elements/text/test/output.js
  assets/src/edit-story/elements/text/test/util.js
  assets/src/edit-story/elements/text/util.js
Labels: Type: Bug, cla: yes

#1124 Make sure that poster image fills video tag
  assets/src/edit-story/components/library/panes/media/mediaElement.js
Labels: Media, Needs Cherry-Picking, Type: Bug, cla: yes

#1107 Dashboard: Story Grid Media Query/Resize Clean Up
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/cardItemMenu.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/constants.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/usePagePreviewSize.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#1101 Add alt to image tags
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/media/utils/getResourceFromAttachment.js
  assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js
  assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js
  assets/src/edit-story/app/media/utils/getResourceFromUploadAPI.js
  assets/src/edit-story/app/media/utils/index.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/elements/media/edit.js
Labels: Media, Needs Cherry-Picking, Type: Bug, cla: yes

#1136 Fixes resizing of highlight text
  assets/src/edit-story/elements/text/display.js
Labels: Needs Cherry-Picking, Text, cla: yes

#1133 Fix empty lines duplicating when editing text fields.
  assets/src/edit-story/elements/text/edit.js
Labels: Needs Cherry-Picking, cla: yes

#1129 Add default background element when adding a new Page.
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/elements/test/index.js
Labels: Type: Bug, cla: yes

#1140 Quick fix: image should be centered in the layer container
  assets/src/edit-story/elements/media/visibleImage.js
Labels: cla: yes

#1139 Fix layering to ensure frames do not block nav items and edit layer covers everything
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/navLayer.js
Labels: cla: yes

#1143 Polished up dashboard story grid
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/cardGridItem/test/cardGridItem.js
  assets/src/dashboard/theme.js
Labels: cla: yes

#877 Add usePreventWindowUnload hook.
  assets/src/edit-story/app/history/historyProvider.js
  assets/src/edit-story/app/history/useHistoryReducer.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/utils/test/usePreventWindowUnload.test.js
  assets/src/edit-story/utils/usePreventWindowUnload.js
Labels: Type: Bug, Type: Enhancement, UX, cla: yes

#992 Use focus out event instead of unmount to set content property
  assets/src/edit-story/elements/text/edit.js
Labels: Type: Bug, cla: yes

#1006 Unable to use scrollbar in dropdown, use popup
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/popup/index.js
Labels: Needs Cherry-Picking, cla: yes

#1148 Simple focus-to-canvas improvements
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/useEditingElement.js
  assets/src/edit-story/components/canvas/useFocusCanvas.js
  assets/src/edit-story/components/canvas/useInsertElement.js
Labels: cla: yes

#1157 Fix video controls on drop targets
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/frameElement.js
Labels: cla: yes

#1153 Drop targets as a single history item
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducer.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/index.js
  assets/src/edit-story/app/story/useStoryReducer/types.js
  assets/src/edit-story/components/dropTargets/provider.js
Labels: cla: yes

#803 Reordering page thumbnails and the grid view
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/draggablePage.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/dropzone/context.js
  assets/src/edit-story/components/dropzone/dropZoneProvider.js
  assets/src/edit-story/components/dropzone/index.js
  assets/src/edit-story/components/dropzone/useDropZone.js
  assets/src/edit-story/components/modal/index.js
  assets/src/edit-story/components/panels/layer/layerList.js
  assets/src/edit-story/components/panels/layer/panel.js
  assets/src/edit-story/components/reorderable/reorderable.js
  assets/src/edit-story/components/reorderable/reorderableItem.js
  assets/src/edit-story/components/reorderable/reorderableScroller.js
  assets/src/edit-story/components/reorderable/reorderableSeparator.js
  assets/src/edit-story/components/reorderable/useReordering.js
  assets/src/edit-story/components/reorderable/useScroll.js
  assets/src/edit-story/utils/test/useLiveRegion.js
  assets/src/edit-story/utils/useLiveRegion.js
Labels: Type: Enhancement, cla: yes

#1145 Dashboard: Popover Panel UI Component
  assets/src/dashboard/app/views/templatesGallery/index.js
  assets/src/dashboard/components/cardGridItem/cardItemMenu.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/dropdown/stories/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/pill/index.js
  assets/src/dashboard/components/pill/stories/index.js
  assets/src/dashboard/components/pill/test/pill.js
  assets/src/dashboard/components/popoverMenu/index.js
  assets/src/dashboard/components/popoverMenu/stories/index.js
  assets/src/dashboard/components/popoverMenu/test/popover-menu.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/dashboard/components/popoverPanel/stories/index.js
  assets/src/dashboard/components/popoverPanel/test/popverPanel.js
  assets/src/dashboard/components/typeaheadOptions/index.js
  assets/src/dashboard/components/types.js
Labels: cla: yes

#1146 Add support for editing from context menu.
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/components/cardGridItem/cardItemMenu.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/constants.js
Labels: cla: yes

#1161 Scrollbar enhancements
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/inspector/design/designInspector.js
  assets/src/edit-story/theme.js
Labels: cla: yes

#1152 All links are two-tap links
  assets/src/edit-story/migration/migrations/v0014_oneTapLinkDeprecate.js
Labels: cla: yes

#1144 Fix duplicate element ids when duplicating page
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/elements/test/index.js
Labels: cla: yes

#1147 Reconcile display and output markup and styling for padding and highlight
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/test/output.js
  assets/src/edit-story/theme.js
  assets/src/edit-story/utils/textMeasurements.js
Labels: cla: yes

#965 Dashboard: My Stories Search (part 3, apiProvider update)
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/views/myStories/index.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#1122 Save story before showing the preview
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/test/buttons.js
  assets/src/edit-story/utils/escapeHTML.js
Labels: Type: Enhancement, cla: yes

#1189 Don't steal focus from the design panel when the edit mode exits
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/useEditingElement.js
  assets/src/edit-story/components/canvas/useFocusCanvas.js
Labels: cla: yes

#1169 Ensure valid HTML in text
  assets/src/edit-story/elements/text/test/util.js
  assets/src/edit-story/elements/text/util.js
Labels: cla: yes

#1188 Fixed layer selection by reverting focus to canvas
  assets/src/edit-story/components/panels/layer/layerList.js
  assets/src/edit-story/components/panels/layer/useLayerSelection.js
Labels: Type: Enhancement, cla: yes

#1162 Dashboard: Sort Dropdown for views
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/index.js
  assets/src/dashboard/app/views/shared/listBarContainer.js
  assets/src/dashboard/app/views/templatesGallery/index.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/constants.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#1198 Add back curly eslint rule
  .eslintrc
  assets/src/edit-story/app/media/useMediaReducer/reducer.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElementsByResourceId.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/components/panels/utils/getBoundRect.js
  assets/src/edit-story/elements/video/frame.js
Labels: Type: Infrastructure, cla: yes

#1105 Basic text paste
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textTab.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/utils/processPastedNodeList.js
  assets/src/edit-story/utils/test/escapeHTML.js
  assets/src/edit-story/utils/test/processPastedNodeList.js
Labels: Type: Enhancement, cla: yes

#1187 Changed exit to be on pointerdown, not click
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/utils/useFocusOut.js
Labels: cla: yes

#1174 Execute focusout callback when element is removed (and was focused)
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/utils/useUnmount.js
Labels: cla: yes

#1219 Use Error Boundary around preview
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/components/previewErrorBoundary.js
Labels: cla: yes

#1173 Dashboard: Bugfix - Conflicting Pill Styling
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/pill/index.js
Labels: Group: Dashboard, cla: yes

#1075 Element lock ratio for size and padding should be stored to data model
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/padding.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/types.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#1171 Dashboard: Link option on 'Button' Component
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/button/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/navigationBar.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#1205 Dashboard: Add List View UI to Dashboard
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/index.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/components/table/stories/table.js
  assets/src/dashboard/constants.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/usePagePreviewSize.js
Labels: cla: yes

#1068 Update ESLint config
  .eslintrc
  assets/src/dashboard/app/views/shared/noResults.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/arrangeElement.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
  assets/src/edit-story/components/colorPicker/gradientLine.js
  assets/src/edit-story/components/colorPicker/gradientStop.js
  assets/src/edit-story/components/colorPicker/test/useColor/removeCurrentStop.js
  assets/src/edit-story/components/colorPicker/useColor.js
  assets/src/edit-story/components/form/color/getPreviewText.js
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/inspector/document/pageAdvancement.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/components/reorderable/useReordering.js
  assets/src/edit-story/migration/migrations/v0006_colorToPattern.js
  assets/src/edit-story/migration/migrations/v0008_paddingToObject.js
  assets/src/edit-story/utils/addQueryArgs.js
  assets/src/edit-story/utils/generatePatternStyles.js
  assets/src/edit-story/utils/url.js
  package-lock.json
  package.json
  tests/e2e/config/bootstrap.js
Labels: Type: Infrastructure, cla: yes

#1243 Dashboard: [TASK] Popover Menu Dynamic Alignment
  assets/src/dashboard/components/cardGridItem/cardItemMenu.js
  assets/src/dashboard/components/popoverMenu/index.js
  assets/src/dashboard/components/popoverMenu/popoverRevealer.js
  assets/src/dashboard/components/typeaheadOptions/index.js
  assets/src/dashboard/constants/animation.js
  assets/src/dashboard/constants/direction.js
  assets/src/dashboard/constants/index.js
Labels: cla: yes

#1250 Dashboard: Infinite Scroll Component
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/infiniteScroller/index.js
  assets/src/dashboard/components/infiniteScroller/stories/index.js
  assets/src/dashboard/components/infiniteScroller/test/infiniteScroller.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#1220 Template Detail: Added template info section
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/bodyWrapper.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/components/navigationBar.js
  assets/src/dashboard/components/types.js
  assets/src/dashboard/templates/index.js
  assets/src/dashboard/theme.js
Labels: cla: yes

#1248 Fix text element not registering the first keystroke
  assets/src/edit-story/elements/text/util.js
Labels: Type: Bug, cla: yes

#1254 Fix dev/prod mode issue
  package.json
  webpack.config.js
Labels: Type: Infrastructure, cla: yes

#1255 Dashboard: Use empty i18n helper to make storybook work
  assets/src/dashboard/app/views/shared/storyListView.js
Labels: Type: Infrastructure, cla: yes

#1256 Dashboard: Remove circular imports from dashboard app
  assets/src/dashboard/app/index.js
  assets/src/dashboard/components/navigationBar.js
Labels: Group: Dashboard, Type: Bug, cla: yes

#1253 [TASK] Remove Story Flash
  assets/src/dashboard/utils/usePagePreviewSize.js
Labels: cla: yes

#1116 Update text element issue on edit mode
  assets/src/edit-story/elements/text/edit.js
Labels: P0, Type: Bug, cla: yes

#1252 Template Detail: Updated header and added left/right controls
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/bookmark-chip/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/multiPartPill/index.js
  assets/src/dashboard/components/multiPartPill/stories/index.js
  assets/src/dashboard/components/navigationBar/components.js
  assets/src/dashboard/components/navigationBar/index.js
  assets/src/dashboard/components/navigationBar/mainNavBar.js
  assets/src/dashboard/components/navigationBar/stories/index.js
  assets/src/dashboard/components/navigationBar/templateNavBar.js
  assets/src/dashboard/icons/left-arrow.svg
  assets/src/dashboard/icons/right-arrow.svg
  assets/src/dashboard/theme.js
Labels: cla: yes

#1193 Alignment panel fix for single element
  assets/src/edit-story/components/panels/alignment/alignment.js
  assets/src/edit-story/components/panels/alignment/test/useAlignment.js
  assets/src/edit-story/components/panels/test/alignment.js
Labels: Type: Bug, cla: yes

#1267 Exclude template assets from plugin bundle for now
  .distignore
Labels: Type: Infrastructure, cla: yes

#1274 Ignore travis deployment file in builds
  .distignore
Labels: Type: Infrastructure, cla: yes

#1282 Added list view sorting for dashboard
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/icons/download.svg
  assets/src/dashboard/theme.js
Labels: cla: yes

#864 Fix Babel config to use correct browserslist config
  babel.config.js
  package-lock.json
  package.json
Labels: Type: Infrastructure, cla: yes

#1299 Improve text-overflow in layers panel
  assets/src/edit-story/components/panels/layer/layer.js
Labels: Type: Enhancement, cla: yes

#1278 Dashboard infinite scroll implementation (My Stories)
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/infiniteScroller/index.js
  assets/src/dashboard/components/infiniteScroller/stories/index.js
  assets/src/dashboard/components/infiniteScroller/test/infiniteScroller.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/utils/clamp.js
  assets/src/dashboard/utils/groupBy.js
  assets/src/dashboard/utils/test/clamp.js
  assets/src/dashboard/utils/test/groupBy.js
Labels: cla: yes

#1289 Issue 1281: Added template api to consolidate all template endpoints
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/__snapshots__/useTemplateApi.js.snap
  assets/src/dashboard/app/api/test/useTemplateApi.js
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/api/wpAdapter.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/templates/index.js
Labels: cla: yes

#1307 Dashboard: infinite scrolling messaging styled
  assets/src/dashboard/components/infiniteScroller/index.js
  assets/src/dashboard/components/infiniteScroller/test/infiniteScroller.js
Labels: Group: Dashboard, cla: yes

#1315 Update code coverage configuration
  .travis.yml
  codecov.yml
Labels: Type: Infrastructure, cla: yes

#1306 Added a hover state for the main buttons (i.e Upload)
  assets/src/edit-story/components/library/common/index.js
  assets/src/edit-story/theme.js
Labels: Type: Enhancement, cla: yes

#1313 Grid View: change current page upon selection
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/gridview/test/gridview.js
Labels: Type: Enhancement, cla: yes

#1311 Added a focus css for search input (minor changes to placeholder color)
  assets/src/edit-story/components/library/common/searchInput.js
  assets/src/edit-story/theme.js
Labels: Group: Media, Type: Enhancement, cla: yes

#1320 Dashboard: Scroll to Top (my stories + storybook)
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/dashboard/components/scrollToTop/index.js
  assets/src/dashboard/components/scrollToTop/stories/index.js
  assets/src/dashboard/components/scrollToTop/test/scrollToTop.js
  assets/src/dashboard/icons/dropDownArrow.svg
  assets/src/dashboard/icons/dropUpArrow.svg
  assets/src/dashboard/style.css
  assets/src/dashboard/utils/getCurrentYAxis.js
Labels: Group: Dashboard, cla: yes

#1297 Fix useLoadStory to load the publish date in UTC time
  assets/src/edit-story/app/api/test/_utils.js
  assets/src/edit-story/app/story/effects/test/useLoadStory.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
Labels: Type: Bug, cla: yes

#1317 Enable E2E Tests on Firefox
  .distignore
  .eslintrc
  .travis.yml
  bin/local-env/install-wordpress.sh
  jest-puppeteer.config.js
  package-lock.json
  package.json
  tests/e2e/config/bootstrap.js
Labels: Type: Infrastructure, cla: yes

#1316 Handle paste processing only when not dealing with files.
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
Labels: cla: yes

#1327 Unskip tests
  assets/src/edit-story/components/link/test/output.js
  assets/src/edit-story/elements/image/test/output.js
  assets/src/edit-story/elements/video/test/output.js
  assets/src/edit-story/masks/test/output.js
  assets/src/edit-story/output/test/page.js
Labels: Type: Infrastructure, cla: yes

#1247 Use auto-save for preview
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/story/actions/test/useAutoSave.js
  assets/src/edit-story/app/story/actions/useAutoSave.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/app/story/utils/getStoryPropsToSave.js
  assets/src/edit-story/app/story/utils/test/getStoryPropsToSave.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/test/buttons.js
  assets/src/edit-story/output/utils/getStoryMarkup.js
  assets/src/edit-story/output/utils/test/getStoryMarkup.js
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
Labels: cla: yes

#1322 Dashboard: Rename Story
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/test/wpAdapter.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/test/cartTitle.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/input/index.js
  assets/src/dashboard/components/input/stories/index.js
  assets/src/dashboard/theme.js
Labels: cla: yes

#1333 Dashboard: Move story and font actions to their own files
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/test/useStoryApi.js
  assets/src/dashboard/app/api/useFontApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/font/fontProvider.js
  assets/src/dashboard/app/views/myStories/index.js
Labels: Group: Dashboard, Size: XS, cla: yes

#1096 Updated Build and Continuous Integration Tooling
  .eslintrc
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/bundle-size.yml
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-drafter.yml
  .github/workflows/update-google-fonts.yml
  .nvmrc
  .travis.yml
  bin/commander.js
  bin/deploy-to-test-environment.sh
  composer.lock
  includes/templates/single-web-story.php
  package.json
Labels: Type: Infrastructure, cla: yes

#1356 Allow php nightly tests to fail
  .travis.yml
Labels: Type: Infrastructure, cla: yes

#1357 Use relative paths for lint-staged
  package.json
Labels: Type: Infrastructure, cla: yes

#1309 Added next/previous controls to template detail view
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/router/index.js
  assets/src/dashboard/app/router/route.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGallery/test/cardGallery.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/constants/index.js
Labels: Group: Dashboard, Group: Templates, Type: Enhancement, cla: yes

#1337 Dashboard: Theme Clean Up
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/noResults.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/components/bookmark-chip/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/infiniteScroller/index.js
  assets/src/dashboard/components/input/index.js
  assets/src/dashboard/components/multiPartPill/index.js
  assets/src/dashboard/components/navigationBar/components.js
  assets/src/dashboard/components/navigationBar/templateNavBar.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/dashboard/components/pill/index.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/dashboard/components/scrollToTop/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadOptions/index.js
  assets/src/dashboard/components/typography.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, cla: yes

#1335 Dashboard: Set up templates for infinite scroll
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/reducer/templates.js
  assets/src/dashboard/app/reducer/test/templates.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/utils/index.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#1364 Dashboard: Color and Categories Filters UI for Templates Gallery
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/app/views/templates/templateFilters.js
  assets/src/dashboard/app/views/templates/test/templateFilters.js
  assets/src/dashboard/components/colorDot.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/pill/index.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/constants/templates.js
  assets/src/dashboard/theme.js
  package-lock.json
Labels: Group: Dashboard, cla: yes

#1355 hide link panel when an element is fill
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/link/index.js
Labels: cla: yes

#1340 Fix fallback logic for image and video element accessibility and title fields
  assets/src/edit-story/components/panels/imageAccessibility.js
  assets/src/edit-story/components/panels/videoAccessibility.js
  assets/src/edit-story/elements/image/output.js
  assets/src/edit-story/elements/image/test/output.js
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/elements/video/test/output.js
Labels: Type: Bug, cla: yes

#1329 Preview media when uploading via paste
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
  assets/src/edit-story/components/canvas/useUploadWithPreview.js
  assets/src/edit-story/types.js
Labels: cla: yes

#1326 Replace mime types with file extensions in error message
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/library/test/_utils/index.js
  assets/src/edit-story/components/uploadDropTarget/message.js
Labels: Type: Bug, cla: yes

#1353 Dashboard: Delete and Duplicate Stories
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
Labels: Group: Dashboard, cla: yes

#1339 Added useIsKeyPressed (and global) hooks for key presses.
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/keyboard/test/index.test.js
Labels: Type: Code Quality, Type: Enhancement, cla: yes

#1377 Simplify `PropTypes.node` usage
  assets/src/dashboard/animations/animator/output.js
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/config/configProvider.js
  assets/src/dashboard/app/font/fontProvider.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/layout/fixed.js
  assets/src/dashboard/components/layout/provider.js
  assets/src/dashboard/components/layout/scrollable.js
  assets/src/dashboard/components/layout/squishable.js
  assets/src/dashboard/components/multiPartPill/index.js
  assets/src/dashboard/components/popoverMenu/index.js
  assets/src/dashboard/components/popoverMenu/popoverCard.js
  assets/src/dashboard/components/popoverMenu/popoverStandard.js
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/config/configProvider.js
  assets/src/edit-story/app/font/fontProvider.js
  assets/src/edit-story/app/history/historyProvider.js
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/snackbar/snackbarProvider.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/components/canvas/canvasElementDropzone.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
  assets/src/edit-story/components/canvas/selectionCanvas.js
  assets/src/edit-story/components/dialog/index.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/library/libraryUploadDropTarget.js
  assets/src/edit-story/components/link/frame.js
  assets/src/edit-story/components/link/output.js
  assets/src/edit-story/components/modal/index.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/panel/simplePanel.js
  assets/src/edit-story/components/panels/shared/note.js
  assets/src/edit-story/components/reorderable/reorderable.js
  assets/src/edit-story/components/reorderable/reorderableItem.js
  assets/src/edit-story/components/sidebar/provider.js
  assets/src/edit-story/components/tooltip/index.js
  assets/src/edit-story/components/transform/transformProvider.js
  assets/src/edit-story/components/uploadDropTarget/dropTarget.js
  assets/src/edit-story/elements/media/display.js
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/masks/frame.js
  assets/src/edit-story/masks/output.js
  assets/src/edit-story/types.js
  assets/src/edit-story/units/unitsProvider.js
Labels: Type: Infrastructure, cla: yes

#1374 Do not include `@wordpress/element` script in bundle
  webpack.config.js
Labels: Type: Infrastructure, cla: yes

#1343 Use Mousetrap for useKeyboardHandlers
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/panels/panel/shared/test/handle.js
  assets/src/edit-story/components/panels/panel/useKeyboardHandlers.js
Labels: Type: Code Quality, Type: Enhancement, cla: yes

#1314 Hide blue indicator when there is only one page
  assets/src/edit-story/components/canvas/carousel/compactIndicator.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
Labels: Type: Enhancement, cla: yes

#1403 Playground: add missing config
  .storybook/stories/playground/index.js
Labels: Type: Infrastructure, cla: yes
