Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-05, with the labels that each got.

#1418 Dashboard 1286: Implementin Toggle Button Group (my stories)
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/toggleButtonGroup/index.js
Labels: cla: yes

#1409 Update SVG icons
  assets/src/dashboard/icons/checkmark.svg
  assets/src/dashboard/icons/moreVertical.svg
  assets/src/edit-story/icons/close_icon.svg
  assets/src/edit-story/icons/default_image.svg
  assets/src/edit-story/icons/edit_pencil.svg
  assets/src/edit-story/icons/external.svg
  assets/src/edit-story/icons/fill_filled_icon.svg
  assets/src/edit-story/icons/fill_highlighted_icon.svg
  assets/src/edit-story/icons/info.svg
  assets/src/edit-story/icons/keyboard.svg
  assets/src/edit-story/icons/layout_helper.svg
  assets/src/edit-story/icons/link.svg
  assets/src/edit-story/icons/overlay_linear.svg
  assets/src/edit-story/icons/overlay_none.svg
  assets/src/edit-story/icons/overlay_radial.svg
  assets/src/edit-story/icons/overlay_solid.svg
  assets/src/edit-story/icons/pause.svg
  assets/src/edit-story/icons/play.svg
  assets/src/edit-story/icons/radio-selected.svg
  assets/src/edit-story/icons/radio.svg
  assets/src/edit-story/icons/remove.svg
  assets/src/edit-story/icons/text_helper.svg
Labels: Type: Infrastructure, cla: yes

#1368 Templates: Added static DIY template
  assets/images/templates/diy/diy_icon_arrow.png
  assets/images/templates/diy/diy_icon_fb.png
  assets/images/templates/diy/diy_icon_insta.png
  assets/images/templates/diy/diy_icon_org_cross.png
  assets/images/templates/diy/diy_icon_tw.png
  assets/images/templates/diy/diy_icon_up_arrow.png
  assets/images/templates/diy/diy_icon_wh_cross.png
  assets/images/templates/diy/diy_icon_yt.png
  assets/images/templates/diy/diy_page1_bg.jpg
  assets/images/templates/diy/diy_page2_bg.jpg
  assets/images/templates/diy/diy_page3_image1.jpg
  assets/images/templates/diy/diy_page4_page5_bg.jpg
  assets/images/templates/diy/diy_page6_bg.jpg
  assets/images/templates/diy/diy_page7_bg.jpg
  assets/images/templates/diy/diy_page8_image1.jpg
  assets/images/templates/diy/diy_page8_image2.jpg
  assets/images/templates/diy/diy_page8_image3.jpg
  assets/images/templates/travel/travel_icon_fb.png
  assets/images/templates/travel/travel_icon_insta.png
  assets/images/templates/travel/travel_icon_tw.png
  assets/images/templates/travel/travel_icon_up_arrow.png
  assets/images/templates/travel/travel_icon_yt.png
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/templates/data/diy.js
  assets/src/dashboard/templates/data/travel.js
  assets/src/dashboard/templates/index.js
Labels: cla: yes

#1423 Templates: Added static Cooking template
  assets/images/templates/cooking/cooking_icon_arrow.png
  assets/images/templates/cooking/cooking_icon_artichoke.png
  assets/images/templates/cooking/cooking_icon_carrot.png
  assets/images/templates/cooking/cooking_icon_eggplant.png
  assets/images/templates/cooking/cooking_icon_facebook.png
  assets/images/templates/cooking/cooking_icon_garlic.png
  assets/images/templates/cooking/cooking_icon_instagram.png
  assets/images/templates/cooking/cooking_icon_lettuce.png
  assets/images/templates/cooking/cooking_icon_logo.png
  assets/images/templates/cooking/cooking_icon_mushroom.png
  assets/images/templates/cooking/cooking_icon_persimmon.png
  assets/images/templates/cooking/cooking_icon_pickle.png
  assets/images/templates/cooking/cooking_icon_radish.png
  assets/images/templates/cooking/cooking_icon_salad.png
  assets/images/templates/cooking/cooking_icon_twitter.png
  assets/images/templates/cooking/cooking_icon_up_arrow.png
  assets/images/templates/cooking/cooking_icon_youtube.png
  assets/images/templates/cooking/cooking_page1_bg.jpg
  assets/images/templates/cooking/cooking_page3_image1.jpg
  assets/images/templates/cooking/cooking_page5_bg.jpg
  assets/images/templates/cooking/cooking_page7_bg.jpg
  assets/images/templates/cooking/cooking_page8_bg.jpg
  assets/images/templates/cooking/cooking_page9_image1.jpg
  assets/images/templates/cooking/cooking_page9_image2.jpg
  assets/images/templates/cooking/cooking_page9_image3.jpg
  assets/images/templates/cooking/cooking_page9_image4.jpg
  assets/src/dashboard/templates/data/cooking.js
  assets/src/dashboard/templates/index.js
Labels: cla: yes

#1310 Universal fullbleed and safezone
  .github/workflows/update-google-fonts.yml
  assets/images/do-not-fit.png
  assets/images/fit-to-device.png
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/utils/usePagePreviewSize.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/library/text/fontPreview.js
  assets/src/edit-story/components/panels/alignment/alignment.js
  assets/src/edit-story/components/panels/backgroundDisplay/dialogContent.js
  assets/src/edit-story/components/panels/backgroundDisplay/index.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/test/backgroundDisplay.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/media/index.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0016_isFullbleedDeprecate.js
  assets/src/edit-story/migration/migrations/v0016_isFullbleedDeprecate.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/utils/styles.js
  assets/src/edit-story/units/dimensions.js
Labels: Type: Enhancement, cla: yes

#1442 #769 Dashboard: Create template from story context menu (needs API)
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/reducer/templates.js
  assets/src/dashboard/app/reducer/test/templates.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
Labels: Group: Dashboard, cla: yes

#1445 Dashboard: minor grid clean up
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/index.js
Labels: Group: Dashboard, cla: yes

#1420 Dashboard: Add API hooks for categories, tags, users. Connected the data fetched to the story's list UI.
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/fetchAllFromPages.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/test/useCategoryApi.js
  assets/src/dashboard/app/api/test/useTagsApi.js
  assets/src/dashboard/app/api/test/useUserApi.js
  assets/src/dashboard/app/api/useCategoriesApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useTagsApi.js
  assets/src/dashboard/app/api/useUserApi.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/types.js
  includes/Dashboard.php
Labels: cla: yes

#1361 Auto-Save (for Draft)
  assets/src/edit-story/app/history/historyProvider.js
  assets/src/edit-story/app/history/useHistoryReducer.js
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/components/autoSaveHandler/index.js
  assets/src/edit-story/components/autoSaveHandler/test/autoSaveHandler.js
  assets/src/edit-story/components/header/buttons.js
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
Labels: cla: yes

#1430 Style loading indicator
  assets/src/edit-story/components/library/panes/media/mediaPane.js
Labels: Group: Media, Type: Enhancement, cla: yes

#1463 Build tool: Remove errant leading slash
  .github/workflows/continuous-deployment.yml
Labels: Type: Infrastructure, cla: yes

#1460 Center Page Carousel
  assets/src/edit-story/components/canvas/carousel/index.js
Labels: Group: Carousel, Type: Enhancement, cla: yes

#1471 Fix `prebuild:fonts` script
  package.json
Labels: Type: Infrastructure, cla: yes

#1375 Unskip Google Fonts AMP validation test
  assets/src/edit-story/output/test/story.js
Labels: AMP, Type: Infrastructure, cla: yes

#1469 (Temporarily) Re-add templates assets to bundle
  .distignore
  assets/src/dashboard/templates/data/cooking.js
  assets/src/dashboard/templates/data/diy.js
  assets/src/dashboard/templates/data/fashion.js
  assets/src/dashboard/templates/data/travel.js
Labels: Group: Templates, Type: Infrastructure, cla: yes

#1446 [TEMPLATE] Fitness
  assets/images/templates/fitness/fitness_page1_bg-alt.png
  assets/images/templates/fitness/fitness_page1_bg.jpg
  assets/images/templates/fitness/fitness_page1_logo.png
  assets/images/templates/fitness/fitness_page2_figure-formatted.png
  assets/images/templates/fitness/fitness_page2_figure.jpg
  assets/images/templates/fitness/fitness_page3_bg.jpg
  assets/images/templates/fitness/fitness_page4_bg.jpg
  assets/images/templates/fitness/fitness_page5_bg.jpg
  assets/images/templates/fitness/fitness_page6_bg.jpg
  assets/images/templates/fitness/fitness_page6_watch.png
  assets/images/templates/fitness/fitness_page7_bg-formatted.png
  assets/images/templates/fitness/fitness_page7_bg.jpg
  assets/images/templates/fitness/fitness_page8_Facebook.png
  assets/images/templates/fitness/fitness_page8_Instagram.png
  assets/images/templates/fitness/fitness_page8_Twitter.png
  assets/images/templates/fitness/fitness_page8_Youtube.png
  assets/images/templates/fitness/fitness_page8_offsetblock.png
  assets/images/templates/fitness/fitness_page8_story1-formatted.png
  assets/images/templates/fitness/fitness_page8_story1.jpg
  assets/images/templates/fitness/fitness_page8_story2-formatted.png
  assets/images/templates/fitness/fitness_page8_story2.jpg
  assets/images/templates/fitness/fitness_page8_story3-formatted.png
  assets/images/templates/fitness/fitness_page8_story3.jpg
  assets/src/dashboard/templates/data/fitness.js
  assets/src/dashboard/templates/index.js
Labels: Group: Dashboard, Group: Templates, cla: yes

#1468 Move capabilities out of history
  assets/src/edit-story/app/story/effects/useHistoryEntry.js
  assets/src/edit-story/app/story/effects/useHistoryReplay.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js
  assets/src/edit-story/app/story/useStoryReducer/test/restore.js
  assets/src/edit-story/app/story/useStoryReducer/useStoryReducer.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/document/status.js
  assets/src/edit-story/components/inspector/document/test/publish.js
  assets/src/edit-story/components/inspector/document/test/status.js
  includes/Story_Post_Type.php
Labels: cla: yes

#1448 #778 Dashboard: Detail Template View - Related Templates UI
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/components/navigationBar/components.js
Labels: Group: Dashboard, cla: yes

#1532 Refactor detail nav files
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/navigationBar/components.js
  assets/src/dashboard/components/templateNavBar/index.js
  assets/src/dashboard/components/templateNavBar/stories/index.js
  assets/src/dashboard/components/templateNavBar/test/templateNavBar.js
Labels: Group: Dashboard, cla: yes

#1399 Complete Move of CI to GitHub Actions
  .github/workflows/continuous-integration.yml
  .github/workflows/release-assets.yml
  .github/workflows/update-google-fonts.yml
  .travis.yml
  bin/deploy-to-test-environment.sh
  bin/local-env/includes.sh
  bin/local-env/install-composer.sh
  bin/local-env/install-node-nvm.sh
Labels: Type: Infrastructure, cla: yes

#1543 Fix travis deployment
  .travis.yml
  bin/deploy-to-test-environment.sh
Labels: Type: Infrastructure, cla: yes

#1544 Revert latest Moveable update
  package-lock.json
  package.json
Labels: Type: Bug, cla: yes

#1462 Dashboard custom sorting: Filter orderby query
  assets/src/dashboard/constants/index.js
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
  tests/phpunit/tests/Story_Post_Type.php
  tests/phpunit/tests/Story_Renderer.php
Labels: PHP, Type: Enhancement, cla: yes

#1551 Dashboard: Clean up header styles and aligns them to the new designs
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/stories/pageHeading.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/toggleButtonGroup/index.js
  assets/src/dashboard/components/typeaheadInput/index.js
Labels: Group: Dashboard, cla: yes

#1536 Templates: Added static Entertainment template
  assets/images/templates/ent/ent_icon_fb.png
  assets/images/templates/ent/ent_icon_gray_star.png
  assets/images/templates/ent/ent_icon_insta.png
  assets/images/templates/ent/ent_icon_logo.png
  assets/images/templates/ent/ent_icon_twtr.png
  assets/images/templates/ent/ent_icon_up_arrow.png
  assets/images/templates/ent/ent_icon_white_star.png
  assets/images/templates/ent/ent_icon_yt.png
  assets/images/templates/ent/ent_page1_bg.jpg
  assets/images/templates/ent/ent_page2_image1.jpg
  assets/images/templates/ent/ent_page4_image1.jpg
  assets/images/templates/ent/ent_page5_image1.jpg
  assets/images/templates/ent/ent_page6_image1.jpg
  assets/images/templates/ent/ent_page7_image1.jpg
  assets/images/templates/ent/ent_page8_image1.jpg
  assets/images/templates/ent/ent_page8_image2.jpg
  assets/images/templates/ent/ent_page9_image1.jpg
  assets/images/templates/ent/ent_page9_image2.jpg
  assets/images/templates/ent/ent_page9_image3.jpg
  assets/images/templates/fitness/fitness_page3_arrow.png
  assets/src/dashboard/templates/data/entertainment.js
  assets/src/dashboard/templates/data/fashion.js
  assets/src/dashboard/templates/data/fitness.js
  assets/src/dashboard/templates/index.js
Labels: cla: yes

#1541 Loading indicator styling
  assets/src/edit-story/components/library/panes/media/mediaPane.js
Labels: Group: Media, Type: Bug, cla: yes

#1574 Remove Delete Page shortcut tooltip
  assets/src/edit-story/components/canvas/pagemenu/index.js
Labels: Type: Bug, cla: yes

#1431 Fix file drag & drop crash for unsupported media types
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/test/useUploadMedia.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  package-lock.json
  package.json
  tests/js/jest.setup.js
Labels: Group: Media, Type: Bug, cla: yes

#1473 Add a basic check for if current user can upload files
  assets/src/edit-story/app/media/test/useUploadMedia.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/uploader/test/useUploader.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/library/test/_utils/index.js
  assets/src/edit-story/components/mediaPicker/test/useMediaPicker.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/masks/output.js
  assets/src/edit-story/utils/createError.js
  assets/src/edit-story/utils/test/createError.js
  includes/Story_Post_Type.php
  package-lock.json
  package.json
  tests/phpunit/tests/Story_Post_Type.php
  tests/phpunit/tests/Story_Renderer.php
Labels: Group: Media, Type: Enhancement, cla: yes

#1573 Dashboard: renaming filteredStories prop throughout components/views
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/stories/pageHeading.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/shared/typeaheadSearch.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/app/views/templates/index.js
Labels: Group: Dashboard, cla: yes

#1553 Fixes editor resizing after fullbleed
  assets/src/edit-story/components/canvas/layout.js
Labels: Group: Canvas, Type: Bug, cla: yes

#1591 Fix initial height of preset panel
  assets/src/edit-story/components/panels/stylePreset/panel.js
  assets/src/edit-story/components/panels/stylePreset/presetGroup.js
  assets/src/edit-story/constants.js
Labels: Type: Bug, cla: yes

#1590 Deploy plugin bundle to wiki repo for easier QA
  .github/workflows/cleanup-pr-assets.yml
  .github/workflows/continuous-integration.yml
Labels: Type: Infrastructure, cla: yes

#1570 Dashboard: Search UI Updates
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadInput/stories/index.js
  assets/src/dashboard/components/typeaheadOptions/index.js
Labels: cla: yes

#1176 Allow disabling warning on exit in development
  assets/src/edit-story/utils/usePreventWindowUnload.js
  assets/src/edit-story/utils/useWhyDidYouUpdate.js
  docs/getting-started.md
Labels: cla: yes

#1566 Dashboard - refactor grid to resize with story ratio
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/constants/pageStructure.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/usePagePreviewSize.js
Labels: Group: Dashboard, cla: yes

#1461 Align flip buttons next to each other
  assets/src/edit-story/components/panels/backgroundSizePosition.js
  assets/src/edit-story/components/panels/shared/flipControls.js
Labels: Type: Bug, cla: yes

#1618 Fixes for DISABLE_PREVENT flag
  assets/src/edit-story/utils/usePreventWindowUnload.js
  docs/getting-started.md
  tests/js/jest.setup.js
  webpack.config.js
Labels: Type: Bug, cla: yes

#1476 Update developer documentation (first pass)
  .github/workflows/continuous-integration.yml
  .github/workflows/release-assets.yml
  .github/workflows/update-google-fonts.yml
  docs/README.md
  docs/architecture.md
  docs/browser-support.md
  docs/canvas.md
  docs/code-style.md
  docs/e2e-tests.md
  docs/environment-variables.md
  docs/getting-started.md
  docs/glossary.md
  docs/local-environment.md
  docs/migrations.md
  docs/staging-environment.md
  docs/storybook.md
  docs/testing-qa.md
  docs/unit-tests.md
  docs/workflows.md
  jest-puppeteer.config.js
  package.json
  tests/e2e/jest.config.js
  tests/js/jest.setup.js
Labels: Type: Documentation, cla: yes

#1607 Dashboard: Focus rename input when the rename menu item is selected
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/test/cartTitle.js
  assets/src/dashboard/components/toggleButtonGroup/index.js
Labels: Group: Dashboard, cla: yes

#1601 Dashboard: Add created date and published status column
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/useCategoriesApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useTagsApi.js
  assets/src/dashboard/app/api/useUserApi.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/bodyWrapper.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/theme.js
  package-lock.json
Labels: Group: Dashboard, cla: yes

#1614 #1508 Dashboard: Update dropdown panel ui
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/dropdown/stories/index.js
  assets/src/dashboard/components/pill/index.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/dashboard/components/popoverPanel/stories/index.js
  assets/src/dashboard/components/popoverPanel/test/popverPanel.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, cla: yes

#1429 Use single input for locked paddings
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/padding.js
  assets/src/edit-story/components/panels/textStyle/padding/common.js
  assets/src/edit-story/components/panels/textStyle/padding/index.js
  assets/src/edit-story/components/panels/textStyle/padding/locked.js
  assets/src/edit-story/components/panels/textStyle/padding/padding.js
  assets/src/edit-story/components/panels/textStyle/padding/unlocked.js
  assets/src/edit-story/types.js
Labels: Type: Enhancement, cla: yes

#1539 Allow changing number values with up/down keys
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/form/test/numeric.js
  package-lock.json
  package.json
Labels: Type: Enhancement, cla: yes

#1475 Global copy-cut-paste-duplicate
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/useCanvasCopyPaste.js
  assets/src/edit-story/components/canvas/useCanvasKeys.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/keyboard/keys.js
  assets/src/edit-story/utils/copyPaste.js
  assets/src/edit-story/utils/nativeCopyPasteExpected.js
  assets/src/edit-story/utils/processPastedNodeList.js
  assets/src/edit-story/utils/test/copyPaste.js
  assets/src/edit-story/utils/test/nativeCopyPasteExpected.js
  assets/src/edit-story/utils/test/processPastedNodeList.js
  assets/src/edit-story/utils/test/useGlobalClipboardHandlers.js
  assets/src/edit-story/utils/useGlobalClipboardHandlers.js
Labels: Type: Enhancement, cla: yes

#1603 Enable toggle UI feedback.
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/test/sizePosition.js
Labels: Group: Editing, Type: Bug, cla: yes

#1659 Reset opacity for newly added background elements
  assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/setBackgroundElement.js
Labels: Type: Enhancement, cla: yes

#1457 Fix rotation angle overflow/underflow
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/canvas/test/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/test/singleSelectionMovable.js
Labels: Group: Design Panel, Type: Bug, cla: yes

#1560 Slight improvements to e2e test setup
  .github/workflows/continuous-integration.yml
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  bin/local-env/docker-compose.yml
  bin/local-env/install-wordpress.sh
  package-lock.json
  tests/e2e/assets/README.md
  tests/e2e/assets/example-1.jpg
  tests/e2e/assets/example-2.jpg
  tests/e2e/assets/example-3.png
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/example.js
  tests/e2e/specs/media/insertMediaFromLibrary.js
Labels: Type: Infrastructure, cla: yes

#1647 Dashboard: Create hook that encapsulates filter, sort, search, and pagination logic. Add tests for each caller and state permutation.
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/utils/test/useStoryView.js
  assets/src/dashboard/utils/useStoryView.js
Labels: Group: Dashboard, Type: Infrastructure, cla: yes

#1616 Templates: Added static Wellbeing template
  assets/images/templates/wellbeing/wellbeing_icon_arrow_head_dark.png
  assets/images/templates/wellbeing/wellbeing_icon_arrow_head_light.png
  assets/images/templates/wellbeing/wellbeing_icon_fb.png
  assets/images/templates/wellbeing/wellbeing_icon_insta.png
  assets/images/templates/wellbeing/wellbeing_icon_twitter.png
  assets/images/templates/wellbeing/wellbeing_icon_up_arrow.png
  assets/images/templates/wellbeing/wellbeing_icon_youtube.png
  assets/images/templates/wellbeing/wellbeing_page10_image1.jpg
  assets/images/templates/wellbeing/wellbeing_page10_image2.jpg
  assets/images/templates/wellbeing/wellbeing_page10_image3.jpg
  assets/images/templates/wellbeing/wellbeing_page1_image1.jpg
  assets/images/templates/wellbeing/wellbeing_page3_bg.jpg
  assets/images/templates/wellbeing/wellbeing_page4_bg.jpg
  assets/images/templates/wellbeing/wellbeing_page5_image1.jpg
  assets/images/templates/wellbeing/wellbeing_page6_bg.jpg
  assets/images/templates/wellbeing/wellbeing_page7_bg.jpg
  assets/images/templates/wellbeing/wellbeing_page8_image1.jpg
  assets/src/dashboard/templates/data/cooking.js
  assets/src/dashboard/templates/data/diy.js
  assets/src/dashboard/templates/data/entertainment.js
  assets/src/dashboard/templates/data/fashion.js
  assets/src/dashboard/templates/data/fitness.js
  assets/src/dashboard/templates/data/travel.js
  assets/src/dashboard/templates/data/wellbeing.js
  assets/src/dashboard/templates/index.js
  assets/src/edit-story/masks/index.js
Labels: Group: Templates, Type: Enhancement, cla: yes

#1065 History: ensure user stays on the page where the change was applied.
  assets/src/edit-story/app/history/historyProvider.js
  assets/src/edit-story/app/history/reducer.js
  assets/src/edit-story/app/history/test/reducer.js
  assets/src/edit-story/app/history/useHistoryReducer.js
  assets/src/edit-story/app/story/effects/useHistoryEntry.js
  assets/src/edit-story/app/story/effects/useHistoryReplay.js
Labels: Group: History, Type: Bug, cla: yes

#1710 Update selection rotate test description
  assets/src/edit-story/components/canvas/test/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/test/singleSelectionMovable.js
Labels: Type: Infrastructure, cla: yes

#1718 Add default value to DISABLE_PREVENT
  webpack.config.js
Labels: Type: Infrastructure, cla: yes

#1691 Fix Page Menu Bar cutting off Layout and Text buttons.
  assets/src/edit-story/components/canvas/pagemenu/index.js
Labels: Type: Bug, cla: yes

#1694 Regenerated template data to use latest version of editor
  assets/src/dashboard/templates/data/beauty.js
  assets/src/dashboard/templates/data/cooking.js
  assets/src/dashboard/templates/data/diy.js
  assets/src/dashboard/templates/data/entertainment.js
  assets/src/dashboard/templates/data/fashion.js
  assets/src/dashboard/templates/data/fitness.js
  assets/src/dashboard/templates/data/travel.js
Labels: Group: Templates, Type: Enhancement, cla: yes

#1060 Absolute positioning of elements (Tooltips, Color picker, Link hints) + fixes
  assets/src/edit-story/app/snackbar/snackbarContainer.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/test/_utils.js
  assets/src/edit-story/components/circularProgress/stories/index.js
  assets/src/edit-story/components/colorPicker/colorPicker.js
  assets/src/edit-story/components/colorPicker/gradientLine.js
  assets/src/edit-story/components/colorPicker/pointer.js
  assets/src/edit-story/components/colorPicker/test/colorPicker/onclose.js
  assets/src/edit-story/components/colorPicker/useColor.js
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/form/color/test/colorPreview.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/form/switch.js
  assets/src/edit-story/components/form/toggle.js
  assets/src/edit-story/components/inspector/context.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/inspectorLayout.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/link/frame.js
  assets/src/edit-story/components/panels/alignment/alignment.js
  assets/src/edit-story/components/panels/shapeStyle.js
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/popup/index.js
  assets/src/edit-story/components/popup/test/popup.js
  assets/src/edit-story/components/popup/utils.js
  assets/src/edit-story/components/sidebar/context.js
  assets/src/edit-story/components/sidebar/index.js
  assets/src/edit-story/components/sidebar/provider.js
  assets/src/edit-story/components/sidebar/use.js
  assets/src/edit-story/components/tooltip/index.js
  assets/src/edit-story/components/tooltip/stories/index.js
  assets/src/edit-story/components/workspace/index.js
  assets/src/edit-story/utils/useFocusOut.js
  package-lock.json
Labels: Type: Enhancement, cla: yes

#1692 Dashboard: Add base layout for Saved Templates View
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/savedTemplates/test/savedTemplates.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/useStoryView.js
Labels: cla: yes

#1596 Add visual regression test using jest
  .github/workflows/continuous-integration.yml
  assets/src/edit-story/components/panels/layer/test/__image_snapshots__/layer-js-layer-text-should-show-ellipsis-for-overflowing-text-1-snap.png
  assets/src/edit-story/components/panels/layer/test/layer.js
  docs/unit-tests.md
  package-lock.json
  package.json
  tests/js/jest.setup.js
Labels: Type: Infrastructure, cla: yes

#1693 #1492 Dashboard: Update story grid item caption
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/stories/storyGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/cardGridItem/test/cartTitle.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/storybookUtils/formattedStoriesArray.js
  assets/src/dashboard/storybookUtils/formattedUsersObject.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/types.js
  assets/src/dashboard/utils/getFormattedDisplayDate.js
  assets/src/dashboard/utils/index.js
  assets/src/dashboard/utils/test/getFormattedDisplayDate.js
Labels: Group: Dashboard, cla: yes

#1558 Fixes element measuring relative to fullbleed (better)
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/selectionCanvas.js
  assets/src/edit-story/units/dimensions.js
Labels: Group: Canvas, Type: Bug, cla: yes

#1730 Dashboard: Show decoded story titles
  assets/src/dashboard/app/api/test/useStoryApi.js
  assets/src/dashboard/app/api/useStoryApi.js
Labels: Group: Dashboard, cla: yes

#1737 Add additional sorting value to ensure the same order of found posts
  includes/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
Labels: cla: yes

#1742 Dashboard: Added support for modal-routing on dashboard to correctly display Template Detail.
  assets/src/dashboard/app/api/test/__snapshots__/useTemplateApi.js.snap
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/router/index.js
  assets/src/dashboard/app/router/route.js
  assets/src/dashboard/app/router/test/route.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/templateNavBar/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/utils/getFormattedDisplayDate.js
  assets/src/dashboard/utils/test/getFormattedDisplayDate.js
Labels: cla: yes

#1762 Update README.md for design docs
  docs/README.md
Labels: Type: Documentation, cla: yes

#1760 Create design-docs.md
  docs/design-docs.md
Labels: Type: Documentation, cla: yes

#1728 #1490 Dashboard: Stories Sort Dropdown Update
  assets/src/dashboard/app/views/savedTemplates/test/savedTemplates.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/dropdown/stories/index.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/popoverMenu/popover.js
  assets/src/dashboard/components/typeaheadOptions/index.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, cla: yes

#1746 Dashboard: result label update and refactor
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/savedTemplates/test/savedTemplates.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/constants/savedTemplates.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/constants/templates.js
  assets/src/dashboard/utils/index.js
  assets/src/dashboard/utils/test/useDashboardResultsLabel.js
  assets/src/dashboard/utils/useDashboardResultsLabel.js
  assets/src/dashboard/utils/useStoryView.js
Labels: Group: Dashboard, cla: yes

#1766 Dashboard: Complete the Saved Templates UI to the currently spec’d out state
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/shared/stories/storyGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/test/cardTitle.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/utils/getFormattedDisplayDate.js
Labels: Group: Dashboard, cla: yes

#1747 Dashboard: Explore templates sort options (UI only)
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/constants/templates.js
Labels: Group: Dashboard, cla: yes

#1772 ensure the date is mocked in tests that involve moment.js
  assets/src/dashboard/utils/test/getFormattedDisplayDate.js
  package-lock.json
  package.json
Labels: cla: yes

#1720 Docs: Update info on QA environment
  docs/README.md
  docs/staging-environment.md
  docs/testing-environments.md
Labels: Type: Documentation, cla: yes

#1662 Ensure files exist before trying to upload media.
  assets/src/edit-story/app/media/test/useUploadMedia.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
Labels: Group: Media, Type: Bug, cla: yes

#1761 Add per-status counts to REST API responses
  includes/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
Labels: PHP, Type: Enhancement, cla: yes

#1764 Dashboard: Story Hover Button UI Update
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/dropdown/test/dropdown.js
  assets/src/dashboard/components/multiPartPill/index.js
  assets/src/dashboard/components/popoverMenu/popover.js
  assets/src/dashboard/components/popoverMenu/popoverStandard.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/constants/templates.js
  assets/src/dashboard/types.js
Labels: Group: Dashboard, cla: yes

#1771 Dashboard: Navigation Hover Styles
  assets/src/dashboard/components/layout/provider.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/dashboard/constants/pageStructure.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, cla: yes

#1788 #1516 Dashboard: Template Detail Pagination
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/components/bookmark-chip/index.js
  assets/src/dashboard/components/templateNavBar/index.js
Labels: Group: Dashboard, cla: yes

#1706 Use Pure Components for simple components
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/navLayer.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/uploadDropTarget/message.js
Labels: Type: Code Quality, Type: Enhancement, cla: yes

#1778 Split CI workflows into multiple files
  .github/workflows/continuous-integration-build.yml
  .github/workflows/continuous-integration-bundle-size.yml
  .github/workflows/continuous-integration-deploy-to-wiki.yml
  .github/workflows/continuous-integration-e2e.yml
  .github/workflows/continuous-integration-lint-css.yml
  .github/workflows/continuous-integration-lint-js.yml
  .github/workflows/continuous-integration-lint-md.yml
  .github/workflows/continuous-integration-lint-php.yml
  .github/workflows/continuous-integration-unit-js.yml
  .github/workflows/continuous-integration-unit-php.yml
  .github/workflows/continuous-integration.yml
Labels: Type: Enhancement, Type: Infrastructure, cla: yes

#1804 Search Results: Result count per type
  includes/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
Labels: PHP, Type: Bug, cla: yes

#1797 #1784 Dashboard: Add counts by story status to header UI
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/toggleButtonGroup/index.js
  assets/src/dashboard/components/toggleButtonGroup/stories/index.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/utils/test/useDashboardResultsLabel.js
  assets/src/dashboard/utils/useDashboardResultsLabel.js
Labels: Group: Dashboard, JavaScript, cla: yes

#1765 Dashboard: Added dev UI so we can tag stories with animations
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/views/index.js
  assets/src/dashboard/app/views/storyAnimTool/components.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/components.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/index.js
  assets/src/dashboard/constants/index.js
Labels: Group: Dashboard, cla: yes

#1811 Dahboard: Remove template filters from view that aren't not ready yet
  assets/src/dashboard/app/views/templates/index.js
Labels: Pod:DashTemp, cla: yes

#1807 Dashboard: clean up gutters in theme and views for continuity
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/bodyWrapper.js
  assets/src/dashboard/app/views/shared/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/contentGutter/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/templateNavBar/index.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/usePagePreviewSize.js
Labels: Group: Dashboard, Pod:DashTemp, cla: yes

#1802 Fix text alignment.
  assets/src/edit-story/elements/text/display.js
Labels: cla: yes

#1717 Alignment text element while editing
  assets/src/edit-story/elements/text/edit.js
Labels: Type: Bug, cla: yes

#1707 Use useMemo for context values
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/useEditingElement.js
  assets/src/edit-story/components/library/libraryProvider.js
Labels: Type: Code Quality, Type: Enhancement, cla: yes

#1709 Add useCallback for DropTargetsProvider and MediaPane
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
Labels: Type: Code Quality, Type: Enhancement, cla: yes

#1724 Fix Design Panel scrolling on Safari
  assets/src/edit-story/components/inspector/design/designInspector.js
  assets/src/edit-story/components/inspector/inspectorLayout.js
Labels: Browser Issues, Group: Design Panel, Type: Bug, cla: yes

#1751 Add a basic database upgrader.
  includes/Database_Upgrader.php
  includes/Plugin.php
  tests/phpstan/bootstrap.php
  tests/phpunit/tests/Database_Upgrader.php
  web-stories.php
Labels: PHP, Type: Enhancement, WordPress, cla: yes

#1815 Add docs about Stories Labs env
  docs/testing-environments.md
Labels: Type: Documentation, cla: yes

#1824 Update issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Documentation, Type: Infrastructure, cla: yes

#1800 Dashboard: Adds Tooltips. Borders around Preview Cards.
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/components/tooltip/index.js
  assets/src/dashboard/components/tooltip/stories/tooltip.js
  assets/src/dashboard/components/tooltip/test/tooltip.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#1785 Increase timeout for visual regression test
  assets/src/edit-story/components/panels/layer/test/layer.js
Labels: Type: Bug, Type: Infrastructure, cla: yes

#1695 Setup Karma in-browser testing infra
  .distignore
  .eslintrc
  .gitignore
  assets/src/edit-story/karma/_init.js
  karma.config.js
  package-lock.json
  package.json
  tests/js/jest.config.js
Labels: Type: Infrastructure, cla: yes

#1812 Karma: puppeeter support and native events
  .eslintrc
  .prettierignore
  assets/src/edit-story/karma/_init.js
  karma.config.js
  karma/README.md
  karma/karma-puppeteer-client/.eslintrc
  karma/karma-puppeteer-client/README.md
  karma/karma-puppeteer-client/client.js
  karma/karma-puppeteer-client/index.js
  karma/karma-puppeteer-launcher/.eslintrc
  karma/karma-puppeteer-launcher/README.md
  karma/karma-puppeteer-launcher/index.js
Labels: cla: yes

#1850 add allow-empty-input in linter
  package.json
Labels: cla: yes

#1700 Basic `flagged` flag usage
  .storybook/stories/playground/index.js
  assets/src/edit-story/index.js
  docs/README.md
  docs/feature-flags.md
  includes/Story_Post_Type.php
  package-lock.json
  package.json
Labels: cla: yes

#1269 Update readme.txt
  readme.txt
Labels: Type: Enhancement, Type: Task, cla: yes

#1296 DevTools with sharing story data
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/snackbar/snackbarContainer.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/components/devTools/devTools.js
  assets/src/edit-story/components/devTools/dummyData.js
  assets/src/edit-story/components/devTools/index.js
  docs/README.md
  docs/devtools.md
  docs/testing-qa.md
Labels: Type: Infrastructure, cla: yes

#1798 Properly implement default background element
  assets/src/edit-story/app/story/effects/usePageBackgrounds.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/addPage.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/arrangeElement.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/deleteElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/selectElement.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/setSelectedElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/toggleElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/addElementToSelection.js
  assets/src/edit-story/app/story/useStoryReducer/test/addPage.js
  assets/src/edit-story/app/story/useStoryReducer/test/addPageAt.js
  assets/src/edit-story/app/story/useStoryReducer/test/arrangeElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/arrangeSelection.js
  assets/src/edit-story/app/story/useStoryReducer/test/clearBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/deleteElementById.js
  assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsById.js
  assets/src/edit-story/app/story/useStoryReducer/test/deleteSelectedElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/setBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/setSelectedElementsById.js
  assets/src/edit-story/app/story/useStoryReducer/test/toggleElementInSelection.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateElementsByResourceId.js
  assets/src/edit-story/app/story/useStoryReducer/test/updatePageProperties.js
  assets/src/edit-story/app/story/useStoryReducer/types.js
  assets/src/edit-story/app/story/useStoryReducer/useStoryReducer.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/canvas/selectionCanvas.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/panels/layer/test/layer.js
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/elements/test/index.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0018_defaultBackgroundElement.js
  assets/src/edit-story/migration/migrations/v0018_defaultBackgroundElement.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/types.js
Labels: Elements: Image, Type: Bug, cla: yes

#1275 Add resize support to box when changing font-face on display/edit mode
  assets/src/edit-story/app/font/actions/useLoadFontFiles.js
  assets/src/edit-story/app/font/test/actions/useLoadFontFiles.js
  assets/src/edit-story/components/library/text/fontPreview.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/components/panels/textStyle/textStyle.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
Labels: Group: Fonts, Pod: Workspace, Type: Bug, Type: Enhancement, cla: yes

#1546 Make adding text via "add new text" or (T+) to use same default font
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/library/panes/text/textTab.js
  assets/src/edit-story/components/library/test/text/textPane.js
  assets/src/edit-story/components/library/test/text/textTab.js
Labels: Group: Fonts, Type: Enhancement, cla: yes

#1697 Karma: intergration fixture and text/edit test
  .eslintrc
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/mediaPicker/test/useMediaPicker.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/components/panels/textStyle/textStyle.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/karma/fixture.js
  assets/src/edit-story/karma/fixtureEvents.js
  assets/src/edit-story/karma/index.js
  assets/src/edit-story/utils/test/textMeasurements.js
  assets/src/edit-story/utils/textMeasurements.js
  karma/karma-puppeteer-client/.eslintrc
  karma/karma-puppeteer-client/client.js
Labels: cla: yes

#1825 Add more permission checks
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/test/buttons.js
  assets/src/edit-story/components/inspector/document/status.js
  assets/src/edit-story/components/inspector/document/test/status.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
  includes/Story_Post_Type.php
Labels: Group: Document Panel, Type: Enhancement, cla: yes

#1832 Dashboard: Add a link to see the classic WordPress view.
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  includes/Dashboard.php
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#1823 Use node version from nvm config for bundle-size action
  .github/workflows/continuous-integration-bundle-size.yml
Labels: Type: Infrastructure, cla: yes

#1783 Delete poster images risking to be orphaned
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/uploader/useUploader.js
  includes/Media.php
  tests/phpunit/tests/Media.php
Labels: Group: Media, PHP, Type: Enhancement, cla: yes

#1882 Dashboard: Fix external link to use new typography preset
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
Labels: Group: Dashboard, Type: Bug, cla: yes

#1806 Fix Background Overlay on flipped background videos
  assets/src/edit-story/elements/media/test/display.js
  assets/src/edit-story/elements/shared/getTransformFlip.js
Labels: Group: Canvas, Pod: Workspace, Type: Bug, cla: yes

#1869 Treat no selected characters as collapsed selection
  assets/src/edit-story/components/richText/styleManipulation.js
Labels: P1, Pod: Workspace, Type: Bug, cla: yes

#1906 Dashboard: Typography Presets follow up formatting
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/infiniteScroller/index.js
  assets/src/dashboard/components/input/index.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/dashboard/components/pill/components.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/components/templateNavBar/index.js
  assets/src/dashboard/components/toggleButtonGroup/index.js
  assets/src/dashboard/components/tooltip/index.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadOptions/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#1799 Remove recursive useMedia usage in useUploader
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/uploader/test/useUploader.js
  assets/src/edit-story/app/uploader/useUploader.js
Labels: Group: Media, Type: Bug, cla: yes

#1809 Karma: produce DOM snapshots and send them to Percy
  .distignore
  .eslintrc
  .gitignore
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/karma/_init.js
  assets/src/edit-story/karma/fixture.js
  karma.config.js
  karma/karma-puppeteer-client/client.js
  karma/karma-puppeteer-launcher/index.js
  package-lock.json
  package.json
  percy.config.yml
Labels: cla: yes

#1702 Add useContextSelectorShallow hook
  assets/src/edit-story/utils/context.js
  assets/src/edit-story/utils/test/context.js
  package-lock.json
  package.json
Labels: cla: yes

#1704 Use use-context-selector versions of createContext, useContext
  assets/src/edit-story/app/api/context.js
  assets/src/edit-story/app/api/useAPI.js
  assets/src/edit-story/app/config/context.js
  assets/src/edit-story/app/config/useConfig.js
  assets/src/edit-story/app/font/context.js
  assets/src/edit-story/app/font/useFont.js
  assets/src/edit-story/app/history/context.js
  assets/src/edit-story/app/history/useHistory.js
  assets/src/edit-story/app/media/context.js
  assets/src/edit-story/app/media/useMedia.js
  assets/src/edit-story/app/snackbar/context.js
  assets/src/edit-story/app/snackbar/useSnackbar.js
  assets/src/edit-story/app/story/context.js
  assets/src/edit-story/app/story/useStory.js
  assets/src/edit-story/components/canvas/context.js
  assets/src/edit-story/components/canvas/useCanvas.js
  assets/src/edit-story/components/dropTargets/context.js
  assets/src/edit-story/components/dropTargets/useDropTargets.js
  assets/src/edit-story/components/form/context.js
  assets/src/edit-story/components/form/useFormContext.js
  assets/src/edit-story/components/inspector/context.js
  assets/src/edit-story/components/inspector/useInspector.js
  assets/src/edit-story/components/keyboard/context.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/library/context.js
  assets/src/edit-story/components/library/useLibrary.js
  assets/src/edit-story/components/overlay/context.js
  assets/src/edit-story/components/overlay/index.js
  assets/src/edit-story/components/panels/panel/context.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/stylePreset/resize.js
  assets/src/edit-story/components/reorderable/context.js
  assets/src/edit-story/components/reorderable/reorderableScroller.js
  assets/src/edit-story/components/reorderable/useReorderable.js
  assets/src/edit-story/components/richText/context.js
  assets/src/edit-story/components/richText/useRichText.js
  assets/src/edit-story/components/transform/context.js
  assets/src/edit-story/components/transform/useTransform.js
  assets/src/edit-story/components/uploadDropTarget/context.js
  assets/src/edit-story/components/uploadDropTarget/use.js
  assets/src/edit-story/theme.js
  assets/src/edit-story/units/context.js
  assets/src/edit-story/units/useUnits.js
  assets/src/edit-story/utils/usePreventWindowUnload.js
Labels: cla: yes

#1589 Bring back eslint-plugin-react-hooks and fix issues
  .eslintrc
  assets/src/dashboard/components/popoverMenu/popoverCard.js
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/components/autoSaveHandler/index.js
  assets/src/edit-story/components/colorPicker/editablePreview.js
  assets/src/edit-story/components/colorPicker/useKeyDeleteStop.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/library/libraryTabs.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/components/panels/alignment/alignment.js
  assets/src/edit-story/components/panels/stylePreset/colorPresetActions.js
  assets/src/edit-story/components/panels/stylePreset/presetGroup.js
  assets/src/edit-story/components/panels/textStyle/color.js
  assets/src/edit-story/components/reorderable/reorderable.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/utils/context.js
  assets/src/edit-story/utils/useLiveRegion.js
  package-lock.json
  package.json
  patches/eslint-plugin-react-hooks+4.0.0.patch
Labels: Type: Infrastructure, cla: yes

#1743 Add custom calendar implementation
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/form/dateTime/calendarStyle.js
  assets/src/edit-story/components/form/dateTime/datePicker.js
  assets/src/edit-story/components/form/dateTime/dateTimePicker.js
  assets/src/edit-story/components/form/dateTime/index.js
  assets/src/edit-story/components/form/dateTime/timePicker.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/document/publish/publishTime.js
  assets/src/edit-story/components/inspector/document/publish/utils.js
  assets/src/edit-story/components/inspector/document/test/publish.js
  assets/src/edit-story/components/popup/index.js
  package-lock.json
  package.json
Labels: cla: yes

#1904 Dashboard: Break apart my stories functionality (refactor)
  .storybook/preview.js
  assets/src/dashboard/app/views/myStories/content/emptyView/index.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/test/emptyView.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/myStories/header/stories/index.js
  assets/src/dashboard/app/views/myStories/header/test/header.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/stories/storyGridView.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/storybookUtils/formattedStoriesArray.js
  assets/src/dashboard/types.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#1933 Use correct input value for "Add color preset" from Color Picker
  assets/src/edit-story/components/colorPicker/colorPicker.js
  assets/src/edit-story/components/panels/stylePreset/colorPresetActions.js
Labels: cla: yes

#1859 List table: add link to dashboard
  includes/Dashboard.php
Labels: Group: Dashboard, Type: Enhancement, WordPress, cla: yes

#1942 Dashboard: update storybook mock stories data
  assets/src/dashboard/storybookUtils/formattedStoriesArray.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#1654 Added call to delete API for media in apiProvider
  assets/src/edit-story/app/api/apiProvider.js
Labels: Group: Media, Type: Enhancement, cla: yes

#1918 Karma: native keyboard supports and shortcuts
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/karma/fixtureEvents.js
  karma/karma-puppeteer-client/README.md
  karma/karma-puppeteer-client/client.js
  karma/karma-puppeteer-launcher/index.js
Labels: Type: Infrastructure, cla: yes

#1934 Karma: native mouse events
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/karma/fixtureEvents.js
  karma/karma-puppeteer-client/README.md
  karma/karma-puppeteer-client/client.js
  karma/karma-puppeteer-launcher/index.js
Labels: Type: Infrastructure, cla: yes

#1941 Karma: handle async rejections and enable debug mode
  assets/src/edit-story/karma/_init.js
  karma.config.cjs
  karma/karma-puppeteer-client/index.cjs
  karma/karma-puppeteer-launcher/index.cjs
Labels: cla: yes

#1864 Karma: run on CI
  .distignore
  .eslintrc
  .github/workflows/continuous-integration-karma.yml
  karma.config.cjs
  package-lock.json
  package.json
  webpack.config.test.cjs
Labels: Type: Infrastructure, cla: yes

#2000 Karma: configure the static asset proxy
  __static__/README.md
  assets/src/edit-story/elements/text/karma/edit.karma.js
  karma.config.cjs
Labels: Type: Infrastructure, cla: yes

#1936 Dashboard: Detail View Performance Enhancements + Routing Fixes
  assets/src/dashboard/app/font/fontProvider.js
  assets/src/dashboard/app/router/index.js
  assets/src/dashboard/app/router/route.js
  assets/src/dashboard/app/router/test/route.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/components/cardGallery/components.js
  assets/src/dashboard/components/cardGallery/index.js
Labels: cla: yes

#1992 Ignore looping media when getting the longest video
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/output/utils/getLongestMediaElement.js
  assets/src/edit-story/output/utils/test/getLongestMediaElement.js
Labels: Type: Bug, cla: yes

#1949 Preset style improvements.
  assets/src/edit-story/components/panels/stylePreset/panel.js
  assets/src/edit-story/components/panels/stylePreset/presets.js
Labels: cla: yes

#1459 New hover dropdown menu for media element
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/library/panes/media/dropDownMenu.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/library/panes/media/stories/mediaElement.js
  assets/src/edit-story/components/library/panes/media/stories/test-image.jpg
  assets/src/edit-story/components/library/panes/media/stories/test-poster.png
  assets/src/edit-story/components/library/panes/media/stories/test-video.mp4
  assets/src/edit-story/components/library/test/_utils/index.js
  assets/src/edit-story/icons/more_horiz.svg
  includes/Story_Post_Type.php
Labels: Group: Media, Type: Enhancement, cla: yes

#2036 Fix: Add required storybook deps and updated babel config.
  babel.config.cjs
  package-lock.json
  package.json
Labels: Type: Infrastructure, cla: yes

#1911 Dashboard: add 'WEB STORIES' as temp title in left rail
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/dashboard/theme.js
  includes/Dashboard.php
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#1954 Dashboard: Update dashboard grid space according to wordpress menu width
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/shared/stories/storyGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/app/views/templates/index.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGrid/test/card-grid.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/constants/pageStructure.js
  assets/src/dashboard/types.js
  assets/src/dashboard/utils/index.js
  assets/src/dashboard/utils/usePagePreviewSize.js
  assets/src/edit-story/utils/useResizeEffect.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#2058 Karma: fix body children layout
  assets/src/edit-story/karma/_init.js
  assets/src/edit-story/karma/fixture.js
Labels: P0, Pod: WP & Infra, Type: Infrastructure, cla: yes

#1947 Fix zooming for media by displaying overflow in edit mode
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/layout.js
Labels: cla: yes

#1711 Bring codeowners file a bit more up to date
  .github/CODEOWNERS
Labels: Type: Infrastructure, Type: Task, cla: yes

#2073 Remove taxonomies from stories.
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/storyListView.js
  includes/Dashboard.php
  includes/Story_Post_Type.php
Labels: cla: yes

#1861 [Feature] Play and iterate through story pages on dashboard
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/previewPage.js
  assets/src/dashboard/components/storyAnimation/provider.js
  assets/src/dashboard/components/storyAnimation/test/WAAPIWrapper.js
  assets/src/dashboard/components/storyAnimation/test/provider.js
  assets/src/dashboard/components/storyAnimation/test/useStoryAnimationContext.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/index.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/index.js
  includes/Dashboard.php
Labels: cla: yes

#1831 Dashboard: Move focus to left nav on toggle button click
  assets/src/dashboard/app/views/shared/stories/pageHeading.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/menuButton.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#1940 Dashboard: Add new arrow svg & give Icons storybook
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/components.js
  assets/src/dashboard/app/views/templates/components.js
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/components/bookmark-chip/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/button/paginationButton.js
  assets/src/dashboard/components/button/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardItemMenu.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/multiPartPill/stories/index.js
  assets/src/dashboard/components/pageStructure/menuButton.js
  assets/src/dashboard/components/pill/components.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/dashboard/components/scrollToTop/index.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/viewStyleBar.js
  assets/src/dashboard/icons/bookmarkFill.svg
  assets/src/dashboard/icons/bookmarkOutline.svg
  assets/src/dashboard/icons/chevronLeft.svg
  assets/src/dashboard/icons/index.js
  assets/src/dashboard/icons/leftArrow.svg
  assets/src/dashboard/icons/rightArrow.svg
  assets/src/dashboard/icons/stories/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#2060 Dashboard: Updated anim tool to support custom props per animation type
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/parts/blinkOn/animationProps.js
  assets/src/dashboard/animations/parts/blinkOn/index.js
  assets/src/dashboard/animations/parts/defaultAnimationProps.js
  assets/src/dashboard/animations/parts/fade/animationProps.js
  assets/src/dashboard/animations/parts/flip/animationProps.js
  assets/src/dashboard/animations/parts/floatOn/animationProps.js
  assets/src/dashboard/animations/parts/index.js
  assets/src/dashboard/animations/parts/move/animationProps.js
  assets/src/dashboard/animations/parts/spin/animationProps.js
  assets/src/dashboard/animations/parts/zoom/animationProps.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/components.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/index.js
Labels: cla: yes

#1656 Call delete API in hover dropdown menu
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/useMediaReducer/actions.js
  assets/src/edit-story/app/media/useMediaReducer/reducer.js
  assets/src/edit-story/app/media/useMediaReducer/types.js
  assets/src/edit-story/components/library/panes/media/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/dropDownMenu.js
  assets/src/edit-story/components/library/panes/media/stories/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/stories/mediaElement.js
  assets/src/edit-story/components/library/test/deleteDialog.js
Labels: Group: Media, Type: Enhancement, cla: yes

#2080 Add storybook story for failed preview dialog
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/previewErrorDialog.js
  assets/src/edit-story/components/header/stories/previewErrorDialog.js
Labels: Type: Infrastructure, cla: yes

#2082 Make rest controller behavior consistent
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Link_Controller.php
  tests/phpunit/tests/REST_API/Link_Controller.php
Labels: Pod: WP & Infra, Type: Enhancement, cla: yes

#1913 Unlock stylelint version
  package-lock.json
  package.json
Labels: Dependencies, Upstream, cla: yes

#2004 Feature | WAAPI Pause & setCurrentTime Aggregate methods
  .storybook/preview.js
  assets/src/dashboard/animations/parts/bounce/index.js
  assets/src/dashboard/animations/parts/fade/index.js
  assets/src/dashboard/animations/parts/flip/index.js
  assets/src/dashboard/animations/parts/floatOn/index.js
  assets/src/dashboard/components/previewPage.js
  assets/src/dashboard/components/storyAnimation/provider.js
  assets/src/dashboard/components/storyAnimation/stories/index.js
  assets/src/dashboard/components/storyAnimation/test/provider.js
  assets/src/dashboard/index.js
  assets/src/dashboard/storybookUtils/playButton.js
  package-lock.json
  package.json
Labels: cla: yes

#2127 Fix eslint on master
  __mocks__/fs.js
Labels: cla: yes

#2106 Karma: improve and document the debug mode
  assets/src/edit-story/karma/_init.js
  karma.config.cjs
  karma/README.md
  karma/karma-puppeteer-launcher/index.cjs
Labels: cla: yes
