Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-03, with the labels that each got.

#436 Add Dependencies label to Google Fonts PRs
  .github/workflows/update-google-fonts.yml
Labels: Type: Infrastructure, cla: yes

#454 Update disabled state for input, numeric, toggle
  assets/src/edit-story/components/form/input.js
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/form/toggle.js
Labels: Type: Enhancement, cla: yes

#458 Do not externalize React packages
  webpack.config.js
Labels: Type: Infrastructure, cla: yes

#457 Leverage useResizeEffect in InspectorProvider
  assets/src/edit-story/components/inspector/inspectorProvider.js
Labels: Type: Enhancement, cla: yes

#389 Introduce and use new Switch component in design panel
  assets/src/edit-story/components/form/index.js
  assets/src/edit-story/components/form/stories/switch.js
  assets/src/edit-story/components/form/switch.js
  assets/src/edit-story/components/form/test/switch.js
  assets/src/edit-story/components/panels/backgroundDisplay.js
  assets/src/edit-story/components/panels/test/backgroundDisplay.js
  assets/src/edit-story/theme.js
Labels: Type: Enhancement, cla: yes

#456 Introduce batching callback to avoid sync flush in React
  .eslintrc
  assets/src/edit-story/app/history/useHistoryReducer.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/library/libraryTabs.js
  assets/src/edit-story/utils/useBatchingCallback.js
Labels: Type: Bug, cla: yes

#450 Text edit mode fixes and start on some tests
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/test/_utils.js
  assets/src/edit-story/components/canvas/test/frameElement.test.js
  assets/src/edit-story/components/canvas/useEditingElement.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/text/test/frame.test.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/utils/getCaretCharacterOffsetWithin.js
Labels: Type: Bug, cla: yes

#461 Fix loading Google Fonts on frontend
  includes/Story_Post_Type.php
Labels: Size: XS, Type: Bug, cla: yes

#495 Update Travis CI configuration
  .travis.yml
Labels: Type: Infrastructure, cla: yes

#492 Fold WordPress admin menu by default
  includes/Story_Post_Type.php
Labels: Size: XS, Type: Enhancement, cla: yes

#346 Generate full HTML document when saving stories
  .storybook/stories/playground/index.js
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/output/ampBoilerplate.js
  assets/src/edit-story/output/getUsedAmpExtensions.js
  assets/src/edit-story/output/story.js
  assets/src/edit-story/output/styles.js
  assets/src/edit-story/output/test/getUsedAmpExtensions.js
  assets/src/edit-story/types.js
  includes/Media.php
  includes/REST_API/Fonts_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/Story_Renderer.php
  includes/templates/single-web-story.php
  tests/phpunit/tests/REST_API/Fonts_Controller.php
  tests/phpunit/tests/Story_Renderer.php
Labels: Type: Enhancement, cla: yes

#502 Exclude stories from test coverage
  tests/js/jest.config.js
Labels: Type: Infrastructure, cla: yes

#503 Codecov config tweaks
  codecov.yml
Labels: Type: Infrastructure, cla: yes

#351 Add initial setup for RTL support
  .distignore
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/canvas/pagenav/index.js
  assets/src/edit-story/components/library/libraryTabs.js
  assets/src/edit-story/components/overlay/withOverlay.js
  bin/local-env/install-wordpress.sh
  includes/Dashboard.php
  includes/Story_Post_Type.php
  package-lock.json
  package.json
  postcss.config.js
  tests/phpunit/tests/Dashboard.php
  webpack.config.js
Labels: Internationalization (I18N), Type: Enhancement, cla: yes

#469 Implement tooltips
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/tooltip/index.js
  assets/src/edit-story/components/tooltip/stories/index.js
Labels: Type: Enhancement, cla: yes

#488 Update react-moveable and disable snap distance
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/movable/cropStyle.js
  assets/src/edit-story/elements/image/edit.js
  package-lock.json
  package.json
Labels: Type: Enhancement, cla: yes

#392 Layer Panel (Opacity)
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/panels/background.js
  assets/src/edit-story/components/panels/backgroundDisplay.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/layerStyle.js
  assets/src/edit-story/components/panels/test/layerStyle.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/image/output.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/elements/shared/getMediaSizePositionProps.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/edit.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0004_mediaElementToResource.js
  assets/src/edit-story/migration/migrations/test/v0005_setOpacity.js
  assets/src/edit-story/migration/migrations/v0004_mediaElementToResource.js
  assets/src/edit-story/migration/migrations/v0005_setOpacity.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/types.js
  codecov.yml
Labels: Type: Enhancement, cla: yes

#269 Implements drag-and-drop, masking drop targets and mask replacement
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/dropTargets/context.js
  assets/src/edit-story/components/dropTargets/index.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/dropTargets/useDropTargets.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/components/library/panes/media/mediaUtils.js
  assets/src/edit-story/components/library/useInsertElement.js
  assets/src/edit-story/components/panels/mask.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/masks/.eslintrc
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/masks/frame.js
  assets/src/edit-story/masks/index.js
  assets/src/edit-story/masks/output.js
  assets/src/edit-story/migration/migrations/v0006_tmpShapeBgToResource.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/types.js
  assets/src/edit-story/utils/objectPick.js
Labels: Type: Enhancement, cla: yes

#422 Design Panel: Size&Position (functionality only)
  assets/src/edit-story/components/panels/backgroundSizePosition.js
  assets/src/edit-story/components/panels/fill.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/scale.js
  assets/src/edit-story/components/panels/shared/flipControls.js
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/test/background.js
  assets/src/edit-story/components/panels/test/fill.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/components/panels/utils/getCommonObjectValue.js
  assets/src/edit-story/components/panels/utils/test/getCommonObjectValue.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/editCropMovable.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/elements/shared/editPanMovable.js
  assets/src/edit-story/elements/shared/getTransformFlip.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/video/edit.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/masks/output.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0007_setFlip.js
  assets/src/edit-story/migration/migrations/v0007_setFlip.js
  assets/src/edit-story/types.js
Labels: Type: Enhancement, cla: yes

#411 Improve carousel design and responsiveness
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/carousel/compactIndicator.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/draggablePage.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/dropzone/index.js
  assets/src/edit-story/icons/keyboard.svg
Labels: Type: Enhancement, cla: yes

#523 Improve button styling in design panel
  assets/src/edit-story/components/form/button.js
  assets/src/edit-story/components/inspector/document/documentInspector.js
  assets/src/edit-story/components/panels/backgroundSizePosition.js
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/videoPoster.js
Labels: Type: Enhancement, cla: yes

#525 Fixes crashes when selecting items
  assets/src/edit-story/app/story/useStoryReducer/reducers/addElements.js
  assets/src/edit-story/components/panels/sizePosition.js
Labels: cla: yes

#506 Add dev-only useWhyDidYouUpdate hook
  .eslintrc
  assets/src/edit-story/utils/useWhyDidYouUpdate.js
Labels: Type: Infrastructure, cla: yes

#510 Use reducer in Media
  assets/src/edit-story/app/media/actions/useLoadMedia.js
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/useMediaReducer/actions.js
  assets/src/edit-story/app/media/useMediaReducer/index.js
  assets/src/edit-story/app/media/useMediaReducer/reducer.js
  assets/src/edit-story/app/media/useMediaReducer/types.js
  assets/src/edit-story/app/media/useMediaReducer/useMediaReducer.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
Labels: Type: Enhancement, cla: yes

#493 Add REST API endpoint to retrieve webpage metadata
  .gitignore
  composer.json
  includes/Plugin.php
  includes/REST_API/Link_Controller.php
  includes/Story_Post_Type.php
  tests/phpunit/data/amp.dev.html
  tests/phpunit/data/example.com.html
  tests/phpunit/tests/Dashboard.php
  tests/phpunit/tests/REST_API/Link_Controller.php
Labels: Type: Enhancement, cla: yes

#532 Add svg to allowed mime types
  includes/Media.php
Labels: cla: yes

#533 Fix video poster insertion
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/library/panes/media/mediaUtils.js
Labels: Type: Bug, cla: yes

#530 Fix an AMP validation issue where an AMP extension was included multiple times
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/getUsedAmpExtensions.js
  assets/src/edit-story/output/test/getUsedAmpExtensions.js
Labels: Type: Bug, cla: yes

#535 Video in Media Library
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/library/panes/media/mediaUtils.js
  assets/src/edit-story/components/library/panes/media/play.svg
  assets/src/edit-story/theme.js
Labels: Type: Enhancement, cla: yes

#524 Video cropping + media elements refactor
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/frame.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/image/layer.js
  assets/src/edit-story/elements/image/output.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/editCropMovable.js
  assets/src/edit-story/elements/media/editPanMovable.js
  assets/src/edit-story/elements/media/frame.js
  assets/src/edit-story/elements/media/getFocalFromOffset.js
  assets/src/edit-story/elements/media/getMediaSizePositionProps.js
  assets/src/edit-story/elements/media/index.js
  assets/src/edit-story/elements/media/output.js
  assets/src/edit-story/elements/media/scalePanel.js
  assets/src/edit-story/elements/media/useAverageColor.js
  assets/src/edit-story/elements/media/util.js
  assets/src/edit-story/elements/media/visibleImage.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/edit.js
  assets/src/edit-story/elements/video/frame.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/layer.js
  assets/src/edit-story/elements/video/output.js
Labels: Type: Enhancement, cla: yes

#542 Small fix: unbreak Esc in layers panel
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/panels/layer/useLayerReordering.js
Labels: cla: yes

#573 Fix PHP Lints
  includes/REST_API/Link_Controller.php
  tests/phpunit/tests/REST_API/Link_Controller.php
Labels: cla: yes

#574 Adding google sans import and setting up initial theme for dashboard
  assets/src/dashboard/app/index.js
  assets/src/dashboard/theme.js
Labels: cla: yes

#555 Adjust Action buttons + add Publish/Schedule button
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/inspector/document/documentInspector.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
Labels: cla: yes

#565 Use data coordinate system everywhere and auto-sizing
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textTab.js
  assets/src/edit-story/components/library/text/fontPreview.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/units/dimensions.js
  assets/src/edit-story/units/index.js
  assets/src/edit-story/utils/textMeasurements.js
Labels: cla: yes

#604 Fixes allowed file types message (unblocks storybook)
  assets/src/edit-story/components/uploadDropTarget/message.js
  package-lock.json
Labels: cla: yes

#605 Upgrades outdated packages
  package-lock.json
  package.json
Labels: cla: yes

#606 Keyboard-only outlines follow up
  assets/src/edit-story/utils/keyboardOnlyOutline.js
Labels: cla: yes

#552 Drop targets fixes
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/movable/moveStyle.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/mask.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/masks/frame.js
  assets/src/edit-story/masks/index.js
Labels: cla: yes

#562 Infinite scroll in Media
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/useMediaReducer/actions.js
  assets/src/edit-story/app/media/useMediaReducer/reducer.js
  assets/src/edit-story/app/media/useMediaReducer/types.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/library/dropzone/index.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/utils/useIntersectionEffect.js
Labels: cla: yes

#453 Custom Dropdown component for design panel
  assets/src/edit-story/components/dropDown/index.js
  assets/src/edit-story/components/dropDown/stories/index.js
  assets/src/edit-story/components/form/index.js
  assets/src/edit-story/components/form/select.js
  assets/src/edit-story/components/inspector/document/documentInspector.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/theme.js
Labels: Type: Enhancement, cla: yes

#617 Storybook Actions Set Up
  .storybook/main.js
Labels: cla: yes

#619 Quick fix: by default any design panel button must be a non-submit button
  assets/src/edit-story/components/form/button.js
Labels: cla: yes

#613 Background overlay/scrim
  assets/src/edit-story/app/story/useStoryReducer/reducers/addPage.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/deleteElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/addElementToSelection.js
  assets/src/edit-story/app/story/useStoryReducer/test/addPage.js
  assets/src/edit-story/app/story/useStoryReducer/test/arrangeElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/arrangeSelection.js
  assets/src/edit-story/app/story/useStoryReducer/test/clearBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/deleteElementById.js
  assets/src/edit-story/app/story/useStoryReducer/test/setBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/setSelectedElementsById.js
  assets/src/edit-story/app/story/useStoryReducer/test/toggleElementInSelection.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/form/switch.js
  assets/src/edit-story/components/form/toggleButton.js
  assets/src/edit-story/components/panels/backgroundOverlay.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/textStyle/textStyle.js
  assets/src/edit-story/icons/overlay_linear.svg
  assets/src/edit-story/icons/overlay_none.svg
  assets/src/edit-story/icons/overlay_radial.svg
  assets/src/edit-story/icons/overlay_solid.svg
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/styles.js
  assets/src/edit-story/types.js
  assets/src/edit-story/utils/backgroundOverlay.js
Labels: cla: yes

#607 Auto-populated link descriptions and thumbnails
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/panels/link.js
  assets/src/edit-story/utils/url.js
  package-lock.json
  package.json
Labels: cla: yes

#629 Fix dropdown issue on document panel
  assets/src/edit-story/components/dropDown/index.js
  assets/src/edit-story/components/inspector/document/documentInspector.js
Labels: cla: yes

#622 Add vector assets for dashboard
  assets/src/dashboard/icons/bookmark-fill.svg
  assets/src/dashboard/icons/bookmark-outline.svg
  assets/src/dashboard/icons/checkmark.svg
  assets/src/dashboard/icons/close.svg
  assets/src/dashboard/icons/download.svg
  assets/src/dashboard/icons/drop-down-arrow-blue.svg
  assets/src/dashboard/icons/drop-down-arrow.svg
  assets/src/dashboard/icons/drop-up-arrow.svg
  assets/src/dashboard/icons/grid.svg
  assets/src/dashboard/icons/list.svg
  assets/src/dashboard/icons/more-vertical.svg
  assets/src/dashboard/icons/play-arrow.svg
  assets/src/dashboard/icons/search.svg
Labels: cla: yes

#623 #547 Dashboard UI Components: Pill
  assets/src/dashboard/components/pill/index.js
  assets/src/dashboard/components/pill/stories/index.js
  assets/src/dashboard/components/pill/test/pill.js
  assets/src/dashboard/theme.js
Labels: cla: yes

#637 Quick fix: a color button must be non-submit
  assets/src/edit-story/components/form/color/colorPreview.js
Labels: cla: yes

#648 Enqueue Google Sans via PHP
  .storybook/preview-head.html
  assets/src/dashboard/style.css
  includes/Dashboard.php
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#650 Dequeue forms.css for editor and dashboard
  assets/src/dashboard/style.css
  assets/src/edit-story/style.css
  includes/Dashboard.php
  includes/Story_Post_Type.php
Labels: Type: Bug, cla: yes

#649 Specify code owners for dashboard
  .github/CODEOWNERS
Labels: Type: Infrastructure, cla: yes

#616 Google Analytics tag from Site Kit
  includes/Story_Renderer.php
  phpunit.xml.dist
  tests/phpunit/tests/Story_Renderer.php
Labels: Type: Enhancement, cla: yes

#651 Fix AMP validation errors for elements without masks
  assets/src/edit-story/masks/output.js
  assets/src/edit-story/masks/test/output.js
Labels: Type: Bug, cla: yes

#653 Add option for looping Videos
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/videoOptions.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/elements/video/test/output.js
Labels: Type: Enhancement, cla: yes

#658 Fix default text-align value for text elements
  assets/src/edit-story/elements/text/index.js
Labels: Size: XS, Type: Bug, cla: yes

#666 Fix lints.
  includes/Dashboard.php
  includes/Story_Post_Type.php
Labels: cla: yes

#627 Remove selected elements and page selection as separate history steps
  assets/src/edit-story/app/history/useHistoryReducer.js
  assets/src/edit-story/app/story/effects/useHistoryEntry.js
  assets/src/edit-story/components/library/dropzone/index.js
Labels: Type: Enhancement, cla: yes

#620 Template Animations: Added bounce animation
  .storybook/preview-head.html
  assets/src/dashboard/animations/animator/animationOutput.js
  assets/src/dashboard/animations/animator/animatorOutput.js
  assets/src/dashboard/animations/animator/index.js
  assets/src/dashboard/animations/animator/output.js
  assets/src/dashboard/animations/animator/types.js
  assets/src/dashboard/animations/configs/bounce.js
  assets/src/dashboard/animations/configs/index.js
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/stories/bounce.js
  assets/src/dashboard/animations/utils/getInitialStyleFromKeyframes.js
  assets/src/dashboard/animations/utils/test/getInitialStyleFromKeyframes.js
Labels: Type: Enhancement, cla: yes

#537 Implements one-tap links
  .travis.yml
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/link/frame.js
  assets/src/edit-story/components/link/guidelines.js
  assets/src/edit-story/components/link/index.js
  assets/src/edit-story/components/link/output.js
  assets/src/edit-story/components/panels/link.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/theme.js
  package-lock.json
  package.json
Labels: Type: Enhancement, cla: yes

#639 Introduce ratio for clip path masks
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/masks/frame.js
  assets/src/edit-story/masks/index.js
  assets/src/edit-story/masks/output.js
Labels: Type: Enhancement, cla: yes

#669 Dashboard: Responsive Navigation + Create Story Button
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/navigation-bar.js
  assets/src/dashboard/components/popover-menu/index.js
  assets/src/dashboard/constants.js
Labels: cla: yes

#659 Fix Travis CI configuration
  .travis.yml
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/library/panes/animation/paneId.js
  bin/local-env/start.sh
  composer.json
  composer.lock
Labels: Type: Infrastructure, cla: yes

#695 ESLint fixes after Prettier update
  __mocks__/colorthief.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/link/frame.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/components/panels/colorPreset.js
  assets/src/edit-story/elements/media/editCropMovable.js
  assets/src/edit-story/elements/media/editPanMovable.js
  assets/src/edit-story/output/page.js
  babel.config.js
Labels: Type: Infrastructure, cla: yes

#664 Use platform-agnostic prettified keyboard shortcuts in tooltips and help texts
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/keyboard/test/prettifyShortcut.js
  assets/src/edit-story/components/tooltip/stories/index.js
Labels: Type: Bug, cla: yes

#699 Minor ESLint fixes
  assets/src/dashboard/animations/configs/bounce.js
  assets/src/dashboard/animations/configs/spin.js
Labels: Group: Dashboard, Type: Bug, cla: yes

#708 Do not print a zero (`0`) when there are no CTA elements
  assets/src/edit-story/output/page.js
Labels: Type: Bug, cla: yes

#657 Improve styling and organization of element panel
  assets/src/edit-story/components/library/common/index.js
  assets/src/edit-story/components/library/common/searchInput.js
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/shared.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/theme.js
Labels: Type: Enhancement, cla: yes

#656 Dashboard: Card Grid + Card Grid Item Base
  assets/src/dashboard/components/card-grid-item/index.js
  assets/src/dashboard/components/card-grid-item/stories/index.js
  assets/src/dashboard/components/card-grid-item/test/card-grid-item.js
  assets/src/dashboard/components/card-grid/index.js
  assets/src/dashboard/components/card-grid/stories/index.js
  assets/src/dashboard/components/card-grid/test/card-grid.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, P0, cla: yes

#707 Use createInterpolateElement to avoid string concatenation for localized strings
  assets/src/edit-story/components/panels/link/infoDialog.js
  package.json
  webpack.config.js
Labels: Type: Enhancement, cla: yes

#717 Support double click on layer panel drag handle to reset height
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/handle.js
  assets/src/edit-story/components/panels/panel/shared/title.js
Labels: Type: Enhancement, cla: yes

#687 Performance & aesthetic improvements for drop targets
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/link/frame.js
  assets/src/edit-story/masks/frame.js
Labels: Type: Enhancement, cla: yes

#661 Fix some low-hanging accessibility issues
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/header/headerLayout.js
  assets/src/edit-story/components/inspector/inspectorTabs.js
  assets/src/edit-story/components/inspector/utils.js
  assets/src/edit-story/components/panels/panel/shared/handle.js
Labels: Type: Bug, cla: yes

#727 Fixes masking on mobile
  assets/src/edit-story/masks/output.js
Labels: cla: yes

#723 Fix LinkType default arg hack due to module loading errors
  assets/src/edit-story/components/link/index.js
  assets/src/edit-story/components/panels/link.js
Labels: Type: Bug, cla: yes

#693 Background element refactor (+ drop targets and fixes)
  assets/src/edit-story/app/story/effects/usePageBackgrounds.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/canvas/selectionCanvas.js
  assets/src/edit-story/components/panels/backgroundSizePosition.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/panels/layer/useLayerReordering.js
  assets/src/edit-story/components/panels/layer/useLayerSelection.js
  assets/src/edit-story/components/panels/layer/useLayers.js
  assets/src/edit-story/components/panels/pageBackground.js
  assets/src/edit-story/components/panels/shapeStyle.js
  assets/src/edit-story/components/panels/shared/flipControls.js
  assets/src/edit-story/components/panels/test/pageBackground.js
  assets/src/edit-story/elements/background/icon.js
  assets/src/edit-story/elements/background/icon.svg
  assets/src/edit-story/elements/background/index.js
  assets/src/edit-story/elements/background/layer.js
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/masks/frame.js
  assets/src/edit-story/masks/output.js
  assets/src/edit-story/migration/migrations/test/v0009_defaultBackground.js
  assets/src/edit-story/migration/migrations/v0009_defaultBackground.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/types.js
Labels: Type: Enhancement, cla: yes

#725 Template Animation: Added blink-on animation
  assets/src/dashboard/animations/animator/animatorOutput.js
  assets/src/dashboard/animations/configs/blinkOn.js
  assets/src/dashboard/animations/configs/index.js
  assets/src/dashboard/animations/configs/test/blinkOn.js
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/stories/blinkOn.js
  assets/src/dashboard/animations/stories/bounce.js
  assets/src/dashboard/animations/stories/spin.js
Labels: Type: Enhancement, cla: yes

#625 Element alignment
  assets/src/edit-story/components/panels/alignment/alignment.js
  assets/src/edit-story/components/panels/alignment/index.js
  assets/src/edit-story/components/panels/alignment/useAlignment.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/utils/getBoundRect.js
  assets/src/edit-story/components/panels/utils/test/getBoundRect.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/icons/align_bottom.svg
  assets/src/edit-story/icons/align_center.svg
  assets/src/edit-story/icons/align_left.svg
  assets/src/edit-story/icons/align_middle.svg
  assets/src/edit-story/icons/align_right.svg
  assets/src/edit-story/icons/align_top.svg
  assets/src/edit-story/icons/horizontal_distribute.svg
  assets/src/edit-story/icons/vertical_distribute.svg
Labels: Type: Enhancement, cla: yes

#752 Fix PHPCS issues
  includes/Dashboard.php
Labels: Type: Bug, cla: yes

#747 Memoize defaultLink and batch metadata update
  assets/src/edit-story/components/panels/link.js
Labels: Type: Bug, cla: yes

#750 Dashboard: Typeahead UI Component
  assets/src/dashboard/components/card-grid-item/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/typeahead-input/index.js
  assets/src/dashboard/components/typeahead-input/stories/index.js
  assets/src/dashboard/components/typeahead-input/test/typeahead-input.js
  assets/src/dashboard/components/typeahead-options/index.js
  assets/src/dashboard/components/typeahead-options/stories/index.js
  assets/src/dashboard/components/typeahead-options/test/typeahead-options.js
  assets/src/dashboard/constants.js
  assets/src/dashboard/icons/close.svg
  assets/src/dashboard/icons/search.svg
  assets/src/dashboard/theme.js
Labels: P1, Size: M, Type: Enhancement, cla: yes

#667 Document Sidebar UI & functionality fixes
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/form/dateTime/calendarStyle.js
  assets/src/edit-story/components/form/dateTime/datePicker.js
  assets/src/edit-story/components/form/dateTime/dateTimePicker.js
  assets/src/edit-story/components/form/dateTime/index.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/dropDown/stories/index.js
  assets/src/edit-story/components/form/helperText.js
  assets/src/edit-story/components/form/index.js
  assets/src/edit-story/components/form/inputGroup.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/form/radioGroup.js
  assets/src/edit-story/components/form/required.js
  assets/src/edit-story/components/form/stories/radioGroup.js
  assets/src/edit-story/components/form/test/radioGroup.js
  assets/src/edit-story/components/inspector/document/documentInspector.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/document/publish/test/utils.js
  assets/src/edit-story/components/inspector/document/publish/utils.js
  assets/src/edit-story/components/inspector/document/slug.js
  assets/src/edit-story/components/inspector/document/status.js
  assets/src/edit-story/components/inspector/document/test/publish.js
  assets/src/edit-story/components/inspector/document/test/slug.js
  assets/src/edit-story/components/inspector/document/test/status.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/icons/radio-selected.svg
  assets/src/edit-story/icons/radio.svg
  assets/src/edit-story/output/story.js
  assets/src/edit-story/output/test/story.js
  assets/src/edit-story/theme.js
  includes/Dashboard.php
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/Story_Renderer.php
  package-lock.json
  package.json
  tests/js/jest.config.js
  tests/phpunit/data/attachment.jpg
  tests/phpunit/tests/Story_Renderer.php
Labels: Type: Enhancement, cla: yes

#720 Add: Workspace - Video Preview
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/frame.js
  assets/src/edit-story/icons/pause.svg
  assets/src/edit-story/icons/play.svg
Labels: Type: Enhancement, cla: yes

#614 Remove "Still Empty" Sections
  assets/src/edit-story/components/library/panes/animation/animationPane.js
  assets/src/edit-story/components/library/panes/index.js
Labels: Type: Enhancement, cla: yes

#791 Use correct vendor prefix for clip-path property
  assets/src/edit-story/masks/output.js
Labels: Type: Bug, cla: yes

#762 Dashboard: Card Grid Item Base UI Component
  assets/src/dashboard/components/card-grid-item/card-preview.js
  assets/src/dashboard/components/card-grid-item/card-title.js
  assets/src/dashboard/components/card-grid-item/index.js
  assets/src/dashboard/components/card-grid-item/stories/index.js
  assets/src/dashboard/components/card-grid/stories/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/theme.js
Labels: P1, Size: S, Type: Enhancement, cla: yes

#814 Remove unnecessary <Spinner> and fix layout shift on media panel.
  assets/src/edit-story/components/library/panes/media/mediaPane.js
Labels: cla: yes

#805 Revert media element drag & drop scale effect
  assets/src/edit-story/components/library/panes/media/mediaElement.js
Labels: Media, cla: yes

#820 Various minor text panel fixes
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textTab.js
  assets/src/edit-story/components/library/text/fontPreview.js
Labels: cla: yes

#815 Ensure that all text components and measurer work use the same CSS/markup
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/panels/textStyle/textStyle.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/test/output.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/utils/textMeasurements.js
Labels: cla: yes

#706 Dialog box and text button components + Link guide dialog box
  .stylelintrc
  assets/images/one-tap-link.png
  assets/images/two-tap-link.png
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/dialog/index.js
  assets/src/edit-story/components/modal/index.js
  assets/src/edit-story/components/modal/stories/index.js
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/link/infoDialog.js
  assets/src/edit-story/components/panels/shared/note.js
  assets/src/edit-story/icons/info.svg
  includes/Story_Post_Type.php
  package.json
  webpack.config.js
Labels: Type: Enhancement, cla: yes

#809 Switch tab to design when selection is changing
  assets/src/edit-story/components/inspector/inspectorProvider.js
Labels: Needs Cherry-Picking, cla: yes

#812 Send fake event when adding new element to page
  assets/src/edit-story/components/canvas/useFocusCanvas.js
  assets/src/edit-story/components/canvas/useInsertElement.js
Labels: Needs Cherry-Picking, cla: yes

#749 Implement editable color input
  assets/src/edit-story/components/form/color/colorBox.js
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/form/color/test/color.js
  assets/src/edit-story/components/form/color/test/colorPreview.js
Labels: Needs Cherry-Picking, Type: Enhancement, cla: yes

#821 Dashboard: Bookmark Chip UI Component
  assets/src/dashboard/components/bookmark-chip/index.js
  assets/src/dashboard/components/bookmark-chip/stories/index.js
  assets/src/dashboard/components/bookmark-chip/test/bookmark-chip.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/constants.js
  assets/src/dashboard/icons/bookmark-fill.svg
  assets/src/dashboard/icons/bookmark-outline.svg
  assets/src/dashboard/theme.js
Labels: Size: XS, Type: Enhancement, cla: yes

#816 Template Animations: Added float-on animation (#618)
  assets/src/dashboard/animations/configs/floatOn.js
  assets/src/dashboard/animations/configs/index.js
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/stories/floatOn.js
Labels: Type: Enhancement, cla: yes

#704 Minimize layer panel height + fixes for expanding/collapsing
  assets/src/edit-story/components/panels/layer/panel.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/panels/panel/shared/handle.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/panel/useDragHandlers.js
Labels: Type: Enhancement, cla: yes

#841 Disable automatic insertion as background
  assets/src/edit-story/components/canvas/useInsertElement.js
Labels: cla: yes

#829 Reduce timing difference for entering text edit mode.
  assets/src/edit-story/elements/text/frame.js
Labels: Needs Cherry-Picking, cla: yes

#827 Disallow masking for background.
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/masks/frame.js
  assets/src/edit-story/masks/output.js
  assets/src/edit-story/masks/test/output.js
Labels: Needs Cherry-Picking, cla: yes

#811 Auto-select entire input field on focus
  assets/src/edit-story/components/form/color/opacityPreview.js
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/utils/useFocusAndSelect.js
Labels: Needs Cherry-Picking, Type: Enhancement, cla: yes

#804 Resize video while resizing
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/media/display.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/frame.js
  assets/src/edit-story/elements/media/output.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/types.js
Labels: Needs Cherry-Picking, cla: yes

#824 Aspect Ratio changed after dragging video to upload as background
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateElementsByVideoId.js
  assets/src/edit-story/elements/media/getMediaSizePositionProps.js
  assets/src/edit-story/elements/video/display.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#860 Revert "Aspect Ratio changed after dragging video to upload as background"
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateElementsByVideoId.js
  assets/src/edit-story/elements/media/getMediaSizePositionProps.js
  assets/src/edit-story/elements/video/display.js
Labels: cla: yes

#857 Exit edit mode on link change
  assets/src/edit-story/components/panels/link/index.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#797 nit: form button hover state
  assets/src/edit-story/components/form/button.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#862 Added API-endpoint for story data
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/views/index.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/components/card-grid-item/card-title.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/navigation-bar.js
  assets/src/dashboard/constants.js
  includes/Dashboard.php
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#847 Fix background element selection
  assets/src/edit-story/components/canvas/selectionCanvas.js
Labels: Type: Bug, cla: yes

#880 Fix: run the default-background migration
  assets/src/edit-story/migration/migrate.js
Labels: cla: yes

#854 Learn more helper dialog for background fit
  assets/images/do-not-fit.png
  assets/images/fit-to-device.png
  assets/src/edit-story/components/dialog/index.js
  assets/src/edit-story/components/panels/backgroundDisplay/dialogContent.js
  assets/src/edit-story/components/panels/backgroundDisplay/index.js
  assets/src/edit-story/components/panels/link/dialogContent.js
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/shared/note.js
  assets/src/edit-story/components/panels/test/backgroundDisplay.js
  assets/src/edit-story/theme.js
Labels: cla: yes

#872 New aspect ratio 2:3
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/text/test/output.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0010_dataPixelTo440.test.js
  assets/src/edit-story/migration/migrations/v0010_dataPixelTo440.js
Labels: cla: yes

#853 Shape previews in the layers panel
  assets/src/edit-story/components/library/panes/media/media.svg
  assets/src/edit-story/components/library/panes/media/mediaTab.js
  assets/src/edit-story/components/library/panes/shapes/shapes.svg
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/shapes/shapesTab.js
  assets/src/edit-story/elements/image/icon.js
  assets/src/edit-story/elements/media/visibleImage.js
  assets/src/edit-story/elements/shape/icon.js
  assets/src/edit-story/elements/shape/layer.js
  assets/src/edit-story/elements/shared/icon_media.svg
  assets/src/edit-story/elements/video/icon.js
  assets/src/edit-story/icons/media.svg
  assets/src/edit-story/icons/shapes.svg
  assets/src/edit-story/icons/video.svg
  assets/src/edit-story/masks/index.js
  assets/src/edit-story/utils/generatePatternStyles.js
  assets/src/edit-story/utils/getBrightnessFromPattern.js
Labels: Type: Enhancement, cla: yes

#884 Snap to common element distances
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/dropTargets/provider.js
Labels: cla: yes

#885 Fix drop targets on background element + disable opacity for backgrounds
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/shapeStyle.js
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/masks/frame.js
  assets/src/edit-story/masks/output.js
Labels: cla: yes

#713 Upload Error Handling - Snackbars Messages
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/snackbar/context.js
  assets/src/edit-story/app/snackbar/index.js
  assets/src/edit-story/app/snackbar/snackbar.js
  assets/src/edit-story/app/snackbar/snackbarContainer.js
  assets/src/edit-story/app/snackbar/snackbarProvider.js
  assets/src/edit-story/app/snackbar/useSnackbar.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
Labels: Needs Cherry-Picking, Type: Enhancement, cla: yes

#844 Dashboard: Responsive Typeahead UI Update
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/typeahead-options/index.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadInput/stories/index.js
  assets/src/dashboard/components/typeaheadInput/test/typeaheadInput.js
Labels: Type: Enhancement, cla: yes

#886 Rotation stepping with shift key
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
Labels: cla: yes

#828 Responsive video playback icon size
  assets/src/edit-story/elements/video/frame.js
Labels: Needs Cherry-Picking, Type: Bug, UX Needed, cla: yes

#916 Fix aspect ratio for carousel and grid
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/output/page.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes

#908 Media/remove attachment
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/app/media/utils/getAttachmentFromResource.js
  assets/src/edit-story/app/media/utils/getResourceFromAttachment.js
  assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js
  assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js
  assets/src/edit-story/app/media/utils/getResourceFromUploadAPI.js
  assets/src/edit-story/app/media/utils/index.js
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
  assets/src/edit-story/components/library/panes/media/mediaUtils.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/types.js
Labels: cla: yes

#915 Fix ID prefix in auto-advance-after
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/test/page.js
Labels: Needs Cherry-Picking, Type: Bug, cla: yes
