Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-09, with the labels that each got.

#4156 Added X/Y inputs to design panel
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/units/dimensions.js
Labels: Accessibility, Elements, Group: Design Panel, Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#4213 Refactor 3-panel DOM structure so sidebars resize well, fix msonry
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/workspace/index.js
  assets/src/edit-story/components/workspace/layout.js
  assets/src/edit-story/constants.js
Labels: Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#4298 [Media3p] reset pagetoken on category deselection
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/test/providerReducer.js
Labels: cla: yes

#4281 Add Tenor provider
  assets/src/edit-story/app/media/media3p/attribution.js
  assets/src/edit-story/app/media/media3p/providerConfiguration.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/icons/tenor_logo_white.svg
  includes/Experiments.php
Labels: cla: yes

#4279 Set isMediaLoading=false to refresh on a new search term
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/test/providerReducer.js
Labels: cla: yes

#4275 Dashboard: Prevent focus on menu separator lines
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/popoverMenu/stories/index.js
  assets/src/dashboard/components/types.js
  assets/src/dashboard/constants/stories.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#4261 Dashboard: Fix Detail View Hard Refresh Bug; Improve overall loading performance
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/reducer/templates.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/components/cardGallery/components.js
  assets/src/dashboard/components/detailViewNavBar/index.js
Labels: Group: Dashboard, P0, Pod: Pea (Dashboard & Templates), Type: Bug, Type: Performance, cla: yes

#4310 Makes retrieving media from local api bypass preloaded cache when WP Upload modal closed.
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/api/test/_utils.js
  assets/src/edit-story/app/api/test/apiProvider.js
  assets/src/edit-story/app/media/local/test/useContextValueProvider.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
Labels: Group: Media, Group: WordPress, Type: Bug, cla: yes

#4321 Remove crossorigin attribute from videos to fix poster caching
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/output/test/page.js
Labels: Group: 3P Media, Pod: Media I/O, cla: yes

#3344 Build tool: work on copy, not source directory
  .github/workflows/continuous-integration-build.yml
  bin/commander.js
  bin/utils/bundlePlugin.js
  bin/utils/createBuild.js
  bin/utils/generateZipFile.js
  bin/utils/index.js
  bin/utils/test/bundlePlugin.js
  bin/utils/test/createBuild.js
  bin/utils/test/generateZipFile.js
  bin/utils/test/updateAssetsURL.js
  bin/utils/updateAssetsURL.js
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4248 Story Editor: Improve Keyboard Navigation on Carousel
  assets/src/edit-story/components/canvas/carousel/compactIndicator.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
Labels: cla: yes

#4305 Workspace: Add Editor Version
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/theme.js
  includes/Story_Post_Type.php
Labels: Group: Editing, Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#4327 Improves flaky tests from #4218 (text staggering)
  assets/src/edit-story/components/library/panes/text/karma/textPane.karma.js
Labels: cla: yes

#4303 Dashboard: Enable keyboard navigation for publisher logos grid
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/stories/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/test/publisherLogo.js
  assets/src/dashboard/app/views/editorSettings/test/editorSettings.js
  assets/src/dashboard/components/cardGallery/index.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4238 Dashboard: A11y - Add ability to tab to/from story preview iframe
  assets/src/dashboard/app/views/previewStory/index.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4329 Embed block: explicitly set dimensions in AMP context
  includes/Story_Renderer/Embed.php
  includes/plugin-compat/amp.php
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#4313 Dashboard: Add checks for logos dimensions
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/constants/index.js
Labels: cla: yes

#4277 Dashboard: Enforce outline on CTA buttons
  assets/src/dashboard/components/button/index.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4309 Dashboard: Added tab support to story list view
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/storyMenu/index.js
  assets/src/dashboard/constants/components.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/types.js
  assets/src/date/getRelativeDisplayDate.js
  assets/src/date/test/getRelativeDisplayDate.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4361 Compare aspect ratios instead of just orientations
  assets/src/edit-story/elements/media/test/util.js
  assets/src/edit-story/elements/media/util.js
Labels: cla: yes

#4323 Fix element links being removed incorrectly
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/test/page.js
Labels: Pod: Prometheus (Workspace), Type: Bug, cla: yes

#4326 Remove gray background for transparent images
  __static__/transparent.png
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/karma/resourceLoading.karma.js
  assets/src/edit-story/elements/media/display.js
  assets/src/edit-story/elements/media/test/display.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/karma/fixture/db/getMediaResponse.js
  assets/src/edit-story/utils/resourceList.js
  assets/src/edit-story/utils/test/resourceList.js
Labels: Elements: Image, Group: Media, Type: Bug, cla: yes

#4337 Dashboard: Maintain grid item focus on delete
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4330 Dashboard: Telemetry Settings Opt-In Checkbox
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/useUserApi.js
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/editorSettings/telemetry/index.js
  assets/src/dashboard/app/views/editorSettings/telemetry/stories/index.js
  assets/src/dashboard/app/views/editorSettings/telemetry/test/telemetrySettings.js
  assets/src/dashboard/app/views/editorSettings/test/editorSettings.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/dashboard/karma/fixture.js
  includes/Dashboard.php
Labels: Group: Dashboard, Group: Settings, Group: Telemetry, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4332 Add meta tags for creation tool name and version
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4336 Dashboard: Add a save button to the google analytics id form
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/test/googleAnalytics.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/constants/index.js
Labels: cla: yes

#4280 Add contentType filter attribute to media3pApiProvider
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/media3p/api/typedefs.js
  assets/src/edit-story/app/media/media3p/test/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
Labels: cla: yes

#4282 Add provider contentTypeFilter json config for Tenor
  assets/src/edit-story/app/media/media3p/providerConfiguration.js
  assets/src/edit-story/app/media/media3p/test/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pPane.js
Labels: cla: yes

#4363 Retain scroll position when changing media tabs
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: cla: yes

#4381 Suppress PHP Lint warning
  includes/Media.php
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4377 Media: Fix creating a resource with missing sizes from the media picker
  assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
Labels: Group: Media, Group: WordPress, Pod: Media I/O, Type: Bug, cla: yes

#4304 Story Editor: Update Font Picker to Designs
  assets/src/edit-story/components/fontPicker/fontList/index.js
  assets/src/edit-story/components/fontPicker/fontList/styled.js
  assets/src/edit-story/components/fontPicker/fontList/utils.js
  assets/src/edit-story/components/fontPicker/fontPicker.js
  assets/src/edit-story/components/fontPicker/fontSearchInput.js
  assets/src/edit-story/components/fontPicker/pickerContainer.js
  assets/src/edit-story/components/fontPicker/scrollList.js
  assets/src/edit-story/components/fontPicker/test/fontPicker.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/icons/checkmark.svg
  assets/src/edit-story/icons/search.svg
  assets/src/edit-story/karma/textStyle.cuj.karma.js
  assets/src/edit-story/theme.js
Labels: Group: Editing, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#4345 Fix updating page advancement on the first load
  .eslintrc
  .github/workflows/continuous-integration-karma-dashboard.yml
  .github/workflows/continuous-integration-karma-edit-story.yml
  assets/src/edit-story/app/history/karma/history.karma.js
  assets/src/edit-story/components/inspector/document/pageAdvancement.js
  assets/src/edit-story/elements/image/karma/resourceLoading.karma.js
  assets/src/edit-story/karma/fixture/fixture.js
  karma-dashboard.config.cjs
  karma-edit-story.config.cjs
Labels: Group: Document Panel, Group: History, Pod: Prometheus (Workspace), Type: Bug, cla: yes

#4141 Fix DOMDocument issues with AMP boilerplate and encodings
  composer.json
  composer.lock
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4260 Story Editor: Carousel Page Preview Aria Labels
  assets/src/edit-story/components/canvas/carousel/compactIndicator.js
  assets/src/edit-story/components/canvas/carousel/index.js
Labels: cla: yes

#4380 Consider multi-selection for X and Y values in the panel
  assets/src/edit-story/components/panels/sizePosition/constants.js
  assets/src/edit-story/components/panels/sizePosition/index.js
  assets/src/edit-story/components/panels/sizePosition/panel.js
  assets/src/edit-story/components/panels/sizePosition/usePresubmitHandlers.js
  assets/src/edit-story/components/panels/sizePosition/utils.js
Labels: P0, Pod: Prometheus (Workspace), cla: yes

#4251 Add missing title dialog
  assets/src/edit-story/components/dialog/index.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/buttons/index.js
  assets/src/edit-story/components/header/buttons/preview.js
  assets/src/edit-story/components/header/buttons/publish.js
  assets/src/edit-story/components/header/buttons/switchToDraft.js
  assets/src/edit-story/components/header/buttons/update.js
  assets/src/edit-story/components/header/context.js
  assets/src/edit-story/components/header/headerLayout.js
  assets/src/edit-story/components/header/karma/publish.karma.js
  assets/src/edit-story/components/header/provider.js
  assets/src/edit-story/components/header/stories/titleMissingDialog.js
  assets/src/edit-story/components/header/test/buttons.js
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/components/header/titleMissingDialog.js
  assets/src/edit-story/components/header/use.js
  assets/src/edit-story/karma/fixture/containers/canvas.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Group: Canvas, Group: FTUE, Pod: Prometheus (Workspace), cla: yes

#4362 Ensure we skip sizes that are malformed.
  assets/src/edit-story/elements/media/test/util.js
  assets/src/edit-story/elements/media/util.js
Labels: Group: Media, Pod: Media I/O, Type: Bug, cla: yes

#4405 Allow expanding the categories section when a category is selected.
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
Labels: Group: 3P Media, Pod: Media I/O, Type: Enhancement, cla: yes

#4317 Dashboard: Enable arrow navigation on explore templates grid
  assets/src/dashboard/app/views/exploreTemplates/karma/exploreTemplates.karma.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/templateGridView.js
  assets/src/dashboard/app/views/templateDetails/components.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/focusableGridItem.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/cardGridItem/test/cardTitle.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/storyMenu/index.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/constants/templates.js
  tests/e2e/specs/dashboard/documentTitle.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4228 Initial plumbing for text sets
  assets/src/edit-story/components/devTools/devTools.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textSets/getTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/index.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/editorial.json
Labels: Elements: Text, Pod: Pea (Dashboard & Templates), Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#4356 Dashboard: Add ability to update default publisher logo, context menu for logos
  assets/src/dashboard/app/api/useSettingsApi.js
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/popoverLogoContextMenu.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/test/publisherLogo.js
  assets/src/dashboard/app/views/editorSettings/test/editorSettings.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/constants/settings.js
  assets/src/dashboard/dataUtils/formattedPublisherLogos.js
  assets/src/dashboard/icons/editPencil.svg
  assets/src/dashboard/icons/index.js
  assets/src/dashboard/karma/apiProviderFixture.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4437 Quick a11y wins
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/media3p/providerTab.js
Labels: cla: yes

#4393 Add karma spec reporter
  karma-dashboard.config.cjs
  karma-edit-story.config.cjs
  package-lock.json
  package.json
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4395 Load newly uploaded videos without a delay
  assets/src/edit-story/components/library/panes/media/common/innerElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
Labels: Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#4442 Enforce webpackChunkName comments for dynamic imports
  .eslintrc
  assets/src/edit-story/components/library/panes/text/textSets/getTextSets.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4410 Update Web Stories icon
  assets/src/story-embed-block/block/icon.svg
  includes/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4441 Fix bundling to not drop certain CSS files
  webpack.config.cjs
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4397 Upload tab: improve width of media types dropdown
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/elements/video/karma/autoplay.karma.js
Labels: Group: Media, Type: Bug, cla: yes

#3261 Embed Block: Ensure AMP Compatibility
  bin/local-env/install-wordpress.sh
  includes/Embed_Block.php
  tests/e2e/config/bootstrap.js
  tests/e2e/matchers/toBeValidAMP.js
  tests/e2e/specs/wordpress/embedBlock.js
  tests/e2e/utils/index.js
  tests/e2e/utils/toolbarProfileOption.js
  tests/phpstan/bootstrap.php
  tests/phpunit/tests/Embed_Block.php
Labels: AMP Output, Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4411 Add WordPress.org assets to repository
  .distignore
  .wordpress-org/README.md
  .wordpress-org/banner-1544x500-rtl.png
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250-rtl.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/icon.svg
Labels: Skip Changelog, Type: Task, cla: yes

#4394 Telemetry updates
  assets/src/activation-notice/app/components/step1.js
  assets/src/activation-notice/app/components/step2.js
  assets/src/activation-notice/app/components/step3.js
  assets/src/activation-notice/app/components/successMessage.js
  assets/src/dashboard/app/router/routerProvider.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/myStories/header/test/header.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/templateGridView.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/utils/useStoryView.js
  assets/src/edit-story/components/errorBoundary/index.js
  assets/src/edit-story/components/header/buttons/preview.js
  assets/src/edit-story/components/header/buttons/publish.js
  assets/src/edit-story/components/header/postPublishDialog.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/story-embed-block/block/edit.js
  assets/src/tracking/enableTracking.js
  assets/src/tracking/shared.js
  assets/src/tracking/test/trackEvent.js
  assets/src/tracking/test/trackScreenView.js
  assets/src/tracking/test/trackTimingComplete.js
  assets/src/tracking/track.js
  assets/src/tracking/trackClick.js
  assets/src/tracking/trackEvent.js
  assets/src/tracking/trackScreenView.js
  assets/src/tracking/trackTimingComplete.js
  assets/src/tracking/typedefs.js
  includes/Tracking.php
  tests/js/jest.config.js
  tests/phpunit/tests/Tracking.php
Labels: Group: Telemetry, Pod: WP & Infra, Type: Enhancement, cla: yes

#4374 Dashboard: Telemetry Opt In Banner
  assets/images/analytics-banner-bg.png
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/exploreTemplates/header/test/header.js
  assets/src/dashboard/app/views/myStories/header/test/header.js
  assets/src/dashboard/app/views/savedTemplates/test/savedTemplates.js
  assets/src/dashboard/app/views/shared/karma/telemetryBanner.karma.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/stories/telemetryBanner.js
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/dashboard/app/views/shared/test/telemetryBanner.js
  assets/src/dashboard/app/views/shared/useTelemetryOptIn.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/karma/fixture.js
  assets/src/dashboard/testUtils/index.js
  assets/src/dashboard/testUtils/mockApiProvider.js
  assets/src/dashboard/testUtils/renderWithTheme.js
  includes/Tracking.php
  package-lock.json
  package.json
  tests/phpunit/tests/Media.php
  tests/phpunit/tests/REST_API/Stories_Autosaves_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/Tracking.php
Labels: Group: Dashboard, Group: Telemetry, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4152 Dashboard: Enable Settings View
  includes/Experiments.php
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4424 Dashboard A11y: Focus on preview close
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
Labels: cla: yes

#4355 Editor: Added keyboard shortcut menu
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/keyboardShortcutsMenu/constants.js
  assets/src/edit-story/components/keyboardShortcutsMenu/getKeyboardShortcuts.js
  assets/src/edit-story/components/keyboardShortcutsMenu/index.js
  assets/src/edit-story/components/keyboardShortcutsMenu/shortcutLabel.js
  assets/src/edit-story/components/keyboardShortcutsMenu/shortcutMenu.js
  assets/src/edit-story/components/keyboardShortcutsMenu/styled.js
  assets/src/edit-story/components/popup/utils.js
  assets/src/edit-story/theme.js
Labels: Pod: Pea (Dashboard & Templates), Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#4439 Apply visibility: inherit to dropdown arrow so there's no 'ghost' arrow
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
Labels: Group: 3P Media, Pod: Media I/O, Type: Bug, cla: yes

#4247 Crop leading & trailing whitespace
  assets/src/edit-story/app/font/defaultFonts.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/useResize.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/test/output.js
  assets/src/edit-story/elements/text/updateForResizeEvent.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/utils/test/textMeasurements.js
  assets/src/edit-story/utils/textMeasurements.js
Labels: Elements: Text, Group: Fonts, Type: Enhancement, cla: yes

#4426 Dashboard: Update logo
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/dashboard/images/logo.svg
  assets/src/dashboard/images/webStoriesFullLogo.svg
  assets/src/dashboard/theme.js
  includes/Dashboard.php
  webpack.config.cjs
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4448 Bump version to 1.0.0-rc.1
  web-stories.php
Labels: Pod: WP & Infra, Type: Infrastructure, Type: Task, cla: yes

#4454 Editor: Enable Keyboard Shortcut Menu
  includes/Experiments.php
Labels: Accessibility, Group: Editing, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4378 Adding a persistent scrollbar for media gallery to fix flickering.
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
Labels: Group: Media, Pod: Media I/O, Type: Enhancement, cla: yes

#4458 fix strange resizing of width of gallery
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
Labels: cla: yes

#4427 Dashboard: Update tests to use new renderWithProviders test util
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/test/googleAnalytics.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/test/publisherLogo.js
  assets/src/dashboard/app/views/editorSettings/telemetry/test/telemetrySettings.js
  assets/src/dashboard/app/views/editorSettings/test/editorSettings.js
  assets/src/dashboard/app/views/exploreTemplates/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/test/emptyView.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/previewStory/test/index.js
  assets/src/dashboard/app/views/shared/test/telemetryBanner.js
  assets/src/dashboard/components/alert/test/index.js
  assets/src/dashboard/components/bookmark-chip/test/bookmark-chip.js
  assets/src/dashboard/components/button/test/button.js
  assets/src/dashboard/components/cardGallery/test/cardGallery.js
  assets/src/dashboard/components/cardGrid/test/card-grid.js
  assets/src/dashboard/components/cardGridItem/test/cardGridItem.js
  assets/src/dashboard/components/cardGridItem/test/cardTitle.js
  assets/src/dashboard/components/detailViewNavBar/test/templateNavBar.js
  assets/src/dashboard/components/dialog/test/dialog.js
  assets/src/dashboard/components/dropdown/test/dropdown.js
  assets/src/dashboard/components/fileUpload/test/fileUpload.js
  assets/src/dashboard/components/infiniteScroller/test/infiniteScroller.js
  assets/src/dashboard/components/inlineInputForm/test/inlineInputForm.js
  assets/src/dashboard/components/modal/test/modal.js
  assets/src/dashboard/components/pageStructure/test/pageStructure.js
  assets/src/dashboard/components/pill/test/pill.js
  assets/src/dashboard/components/popoverMenu/test/popover-menu.js
  assets/src/dashboard/components/popoverPanel/test/popverPanel.js
  assets/src/dashboard/components/scrollToTop/test/scrollToTop.js
  assets/src/dashboard/components/storyMenu/test/storyMenu.js
  assets/src/dashboard/components/toaster/test/toaster.js
  assets/src/dashboard/components/toggleButtonGroup/test/toggleButtonGroup.js
  assets/src/dashboard/components/tooltip/test/tooltip.js
  assets/src/dashboard/components/typeaheadInput/test/typeaheadInput.js
  assets/src/dashboard/components/typeaheadOptions/test/typeaheadOptions.js
  assets/src/dashboard/components/viewStyleBar/test/viewStyleBar.js
  assets/src/dashboard/testUtils/index.js
  assets/src/dashboard/testUtils/mockApiProvider.js
  assets/src/dashboard/testUtils/renderWithProviders.js
Labels: cla: yes

#4468 Dashboard: Prevent Telemetry Banner from squishing stories
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/dashboard/components/layout/provider.js
  assets/src/dashboard/constants/index.js
Labels: cla: yes

#4479 E2E Tests: Add tests with JS disabled
  tests/e2e/specs/dashboard/noJS.js
  tests/e2e/specs/editor/noJS.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4465 Add since annotation to all PHPdoc blocks
  includes/Activation_Flag.php
  includes/Activation_Notice.php
  includes/Admin.php
  includes/Analytics.php
  includes/Dashboard.php
  includes/Database_Upgrader.php
  includes/Discovery.php
  includes/Embed_Block.php
  includes/Experiments.php
  includes/Fonts.php
  includes/KSES.php
  includes/Media.php
  includes/Model/Story.php
  includes/Plugin.php
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Fonts_Controller.php
  includes/REST_API/Link_Controller.php
  includes/REST_API/Stories_Autosaves_Controller.php
  includes/REST_API/Stories_Base_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/REST_API/Stories_Media_Controller.php
  includes/Settings.php
  includes/Story_Post_Type.php
  includes/Story_Renderer/Embed.php
  includes/Story_Renderer/HTML.php
  includes/Story_Renderer/Image.php
  includes/Template_Post_Type.php
  includes/Tracking.php
  includes/Traits/Assets.php
  includes/Traits/Document_Parser.php
  includes/Traits/Publisher.php
  includes/Traits/Types.php
  includes/Updater.php
  includes/namespace.php
  includes/plugin-compat/amp.php
  includes/uninstall.php
  uninstall.php
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4438 Use patch-package to fix horizontal jitter in the media gallery
  patches/react-photo-gallery+8.0.0.patch
Labels: Group: 3P Media, Type: Bug, cla: yes

#4462 Single Text Set Preview
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textSets/index.js
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/editorial.json
  assets/src/edit-story/components/library/panes/text/textSets/stories/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/utils.js
  assets/src/edit-story/constants.js
Labels: Pod: Prometheus (Workspace), cla: yes

#4494 E2E Tests: reduce flakiness
  package-lock.json
  patches/puppeteer+5.2.1.patch
  tests/e2e/specs/editor/publishingFlow.js
  tests/e2e/specs/wordpress/embedBlock.js
  tests/e2e/utils/index.js
  tests/e2e/utils/publishPost.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4483 Dashboard: Dynamically Size Telemetry Banner
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/dashboard/components/layout/provider.js
  assets/src/dashboard/constants/index.js
Labels: Pod: Pea (Dashboard & Templates), cla: yes

#4447 Update block name to ‘Web Stories’
  assets/src/story-embed-block/block/index.js
  tests/e2e/specs/wordpress/embedBlock.js
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4503 Use new babel eslint parser
  .eslintrc
  package-lock.json
  package.json
Labels: Pod: WP & Infra, Skip Changelog, Type: Code Quality, Type: Infrastructure, cla: yes

#4504 AMP: Added tests to validate text element output
  assets/src/edit-story/output/test/__snapshots__/textElement.js.snap
  assets/src/edit-story/output/test/_utils/constants.js
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/output/test/story.js
  assets/src/edit-story/output/test/textElement.js
Labels: AMP Output, Pod: Pea (Dashboard & Templates), Skip Changelog, Type: Infrastructure, cla: yes

#4471 Added karma tests and storybook entry for Keyboard Shortcuts menu
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/keyboardShortcutsMenu/index.js
  assets/src/edit-story/components/keyboardShortcutsMenu/karma/keyboardShortcuts.karma.js
  assets/src/edit-story/components/keyboardShortcutsMenu/stories/index.js
Labels: Pod: Pea (Dashboard & Templates), Skip Changelog, Type: Enhancement, Type: Infrastructure, cla: yes

#4521 Prevent removal of amp-story that lacks mandatory attributes
  includes/Story_Post_Type.php
Labels: cla: yes

#4435 Unsplash bake in
  assets/src/edit-story/components/library/karma/libraryTabs.karma.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/elements/image/karma/resourceLoading.karma.js
  assets/src/edit-story/elements/video/karma/autoplay.karma.js
  includes/Experiments.php
Labels: cla: yes

#4375 Use prod media3p key and domain
  assets/src/edit-story/app/media/media3p/api/apiFetcher.js
Labels: cla: yes

#4482 Fix edit mode for Text Style Presets
  assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js
  assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js
  assets/src/edit-story/components/panels/preset/presetPanel.js
  assets/src/edit-story/karma/fixture/containers/designPanel/colorPreset.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/textStylePreset.js
Labels: Group: Design Panel, Group: Saved Styles, Pod: Prometheus (Workspace), cla: yes

#4478 Text sets: improve the insertion logic
  assets/src/edit-story/components/library/panes/text/textSets/index.js
  assets/src/edit-story/components/library/panes/text/textSets/karma/textSets.karma.js
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/textSets.js
  assets/src/edit-story/components/library/panes/text/textSets/useInsertTextSet.js
Labels: Pod: Prometheus (Workspace), cla: yes

#4496 Generalize Pill component
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/media3p/categories/typedefs.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pCategories.js
  assets/src/edit-story/components/library/panes/shared/index.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/constants.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/index.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/pill.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/pillGroup.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/stories/pill.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/stories/pillGroup.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/test/pillGroup.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/useExpandAnimation.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/useHandleRowVisibility.js
  assets/src/edit-story/components/library/panes/shared/useRovingTabIndex.js
  assets/src/edit-story/karma/fixture/containers/library.js
  assets/src/edit-story/theme.js
Labels: Pod: Prometheus (Workspace), cla: yes

#4527 Fix default analytics configuration
  includes/Analytics.php
  tests/phpunit/tests/Analytics.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#4480 Remove all poster fallback logic
  assets/images/fallback-poster.png
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/serializers/storyPreview.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/edit-story/output/story.js
  assets/src/edit-story/output/test/story.js
  assets/src/edit-story/output/utils/test/getStoryMarkup.js
  includes/Story_Post_Type.php
  includes/Story_Renderer/HTML.php
  tests/phpunit/data/story_post_content.html
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: AMP Output, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4515 Use `/web-stories/` as the default base for stories, instead of `/stories/`
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/edit-story/app/api/test/_utils.js
  includes/Database_Upgrader.php
  includes/Story_Post_Type.php
  tests/e2e/specs/editor/__snapshots__/publishingFlow.js.snap
  tests/phpunit/tests/Story_Post_Type.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4539 Remove `amp` attribute when no poster is set
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: AMP Output, Group: WordPress, P0, Pod: WP & Infra, cla: yes

#4531 Removed `isBold` from text style preset (using only `fontWeight`)
  assets/src/edit-story/components/panels/preset/test/utils.js
  assets/src/edit-story/components/panels/preset/useApplyPreset.js
  assets/src/edit-story/components/panels/preset/utils.js
Labels: Elements: Text, Pod: Prometheus (Workspace), cla: yes

#4502 Dashboard: Reposition display on template change in detail view
  assets/src/dashboard/app/views/templateDetails/components.js
  assets/src/dashboard/app/views/templateDetails/content/detailsGallery/index.js
  assets/src/dashboard/app/views/templateDetails/content/detailsGallery/stories/index.js
  assets/src/dashboard/app/views/templateDetails/content/index.js
  assets/src/dashboard/app/views/templateDetails/content/relatedGrid/index.js
  assets/src/dashboard/app/views/templateDetails/content/relatedGrid/stories/index.js
  assets/src/dashboard/app/views/templateDetails/content/relatedGrid/test/relatedGrid.js
  assets/src/dashboard/app/views/templateDetails/content/stories/index.js
  assets/src/dashboard/app/views/templateDetails/header/index.js
  assets/src/dashboard/app/views/templateDetails/header/stories/index.js
  assets/src/dashboard/app/views/templateDetails/header/test/header.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/types.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, Type: Enhancement, cla: yes

#4486 Dashboard: Make 'Open in Editor' an a-tag link
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/popoverMenu/story-menu-generator.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#2845 FTUE: Add "Get Started" story for users to view in the editor
  bin/commander.js
  includes/Activation_Notice.php
  includes/Demo_Content.php
  includes/REST_API/Stories_Controller.php
  includes/data/stories/demo.json
  tests/e2e/specs/wordpress/getStartedStory.js
  tests/phpunit/tests/Demo_Content.php
Labels: Group: WordPress, P0, Pod: WP & Infra, Type: Enhancement, cla: yes

#4525 Fix layer panel accessibility
  assets/src/edit-story/components/keyboardShortcutsMenu/constants.js
  assets/src/edit-story/components/keyboardShortcutsMenu/getKeyboardShortcuts.js
  assets/src/edit-story/components/keyboardShortcutsMenu/styled.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/panels/layer/panel.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/handle.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/layers.js
Labels: Accessibility, Pod: Prometheus (Workspace), cla: yes

#4535 Fixed new element position
  assets/src/edit-story/components/canvas/useInsertElement.js
Labels: Pod: Prometheus (Workspace), cla: yes

#4556 Bump some GitHub action versions
  .github/workflows/continuous-integration-build.yml
  .github/workflows/continuous-integration-bundle-size.yml
  .github/workflows/continuous-integration-e2e.yml
  .github/workflows/continuous-integration-gh-pages.yml
  .github/workflows/continuous-integration-karma-dashboard.yml
  .github/workflows/continuous-integration-karma-edit-story.yml
  .github/workflows/continuous-integration-lint-css.yml
  .github/workflows/continuous-integration-lint-js.yml
  .github/workflows/continuous-integration-lint-md.yml
  .github/workflows/continuous-integration-lint-php.yml
  .github/workflows/continuous-integration-unit-js.yml
  .github/workflows/continuous-integration-unit-php.yml
  .github/workflows/update-google-fonts.yml
  .github/workflows/update-templates.yml
Labels: Dependencies, cla: yes

#4488 Dashboard: Make stories list view header sticky to keep in view on scroll
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/layout/provider.js
  assets/src/dashboard/components/layout/squishable.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/constants/pageStructure.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#4534 Dashboard: keep grid top in view of initial focus
  assets/src/dashboard/components/cardGrid/index.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4553 Prevent more markup being stripped for users without unfiltered_html capabilities
  includes/KSES.php
  tests/phpunit/tests/KSES.php
Labels: Group: WordPress, P0, Pod: WP & Infra, Type: Bug, cla: yes

#4545 Hiding horizontal scrollbar in media pane
  assets/src/edit-story/components/library/panes/media/common/styles.js
Labels: Group: Media, Pod: Prometheus (Workspace), cla: yes

#4572 Small i18n string improvements
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/templateGridView.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/form/color/color.js
Labels: Group: WordPress, Internationalization (I18N), Pod: WP & Infra, Type: Enhancement, cla: yes

#4519 Website: Web Stories Scraper
  .editorconfig
  .nvmrc
  web-stories-scraper/.eslintrc
  web-stories-scraper/.markdownlintignore
  web-stories-scraper/.npmrc
  web-stories-scraper/.prettierignore
  web-stories-scraper/.prettierrc
  web-stories-scraper/LICENSE
  web-stories-scraper/README.md
  web-stories-scraper/babel.config.cjs
  web-stories-scraper/index.js
  web-stories-scraper/package-lock.json
  web-stories-scraper/package.json
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4548 Added icons for arrow keys
  assets/src/edit-story/components/keyboardShortcutsMenu/constants.js
  assets/src/edit-story/components/keyboardShortcutsMenu/karma/keyboardShortcuts.karma.js
  assets/src/edit-story/components/keyboardShortcutsMenu/styled.js
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/key_arrow_up.svg
Labels: cla: yes

#4600 Added plain text paste handler
  assets/src/edit-story/components/richText/editor.js
  assets/src/edit-story/components/richText/karma/inlineSelection.karma.js
  assets/src/edit-story/components/richText/provider.js
  assets/src/edit-story/components/richText/useHandlePastedText.js
  karma/fixture/events.js
Labels: Elements: Text, Group: Copy/Paste, Pod: Prometheus (Workspace), cla: yes

#4565 Dashboard: Some style tweaks mostly surrounding spacing
  assets/src/dashboard/app/views/exploreTemplates/content/emptyView.js
  assets/src/dashboard/app/views/myStories/content/emptyView/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/noResults.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/components/cardGallery/components.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/dashboard/components/typography/index.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/constants/pageStructure.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4538 bake in coverr
  assets/src/edit-story/app/media/media3p/providerConfiguration.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  includes/Experiments.php
Labels: cla: yes

#4606 Handle redirects for `/stories/1234/`
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#4609 Bake in flags for stable release
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/shared/karma/telemetryBanner.karma.js
  assets/src/dashboard/app/views/toaster/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/keyboardShortcutsMenu/karma/keyboardShortcuts.karma.js
  includes/Experiments.php
Labels: Pod: WP & Infra, Type: Code Quality, Type: Infrastructure, cla: yes

#4611 Update demo content for stable release
  includes/Demo_Content.php
  includes/data/stories/demo.json
Labels: Group: WordPress, P0, Pod: WP & Infra, Type: Enhancement, cla: yes

#4583 Update plugin activation message styling
  .storybook/main.cjs
  assets/src/activation-notice/app/components/image.js
  assets/src/activation-notice/app/components/link.js
  assets/src/activation-notice/app/components/messageContent.js
  assets/src/activation-notice/app/components/paragraph.js
  assets/src/activation-notice/app/components/step1.js
  assets/src/activation-notice/app/components/step2.js
  assets/src/activation-notice/app/components/step3.js
  assets/src/activation-notice/app/components/successMessage.js
  assets/src/activation-notice/app/components/test/step1.js
  assets/src/activation-notice/app/components/test/step2.js
  assets/src/activation-notice/app/components/test/step3.js
  assets/src/activation-notice/app/components/test/successMessage.js
  assets/src/activation-notice/app/index.js
  assets/src/activation-notice/stories/index.js
  assets/src/activation-notice/testUtils/renderWithTheme.js
  assets/src/activation-notice/theme.js
  tests/e2e/specs/wordpress/pluginActivation.js
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4301 Run database upgrader on plugin activation
  includes/namespace.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4300 WordPress: Remove custom updater
  includes/Plugin.php
  includes/Updater.php
  tests/phpunit/tests/Plugin.php
  tests/phpunit/tests/Updater.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4601 Story Editor: Preset Panel Height & Collapse Persistence
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js
  assets/src/edit-story/components/panels/preset/presetPanel.js
  assets/src/edit-story/constants.js
Labels: Group: Design Panel, Group: Saved Colors, Group: Saved Styles, Type: Enhancement, cla: yes

#4610 Update readme for stable release
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  readme.txt
Labels: Pod: WP & Infra, Skip Changelog, Type: Task, cla: yes

#4617 fixed images
  build/en/docs/index.njk
Labels: cla: yes

#4618 Bump version to 1.0.0
  .distignore
  web-stories.php
Labels: Skip Changelog, Type: Task, cla: yes

#4631 fixed image sizes
  build/en/docs/index.njk
Labels: Website, cla: yes

#4657 Dashboard: A11y missing H1
  assets/src/dashboard/components/pageStructure/navigationComponents.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4658 fixed format issues, typos, images and added image
  build/en/docs/index.njk
  build/img/docs/12.png
  build/img/docs/5.png
  build/img/docs/keyboard.png
Labels: Website, cla: yes

#4522 Story Editor: Added Cover Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/cover.json
Labels: Group: Library, Group: Presets, Type: Enhancement, cla: yes

#4662 build for prod
  public/docs/index.html
  public/index.html
Labels: cla: yes

#4663 site tweaks
  build/en/docs/index.njk
  build/img/instagram-logo.png
  public/docs/index.html
  public/img/instagram-logo.png
Labels: cla: yes

#4665 🚡
  build/css/main.css
  build/en/index.njk
  public/css/main.css
  public/docs/index.html
  public/index.html
Labels: cla: yes

#4666 more
  build/css/main.css
  public/css/main.css
  public/docs/index.html
  public/index.html
Labels: cla: yes

#4667 docs fixes
  build/css/main.css
  build/en/docs/index.njk
  public/css/main.css
  public/docs/index.html
  public/img/64a593aa.png
  public/img/f1c5beeb.png
  public/index.html
Labels: cla: yes

#4668 make things less bad
  build/css/main.css
  build/en/index.njk
  public/css/main.css
  public/docs/index.html
  public/index.html
Labels: cla: yes

#4670 Readme: Remove duplicate paragraph
  readme.txt
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, Type: Task, cla: yes

#4674 Add .gitattributes file
  .gitattributes
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4672 Bump version to 1.1.0-alpha
  web-stories.php
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4619 Dashboard: Minor Template details Perf updates
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/components/cardGallery/index.js
Labels: Group: Templates, Type: Enhancement, Type: Performance, cla: yes

#4676 Try re-running failed karma tests once
  .github/workflows/continuous-integration-karma-dashboard.yml
  .github/workflows/continuous-integration-karma-edit-story.yml
  karma-dashboard.config.cjs
  karma-edit-story.config.cjs
  karma/karma-failed-tests-reporter/.eslintrc
  karma/karma-failed-tests-reporter/README.md
  karma/karma-failed-tests-reporter/index.cjs
  package.json
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4681 remove svg logo opacity, make docs on mobile less not good
  build/css/main.css
  build/img/web-creators-logo.svg
  public/css/main.css
  public/docs/index.html
  public/index.html
Labels: cla: yes

#4691 Karma: retry failed tests in the same step
  .github/workflows/continuous-integration-karma-dashboard.yml
  .github/workflows/continuous-integration-karma-edit-story.yml
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4540 Install phpstan via composer
  .github/workflows/continuous-integration-lint-php.yml
  composer.json
  composer.lock
  package.json
  phpcs.xml.dist
  phpstan.neon.dist
  tests/phpstan/src/GetPostDynamicFunctionReturnTypeExtension.php
  tests/phpstan/src/GetPostsDynamicFunctionReturnTypeExtension.php
  tests/phpstan/src/IsWpErrorFunctionTypeSpecifyingExtension.php
  tests/phpstan/stubs/wordpress-defines.php
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4655 Dashboard: Fix width bug on settings page
  assets/src/dashboard/app/views/editorSettings/components.js
Labels: Group: Dashboard, Type: Bug, cla: yes

#4731 Disable amp-to-amp linking for amp-story-player
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: AMP Output, Group: Integration, Group: WordPress, Pod: WP & Infra, cla: yes

#4696 Editor: Quote Text Set
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/quote.json
  assets/src/edit-story/masks/index.js
Labels: cla: yes

#4552 Story Editor: Added Editorial Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/raw/editorial.json
Labels: Group: Presets, Type: Enhancement, cla: yes

#4547 Story Editor: Added Step Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/step.json
Labels: Group: Presets, Type: Enhancement, cla: yes

#4746 Add target attributes to `<a>` tags
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: AMP Output, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4537 Story Editor: Added Section Header Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/section_header.json
Labels: Group: Presets, Type: Enhancement, cla: yes

#4732 Add target=_blank to element links
  assets/src/edit-story/components/elementLink/output.js
  assets/src/edit-story/components/elementLink/test/output.js
Labels: AMP Output, Group: Links, Type: Enhancement, cla: yes

#4730 Fixed flaky test and started using Percy
  assets/src/edit-story/components/richText/karma/inlineSelection.karma.js
  karma/fixture/init.js
Labels: Type: Infrastructure, cla: yes

#4761 Always override existing poster attribute on render
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: AMP Output, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes
