Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-10, with the labels that each got.

#4646 Ensure selection is displayed on top of Page navigation arrows
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/karma/selection.karma.js
  assets/src/edit-story/components/canvas/navLayer.js
  assets/src/edit-story/components/canvas/pagenav/index.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/karma/fixture/containers/canvas.js
  assets/src/edit-story/karma/fixture/containers/designPanel/textStyle.js
Labels: Pod: Prometheus (Workspace), Type: Bug, cla: yes

#4630 Dashboard: Restore GA Tracking Input's Label
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/test/googleAnalytics.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4776 Set up CodeQL code scanning
  .github/workflows/codeql-analysis.yml
  bin/utils/copyFiles.js
  bin/utils/generateZipFile.js
  bin/utils/test/copyFiles.js
  bin/utils/test/generateZipFile.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4777 Improve ESLint configuration for node scripts
  .eslintrc
  __mocks__/fs.js
  bin/utils/normalizeFont.js
  bin/utils/test/getFontMetrics.js
  package-lock.json
  package.json
  tests/e2e/config/bootstrap.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4779 Added waitFor call to let text sets load before executing karma tests
  assets/src/edit-story/components/library/panes/text/textSets/karma/textSets.karma.js
Labels: cla: yes

#4781 E2E Tests: Use `waitForTimeout` instead of `waitFor`
  tests/e2e/utils/previewStory.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4778 Karma: Add custom matcher for aXe accessibility violations
  assets/src/edit-story/components/canvas/karma/cloneSelection.karma.js
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  karma-dashboard.config.cjs
  karma-edit-story.config.cjs
  karma/fixture/init.js
  package-lock.json
  package.json
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4770 Story Editor: Added Table Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/table.json
Labels: Group: Presets, Type: Enhancement, cla: yes

#4765 Workspace: Grow/shrink text box element when padding increases or decreases.
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/padding.js
Labels: Elements: Text, Group: Editing, Pod: Pea, Type: Enhancement, cla: yes

#4543 Prefix Composer Dependencies
  .distignore
  .github/workflows/continuous-integration-unit-php.yml
  .gitignore
  bin/utils/createBuild.js
  bin/utils/test/createBuild.js
  codecov.yml
  composer.json
  composer.lock
  includes/AMP/Canonical_Sanitizer.php
  includes/AMP/Meta_Sanitizer.php
  includes/AMP/Optimization.php
  includes/AMP/Sanitization.php
  includes/AMP/Story_Sanitizer.php
  includes/Story_Renderer/HTML.php
  phpcs.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
  scoper.inc.php
  tests/phpunit/tests/AMP/Canonical_Sanitizer.php
  tests/phpunit/tests/AMP/Meta_Sanitizer.php
  tests/phpunit/tests/AMP/Optimization.php
  tests/phpunit/tests/AMP/Sanitization.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Infrastructure, cla: yes

#4589 Complete Text Sets Panel
  .github/workflows/codeql-analysis.yml
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/shared/index.js
  assets/src/edit-story/components/library/panes/text/textSets/karma/textSets.karma.js
  assets/src/edit-story/components/library/panes/text/textSets/test/raw.js
  assets/src/edit-story/components/library/panes/text/textSets/test/textSets.js
  assets/src/edit-story/components/library/panes/text/textSets/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/textSets.js
  assets/src/edit-story/components/library/panes/text/textSets/utils.js
Labels: Group: Presets, Pod: Prometheus, Type: Enhancement, cla: yes

#4660 Story Editor: Persist Active Page Between Reloads
  assets/src/edit-story/app/story/effects/test/useHashState.js
  assets/src/edit-story/app/story/effects/useHashState.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js
  assets/src/edit-story/app/story/useStoryReducer/test/_utils.js
  assets/src/edit-story/app/story/useStoryReducer/test/restore.js
  assets/src/edit-story/app/story/useStoryReducer/useStoryReducer.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/utils/useRefreshPostEditURL.js
Labels: Pod: Pea, cla: yes

#4698 Dashboard: Left Nav a11y updates
  assets/src/dashboard/components/pageStructure/index.js
Labels: Accessibility, Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#4750 Editor: Contact Text Set
  assets/src/edit-story/components/library/panes/text/textSets/karma/textSets.karma.js
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/contact.json
  assets/src/edit-story/masks/index.js
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4748 Dashboard: add support link to navigation
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/test/pageStructure.js
  assets/src/dashboard/constants/index.js
Labels: Group: Dashboard, Pod: Pea, cla: yes

#4697 Dashboard: Scroll to top a11y updates
  assets/src/dashboard/components/layout/provider.js
  assets/src/dashboard/components/layout/scrollable.js
Labels: Accessibility, Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#4787 Remove fallback publisher logo
  assets/images/fallback-wordpress-publisher-logo.png
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/edit-story/output/story.js
  assets/src/edit-story/output/test/story.js
  assets/src/edit-story/output/utils/test/getStoryMarkup.js
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/Story_Renderer/HTML.php
  includes/Traits/Publisher.php
  tests/phpunit/tests/Discovery.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#4822 Dashboard: Fix failing settings page karma test
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
Labels: Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#4563 Story Editor: Added List Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/loadTextSets.js
  assets/src/edit-story/components/library/panes/text/textSets/raw/list.json
  assets/src/edit-story/masks/index.js
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4763 Update Stories WordPress admin menu
  includes/Dashboard.php
  includes/Experiments.php
  tests/e2e/specs/dashboard/documentTitle.js
  tests/e2e/specs/dashboard/templates/useTemplate.js
  tests/e2e/specs/wordpress/adminMenu.js
  tests/phpunit/tests/Dashboard.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4786 Drop targeting: preserve origin element link if available.
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/components/dropTargets/karma/order.karma.js
Labels: Pod: Prometheus, cla: yes

#4704 Add design space guidelines
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/karma/snapping.karma.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/useDrag.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js
  assets/src/edit-story/components/canvas/test/multiSelectionMoveable.js
  assets/src/edit-story/components/canvas/utils/useSnapping.js
  assets/src/edit-story/components/moveable/moveStyle.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/theme.js
Labels: Pod: Prometheus, cla: yes

#4824 Story Editor: Added Table Funky Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/raw/table.json
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4827 Story Editor: Added Step & Contact Funky Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/raw/contact.json
  assets/src/edit-story/components/library/panes/text/textSets/raw/step.json
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4654 Dashboard: A11y improvements for the telemetry banner
  assets/src/dashboard/app/views/shared/karma/telemetryBanner.karma.js
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/dashboard/app/views/shared/test/telemetryBanner.js
Labels: Accessibility, Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#4831 Story Editor: Added List Funky Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/raw/list.json
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4826 Story Editor: Added Cover Funky Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/raw/cover.json
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4825 Story Editor: Added Editorial Funky Text Sets
  assets/src/edit-story/components/library/panes/text/textSets/raw/editorial.json
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4699 Dashboard: Template Details a11y updates
  assets/src/dashboard/app/views/exploreTemplates/karma/exploreTemplates.karma.js
  assets/src/dashboard/app/views/templateDetails/header/index.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/dashboard/components/detailViewNavBar/index.js
Labels: Accessibility, Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#4820 Dashboard: fix console warning for htmlFor
  .eslintrc
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
Labels: Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#4844 Story Editor: Added Contact text set design updates
  assets/src/edit-story/components/library/panes/text/textSets/raw/contact.json
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4608 Fixed numeric sanitization logic so entering in values can be easier
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/form/test/numeric.js
  assets/src/edit-story/components/panels/test/layerStyle.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/richText/karma/inlineSelection.karma.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
  assets/src/edit-story/components/richText/karma/singleSelection.karma.js
Labels: Pod: Pea, Type: Enhancement, cla: yes

#4845 Story Editor: Added Quote text set design updates
  assets/src/edit-story/components/library/panes/text/textSets/raw/quote.json
Labels: Group: Presets, Group: Workspace, Type: Enhancement, cla: yes

#4759 Re-index stories in Yoast SEO if permalinks are outdated
  includes/Database_Upgrader.php
  phpstan.neon.dist
  tests/phpstan/bootstrap.php
  tests/phpstan/stubs/amp.php
  tests/phpstan/stubs/wordpress-seo.php
  tests/phpstan/stubs/wp-cli.php
  tests/phpstan/stubs/wpdotcom.php
  web-stories.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4835 Improve bulk updated messages for stories
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4834 Support string translations with markup
  assets/src/activation-notice/app/components/step1.js
  assets/src/activation-notice/app/components/step2.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/app/views/editorSettings/telemetry/index.js
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/edit-story/components/header/postPublishDialog.js
  assets/src/edit-story/components/header/titleMissingDialog.js
  assets/src/i18n/index.js
  assets/src/i18n/test/transformNode.js
  assets/src/i18n/test/translateWithMarkup.js
  assets/src/i18n/translateWithMarkup.js
Labels: Group: WordPress, Internationalization (I18N), Pod: WP & Infra, Type: Enhancement, cla: yes

#4792 Tests: Improve multisite compatibility and how capabilities are set
  includes/namespace.php
  tests/phpunit/tests/Database_Upgrader.php
  tests/phpunit/tests/Discovery.php
  tests/phpunit/tests/REST_API/Embed_Controller.php
  tests/phpunit/tests/REST_API/Link_Controller.php
  tests/phpunit/tests/REST_API/Stories_Autosaves_Controller.php
  tests/phpunit/tests/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4766 Average background media color for page background
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  assets/src/edit-story/components/dropTargets/karma/order.karma.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/library/panes/media/common/innerElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/sizePosition/panel.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/utils/getMediaBaseColor.js
Labels: Pod: Prometheus, cla: yes

#4795 Fix typo in test name
  assets/src/edit-story/components/library/karma/shapes/shapes.karma.js
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#4856 Change "Multiple" to "Mixed"
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/form/color/test/colorPreview.js
  assets/src/edit-story/components/form/index.js
  assets/src/edit-story/components/form/multipleValue.js
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/panels/test/imageAccessibility.js
  assets/src/edit-story/components/panels/test/layerStyle.js
  assets/src/edit-story/components/panels/test/linkPanel.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/test/videoAccessibility.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/components/richText/karma/inlineSelection.karma.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
  assets/src/edit-story/components/richText/karma/singleSelection.karma.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#4774 Dashboard: get author names via _embedded data to avoid excess call for users
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/test/useStoryApi.js
  assets/src/dashboard/app/api/test/useUserApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useUserApi.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/serializers/stories.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/stories/storyGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/dashboard/testUtils/mockApiProvider.js
  assets/src/dashboard/types.js
  includes/Dashboard.php
  includes/REST_API/Stories_Controller.php
Labels: Group: Dashboard, Pod: Pea, Type: Performance, cla: yes

#4837 Improve link handling
  assets/src/edit-story/components/elementLink/frame.js
  assets/src/edit-story/components/elementLink/output.js
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js
  assets/src/edit-story/output/test/page.js
Labels: Elements, Group: Links, Pod: Prometheus, Type: Bug, cla: yes

#4889 Readme: add link to license badge
  README.md
Labels: Skip Changelog, Type: Documentation, cla: yes

#4497 Wrap Apps in Strict Mode
  assets/src/activation-notice/index.js
  assets/src/dashboard/index.js
  assets/src/edit-story/index.js
Labels: Pod: WP & Infra, Type: Enhancement, Type: Infrastructure, cla: yes

#4886 Analytics: add events for bookend
  includes/Analytics.php
Labels: Group: Analytics, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4875 Fix missing frame when selecting an element
  assets/src/edit-story/components/canvas/karma/selection.karma.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js
Labels: Group: Workspace, Pod: Prometheus, Type: Bug, cla: yes

#4733 Change amp-story-page background color to match editor preview
  assets/src/edit-story/output/utils/styles.js
  assets/src/edit-story/theme.js
Labels: Group: Canvas, Pod: Prometheus, Type: Enhancement, cla: yes

#4783 Added ability for partial hex values in color input
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/form/color/getHexFromValue.js
  assets/src/edit-story/components/form/color/test/colorPreview.js
  assets/src/edit-story/components/form/color/test/getHexFromValue.js
  assets/src/edit-story/components/richText/karma/inlineSelection.karma.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
  assets/src/edit-story/components/richText/karma/singleSelection.karma.js
Labels: Pod: Pea, Type: Enhancement, cla: yes

#4513 Include AMP PHP Library
  .distignore
  .github/workflows/continuous-integration-unit-php.yml
  .gitignore
  bin/utils/createBuild.js
  bin/utils/test/createBuild.js
  codecov.yml
  composer.json
  composer.lock
  includes/AMP/Canonical_Sanitizer.php
  includes/AMP/Integration/AMP_Story_Sanitizer.php
  includes/AMP/Meta_Sanitizer.php
  includes/AMP/Optimization.php
  includes/AMP/Sanitization.php
  includes/AMP/Story_Sanitizer.php
  includes/AMP/Traits/Sanitization_Utils.php
  includes/REST_API/Link_Controller.php
  includes/Story_Post_Type.php
  includes/Story_Renderer/HTML.php
  includes/Traits/Document_Parser.php
  package.json
  patches/php-css-parser-commit-10a2501.patch
  patches/php-css-parser-pull-185.patch
  patches/php-css-parser-pull-193.patch
  phpcs.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
  scoper.inc.php
  tests/phpstan/bootstrap.php
  tests/phpstan/stubs/amp.php
  tests/phpunit/includes/MarkupComparison.php
  tests/phpunit/includes/ScriptHash.php
  tests/phpunit/tests/AMP/Canonical_Sanitizer.php
  tests/phpunit/tests/AMP/Meta_Sanitizer.php
  tests/phpunit/tests/AMP/Optimization.php
  tests/phpunit/tests/AMP/Sanitization.php
  tests/phpunit/tests/AMP/Story_Sanitizer.php
  tests/phpunit/tests/Story_Renderer/HTML.php
  web-stories.php
Labels: AMP Output, Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4780 Web Stories Embed Shortcode
  assets/src/story-embed-block/block/index.js
  assets/src/story-embed-block/block/transforms.js
  includes/Block/Embed_Block.php
  includes/Embed_Base.php
  includes/Plugin.php
  includes/Shortcode/Embed_Shortcode.php
  includes/Story_Renderer/Embed.php
  includes/Story_Renderer/Image.php
  tests/phpunit/tests/Block/Embed_Block.php
  tests/phpunit/tests/Embed_Base.php
  tests/phpunit/tests/Shortcode/Embed_Shortcode.php
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4852 Story Editor: Design Updates to Panel
  assets/src/edit-story/components/library/common/index.js
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/shapes/shapePreview.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/shared/index.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/library/test/text/textPane.js
  assets/src/edit-story/constants.js
Labels: Group: Workspace, cla: yes

#4892 Animation: Rotation UI Component
  assets/src/edit-story/components/panels/animation/directionRadioInput.js
  assets/src/edit-story/components/panels/animation/stories/directionRadioInput.js
Labels: Group: Animations, Type: Bug, Type: Enhancement, cla: yes

#4901 Editor: Virtualize Text Sets List
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textSets/getTextSetReducer.js
  assets/src/edit-story/components/library/panes/text/textSets/test/getTextSetReducer.js
  assets/src/edit-story/components/library/panes/text/textSets/test/textSets.js
  assets/src/edit-story/components/library/panes/text/textSets/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/textSets.js
  package-lock.json
  package.json
Labels: Group: Library, Group: Workspace, Pod: Pea, Type: Bug, Type: Performance, cla: yes

#4908 Add mbstring polyfill
  composer.json
  composer.lock
  includes/polyfills/mbstring.php
  phpcs.xml.dist
  phpstan.neon.dist
  scoper.inc.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4855 Dashboard: Catch Saved Templates up to existing structures
  assets/src/dashboard/app/reducer/templates.js
  assets/src/dashboard/app/serializers/savedTemplates.js
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/savedTemplates/content/index.js
  assets/src/dashboard/app/views/savedTemplates/content/stories/index.js
  assets/src/dashboard/app/views/savedTemplates/content/test/content.js
  assets/src/dashboard/app/views/savedTemplates/header/index.js
  assets/src/dashboard/app/views/savedTemplates/header/stories/index.js
  assets/src/dashboard/app/views/savedTemplates/header/test/header.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/savedTemplates/savedTemplatesGridView/index.js
  assets/src/dashboard/app/views/savedTemplates/test/savedTemplates.js
  assets/src/dashboard/app/views/shared/index.js
  assets/src/dashboard/app/views/shared/savedTemplateGridView.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/constants/savedTemplates.js
Labels: Group: Dashboard, Pod: Pea, Type: Code Quality, cla: yes

#4842 Disable height field if unlocked and text is in selection.
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/panels/karma/sizePosition.karma.js
  assets/src/edit-story/components/panels/sizePosition/panel.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/sizePosition.js
Labels: Pod: Prometheus, cla: yes

#4887 Enforce Canvas to be LTR to support Moveable
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/karma/rtl.karma.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Group: Selection, Internationalization (I18N), Pod: Prometheus, Type: Bug, cla: yes

#4695 Dashboard: Settings view a11y updates
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/popoverLogoContextMenu.js
  assets/src/dashboard/app/views/editorSettings/telemetry/index.js
  assets/src/dashboard/components/popoverMenu/menu.js
Labels: Accessibility, Group: Dashboard, Type: Enhancement, cla: yes

#4680 Dashboard: Focusable Search
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/typeaheadSearch.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/typeahead/components.js
  assets/src/dashboard/components/typeahead/index.js
  assets/src/dashboard/components/typeahead/stories/index.js
  assets/src/dashboard/components/typeahead/test/typeaheadInput.js
  assets/src/dashboard/components/typeahead/test/useTypeahead.js
  assets/src/dashboard/components/typeahead/typeaheadOptions/components.js
  assets/src/dashboard/components/typeahead/typeaheadOptions/index.js
  assets/src/dashboard/components/typeahead/typeaheadOptions/stories/index.js
  assets/src/dashboard/components/typeahead/typeaheadOptions/test/typeaheadOptions.js
  assets/src/dashboard/components/typeahead/useTypeahead.js
  assets/src/dashboard/components/typeaheadInput/index.js
  assets/src/dashboard/components/typeaheadOptions/index.js
Labels: Accessibility, Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#4905 Workspace: Show text sets for used fonts in story
  assets/src/edit-story/components/library/panes/text/textSets/test/textSets.js
  assets/src/edit-story/components/library/panes/text/textSets/textSets.js
  assets/src/edit-story/utils/getInUseFonts.js
  assets/src/edit-story/utils/test/getInUseFonts.js
Labels: Elements: Text, Group: Workspace, Type: Enhancement, cla: yes

#4846 Workspace: Fix crash where we have multiple elements with multiple colors selected
  assets/src/edit-story/components/panels/textStyle/useRichTextFormatting.js
Labels: Group: Editing, Group: Workspace, P0, Pod: Pea, Type: Bug, cla: yes

#4769 Dashboard: Trigger load more stories when using keyboard to navigate grid
  assets/src/dashboard/app/views/exploreTemplates/content/index.js
  assets/src/dashboard/app/views/savedTemplates/content/index.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/detailViewNavBar/index.js
  assets/src/dashboard/components/infiniteScroller/index.js
  assets/src/dashboard/components/scrollToTop/index.js
  assets/src/dashboard/components/storyMenu/index.js
  assets/src/dashboard/components/typeahead/components.js
  assets/src/dashboard/components/viewStyleBar/index.js
Labels: Accessibility, Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#4675 Fix the padding/alignment issues in highlight mode
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/output/test/__snapshots__/textElement.js.snap
Labels: Elements: Text, Group: Fonts, Type: Enhancement, cla: yes

#4988 Text Sets: Lists
  assets/src/edit-story/components/library/panes/text/textSets/raw/list.json
Labels: Pod: Pea, cla: yes

#4993 Text Sets: Steps
  assets/src/edit-story/components/library/panes/text/textSets/raw/step.json
Labels: Pod: Pea, cla: yes

#4992 Text Sets: Section header
  assets/src/edit-story/components/library/panes/text/textSets/raw/section_header.json
Labels: cla: yes

#4991 Text Sets: Editorial
  assets/src/edit-story/components/library/panes/text/textSets/raw/editorial.json
Labels: cla: yes

#4987 Text Sets: Table
  assets/src/edit-story/components/library/panes/text/textSets/raw/table.json
Labels: cla: yes

#4985 Text Sets: Quote
  assets/src/edit-story/components/library/panes/text/textSets/raw/quote.json
Labels: cla: yes

#4984 Text Sets: Cover
  assets/src/edit-story/components/library/panes/text/textSets/raw/cover.json
Labels: cla: yes

#4929 Workspace: Font variant bug
  assets/src/edit-story/components/richText/getFontVariants.js
  assets/src/edit-story/components/richText/test/getFontVariants.js
  assets/src/edit-story/output/utils/getFontDeclarations.js
  assets/src/edit-story/utils/test/getGoogleFontURL.js
Labels: Elements: Text, Group: Fonts, Group: Workspace, P1, Pod: Pea, Type: Bug, cla: yes

#4849 Use shortcode when classic editor plugin is active
  bin/local-env/install-wordpress.sh
  includes/Admin.php
  tests/e2e/specs/editor/__snapshots__/publishingFlow.js.snap
  tests/e2e/specs/editor/publishingFlow.js
  tests/phpunit/tests/Admin.php
Labels: Group: Blocks, Type: Enhancement, cla: yes

#4671 Embed Block: responsive design improvements
  .stylelintignore
  assets/src/story-embed-block/block/edit.js
  assets/src/story-embed-block/block/embedPreview.js
  includes/Block/Embed_Block.php
  includes/Embed_Base.php
  includes/Story_Renderer/Embed.php
  includes/assets/embed.css
  package.json
Labels: AMP Format, AMP Output, Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4615 Add captions option for video elements.
  assets/src/edit-story/components/panels/captions/captions.js
  assets/src/edit-story/components/panels/captions/index.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/elements/video/test/output.js
  assets/src/edit-story/types.js
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Accessibility, Elements: Video, Group: Media, Type: Enhancement, cla: yes

#4999 Fix composer version.
  .github/workflows/continuous-integration-build.yml
  .github/workflows/continuous-integration-e2e.yml
  .github/workflows/continuous-integration-lint-php.yml
  .github/workflows/continuous-integration-unit-php.yml
Labels: cla: yes

#5001 Lock version number of php-scoper
  composer.json
  composer.lock
Labels: cla: yes

#4932 Readme: Add Terms of Service
  readme.txt
Labels: Type: Documentation, cla: yes

#5002 Update PHPStan config
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: Pod: WP & Infra, Type: Code Quality, Type: Infrastructure, cla: yes

#4994 Surface third party media usage notice
  assets/src/edit-story/components/library/karma/libraryTabs.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/stories/termsDialog.js
  assets/src/edit-story/components/library/panes/media/media3p/termsDialog.js
  assets/src/edit-story/components/library/test/__snapshots__/termsDialog.js.snap
  assets/src/edit-story/components/library/test/termsDialog.js
  assets/src/edit-story/utils/localStore.js
Labels: Group: 3P Media, Group: Media, P1, Pod: Pea, cla: yes

#4900 Text Style: Reset font weight to regular on font family change
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/components/panels/textStyle/getClosestFontWeight.js
  assets/src/edit-story/components/panels/textStyle/test/getClosestFontWeight.js
  assets/src/edit-story/components/panels/textStyle/useRichTextFormatting.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
  assets/src/edit-story/karma/textStyle.cuj.karma.js
Labels: Elements: Text, Pod: Pea, Type: Bug, cla: yes

#4974 Frontend: Avoid mixed content warnings by fixing URLs to use HTTPS
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5009 Admin menu: avoid unnecessary redirects
  includes/Dashboard.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4859 Base64-encode HTML markup over the wire
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/api/base64Encode.js
  assets/src/edit-story/app/api/test/base64Encode.js
  composer.json
  composer.lock
  includes/Dashboard.php
  includes/REST_API/Stories_Base_Controller.php
  includes/Story_Post_Type.php
  includes/Traits/Decoder.php
  tests/js/setup-globals.js
  tests/phpunit/tests/Traits/Decoder.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#4775 Editor: Font sizes now allow decimals and updated text presets font sizes.
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/library/panes/text/karma/textPane.karma.js
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/panels/karma/textStyle.karma.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/units/dimensions.js
Labels: Pod: Pea, Type: Enhancement, cla: yes

#4983 Embeds: Add filter for default attributes
  includes/Embed_Base.php
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#4613 Text Sets: Enable feature flag plus integration tests
  assets/src/edit-story/components/library/panes/text/karma/textPane.karma.js
  assets/src/edit-story/components/library/panes/text/karma/textSets.cuj.karma.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textSets/karma/textSets.karma.js
  assets/src/edit-story/karma/fixture/containers/library/index.js
  assets/src/edit-story/karma/fixture/containers/library/text.js
  includes/Experiments.php
Labels: Group: Presets, Pod: Pea, Type: Enhancement, cla: yes

#5019 Added embed query for getting author data on duplication.
  assets/src/dashboard/app/api/useStoryApi.js
Labels: Group: Dashboard, Type: Bug, cla: yes

#4904 Workspace: Enable Tenor GIF integration with editor
  assets/src/edit-story/app/media/media3p/providerConfiguration.js
  includes/Experiments.php
Labels: Group: 3P Media, Pod: Pea, Status: Blocked, cla: yes

#4986 Enable react/no-array-index-key rule
  .eslintrc
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/colorList/index.js
  assets/src/dashboard/components/infiniteScroller/stories/index.js
  assets/src/dashboard/components/pill/stories/index.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/i18n/translateWithMarkup.js
Labels: Type: Infrastructure, cla: yes

#5022 Fix base64 encoding when using chars from different range
  assets/src/edit-story/app/api/base64Encode.js
  assets/src/edit-story/app/api/test/base64Encode.js
Labels: Group: WordPress, P0, Pod: WP & Infra, Type: Bug, cla: yes

#4979 Improve E2E test flakyness.
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  percy.config.yml
  tests/e2e/specs/dashboard/dashboard.js
  tests/e2e/specs/dashboard/documentTitle.js
  tests/e2e/specs/wordpress/adminMenu.js
  tests/e2e/specs/wordpress/getStartedStory.js
  tests/e2e/specs/wordpress/pluginActivation.js
  tests/e2e/utils/publishPost.js
Labels: Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#5034 Fix ability to rename dashboard stories
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/useStoryApi.js
Labels: Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#5026 Fix typo in media pane search input prop
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
Labels: Group: Media, Type: Code Quality, cla: yes

#5038 Make WAF workaround opt-in for now
  includes/Dashboard.php
  includes/Decoder.php
  includes/Experiments.php
  includes/REST_API/Stories_Base_Controller.php
  includes/Story_Post_Type.php
  tests/phpunit/tests/Decoder.php
  tests/phpunit/tests/Traits/Decoder.php
Labels: Group: Integration, Group: WordPress, P0, Pod: WP & Infra, Type: Bug, cla: yes

#5047 Bump version to 1.1.0
  readme.txt
  web-stories.php
Labels: Type: Enhancement, cla: yes

#5045 Revert "Text Style: Reset font weight to regular on font family change"
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/components/panels/textStyle/getClosestFontWeight.js
  assets/src/edit-story/components/panels/textStyle/test/getClosestFontWeight.js
  assets/src/edit-story/components/panels/textStyle/useRichTextFormatting.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
  assets/src/edit-story/karma/textStyle.cuj.karma.js
Labels: Elements: Text, Group: Design Panel, Group: Fonts, P0, Type: Bug, cla: yes

#5042 Code Quality: Add PHPMD to code base
  .distignore
  .github/workflows/continuous-integration-lint-php.yml
  composer.json
  composer.lock
  includes/AMP/Sanitization.php
  includes/Activation_Flag.php
  includes/Analytics.php
  includes/Experiments.php
  includes/KSES.php
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Link_Controller.php
  includes/REST_API/Stories_Autosaves_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/Tracking.php
  includes/namespace.php
  package.json
  phpmd.xml
Labels: Pod: WP & Infra, Type: Code Quality, Type: Infrastructure, cla: yes

#5078 Prevent issues with centered embed blocks on certain themes
  includes/assets/embed.css
Labels: Group: Blocks, Group: Integration, Group: WordPress, Pod: WP & Infra, cla: yes
