Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-08, with the labels that each got.

#3566 3P Media: Add author attribution to the Media Element
  assets/src/edit-story/components/library/panes/media/common/attribution.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/stories/mediaElement.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3644 Dashboard: Prevent current template from being listed as related
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/views/templateDetails/index.js
Labels: Group: Dashboard, Group: Templates, Type: Bug, cla: yes

#3393 Workspace: Add Save and Select All Keyboard Events
  assets/src/edit-story/components/canvas/karma/canvasKeys.karma.js
  assets/src/edit-story/components/canvas/test/useCanvasKeys.js
  assets/src/edit-story/components/canvas/useCanvasKeys.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/keyboard/index.js
Labels: Group: Editing, Pod: Pea (Dashboard & Templates), Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#3642 Animations: Added Animation Timeline Base
  assets/src/edit-story/components/animationTimeline/components.js
  assets/src/edit-story/components/animationTimeline/index.js
  assets/src/edit-story/components/animationTimeline/stories/index.js
  assets/src/edit-story/components/animationTimeline/test/animationTimeline.test.js
  assets/src/edit-story/theme.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3645 Adding percy tests to mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: Group: Media, Skip Changelog, Type: Infrastructure, cla: yes

#3549 Improve Site Kit Analytics module detection
  includes/Analytics.php
  phpstan.neon.dist
  tests/phpunit/tests/Analytics.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3691 Performance: Fix media preloading
  includes/templates/admin/edit-story.php
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#3545 Dashboard: Added Fly In animation effect
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/effects/flyIn/index.js
  assets/src/dashboard/animations/effects/flyIn/stories/index.js
  assets/src/dashboard/animations/parts/index.js
  assets/src/dashboard/animations/utils/getOffPageOffset.js
  assets/src/dashboard/animations/utils/test/defaultUnit.js
  assets/src/dashboard/animations/utils/test/getOffPageOffset.js
  assets/src/dashboard/components/storyAnimation/provider.js
  assets/src/dashboard/components/storyAnimation/test/provider.js
  assets/src/dashboard/constants/components.js
  assets/src/dashboard/constants/pageStructure.js
  assets/src/dashboard/storybookUtils/ampStoryWrapper.js
  assets/src/dashboard/storybookUtils/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3692 Add default values for meta fields
  includes/Media.php
  includes/Tracking.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#3682 Media: Use thumbnails with same orientation
  assets/src/edit-story/app/media/utils/getThumbnailUrl.js
  assets/src/edit-story/app/media/utils/test/getThumbnailUrl.js
Labels: Group: Media, Type: Enhancement, cla: yes

#3320 Media: Enable row-based gallery in Uploads tab
  includes/Story_Post_Type.php
Labels: Group: Media, Type: Enhancement, cla: yes

#3710 Media: Include Square as a possible orientation when trying to find a thumbnail of correct orientation
  assets/src/edit-story/app/media/utils/getThumbnailUrl.js
  assets/src/edit-story/app/media/utils/test/getThumbnailUrl.js
Labels: cla: yes

#3711 fix mediaFetching local karma test
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/karma/mediaFetching.karma.js
Labels: cla: yes

#3577 3P Media: Display loading pill position: absolute and xor with attribution
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/common/test/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3714 Increase priority for template_include filter
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#3521 Workspace: Add support for curated fonts in the new font picker
  assets/src/edit-story/app/font/curatedFonts.js
  assets/src/edit-story/app/font/fontProvider.js
  assets/src/edit-story/components/fontPicker/pickerContainer.js
  assets/src/edit-story/components/fontPicker/test/fontPicker.js
Labels: Group: Fonts, Type: Enhancement, cla: yes

#3506 Use DOMDocument for rendering full story
  includes/Story_Renderer.php
  phpcs.xml.dist
  tests/phpunit/tests/Story_Renderer.php
Labels: Group: WordPress, PHP, Pod: WP & Infra, Type: Enhancement, cla: yes

#3715 Enable dev mode locally
  bin/local-env/install-wordpress.sh
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Infrastructure, cla: yes

#3480 Add UI to enable/disable experiments (feature flags)
  bin/local-env/install-wordpress.sh
  docs/feature-flags.md
  includes/Dashboard.php
  includes/Experiments.php
  includes/Plugin.php
  includes/Settings.php
  includes/Story_Post_Type.php
  includes/namespace.php
  includes/templates/admin/experiments.php
  phpstan.neon.dist
  tests/e2e/utils/experimentalFeatures.js
  tests/e2e/utils/index.js
  tests/phpstan/bootstrap.php
  tests/phpunit/tests/Dashboard.php
  tests/phpunit/tests/Experiments.php
  tests/phpunit/tests/Plugin.php
  tests/phpunit/tests/Settings.php
  tests/phpunit/tests/Story_Post_Type.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3693 Animations: Add Twirl In Animation Effect
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/effects/twirlIn/index.js
  assets/src/dashboard/animations/effects/twirlIn/stories/index.js
  assets/src/dashboard/animations/parts/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3620 Add provider json configuration, adding a dummy Coverr provider
  assets/src/edit-story/app/media/local/actions.js
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/attribution.js
  assets/src/edit-story/app/media/media3p/providerConfiguration.js
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/test/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/useFetchCategoriesEffect.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
  assets/src/edit-story/app/media/providerType.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/stories/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/common/test/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/providerTab.js
  assets/src/edit-story/components/library/test/mediaElement.js
  includes/Experiments.php
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3621 Improve AMP plugin compatibility
  assets/src/edit-story/output/story.js
  codecov.yml
  includes/Embed_Block.php
  includes/Plugin.php
  includes/Story_Post_Type.php
  includes/namespace.php
  includes/plugin-compat/amp.php
  tests/phpunit/tests/Plugin.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: AMP, cla: yes

#3507 Add custom capabilities for story post type
  includes/Dashboard.php
  includes/Database_Upgrader.php
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Fonts_Controller.php
  includes/REST_API/Link_Controller.php
  includes/Story_Post_Type.php
  includes/namespace.php
  tests/phpunit/tests/Dashboard.php
  tests/phpunit/tests/Story_Post_Type.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3485 Update poster image sizes
  includes/Admin.php
  includes/Discovery.php
  includes/Media.php
  includes/Story_Renderer.php
  tests/phpunit/tests/Admin.php
  tests/phpunit/tests/Media.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3695 Animations: Added Zoom animation effect
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/effects/zoom/index.js
  assets/src/dashboard/animations/effects/zoom/stories/index.js
  assets/src/dashboard/animations/parts/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3730 3P Media: Misc fixes
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/media3p/categories/reducer.js
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/test/providerReducer.js
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/categoryPill.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
Labels: Group: 3P Media, Type: Bug, cla: yes

#3749 update duration location
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/theme.js
Labels: cla: yes

#3244 Dashboard: Display dates relative to proper timezone
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/test/useStoryApi.js
  assets/src/dashboard/app/api/test/useTemplateApi.js
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/serializers/stories.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/cardGridItem/test/cardTitle.js
  assets/src/dashboard/dataUtils/dateSettings.js
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/dashboard/dataUtils/formattedTemplatesArray.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/dashboard/karma/fixture.js
  assets/src/dashboard/storybookUtils/index.js
  assets/src/dashboard/types.js
  assets/src/dashboard/utils/getFormattedDisplayDate.js
  assets/src/dashboard/utils/index.js
  assets/src/dashboard/utils/test/getFormattedDisplayDate.js
  includes/Dashboard.php
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#3184 Fix Text element new lines oddities/bounding box + highlight in edit mode
  assets/src/edit-story/components/canvas/singleSelectionMoveable.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/units/dimensions.js
  assets/src/edit-story/units/unitsProvider.js
Labels: Elements: Text, Type: Bug, cla: yes

#3559 Update plugin activation notice styling
  assets/src/activation-notice/app/components/messageContent.js
  assets/src/activation-notice/app/components/step1.js
  assets/src/activation-notice/app/components/successMessage.js
  assets/src/activation-notice/app/index.js
  assets/src/activation-notice/app/utils/usePrefersDarkMode.js
  includes/Activation_Notice.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#3709 Animations: Added duration-based ruler to animation timeline.
  assets/src/edit-story/components/animationTimeline/components.js
  assets/src/edit-story/components/animationTimeline/index.js
  assets/src/edit-story/components/animationTimeline/ruler.js
  assets/src/edit-story/components/animationTimeline/stories/index.js
  assets/src/edit-story/components/animationTimeline/test/animationTimeline.test.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3720 Animations: Added Drop Animation Effect
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/effects/drop/index.js
  assets/src/dashboard/animations/effects/drop/stories/index.js
  assets/src/dashboard/animations/parts/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3751 Add loading pill delay
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
Labels: Group: Media, Type: Enhancement, cla: yes

#3576 3P Media: Categories animations
  assets/src/edit-story/app/media/media3p/test/providerReducer.js
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pPane.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3708 Add transformer for media3p video resources
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/app/media/utils/test/getResourceFromMedia3p.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3743 Animation: Added Whoosh-In animation effect
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/effects/whooshIn/animationProps.js
  assets/src/dashboard/animations/effects/whooshIn/index.js
  assets/src/dashboard/animations/effects/whooshIn/stories/index.js
  assets/src/dashboard/animations/parts/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3782 Adding types for media3p
  assets/src/edit-story/app/media/media3p/categories/reducer.js
  assets/src/edit-story/app/media/media3p/categories/typedefs.js
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/typedefs.js
  assets/src/edit-story/app/media/media3p/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/useFetchCategoriesEffect.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
Labels: cla: yes

#3814 Remove ProviderType
  assets/src/edit-story/app/media/local/actions.js
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/providerConfiguration.js
  assets/src/edit-story/app/media/providerType.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/stories/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/test/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/test/mediaElement.js
Labels: cla: yes

#3806 Fix fill in edit mode
  assets/src/edit-story/elements/text/edit.js
Labels: cla: yes

#3828 Update 'Tested up to' value for WordPress 5.5
  readme.txt
Labels: Group: WordPress, Pod: WP & Infra, Type: Infrastructure, cla: yes

#3825 Multisite: Run activation hook on new site creation
  includes/namespace.php
  phpunit.xml.dist
  tests/phpunit/tests/Plugin.php
  tests/phpunit/tests/Story_Post_Type.php
  tests/phpunit/tests/Uninstall.php
  tests/phpunit/tests/Updater.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#3812 Animations: Added pan animation effect.
  assets/src/dashboard/animations/constants.js
  assets/src/dashboard/animations/effects/flyIn/animationProps.js
  assets/src/dashboard/animations/effects/pan/animationProps.js
  assets/src/dashboard/animations/effects/pan/index.js
  assets/src/dashboard/animations/effects/pan/stories/index.js
  assets/src/dashboard/animations/parts/index.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3584 Editor: Animations: Add initial play functionality to editor
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/previewPage.js
  assets/src/dashboard/components/storyAnimation/provider.js
  assets/src/dashboard/components/storyAnimation/test/provider.js
  assets/src/dashboard/constants/stories.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducer.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/index.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateAnimationState.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/restore.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateSelectedElements.js
  assets/src/edit-story/app/story/useStoryReducer/types.js
  assets/src/edit-story/app/story/useStoryReducer/useStoryReducer.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/canvas/selection.js
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  assets/src/edit-story/components/inspector/design/designInspector.js
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/play_circular.svg
  assets/src/edit-story/icons/stop_circular.svg
Labels: Group: Animations, Type: Enhancement, cla: yes

#3854 Dashboard: Settings Publisher Logo UI
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/stories/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/test/publisherLogo.js
  assets/src/dashboard/components/fileUpload/index.js
  assets/src/dashboard/components/fileUpload/stories/index.js
  assets/src/dashboard/components/fileUpload/test/fileUpload.js
  assets/src/dashboard/theme.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#3860 Adding type defs to media/ and media/local/ + some readability fixes
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/local/typedefs.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
  assets/src/edit-story/app/media/local/useLocalMedia.js
  assets/src/edit-story/app/media/media3p/categories/reducer.js
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/typedefs.js
  assets/src/edit-story/app/media/media3p/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
  assets/src/edit-story/app/media/pagination/reducer.js
  assets/src/edit-story/app/media/typedefs.js
  assets/src/edit-story/app/media/useMedia.js
  assets/src/edit-story/app/media/useMediaReducer.js
Labels: cla: yes

#3753 Remove currently on-by-default flags
  assets/src/dashboard/karma/fixture.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/stories/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/test/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/useRovingTabIndex.js
  assets/src/edit-story/components/library/panes/media/local/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/test/_utils/index.js
  assets/src/edit-story/components/library/test/mediaElement.js
  assets/src/edit-story/components/library/test/mediaPane.js
  assets/src/edit-story/flags.js
  assets/src/edit-story/karma/fixture/fixture.js
  includes/Experiments.php
Labels: Type: Code Quality, Type: Infrastructure, cla: yes

#3821 Wire up Coverr videos in the Coverr tab
  __static__/beach.jpg
  __static__/beach.mp4
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/app/media/utils/test/getResourceFromMedia3p.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/providerTab.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/output.js
  assets/src/edit-story/output/test/page.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3870 Render image preview in stories RSS feed
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#3696 Get font metrics
  bin/utils/buildFonts.js
  bin/utils/constants.js
  bin/utils/fetch.js
  bin/utils/getFontMetrics.js
  bin/utils/normalizeFont.js
  bin/utils/test/buildFonts.js
  bin/utils/test/fixtures/abezee.ttf
  bin/utils/test/getFontMetrics.js
  includes/REST_API/Fonts_Controller.php
  includes/data/fonts.json
  package-lock.json
  package.json
  tests/phpunit/tests/Fonts.php
  tests/phpunit/tests/REST_API/Fonts_Controller.php
Labels: Group: Fonts, Type: Infrastructure, cla: yes

#3727 Dashboard: Story Previews
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/views/exploreTemplates/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/previewStory/stories/previewStory.js
  assets/src/dashboard/app/views/previewStory/test/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/dashboard/storybookUtils/index.js
  assets/src/dashboard/utils/useStoryView.js
  assets/src/dashboard/utils/useTemplateView.js
  includes/Experiments.php
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#3215 Enable new font picker + add Karma tests
  assets/src/edit-story/app/font/curatedFonts.js
  assets/src/edit-story/components/fontPicker/fontPicker.js
  assets/src/edit-story/components/fontPicker/pickerContainer.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/karma/textStyle.cuj.karma.js
  includes/Experiments.php
Labels: Group: Fonts, Type: Enhancement, cla: yes

#3872 Enable story player for search and archives
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3813 Fix accessibility for tab panels in general and inspector tabs in particular
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/document/slug.js
  assets/src/edit-story/components/inspector/document/status.js
  assets/src/edit-story/components/inspector/document/test/publish.js
  assets/src/edit-story/components/inspector/document/test/status.js
  assets/src/edit-story/components/inspector/inspectorContent.js
  assets/src/edit-story/components/inspector/inspectorLayout.js
  assets/src/edit-story/components/library/libraryLayout.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/tabview/index.js
Labels: Accessibility, Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#3867 Typedefs for media3p api
  assets/src/edit-story/app/media/context.js
  assets/src/edit-story/app/media/media3p/api/context.js
  assets/src/edit-story/app/media/media3p/api/media3pApiProvider.js
  assets/src/edit-story/app/media/media3p/api/typedefs.js
  assets/src/edit-story/app/media/media3p/api/useMedia3pApi.js
Labels: Group: 3P Media, Type: Code Quality, cla: yes

#3862 Media Library: Add a background color to media elements
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
Labels: Group: Media, Type: Enhancement, cla: yes

#3526 Add srcset attribute for images
  assets/src/edit-story/app/media/utils/getThumbnailUrl.js
  assets/src/edit-story/app/media/utils/test/getThumbnailUrl.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/layer.js
  assets/src/edit-story/elements/image/output.js
  assets/src/edit-story/elements/image/test/output.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/test/display.js
  assets/src/edit-story/elements/media/test/util.js
  assets/src/edit-story/elements/media/util.js
Labels: Elements: Image, Group: Media, Type: Enhancement, cla: yes

#3883 Fixed range handle color
  assets/src/edit-story/components/rangeInput/index.js
Labels: Accessibility, Group: Document Panel, Group: Grid View, Pod: Prometheus (Workspace), cla: yes

#3938 Update poster fallback image
  assets/images/fallback-poster.jpg
  assets/images/fallback-poster.png
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/edit-story/output/utils/test/getStoryMarkup.js
  includes/Story_Post_Type.php
  includes/Story_Renderer/HTML.php
  tests/phpunit/data/story_post_content.html
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#3907 Add check for incompatible WordPress version
  includes/namespace.php
  tests/phpstan/bootstrap.php
  web-stories.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#3917 Make stack traces more readable
  webpack.config.cjs
Labels: Type: Enhancement, Type: Infrastructure, cla: yes

#3881 Remove capabilities on plugin uninstall
  includes/Story_Post_Type.php
  includes/uninstall.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#3918 Prevent "Auto Draft" titles and permalinks
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/karma/fixture/fixture.js
  includes/Story_Post_Type.php
  tests/phpunit/data/story_post_content.html
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: Dashboard, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#3922 Animation: Resizable and Draggable Animation Bar
  assets/src/edit-story/components/animationTimeline/components.js
  assets/src/edit-story/components/animationTimeline/index.js
  assets/src/edit-story/components/animationTimeline/ruler.js
  assets/src/edit-story/components/animationTimeline/stories/index.js
  assets/src/edit-story/components/animationTimeline/timingBar.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#3986 Improve frontend rendering
  includes/Story_Renderer/HTML.php
  includes/templates/frontend/single-web-story.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: Group: WordPress, Type: Bug, Type: Infrastructure, cla: yes

#3892 Extract common parts of getImageUrl and getVideoUrl to common fn
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
Labels: Group: Media, Type: Code Quality, cla: yes

#3780 Update useRovingTabIndex to focus outer element instead of firstChild
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/useRovingTabIndex.js
Labels: Group: Media, Type: Enhancement, cla: yes

#3863 Use DropDown for MediaType filter
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/elements/video/karma/autoplay.karma.js
Labels: Group: Media, Type: Enhancement, cla: yes

#4001 Add Coverr logo and proper attribution link
  assets/src/edit-story/app/media/media3p/attribution.js
  assets/src/edit-story/icons/coverr_logo.svg
Labels: cla: yes

#3781 Arrow navigate between media3p category pills
  assets/src/edit-story/components/library/panes/media/media3p/categoryPill.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
Labels: Accessibility, Group: 3P Media, Type: Enhancement, cla: yes

#4004 Fix local media pagination karma test flakiness
  assets/src/edit-story/components/library/panes/media/local/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: cla: yes

#3857 Fix aria attributes for the category expand button
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pCategories.js
Labels: Accessibility, Type: Enhancement, cla: yes

#3882 Add test to verify curated fonts list is valid
  assets/src/edit-story/app/font/test/curatedFonts.js
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#4007 add keyboard navigation to provider tabs
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/providerTab.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#4010 Fix flex issues
  assets/src/edit-story/components/library/libraryLayout.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
Labels: Group: 3P Media, Type: Bug, cla: yes

#4011 Make the Coverr logo prettier
  assets/src/edit-story/app/media/media3p/attribution.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3893 3P Media: Calculate Coverr preview image/video size if not present
  assets/src/edit-story/app/media/media3p/providerConfiguration.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/app/media/utils/test/getResourceFromMedia3p.js
Labels: Group: 3P Media, Type: Enhancement, cla: yes

#3904 Prevent media from scrolling on resize when tab is not selected
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/karma/mediaFetching.karma.js
Labels: Group: Media, Type: Bug, cla: yes

#4047 PHPStan fixes
  .github/workflows/continuous-integration-lint-php.yml
  includes/REST_API/Fonts_Controller.php
  includes/REST_API/Stories_Autosaves_Controller.php
  includes/REST_API/Stories_Base_Controller.php
  includes/REST_API/Stories_Controller.php
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#4043 Fix fullbleedRef console warning
  assets/src/edit-story/components/canvas/layout.js
Labels: Type: Code Quality, cla: yes

#4040 Add key accidentally removed in #3780
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
Labels: Type: Code Quality, cla: yes

#4016 Enable React apps to use dynamic imports
  .eslintrc
  assets/src/activation-notice/index.js
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/index.js
  assets/src/dashboard/templates/getTemplates.js
  assets/src/dashboard/templates/index.js
  assets/src/edit-story/index.js
  assets/src/story-embed-block/index.js
  includes/Activation_Notice.php
  includes/Dashboard.php
  includes/Embed_Block.php
  includes/Story_Post_Type.php
  tests/e2e/specs/dashboard/templates/useTemplate.js
  webpack.config.cjs
Labels: Pod: WP & Infra, Type: Enhancement, Type: Infrastructure, cla: yes

#4049 Update chunkFilename
  .github/workflows/continuous-integration-bundle-size.yml
  webpack.config.cjs
Labels: Skip Changelog, Type: Code Quality, Type: Infrastructure, cla: yes

#3643 Fix video play/pause state after DND
  .github/workflows/continuous-integration-unit-php.yml
  assets/src/dashboard/app/api/useSettingsApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/app/views/exploreTemplates/content/emptyView.js
  assets/src/dashboard/app/views/myStories/content/emptyView/index.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/myStories/header/test/header.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/templateDetails/components.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/components/alert/index.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/fileUpload/index.js
  assets/src/dashboard/components/modal/index.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/menuButton.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/dashboard/components/popoverPanel/stories/index.js
  assets/src/dashboard/components/scrollToTop/index.js
  assets/src/dashboard/components/viewStyleBar/stories/index.js
  assets/src/edit-story/app/media/media3p/useFetchCategoriesEffect.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/colorPicker/gradientPicker.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/inspector/document/test/status.js
  assets/src/edit-story/components/library/panes/media/common/mediaGallery.js
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/common/useRovingTabIndex.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/text/textIcon.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/panels/backgroundSizePosition.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/components/panels/videoOptions.js
  assets/src/edit-story/components/reorderable/useReordering.js
  assets/src/edit-story/components/uploadDropTarget/message.js
  assets/src/edit-story/elements/video/controls.js
  assets/src/edit-story/elements/video/karma/autoplay.karma.js
  assets/src/edit-story/karma/fixture/containers/canvas.js
  assets/src/edit-story/karma/fixture/containers/container.js
Labels: Elements: Video, Type: Bug, cla: yes

#3543 Editor: Fix issue with changing text height due to line breaks
  assets/src/edit-story/components/richText/customImport.js
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/elements/text/output.js
Labels: Elements: Text, Type: Bug, cla: yes

#4041 Media: populate sizes when images are uploaded via cop/paste or drag/drop
  assets/src/edit-story/components/canvas/useUploadWithPreview.js
Labels: Group: Media, Type: Bug, cla: yes

#4039 Media: Fix issue where images from the WP media modal are broken
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js
Labels: Group: Media, Type: Bug, cla: yes

#2548 Karma: show virtual cursor
  karma/fixture/init.js
  karma/karma-puppeteer-launcher/snapshot.cjs
Labels: Type: Infrastructure, cla: yes

#4046 RegisterUsage on useInsertElement (not drag/click)
  assets/src/edit-story/components/canvas/test/useInsertElement.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
Labels: Group: Media, Type: Bug, cla: yes

#4002 Expand the categories section on arrow key down
  assets/src/edit-story/components/library/panes/media/common/useRovingTabIndex.js
  assets/src/edit-story/components/library/panes/media/media3p/categoryPill.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
Labels: Accessibility, Group: 3P Media, Type: Enhancement, cla: yes

#4005 Display preview video in gallery instead of the full video (for Coverr)
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js
  assets/src/edit-story/elements/media/test/util.js
  assets/src/edit-story/elements/media/util.js
Labels: Group: Media, Type: Enhancement, cla: yes

#4070 Update fullbleedRef type to be less verbose
  assets/src/edit-story/components/canvas/layout.js
Labels: Type: Code Quality, cla: yes

#4027 Dashboard: Handle stories with no titles in list view and search dropdown
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/shared/typeaheadSearch.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#4068 Dashboard: Rename story text box is cut off
  assets/src/dashboard/components/input/index.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#4111 Add delay before preloading preview videos
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: cla: yes

#3999 check isDrag to not trigger dragging code onclick.
  assets/src/edit-story/components/canvas/singleSelectionMoveable.js
Labels: Group: Selection, Type: Bug, cla: yes

#4115 Fixes for Safari, and for weird autoloading edge case
  assets/src/edit-story/components/library/libraryLayout.js
  assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
Labels: Browser Issues, Group: Media, Type: Bug, cla: yes

#4012 Prepare release: 1.0.0-beta.2
  web-stories.php
Labels: Pod: WP & Infra, Type: Infrastructure, Type: Task, cla: yes

#4142 GH Pages Update for Beta 2
  beta/index.html
  service/plugin-updates.json
Labels: Type: Task, cla: yes

#4025 Dashboard (Settings View) - Add, remove and view publisher logos
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/useMediaApi.js
  assets/src/dashboard/app/api/useSettingsApi.js
  assets/src/dashboard/app/reducer/media.js
  assets/src/dashboard/app/reducer/settings.js
  assets/src/dashboard/app/reducer/test/media.js
  assets/src/dashboard/app/reducer/test/settings.js
  assets/src/dashboard/app/serializers/index.js
  assets/src/dashboard/app/serializers/publisherLogo.js
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/test/googleAnalytics.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/stories/index.js
  assets/src/dashboard/app/views/editorSettings/publisherLogo/test/publisherLogo.js
  assets/src/dashboard/app/views/editorSettings/test/editorSettings.js
  assets/src/dashboard/app/views/toaster/index.js
  assets/src/dashboard/components/fileUpload/index.js
  assets/src/dashboard/components/fileUpload/stories/index.js
  assets/src/dashboard/components/fileUpload/test/fileUpload.js
  assets/src/dashboard/components/inlineInputForm/index.js
  assets/src/dashboard/dataUtils/formattedPublisherLogos.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/dashboard/karma/fixture.js
  assets/src/dashboard/types.js
  includes/Dashboard.php
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4108 [WIP] Animations: Can remove animation effects using animation panel
  assets/src/animation/parts/index.js
  assets/src/animation/utils/getDefaultFieldValue.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/index.js
  assets/src/edit-story/components/panels/animation/effectInput.js
  assets/src/edit-story/components/panels/animation/effectPanel.js
  assets/src/edit-story/components/panels/animation/panel.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#4065 Animation: Circle Alignment on Bounce Animation part
  assets/src/dashboard/templates/raw/fitness.json
  assets/src/dashboard/templates/test/raw.js
  assets/src/edit-story/masks/index.js
Labels: Group: Animations, Group: Templates, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#4113 Media: Improve "No media found" message
  assets/src/edit-story/components/library/panes/media/common/styles.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pPane.js
  assets/src/edit-story/theme.js
Labels: Group: 3P Media, Group: Media, Type: Enhancement, cla: yes

#3787 Visual revamp: second pass (pills, slider, more)
  assets/src/edit-story/components/canvas/carousel/compactIndicator.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/switch.js
  assets/src/edit-story/components/library/common/searchInput.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/media3p/categoryPill.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/pill.js
  assets/src/edit-story/components/library/panes/media/media3p/providerTab.js
  assets/src/edit-story/components/library/panes/shapes/shapePreview.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/library/text/fontPreview.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/rangeInput/index.js
  assets/src/edit-story/theme.js
Labels: Pod: Prometheus (Workspace), Type: Enhancement, cla: yes

#2848 Page Attachment as linked content
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/pageAttachment/index.js
  assets/src/edit-story/components/canvas/pageAttachment/karma/pageAttachment.cuj.karma.js
  assets/src/edit-story/components/canvas/pageAttachment/test/pageAttachment.js
  assets/src/edit-story/components/canvas/test/multiSelectionMoveable.js
  assets/src/edit-story/components/canvas/test/singleSelectionMoveable.js
  assets/src/edit-story/components/form/index.js
  assets/src/edit-story/components/form/link.js
  assets/src/edit-story/components/form/stories/link.js
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/panels/alignment/alignment.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/pageAttachment/index.js
  assets/src/edit-story/components/panels/stylePreset/presets.js
  assets/src/edit-story/components/panels/test/linkPanel.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/utils/getBoundRect.js
  assets/src/edit-story/utils/isElementBelowLimit.js
  assets/src/edit-story/utils/test/getBoundRect.js
  assets/src/edit-story/utils/useElementsWithLinks.js
Labels: Group: Page Attachment, Type: Enhancement, cla: yes

#4178 [Media] Add srcset to cropbox
  assets/src/edit-story/elements/media/edit.js
Labels: cla: yes

#4179 use correct staging key
  assets/src/edit-story/app/media/media3p/api/apiFetcher.js
Labels: cla: yes

#4167 Editor: Updated close icon and fixed input text overlap
  .storybook/main.cjs
  assets/src/animation/parts/index.js
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/icons/close_icon.svg
Labels: cla: yes

#4165 Fixed font-size in layer panel
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/elements/shape/layer.js
Labels: Group: Design Panel, Group: Editing, Type: Bug, cla: yes

#4146 Dashboard: Refactor Config Provider to use useContextSelector
  assets/src/dashboard/app/config/context.js
  assets/src/dashboard/app/config/useConfig.js
  assets/src/dashboard/utils/index.js
Labels: Group: Dashboard, Type: Enhancement, Type: Performance, cla: yes

#4206 Fix flex issues in Safari.
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/pill.js
Labels: cla: yes

#4207 add animations for categories
  assets/src/edit-story/components/library/panes/media/media3p/categoryPill.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pCategories.js
Labels: cla: yes

#4145 Make snackbar message readable
  assets/src/edit-story/app/snackbar/snackbar.js
Labels: Type: Infrastructure, cla: yes

#4190 Dashboard: Refactor Navigation Provider to use useContextSelector
  assets/src/dashboard/components/navProvider.js
Labels: cla: yes

#4151 Dashboard: Refactor API Provider to use useContextSelector
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/useApi.js
  assets/src/dashboard/app/font/fontProvider.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/exploreTemplates/index.js
  assets/src/dashboard/app/views/exploreTemplates/karma/exploreTemplates.karma.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/dashboard/app/views/toaster/index.js
Labels: Group: Dashboard, Type: Enhancement, Type: Performance, cla: yes

#4192 Dashboard: Refactor Toaster Provider to use useContextSelector
  assets/src/dashboard/components/toaster/provider.js
  assets/src/dashboard/components/toaster/useToastContext.js
Labels: cla: yes

#4191 Dashboard: Refactor Router Provider to use useContextSelector
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/router/route.js
  assets/src/dashboard/app/router/routerProvider.js
  assets/src/dashboard/app/router/test/router.js
  assets/src/dashboard/app/router/useRouteHistory.js
Labels: cla: yes

#4158 Refactor Moveables
  assets/src/edit-story/components/canvas/multiSelectionMoveable.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/useDrag.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/useResize.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/useRotate.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/useResize.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/useRotate.js
  assets/src/edit-story/components/canvas/utils/normalizeRotationDegrees.js
  assets/src/edit-story/components/canvas/utils/useElementOutOfCanvas.js
  assets/src/edit-story/components/canvas/utils/useSnapping.js
Labels: Group: Selection, Type: Code Quality, cla: yes

#4225 Dashboard: Prevent Related Templates tests from randomly failing
  assets/src/dashboard/karma/apiProviderFixture.js
Labels: cla: yes

#4112 Implement reset poster image
  assets/src/edit-story/components/dropDownMenu/index.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/library/panes/media/local/dropDownMenu.js
  assets/src/edit-story/components/panels/karma/videoAccessibility.karma.js
  assets/src/edit-story/components/panels/test/videoAccessibility.js
  assets/src/edit-story/components/panels/videoAccessibility.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/videoAccessibility.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Accessibility, Elements: Video, Group: Design Panel, Pod: Prometheus (Workspace), cla: yes

#3973 Fix input focus borders
  assets/src/edit-story/components/form/color/colorBox.js
  assets/src/edit-story/components/form/text.js
Labels: Accessibility, Group: Design Panel, Pod: Prometheus (Workspace), Type: Bug, cla: yes

#4074 Animation: Timeline Keyboard Controls
  assets/src/edit-story/components/animationTimeline/index.js
  assets/src/edit-story/components/animationTimeline/stories/index.js
  assets/src/edit-story/components/animationTimeline/test/animationTimeline.test.js
  assets/src/edit-story/components/animationTimeline/timingBar.js
Labels: Group: Animations, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4187 Dashboard: Remove fixed height on preview cards
  assets/src/dashboard/components/cardGallery/components.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Bug, cla: yes

#4164 Support link panel for multi-selection
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js
  assets/src/edit-story/utils/useElementsWithLinks.js
Labels: Group: Design Panel, Group: Links, Type: Bug, cla: yes

#2904 Remove redundant showOverflow from Popup usages.
  assets/src/edit-story/components/elementLink/frame.js
  assets/src/edit-story/elements/video/controls.js
Labels: Type: Code Quality, cla: yes

#4224 Workspace: Update panel divider color from blue to gray
  assets/src/edit-story/components/panels/panel/shared/title.js
Labels: cla: yes

#4138 Workspace: Layer panel bg focus color
  assets/src/edit-story/components/panels/layer/layer.js
Labels: cla: yes

#4230 Bug: Tooltip Text Wrapping & Improvements
  assets/src/edit-story/components/panels/stylePreset/presets.js
  assets/src/edit-story/components/popup/index.js
  assets/src/edit-story/components/popup/utils.js
  assets/src/edit-story/components/tooltip/index.js
Labels: cla: yes

#4067 Dashboard: Improve Search Stories Perf/UX
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/myStories/header/test/header.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
Labels: cla: yes

#4144 Dashboard: Add copy story URL and open story menu action items
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/serializers/stories.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/alert/components.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/popoverMenu/stories/index.js
  assets/src/dashboard/components/popoverMenu/test/popover-menu.js
  assets/src/dashboard/components/types.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/types.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes

#4265 rename provider tabs and add aria-label to library tabs
  assets/src/edit-story/app/media/media3p/providerConfiguration.js
  assets/src/edit-story/app/media/media3p/typedefs.js
  assets/src/edit-story/components/library/panes/media/local/mediaIcon.js
  assets/src/edit-story/components/library/panes/media/media3p/media3pIcon.js
  assets/src/edit-story/karma/fixture/containers/library.js
Labels: cla: yes

#4267 Disable search when category is selected
  assets/src/edit-story/components/library/panes/media/media3p/media3pPane.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pPane.js
Labels: cla: yes

#4218 Consecutive text placement
  assets/src/edit-story/app/history/historyProvider.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/library/panes/text/karma/textPane.karma.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/library/panes/text/useInsertPreset.js
  assets/src/edit-story/karma/fixture/containers/library.js
  assets/src/edit-story/units/dimensions.js
  assets/src/edit-story/utils/getInsertedElementSize.js
  assets/src/edit-story/utils/test/getInsertedElementSize.js
Labels: Pod: Prometheus (Workspace), cla: yes

#4154 Allow trailing space (hyphen) in permalink while typing
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/inspector/document/slug.js
  assets/src/edit-story/components/inspector/document/test/slug.js
  assets/src/edit-story/utils/cleanForSlug.js
  assets/src/edit-story/utils/test/cleanForSlug.js
Labels: Group: Document Panel, Pod: Prometheus (Workspace), Type: Bug, cla: yes

#2108 Keyboard navigation for media editor
  assets/src/edit-story/components/canvas/test/useCanvasKeys.js
  assets/src/edit-story/components/canvas/useCanvasKeys.js
  assets/src/edit-story/elements/image/karma/edit.karma.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/editPanMoveable.js
  assets/src/edit-story/elements/media/scalePanel.js
  assets/src/edit-story/karma/fixture/containers/canvas.js
  assets/src/edit-story/utils/getKeyboardMovement.js
Labels: Accessibility, Elements: Image, Elements: Video, Group: Media, Type: Enhancement, cla: yes

#4262 Workspace: SafeZone Toggle/Button A11y Improvements
  assets/src/edit-story/components/canvas/carousel/index.js
Labels: cla: yes

#4227 Dashboard: Use Keydown Event to Trigger Sort in List View
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/storyListView.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4249 Updated text preset settings to match designs
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/library/text/fontPreview.js
  assets/src/edit-story/constants.js
Labels: cla: yes

#4263 Dashboard: Keyboard Navigation for Template Detail View
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/dashboard/components/cardGallery/components.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGallery/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/dataUtils/formattedTemplatesArray.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/index.js
  assets/src/dashboard/utils/useGridViewKeys.js
  assets/src/edit-story/components/canvas/gridview/test/useGridViewKeys.js
  assets/src/edit-story/components/canvas/gridview/useGridViewKeys.js
Labels: Accessibility, Group: Dashboard, Pod: Pea (Dashboard & Templates), cla: yes

#4276 Dashboard: Confirmation dialog before removing logos
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/editorSettings/test/editorSettings.js
Labels: Group: Dashboard, Pod: Pea (Dashboard & Templates), Type: Enhancement, cla: yes
