Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-11, with the labels that each got.

#5027 Put eyedropper behind feature flag
  assets/src/edit-story/components/colorPicker/currentColorPicker.js
  assets/src/edit-story/components/colorPicker/stories/index.js
  includes/Experiments.php
Labels: Group: Patterns, Pod: Prometheus, Type: Enhancement, cla: yes

#5029 prepublish media guidelines (guidance)
  assets/src/edit-story/app/prepublish/constants.js
  assets/src/edit-story/app/prepublish/guidance/media.js
  assets/src/edit-story/app/prepublish/guidance/test/media.js
  assets/src/edit-story/app/prepublish/types.js
  assets/src/edit-story/types.js
Labels: Group: Pre-Publish Panel, Pod: Pea, Type: Enhancement, cla: yes

#4893 Design System Storybook (new theme colors)
  .storybook/main.cjs
  .storybook/preview.js
  assets/src/design-system/index.js
  assets/src/design-system/stories/index.js
  assets/src/design-system/theme/colors.js
  assets/src/design-system/theme/index.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#5082 Fix PHP-CSS-Parser patching
  composer.json
  composer.lock
  patches/php-css-parser-commit-10a2501.patch
  patches/php-css-parser-pull-185.patch
  patches/php-css-parser-pull-193.patch
  web-stories.php
Labels: AMP Output, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5055 3P Media: Add poster image for GIF video elements
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/app/media/utils/test/getResourceFromMedia3p.js
  assets/src/edit-story/elements/gif/output.js
  assets/src/edit-story/elements/gif/test/__snapshots__/output.js.snap
  assets/src/edit-story/elements/gif/test/output.js
Labels: Elements: GIF, Group: 3P Media, Pod: Pea, Type: Bug, cla: yes

#5120 Improve API usage to prevent WAF false positives
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/test/wpAdapter.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/wpAdapter.js
  assets/src/edit-story/app/api/apiProvider.js
  codecov.yml
  includes/Dashboard.php
  includes/Plugin.php
  includes/REST_API/Stories_Settings_Controller.php
  includes/REST_API/Stories_Users_Controller.php
  includes/Story_Post_Type.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, cla: yes

#4906 Animations: Animation Parts Seen as a Limited Effect to user
  assets/src/animation/constants.js
  assets/src/edit-story/components/panels/animation/effectPanel.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#5086 prepublish checklist - missing critical metadata
  assets/src/edit-story/app/prepublish/errors/metadata.js
  assets/src/edit-story/app/prepublish/errors/test/metadata.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
Labels: Group: Pre-Publish Panel, Pod: Pea, cla: yes

#5092 Lints: Install composer-normalize via phar
  .github/workflows/continuous-integration-lint-php.yml
  composer.json
  composer.lock
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5085 Design System Storybook - Dialog (and a base modal)
  assets/src/design-system/components/dialog/index.js
  assets/src/design-system/components/dialog/stories/index.js
  assets/src/design-system/components/dialog/test/dialog.js
  assets/src/design-system/components/index.js
  assets/src/design-system/components/modal/index.js
  assets/src/design-system/components/modal/stories/index.js
  assets/src/design-system/components/modal/test/modal.js
  assets/src/design-system/theme/colors.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#5144 Update Getting Started documentation
  docs/getting-started.md
Labels: Type: Documentation, cla: yes

#5033 Add prepublish text length guidelines
  assets/src/edit-story/app/prepublish/guidance/test/text.js
  assets/src/edit-story/app/prepublish/guidance/text.js
Labels: Group: Pre-Publish Panel, Pod: Pea, Type: Enhancement, cla: yes

#5194 Add accessibility and distribution pre-publish warnings
  assets/src/edit-story/app/prepublish/warning/accessibility.js
  assets/src/edit-story/app/prepublish/warning/distribution.js
  assets/src/edit-story/app/prepublish/warning/test/accessibility.js
  assets/src/edit-story/app/prepublish/warning/test/distribution.js
  assets/src/edit-story/utils/contrastUtils.js
  assets/src/edit-story/utils/test/contrastUtils.js
  package-lock.json
  package.json
Labels: cla: yes

#5199 Redirect for child pages with stories slug
  includes/Story_Post_Type.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5104 Fix date and time
  assets/src/date/convertFormatString.js
  assets/src/date/format.js
  assets/src/date/getOptions.js
  assets/src/date/getTimeZoneString.js
  assets/src/date/settings.js
  assets/src/date/test/convertFormatString.js
  assets/src/date/test/format.js
  includes/Locale.php
Labels: Group: Dates, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5140 Fix AMP plugin sanitizer setup
  includes/AMP/Integration/AMP_Story_Sanitizer.php
  includes/AMP/Story_Sanitizer.php
  includes/AMP/Traits/Sanitization_Utils.php
  includes/Story_Post_Type.php
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/AMP/Story_Sanitizer.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: AMP Output, Group: Analytics, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5129 Fix disabling background reordering for layer panel
  assets/src/edit-story/components/panels/layer/layerList.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#5024 Dashboard: WordPress Admin Menu not highlighting the right page
  assets/src/dashboard/app/router/routerProvider.js
  assets/src/edit-story/elements/media/imageDisplay.js
  tests/e2e/specs/dashboard/adminMenu.js
Labels: Group: Dashboard, Group: WordPress, Pod: Pea, Type: Enhancement, cla: yes

#5151 Animation: Effect Chooser Component
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/effectChooserElements.js
  assets/src/edit-story/components/panels/animation/stories/effectChooser.js
  assets/src/edit-story/components/panels/animation/test/effectChooser.js
Labels: Group: Animations, cla: yes

#5073 Dashboard: Integrate new theme values
  .storybook/preview.js
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/emptyContentMessage.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/savedTemplateGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/dashboard/app/views/shared/templateGridView.js
  assets/src/dashboard/app/views/storyAnimTool/components.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/components.js
  assets/src/dashboard/app/views/templateDetails/components.js
  assets/src/dashboard/components/alert/components.js
  assets/src/dashboard/components/bookmark-chip/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/button/paginationButton.js
  assets/src/dashboard/components/cardGallery/components.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/focusableGridItem.js
  assets/src/dashboard/components/colorList/index.js
  assets/src/dashboard/components/contentGutter/index.js
  assets/src/dashboard/components/detailViewNavBar/index.js
  assets/src/dashboard/components/dialog/index.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/fileUpload/index.js
  assets/src/dashboard/components/infiniteScroller/index.js
  assets/src/dashboard/components/inlineInputForm/index.js
  assets/src/dashboard/components/input/index.js
  assets/src/dashboard/components/layout/squishable.js
  assets/src/dashboard/components/link/index.js
  assets/src/dashboard/components/multiPartPill/index.js
  assets/src/dashboard/components/multiPartPill/stories/index.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/menuButton.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/dashboard/components/pill/components.js
  assets/src/dashboard/components/popoverMenu/menu.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/dashboard/components/scrollToTop/index.js
  assets/src/dashboard/components/storyMenu/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/components/toggleButtonGroup/index.js
  assets/src/dashboard/components/tooltip/index.js
  assets/src/dashboard/components/typeahead/components.js
  assets/src/dashboard/components/typeahead/typeaheadOptions/components.js
  assets/src/dashboard/components/typography/index.js
  assets/src/dashboard/components/viewStyleBar/index.js
  assets/src/dashboard/testUtils/renderWithProviders.js
Labels: Pod: Pea, Type: Enhancement, cla: yes

#5213 Fixed line-height css generation
  assets/src/edit-story/elements/text/test/util.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/output/test/__snapshots__/textElement.js.snap
Labels: AMP Output, Elements: Text, cla: yes

#5219 Skip AMP sanitization for missing video posters, accepting AMP invalidation
  includes/Story_Post_Type.php
  tests/phpunit/tests/AMP/Sanitization.php
  tests/phpunit/tests/AMP/Story_Sanitizer.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: AMP Output, Elements: Video, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5121 Media: avoid inserting .mov files from media picker
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  bin/local-env/install-wordpress.sh
  tests/e2e/assets/small-video.mov
  tests/e2e/specs/editor/media/insertMovVideo.js
Labels: Group: Library, Group: Media, P2, Pod: Pea, Type: Enhancement, cla: yes

#5125 Fix pasting for search inputs
  assets/src/edit-story/utils/nativeCopyPasteExpected.js
  assets/src/edit-story/utils/test/nativeCopyPasteExpected.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#5148 Deploy to staging environment via GitHub actions
  .distignore
  .github/workflows/continuous-integration-build.yml
  .gitignore
  .prettierignore
  .travis_deploy_key.enc
  bin/deploy-to-test-environment.sh
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5146 Admin Menu should not be collapsed on dashboard
  includes/Admin.php
Labels: Group: Dashboard, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5149 Editor: Provide featured media details via API
  assets/src/dashboard/app/api/test/useStoryApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/prepublish/errors/metadata.js
  assets/src/edit-story/app/prepublish/errors/test/metadata.js
  assets/src/edit-story/app/story/actions/test/useAutoSave.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/app/story/utils/test/getStoryPropsToSave.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/document/test/publish.js
  assets/src/edit-story/output/story.js
  assets/src/edit-story/output/test/story.js
  assets/src/edit-story/output/utils/test/getStoryMarkup.js
  assets/src/edit-story/types.js
  includes/Dashboard.php
  includes/REST_API/Stories_Controller.php
  includes/namespace.php
  includes/templates/admin/edit-story.php
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#5225 Media: Filter REST API responses by media types allowed by plugin
  includes/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5227 Update Jest to v26
  __mocks__/fs.js
  assets/src/edit-story/components/header/buttons/preview.js
  assets/src/edit-story/components/header/test/buttons.js
  assets/src/edit-story/utils/nativeCopyPasteExpected.js
  assets/src/edit-story/utils/test/nativeCopyPasteExpected.js
  assets/src/edit-story/utils/test/useGlobalClipboardHandlers.js
  package-lock.json
  package.json
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5115 Allow changing hex value of multi-selection mixed color
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/form/color/test/colorPreview.js
  assets/src/edit-story/components/richText/karma/inlineSelection.karma.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
  assets/src/edit-story/components/richText/karma/singleSelection.karma.js
Labels: Pod: Prometheus, cla: yes

#5141 Add dedicated Site Kit integrations class
  includes/Analytics.php
  includes/Dashboard.php
  includes/Integrations/Site_Kit.php
  includes/Plugin.php
  tests/phpunit/tests/Analytics.php
  tests/phpunit/tests/Dashboard.php
  tests/phpunit/tests/Integrations/Site_Kit.php
Labels: Group: Dashboard, Group: Integration, Group: Settings, Group: WordPress, Pod: WP & Infra, cla: yes

#5150 Introduce separate AMP & Jetpack integration classes
  includes/Integrations/AMP.php
  includes/Integrations/Jetpack.php
  includes/Plugin.php
  includes/Story_Post_Type.php
  tests/phpunit/tests/AMP/Sanitization.php
  tests/phpunit/tests/Activation_Notice.php
  tests/phpunit/tests/Integrations/AMP.php
  tests/phpunit/tests/Integrations/Jetpack.php
  tests/phpunit/tests/Integrations/Site_Kit.php
  tests/phpunit/tests/Story_Post_Type.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#5196 Add docs about turning on the experiments tab
  docs/feature-flags.md
Labels: Type: Documentation, cla: yes

#5233 Skip sanitization for amp-video > source with invalid src
  includes/Integrations/AMP.php
  tests/phpunit/tests/AMP/Sanitization.php
Labels: AMP Output, Group: WordPress, Pod: WP & Infra, cla: yes

#4918 Add REST API Status Checks
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/statusCheck/index.js
  assets/src/edit-story/components/statusCheck/statusCheck.js
  assets/src/edit-story/components/statusCheck/test/statusCheck.js
  assets/src/edit-story/components/statusCheck/utils.js
  assets/src/edit-story/karma/fixture/fixture.js
  includes/Experiments.php
  includes/Plugin.php
  includes/REST_API/Status_Check_Controller.php
  includes/Story_Post_Type.php
  tests/phpunit/tests/REST_API/Status_Check_Controller.php
Labels: Pod: WP & Infra, Type: Enhancement, cla: yes

#5138 Story Data: Single Animation Target
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/templates/raw/beauty.json
  assets/src/dashboard/templates/raw/cooking.json
  assets/src/dashboard/templates/raw/diy.json
  assets/src/dashboard/templates/raw/entertainment.json
  assets/src/dashboard/templates/raw/fashion.json
  assets/src/dashboard/templates/raw/fitness.json
  assets/src/dashboard/templates/raw/travel.json
  assets/src/dashboard/templates/raw/wellbeing.json
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0025_singleAnimationTarget.js
  assets/src/edit-story/migration/migrations/v0025_singleAnimationTarget.js
Labels: cla: yes

#5123 Editor: remove mask from text element output
  assets/src/edit-story/elements/text/test/output.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/test/__snapshots__/textElement.js.snap
  assets/src/edit-story/output/test/textElement.js
  tests/e2e/specs/editor/authorUser.js
  tests/e2e/utils/addTextElement.js
  tests/e2e/utils/index.js
Labels: Elements: Text, Group: Masking, Type: Bug, cla: yes

#5198 Add NextGEN Gallery integration class
  includes/Integrations/NextGen_Gallery.php
  includes/Plugin.php
  tests/phpunit/tests/Admin.php
  tests/phpunit/tests/Database_Upgrader.php
  tests/phpunit/tests/Discovery.php
  tests/phpunit/tests/Integrations/NextGen_Gallery.php
  tests/phpunit/tests/Integrations/Site_Kit.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5238 Bump version to 1.1.1 and update readme.txt
  readme.txt
  web-stories.php
Labels: Type: Task, cla: yes

#5248 Fix markdown in readme
  readme.txt
Labels: Skip Changelog, Type: Documentation, cla: yes

#5242 Workspace: Connect Animation Effect Chooser to Editor
  assets/src/edit-story/components/fontPicker/fontList/styled.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/library/common/scrollbarStyles.js
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/effectChooserDropdown.js
  assets/src/edit-story/components/panels/animation/panel.js
  assets/src/edit-story/components/panels/animation/stories/effectChooser.js
  composer.lock
Labels: Group: Animations, Group: Workspace, Pod: Pea, Type: Enhancement, cla: yes

#5195 Design System: More colors for the theme
  assets/src/design-system/components/button/index.js
  assets/src/design-system/components/dialog/index.js
  assets/src/design-system/components/modal/index.js
  assets/src/design-system/components/tab/index.js
  assets/src/design-system/components/tabGroup/stories/index.js
  assets/src/design-system/components/typography/text/index.js
  assets/src/design-system/stories/index.js
  assets/src/design-system/theme/colors.js
  assets/src/design-system/theme/helpers/outline.js
Labels: Group: Design System, Pod: Pea, cla: yes

#5212 Improve compatibility checks and experience for unsupported versions of PHP
  codecov.yml
  includes/Plugin.php
  includes/compat/Web_Stories_Compatibility.php
  includes/compat/amp.php
  includes/namespace.php
  phpcs.xml.dist
  tests/phpunit/tests/Web_Stories_Compatibility.php
  web-stories.php
Labels: Group: WordPress, PHP, Pod: WP & Infra, Type: Code Quality, Type: Infrastructure, cla: yes

#5285 E2E Tests: Make `publishPost` util more robust
  tests/e2e/utils/publishPost.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5116 Fix Video Captions behaviour
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/components/panels/index.js
Labels: Elements: Video, Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#5288 Force Jetpack to see Web Stories as an AMP request
  includes/Integrations/Jetpack.php
  tests/phpunit/tests/Integrations/Jetpack.php
  tests/phpunit/tests/Web_Stories_Compatibility.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5245 Design System Storybook: Better buttons
  assets/src/design-system/components/button/constants.js
  assets/src/design-system/components/button/index.js
  assets/src/design-system/components/button/stories/index.js
  assets/src/design-system/components/dialog/stories/index.js
  assets/src/design-system/components/index.js
  assets/src/design-system/components/modal/stories/index.js
  assets/src/design-system/components/pill/index.js
  assets/src/design-system/components/pill/stories/index.js
  assets/src/design-system/components/pill/test/pill.js
  assets/src/design-system/components/tabGroup/index.js
  assets/src/design-system/components/tabGroup/stories/index.js
  assets/src/design-system/components/tabGroup/test/tabGroup.js
  assets/src/design-system/theme/helpers/outline.js
Labels: Group: Design System, Pod: Pea, cla: yes

#5260 Fix opacity and hue sliders of color picker
  assets/src/edit-story/components/colorPicker/currentColorPicker.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#5261 Remove safezone markers and icon
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/utils/useSnapping.js
  assets/src/edit-story/components/keyboardShortcutsMenu/karma/keyboardShortcuts.karma.js
Labels: Pod: Prometheus, cla: yes

#5131 Fix selecting media creating history entries
  assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/media/index.js
  assets/src/edit-story/elements/video/index.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#5302 package(update): replace color-contrast-checker with hues
  assets/src/edit-story/app/prepublish/warning/test/accessibility.js
  assets/src/edit-story/utils/contrastUtils.js
  assets/src/edit-story/utils/test/contrastUtils.js
  package-lock.json
  package.json
Labels: cla: yes

#5306 Design System Storybook: More Icons
  assets/src/design-system/icons/action/grid.svg
  assets/src/design-system/icons/action/gridMany.svg
  assets/src/design-system/icons/action/gridSingle.svg
  assets/src/design-system/icons/action/index.js
  assets/src/design-system/icons/action/save.svg
  assets/src/design-system/icons/editor/index.js
  assets/src/design-system/icons/editor/placeholder.svg
  assets/src/design-system/icons/editor/reverseColor.svg
  assets/src/design-system/icons/editor/rotateColor.svg
  assets/src/design-system/icons/editor/staggerFromLeft.svg
  assets/src/design-system/icons/editor/staggerFromRight.svg
  assets/src/design-system/icons/navigation/doubleChevron.svg
  assets/src/design-system/icons/navigation/index.js
Labels: Group: Dashboard, Group: Design System, Pod: Pea, cla: yes

#5049 Settings: Add Site Kit Specific UI
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/stories/index.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/test/googleAnalytics.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/components/input/index.js
  assets/src/dashboard/karma/fixture.js
  includes/Dashboard.php
Labels: Group: Settings, Pod: Pea, cla: yes

#5351 AMP Sanitization: Include metadata fallback file
  scoper.inc.php
Labels: Pod: WP & Infra, Type: Bug, cla: yes

#5349 Animation Panel: Update UI and connect Direction Picker
  assets/src/animation/constants.js
  assets/src/animation/effects/flyIn/animationProps.js
  assets/src/animation/effects/pan/animationProps.js
  assets/src/animation/effects/rotateIn/animationProps.js
  assets/src/edit-story/components/panels/animation/directionRadioInput.js
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/effectChooserDropdown.js
  assets/src/edit-story/components/panels/animation/effectInput.js
  assets/src/edit-story/components/panels/animation/effectPanel.js
  assets/src/edit-story/components/panels/animation/panel.js
  assets/src/edit-story/components/panels/animation/test/effectChooser.js
  assets/src/edit-story/components/panels/karma/animation.karma.js
  assets/src/edit-story/karma/fixture/containers/designPanel/animationPanel.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
Labels: Group: Animations, cla: yes

#5339 Design System: Focus style update (Buttons and Pills)
  assets/src/design-system/components/button/index.js
  assets/src/design-system/components/pill/index.js
  assets/src/design-system/theme/helpers/outline.js
Labels: Group: Design System, Pod: Pea, cla: yes

#5127 Design panel behavior and state
  assets/src/edit-story/components/inspector/document/excerpt.js
  assets/src/edit-story/components/inspector/document/pageAdvancement.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/document/slug.js
  assets/src/edit-story/components/inspector/document/status.js
  assets/src/edit-story/components/inspector/document/test/excerpt.js
  assets/src/edit-story/components/inspector/document/test/pageAdvancement.js
  assets/src/edit-story/components/inspector/document/test/publish.js
  assets/src/edit-story/components/inspector/document/test/slug.js
  assets/src/edit-story/components/inspector/document/test/status.js
  assets/src/edit-story/components/panels/karma/textStyle.karma.js
  assets/src/edit-story/components/panels/layer/panel.js
  assets/src/edit-story/components/panels/noSelection.js
  assets/src/edit-story/components/panels/pageStyle.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/simplePanel.js
  assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js
  assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js
  assets/src/edit-story/components/panels/preset/test/colorPresetPanel.js
  assets/src/edit-story/components/panels/preset/test/stylePresetPanel.js
  assets/src/edit-story/components/panels/shapeStyle.js
  assets/src/edit-story/components/panels/test/imageAccessibility.js
  assets/src/edit-story/components/panels/test/layerStyle.js
  assets/src/edit-story/components/panels/test/linkPanel.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/components/panels/test/videoAccessibility.js
  assets/src/edit-story/components/panels/textStyle/panel.js
  assets/src/edit-story/karma/fixture/containers/designPanel/textStyle.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#4981 Border radius panel
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/elementBorder/index.js
  assets/src/edit-story/components/elementBorder/utils.js
  assets/src/edit-story/components/panels/borderRadius/index.js
  assets/src/edit-story/components/panels/borderRadius/panel.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/karma/borderRadius.karma.js
  assets/src/edit-story/elements/media/display.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/index.js
  assets/src/edit-story/elements/shape/display.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/icons/border_lock_line.svg
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/borderRadius.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/textStyle.js
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/test/page.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#5350 WordPress 5.6 Compatibility
  .github/workflows/continuous-integration-unit-php.yml
  readme.txt
Labels: cla: yes

#5321 Edit Story: don't alter history with page persistence
  assets/src/edit-story/app/story/effects/useHashState.js
Labels: Group: Workspace, Pod: Pea, Type: Bug, cla: yes

#5346 Added update of local duration when story loads
  assets/src/edit-story/components/inspector/document/pageAdvancement.js
Labels: Pod: Prometheus, cla: yes

#5368 Workspace: Disable tooltip when Publish Checklist Flag is off
  assets/src/edit-story/components/header/buttons/publish.js
Labels: Group: Workspace, cla: yes

#5366 Fix style-lint: remove redundant bracket.
  assets/src/edit-story/components/elementBorder/index.js
  assets/src/edit-story/components/header/karma/publish.karma.js
Labels: Type: Code Quality, cla: yes

#5112 Added new copy-paste handlers for both canvas and editor
  assets/src/edit-story/components/canvas/useCanvasCopyPaste.js
  assets/src/edit-story/components/richText/formatters/convert.js
  assets/src/edit-story/components/richText/formatters/weight.js
  assets/src/edit-story/components/richText/getPastedBlocks.js
  assets/src/edit-story/components/richText/test/getPastedBlocks.js
  assets/src/edit-story/components/richText/useHandlePastedText.js
  assets/src/edit-story/components/richText/usePasteTextContent.js
  assets/src/edit-story/utils/copyPaste.js
  assets/src/edit-story/utils/test/copyPaste.js
Labels: Group: Copy/Paste, Pod: Prometheus, cla: yes

#5224 Design System Storybook: Banner
  assets/src/design-system/components/banner/index.js
  assets/src/design-system/components/banner/stories/index.js
  assets/src/design-system/components/button/index.js
  assets/src/design-system/components/dialog/index.js
  assets/src/design-system/components/modal/index.js
  assets/src/design-system/components/pill/index.js
  assets/src/design-system/components/snackbar/snackbarMessage.js
  assets/src/design-system/components/typography/text/index.js
  assets/src/design-system/theme/borders.js
Labels: Group: Dashboard, Group: Design System, Pod: Pea, cla: yes

#5348 Allow scaling media using scroll-wheel
  assets/src/edit-story/elements/image/karma/edit.karma.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/karma/textStyle.cuj.karma.js
  karma/fixture/events.js
  karma/karma-puppeteer-launcher/mouseWithDnd.cjs
Labels: Pod: Prometheus, cla: yes

#5004 Add trailing slashes to REST API paths
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/edit-story/app/api/apiProvider.js
  includes/Dashboard.php
  includes/REST_API/Stories_Base_Controller.php
  includes/Story_Post_Type.php
  includes/namespace.php
  includes/templates/admin/edit-story.php
Labels: Pod: WP & Infra, Type: Enhancement, Type: Infrastructure, cla: yes

#5312 Discovery: Add filters to allow disabling metadata output
  includes/Discovery.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5402 Fix story title too long error to properly describe prepublish error
  assets/src/edit-story/app/prepublish/constants.js
  assets/src/edit-story/app/prepublish/guidance/test/general.js
Labels: Group: Pre-Publish Panel, Type: Bug, cla: yes

#5398 E2E Tests: Test Site Kit integration
  phpcs.xml.dist
  tests/e2e/plugins/site-kit-mock.php
  tests/e2e/specs/dashboard/integrations/sitekit.js
  tests/e2e/specs/editor/authorUser.js
  tests/e2e/specs/editor/integrations/sitekit.js
  tests/e2e/utils/index.js
  tests/e2e/utils/insertStoryTitle.js
Labels: cla: yes

#5437 Pre-publish: Ignore background images when checking for too small on the page
  assets/src/edit-story/app/prepublish/guidance/media.js
  assets/src/edit-story/app/prepublish/guidance/test/media.js
Labels: cla: yes

#5353 E2E Tests: Test video poster generation
  assets/src/edit-story/components/canvas/karma/backgroundCopyPaste.karma.js
  assets/src/edit-story/components/canvas/karma/cloneSelection.karma.js
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/local/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/panels/videoAccessibility.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/karma/fixture/containers/library/index.js
  assets/src/edit-story/karma/fixture/fixture.js
  bin/local-env/install-wordpress.sh
  tests/e2e/assets/small-video.webm
  tests/e2e/specs/editor/media/insertMediaFromDialog.js
  tests/e2e/specs/editor/media/insertMediaFromLibrary.js
  tests/e2e/specs/editor/media/insertMovVideo.js
  tests/e2e/specs/editor/media/insertWebMVideo.js
  tests/e2e/specs/editor/prepublishChecklist.js
  tests/e2e/specs/editor/publishingFlow.js
  tests/e2e/specs/wordpress/getStartedStory.js
  tests/e2e/utils/clickButton.js
  tests/e2e/utils/index.js
Labels: Group: Media, Pod: WP & Infra, Type: Infrastructure, cla: yes

#5442 Include WordPress version in bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#5435 Text Sets: Use borders on hairline cover
  assets/src/edit-story/components/library/panes/text/textSets/raw/cover.json
Labels: Elements: Text, Pod: Pea, cla: yes

#5461 Docs: Update storybook URL
  docs/storybook.md
Labels: Type: Documentation, Type: Task, cla: yes

#5466 Frontend: Do not pass charset when assembling document
  includes/Story_Renderer/HTML.php
Labels: AMP Output, PHP, Pod: WP & Infra, Type: Bug, cla: yes

#5423 E2E Tests: Update CI build matrix
  .github/workflows/continuous-integration-e2e.yml
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5284 Docker: Pin composer at v1
  bin/local-env/install-composer.sh
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5327 Change the relevant color instantly when changing colors in the color picker
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/colorPicker/colorPicker.js
  assets/src/edit-story/components/elementBorder/index.js
  assets/src/edit-story/components/elementBorder/utils.js
  assets/src/edit-story/components/form/color/color.js
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/panels/border/panel.js
  assets/src/edit-story/components/panels/border/shared.js
  assets/src/edit-story/components/panels/shapeStyle.js
  assets/src/edit-story/components/panels/textStyle/color.js
  assets/src/edit-story/components/richText/customInlineDisplay.js
  assets/src/edit-story/components/richText/fauxSelection.js
  assets/src/edit-story/components/transform/transformProvider.js
  assets/src/edit-story/elements/media/display.js
  assets/src/edit-story/elements/shape/display.js
  assets/src/edit-story/elements/shared/useCSSVarColorTransformHandler.js
  assets/src/edit-story/elements/shared/useColorTransformHandler.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#5418 E2E Tests: Test AMP Plugin Integration
  tests/e2e/specs/integrations/amp.js
  tests/e2e/utils/index.js
  tests/e2e/utils/setAnalyticsCode.js
Labels: Group: Integration, Pod: WP & Infra, Type: Infrastructure, cla: yes

#5426 Animation: Play selected element's new animation effect on selection
  assets/src/animation/components/WAAPIWrapper.js
  assets/src/animation/components/provider.js
  assets/src/animation/components/test/provider.js
  assets/src/animation/constants.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/setSelectedElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/setSelectedElementsById.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/canvas/selection.js
  assets/src/edit-story/components/inspector/design/useDesignPanels.js
  assets/src/edit-story/components/panels/animation/panel.js
Labels: cla: yes

#5341 Page Layout Tab Structure
  assets/src/dashboard/templates/index.js
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/api/test/apiProvider.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/library/panes/common/styles.js
  assets/src/edit-story/components/library/panes/pageLayouts/index.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayout.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayouts.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsIcon.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/pageLayouts/paneId.js
  assets/src/edit-story/components/library/panes/pageLayouts/test/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/text/textSets/textSets.js
  includes/Experiments.php
Labels: cla: yes

#5465 Fix captions panel crashing in case of mixed multi-selection
  assets/src/edit-story/components/panels/captions/captions.js
  assets/src/edit-story/components/panels/test/captions.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#5419 Fix output overflow regression
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/test/output.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/test/__snapshots__/textElement.js.snap
Labels: Pod: Prometheus, Type: Bug, cla: yes

#5434 Text Sets: Use background color instead of shape for roboto cover
  assets/src/edit-story/components/library/panes/text/textSets/raw/cover.json
Labels: Elements: Text, Pod: Pea, cla: yes

#5460 Animations Panel: Rename "zoom" foreground animation to "scale"
  assets/src/edit-story/components/panels/animation/effectChooser.js
  assets/src/edit-story/components/panels/animation/test/effectChooser.js
Labels: Group: Animations, Pod: Pea, Type: Enhancement, cla: yes

#5364 Stabilize WAF Compatibility
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/api/test/base64Encode.js
  assets/src/edit-story/utils/base64Encode.js
  assets/src/edit-story/utils/test/base64Encode.js
  includes/Dashboard.php
  includes/Decoder.php
  includes/Experiments.php
  includes/Plugin.php
  includes/REST_API/Status_Check_Controller.php
  includes/REST_API/Stories_Base_Controller.php
  includes/Story_Post_Type.php
  tests/phpunit/tests/Decoder.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5485 Pre-publish: Use full size image for "low image resolution" accessibility check
  assets/src/edit-story/app/prepublish/warning/accessibility.js
  assets/src/edit-story/app/prepublish/warning/test/accessibility.js
Labels: Group: Pre-Publish Panel, Pod: Pea, Type: Bug, cla: yes

#5264 Accessibility: remove 'Edit: ' or verbs prefixes in announced names
  assets/src/edit-story/components/canvas/karma/backgroundCopyPaste.karma.js
  assets/src/edit-story/components/canvas/karma/keys.karma.js
  assets/src/edit-story/components/canvas/pageAttachment/karma/pageAttachment.cuj.karma.js
  assets/src/edit-story/components/form/advancedDropDown/test/dropDown.js
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/form/color/test/color.js
  assets/src/edit-story/components/form/color/test/colorPreview.js
  assets/src/edit-story/components/form/stories/link.js
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/components/inspector/document/excerpt.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/document/publish/publishTime.js
  assets/src/edit-story/components/inspector/document/slug.js
  assets/src/edit-story/components/inspector/document/test/excerpt.js
  assets/src/edit-story/components/inspector/document/test/publish.js
  assets/src/edit-story/components/inspector/document/test/slug.js
  assets/src/edit-story/components/panels/border/borderWidth.js
  assets/src/edit-story/components/panels/imageAccessibility.js
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js
  assets/src/edit-story/components/panels/pageAttachment/index.js
  assets/src/edit-story/components/panels/test/imageAccessibility.js
  assets/src/edit-story/components/panels/test/linkPanel.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/test/videoAccessibility.js
  assets/src/edit-story/components/panels/textStyle/fontPicker.js
  assets/src/edit-story/components/panels/textStyle/padding.js
  assets/src/edit-story/components/panels/videoAccessibility.js
  assets/src/edit-story/karma/fixture/containers/canvas.js
  assets/src/edit-story/karma/fixture/containers/common/color.js
  assets/src/edit-story/karma/fixture/containers/designPanel/border.js
  assets/src/edit-story/karma/fixture/containers/designPanel/link.js
  assets/src/edit-story/karma/textStyle.cuj.karma.js
Labels: Accessibility, Group: Design Panel, Group: Document Panel, Type: Enhancement, cla: yes
