Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-01, with the labels that each got.

#132 Merge pull request #132 from google/update/continuous-deployment-config
  .gitignore
  .travis.yml
  .travis_deploy_key.enc
  bin/deploy-to-test-environment.sh
Labels: Type: Infrastructure, cla: yes

#133 Fix all lint errors and warnings
  .stylelintrc
  .travis.yml
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/canvas/pagenav/index.js
  assets/src/edit-story/components/canvas/pagepreview/index.js
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/components/inspector/documentInspector.js
  assets/src/edit-story/components/inspector/inspectorLayout.js
  assets/src/edit-story/components/inspector/inspectorTabs.js
  assets/src/edit-story/components/library/libraryLayout.js
  assets/src/edit-story/components/library/mediaLibrary.js
  assets/src/edit-story/components/library/tabs/index.js
  assets/src/edit-story/components/movable/cropStyle.js
  assets/src/edit-story/components/overlay/index.js
  assets/src/edit-story/components/overlay/withOverlay.js
  assets/src/edit-story/components/switch/index.js
  assets/src/edit-story/components/uploadButton/index.js
  assets/src/edit-story/elements/image/frame.js
  assets/src/edit-story/elements/image/scalePanel.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/theme.js
  assets/src/edit-story/utils/pointerEventsCss.js
Labels: Type: Infrastructure, cla: yes

#134 Make storybook output less verbose
  package.json
Labels: Type: Infrastructure, cla: yes

#131 Add GitHub action to periodically update list of Google Fonts
  .github/workflows/update-google-fonts.yml
Labels: Type: Enhancement, Type: Infrastructure, cla: yes

#139 Add some contributing docs
  .distignore
  CONTRIBUTING.md
  README.md
  docs/getting-started.md
  readme.md
Labels: Type: Documentation, cla: yes

#138 Add back local development environment
  .gitignore
  bin/local-env/docker-compose.yml
  bin/local-env/includes.sh
  bin/local-env/install-composer.sh
  bin/local-env/install-node-nvm.sh
  bin/local-env/install-wordpress.sh
  bin/local-env/launch-containers.sh
  bin/local-env/start.sh
  bin/local-env/stop.sh
  package.json
Labels: Type: Infrastructure, cla: yes

#148 Fix upload size
  bin/local-env/docker-compose.yml
  bin/local-env/uploads.ini
Labels: cla: yes

#140 Improve amp plugin compat
  assets/images/fallback-poster.jpg
  assets/images/fallback-wordpress-publisher-logo.png
  assets/src/edit-story/components/library/mediaLibrary.js
  includes/Media.php
  includes/Story_Post_Type.php
  includes/templates/single-web-story.php
Labels: cla: yes

#135 Video Poster
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/components/inspector/document/documentInspector.js
  assets/src/edit-story/components/library/mediaLibrary.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/videoPoster.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/preview.js
  assets/src/edit-story/elements/video/save.js
  assets/src/edit-story/utils/getFirstFrameOfVideo.js
  assets/src/edit-story/utils/useUploadVideoFrame.js
  includes/Media.php
Labels: cla: yes

#136 Editor page resize and units conversion
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/navLayer.js
  assets/src/edit-story/components/canvas/selectionCanvas.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/library/shapeLibrary.js
  assets/src/edit-story/components/movable/index.js
  assets/src/edit-story/components/overlay/index.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/editCropMovable.js
  assets/src/edit-story/elements/image/frame.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/image/scalePanel.js
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/elements/shared.js
  assets/src/edit-story/elements/square/display.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/types.js
  assets/src/edit-story/units/context.js
  assets/src/edit-story/units/dimensions.js
  assets/src/edit-story/units/index.js
  assets/src/edit-story/units/unitsProvider.js
  assets/src/edit-story/units/useUnits.js
  assets/src/edit-story/utils/calculateFitTextFontSize.js
  assets/src/edit-story/utils/pointerEventsCss.js
  assets/src/edit-story/utils/useResizeEffect.js
Labels: cla: yes

#161 Only collect JS coverage when prompted to
  tests/js/jest.config.js
Labels: Type: Infrastructure, cla: yes

#154 Update pre-commit hooks to only lint staged files
  package-lock.json
  package.json
Labels: Type: Enhancement, Type: Infrastructure, cla: yes

#165 Fix video poster
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/types.js
Labels: cla: yes

#162 Use 1080:1920 base for data pixels and prototype data migration system
  .eslintrc
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/library/libraryContent.js
  assets/src/edit-story/components/library/textLibrary.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/migration/dataVersion.js
  assets/src/edit-story/migration/index.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0001_storyDataArrayToObject.js
  assets/src/edit-story/migration/migrations/test/v0002_dataPixelTo1080.js
  assets/src/edit-story/migration/migrations/v0001_storyDataArrayToObject.js
  assets/src/edit-story/migration/migrations/v0002_dataPixelTo1080.js
  assets/src/edit-story/units/index.js
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
Labels: cla: yes

#167 Remove unneeded SlotFillProvider
  assets/src/edit-story/app/index.js
Labels: cla: yes

#155 Rename "css" constants to follow variable case
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/library/mediaLibrary.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/frame.js
  assets/src/edit-story/elements/image/util.js
  assets/src/edit-story/elements/shared.js
  assets/src/edit-story/elements/square/display.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/video/display.js
Labels: cla: yes

#178 Urgent: fix new story creation and migration NPE
  assets/src/edit-story/app/story/effects/useLoadStory.js
Labels: cla: yes

#177 Update calculatable properties in side panels
  assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateElementsById.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateSelectedElements.js
  assets/src/edit-story/components/inspector/design/useDesignPanels.js
  assets/src/edit-story/components/panels/size.js
Labels: cla: yes

#179 Update copy/paste handler to use new story API
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
Labels: cla: yes

#170 Improved element drag and drop UI
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/utils.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/selection.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/movable/cropStyle.js
  assets/src/edit-story/components/movable/moveStyle.js
  assets/src/edit-story/elements/image/editPanMovable.js
  assets/src/edit-story/elements/image/scalePanel.js
  assets/src/edit-story/theme.js
  assets/src/edit-story/utils/objectWithout.js
  bin/install-wp-tests.sh
Labels: cla: yes
