Repository GoogleForCreators/web-stories-wp, pull requests merged in 2020-06, with the labels that each got.

#1988 Add labels for all inputs
  assets/src/edit-story/components/button/test/button.js
  assets/src/edit-story/components/canvas/gridview/test/gridview.js
  assets/src/edit-story/components/form/color/color.js
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/form/dateTime/dateTime.js
  assets/src/edit-story/components/form/dateTime/index.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/form/dropDown/stories/index.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/form/numeric.js
  assets/src/edit-story/components/form/test/numeric.js
  assets/src/edit-story/components/form/test/radioGroup.js
  assets/src/edit-story/components/form/test/switch.js
  assets/src/edit-story/components/form/test/toggle.js
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/header/test/buttons.js
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/components/inspector/document/publish/index.js
  assets/src/edit-story/components/inspector/document/publish/publishTime.js
  assets/src/edit-story/components/inspector/document/slug.js
  assets/src/edit-story/components/inspector/document/test/pageAdvancement.js
  assets/src/edit-story/components/inspector/document/test/publish.js
  assets/src/edit-story/components/inspector/document/test/slug.js
  assets/src/edit-story/components/inspector/document/test/status.js
  assets/src/edit-story/components/library/common/searchInput.js
  assets/src/edit-story/components/library/test/text/textPane.js
  assets/src/edit-story/components/panels/backgroundOverlay.js
  assets/src/edit-story/components/panels/imageAccessibility.js
  assets/src/edit-story/components/panels/layer/test/layer.js
  assets/src/edit-story/components/panels/layerStyle.js
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/stylePreset/test/colorPresetActions.js
  assets/src/edit-story/components/panels/test/layerStyle.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/test/videoAccessibility.js
  assets/src/edit-story/components/panels/textStyle/color.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/components/panels/textStyle/padding/locked.js
  assets/src/edit-story/components/panels/textStyle/padding/unlocked.js
  assets/src/edit-story/components/panels/textStyle/textStyle.js
  assets/src/edit-story/components/panels/videoAccessibility.js
Labels: cla: yes

#1973 Moveable: Update all elements together after group actions.
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/test/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/test/singleSelectionMovable.js
Labels: cla: yes

#2138 Dashboard: click story title action
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/test/useStoryApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/myStories/header/test/header.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/link/index.js
  assets/src/dashboard/components/link/stories/index.js
  assets/src/dashboard/storybookUtils/formattedStoriesArray.js
Labels: Group: Dashboard, P1, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2160 Dashboard: bug fix - button wrap on hover
  assets/src/dashboard/components/button/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Bug, cla: yes

#2129 1513 | Animate Active Story Page In Template Detail
  assets/src/dashboard/app/views/templates/detail.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGallery/test/cardGallery.js
Labels: cla: yes

#2155 Disable trashing Story from editor
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/story/actions/useDeleteStory.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/components/inspector/document/status.js
  assets/src/edit-story/components/inspector/document/test/slug.js
  assets/src/edit-story/components/inspector/document/test/status.js
  assets/src/edit-story/karma/fixture.js
Labels: cla: yes

#1880 Add click detection to multi-selection Moveable
  assets/src/edit-story/components/canvas/karma/multiSelectionMovable.karma.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/test/multiSelectionMovable.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/utils/isMouseUpAClick.js
  assets/src/edit-story/utils/test/isMouseUpAClick.js
Labels: cla: yes

#2075 Improve Site Kit Google Analytics integration
  includes/Plugin.php
  includes/Story_Renderer.php
  tests/phpunit/tests/Story_Renderer.php
Labels: Pod: WP & Infra, Type: Enhancement, cla: yes

#2091 Fix page nav hover style
  assets/src/edit-story/components/canvas/pagenav/index.js
Labels: Pod: Workspace, Type: Enhancement, cla: yes

#2150 Karma - Add media library with images and videos
  __static__/asteroid.ogg
  __static__/asteroid.png
  __static__/blue-marble.jpg
  __static__/curiosity.jpg
  __static__/earth.jpg
  __static__/mars.jpg
  __static__/ranger9.ogg
  __static__/ranger9.png
  __static__/saturn.jpg
  assets/src/edit-story/karma/db/getMediaResponse.js
  assets/src/edit-story/karma/fixture.js
Labels: Pod: Workspace, Type: Infrastructure, cla: yes

#2125 Karma: proposal to simplify mouse events
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/karma/fixtureEvents.js
Labels: cla: yes

#1300 Workspace: Font Dropdown with Typeface Previews
  assets/src/edit-story/app/font/fontProvider.js
  assets/src/edit-story/components/fontPicker/fontPicker.js
  assets/src/edit-story/components/fontPicker/index.js
  assets/src/edit-story/components/fontPicker/pickerContainer.js
  assets/src/edit-story/components/fontPicker/scrollList.js
  assets/src/edit-story/components/fontPicker/test/fontPicker.js
  assets/src/edit-story/components/fontPicker/test/fontsResponse.json
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/panels/test/textStyle.js
  assets/src/edit-story/components/panels/textStyle/font.js
  assets/src/edit-story/icons/checkmark.svg
  assets/src/edit-story/utils/loadStylesheet.js
  includes/Story_Post_Type.php
Labels: Group: Fonts, Type: Enhancement, cla: yes

#2184 Fix PHPCS warnings
  includes/Embed_Block.php
  includes/Media.php
  includes/Story_Post_Type.php
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#2193 DB Upgrader: Don’t update previous version if there were no updates
  includes/Database_Upgrader.php
  tests/phpunit/tests/Database_Upgrader.php
Labels: Pod: WP & Infra, Type: Bug, cla: yes

#2109 Remove obsolete `Domain Path` plugin header
  web-stories.php
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#2128 Dashboard: Add feature flag for in-progress views.
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/test/pageStructure.js
  assets/src/dashboard/constants/index.js
  includes/Dashboard.php
Labels: cla: yes

#1976 Deprecate `isFill` (fullBleed) setting
  assets/src/dashboard/storybookUtils/formattedStoriesArray.js
  assets/src/dashboard/templates/data/beauty.js
  assets/src/dashboard/templates/data/cooking.js
  assets/src/dashboard/templates/data/diy.js
  assets/src/dashboard/templates/data/entertainment.js
  assets/src/dashboard/templates/data/fashion.js
  assets/src/dashboard/templates/data/fitness.js
  assets/src/dashboard/templates/data/travel.js
  assets/src/dashboard/templates/data/wellbeing.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/panels/alignment/alignment.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/test/alignment.js
  assets/src/edit-story/components/panels/test/sizePosition.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/index.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/icons/fullbleed.svg
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0020_isFillDeprecate.js
  assets/src/edit-story/migration/migrations/v0020_isFillDeprecate.js
  assets/src/edit-story/types.js
  assets/src/edit-story/units/dimensions.js
Labels: cla: yes

#2121 Flush rewrite rules on plugin activation
  includes/namespace.php
  phpstan.neon.dist
  tests/phpstan/bootstrap.php
Labels: Pod: WP & Infra, Type: Enhancement, cla: yes

#2163 Dashboard: Add story context menu to list view
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/savedTemplates/savedTemplatesGridView/index.js
  assets/src/dashboard/app/views/shared/stories/storyGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/cardGridItem/test/cardTitle.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/inlineInputForm/index.js
  assets/src/dashboard/components/inlineInputForm/stories/index.js
  assets/src/dashboard/components/inlineInputForm/test/inlineInputForm.js
  assets/src/dashboard/components/storyMenu/index.js
  assets/src/dashboard/components/storyMenu/stories/index.js
  assets/src/dashboard/components/storyMenu/test/storyMenu.js
  assets/src/dashboard/icons/moreVertical.svg
  assets/src/dashboard/types.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#2195 Dashboard: Refresh stories preview after workspace changes
  assets/src/dashboard/app/api/useStoryApi.js
Labels: Group: Dashboard, Type: Enhancement, cla: yes

#2221 Dashboard: Update story-anim-tool to help update/migrate templates easier
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/app/views/storyAnimTool/updateTemplateForm.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2107 Accessibility: minimum page thumbnail size
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/layout.js
Labels: cla: yes

#2069 Fix spacing above images and next to scrollbar in media pane
  assets/src/edit-story/components/library/panes/media/mediaPane.js
Labels: Pod: Media I/O, cla: yes

#2191 Improve Story Discoverability on Frontend
  includes/Discovery.php
  includes/Media.php
  includes/Plugin.php
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/Story_Renderer.php
Labels: Group: Discoverability, Pod: WP & Infra, Type: Enhancement, cla: yes

#1997 Add template post type
  includes/Admin.php
  includes/Plugin.php
  includes/REST_API/Stories_Base_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/Template_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#2192 Editor: Add storybook story for icons
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/colorPicker/gradientPicker.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/form/radioGroup.js
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/inspector/document/publish/publishTime.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/library/panes/media/mediaTab.js
  assets/src/edit-story/components/library/panes/shapes/shapesTab.js
  assets/src/edit-story/components/link/frame.js
  assets/src/edit-story/components/panels/alignment/alignment.js
  assets/src/edit-story/components/panels/layer/layer.js
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/shared/flipControls.js
  assets/src/edit-story/components/panels/shared/note.js
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/components/panels/stylePreset/header.js
  assets/src/edit-story/components/panels/stylePreset/presets.js
  assets/src/edit-story/components/panels/textStyle/color.js
  assets/src/edit-story/components/panels/textStyle/padding/locked.js
  assets/src/edit-story/components/panels/textStyle/padding/unlocked.js
  assets/src/edit-story/components/panels/textStyle/textStyle.js
  assets/src/edit-story/elements/image/icon.js
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/stories/index.js
  assets/src/edit-story/utils/backgroundOverlay.js
Labels: Type: Infrastructure, cla: yes

#1878 Fix various background inconsistencies
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/panels/sizePosition.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/media/index.js
  assets/src/edit-story/karma/fixture.js
  assets/src/edit-story/utils/objectPick.js
  assets/src/edit-story/utils/test/objectPick.js
Labels: Elements: Text, Pod: Workspace, cla: yes

#2164 Remove Branded Logos from Templates.
  .eslintignore
  assets/images/templates/beauty/beauty_page9_story2.jpg
  assets/images/templates/entertainment/ent_icon_fb.png
  assets/images/templates/entertainment/ent_icon_gray_star.png
  assets/images/templates/entertainment/ent_icon_insta.png
  assets/images/templates/entertainment/ent_icon_logo.png
  assets/images/templates/entertainment/ent_icon_twtr.png
  assets/images/templates/entertainment/ent_icon_up_arrow.png
  assets/images/templates/entertainment/ent_icon_white_star.png
  assets/images/templates/entertainment/ent_icon_yt.png
  assets/images/templates/entertainment/ent_page1_bg.jpg
  assets/images/templates/entertainment/ent_page2_image1.jpg
  assets/images/templates/entertainment/ent_page4_image1.jpg
  assets/images/templates/entertainment/ent_page5_image1.jpg
  assets/images/templates/entertainment/ent_page6_image1.jpg
  assets/images/templates/entertainment/ent_page7_image1.jpg
  assets/images/templates/entertainment/ent_page8_image1.jpg
  assets/images/templates/entertainment/ent_page8_image2.jpg
  assets/images/templates/entertainment/ent_page9_image1.jpg
  assets/images/templates/entertainment/ent_page9_image2.jpg
  assets/images/templates/entertainment/ent_page9_image3.jpg
  assets/src/dashboard/templates/data/beauty.js
  assets/src/dashboard/templates/data/cooking.js
  assets/src/dashboard/templates/data/diy.js
  assets/src/dashboard/templates/data/entertainment.js
  assets/src/dashboard/templates/data/fashion.js
  assets/src/dashboard/templates/data/fitness.js
  assets/src/dashboard/templates/data/travel.js
  assets/src/dashboard/templates/data/wellbeing.js
  assets/src/dashboard/templates/getTemplates.js
  assets/src/dashboard/templates/index.js
  assets/src/dashboard/templates/raw/beauty.json
  assets/src/dashboard/templates/raw/cooking.json
  assets/src/dashboard/templates/raw/diy.json
  assets/src/dashboard/templates/raw/entertainment.json
  assets/src/dashboard/templates/raw/fashion.json
  assets/src/dashboard/templates/raw/fitness.json
  assets/src/dashboard/templates/raw/travel.json
  assets/src/dashboard/templates/raw/wellbeing.json
  assets/src/dashboard/templates/test/getTemplates.js
  assets/src/dashboard/utils/index.js
  assets/src/dashboard/utils/memoize.js
  assets/src/dashboard/utils/test/memoize.js
  docs/README.md
  docs/external-template-creation.md
  package.json
Labels: Group: Templates, Pod: Dashboard & Templates, Type: Documentation, Type: Enhancement, cla: yes

#2032 Added clear button to Media search pane
  assets/src/edit-story/components/form/text.js
  assets/src/edit-story/components/library/common/searchInput.js
  assets/src/edit-story/components/library/panes/media/mediaPane.js
Labels: Pod: Media I/O, cla: yes

#2267 Ignore default mask in the output
  assets/src/edit-story/masks/output.js
  assets/src/edit-story/masks/test/output.js
  assets/src/edit-story/output/element.js
Labels: cla: yes

#2279 Add Gutenberg plugin to local environment
  bin/local-env/install-wordpress.sh
Labels: Type: Infrastructure, cla: yes

#2057 Dashboard: Update Focus Out to handle where mouse clicks start
  assets/src/dashboard/utils/useFocusOut.js
Labels: Group: Dashboard, P0, Pod: Dashboard & Templates, cla: yes

#2141 Dashboard: Migrate templates on load to latest version
  assets/src/dashboard/templates/getTemplates.js
Labels: cla: yes

#2260 Feature | Adds animation controls in /story-anim-tool
  assets/src/dashboard/animations/parts/simpleAnimation.js
  assets/src/dashboard/app/views/storyAnimTool/emitter.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/components.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/index.js
  assets/src/dashboard/app/views/storyAnimTool/updateTemplateForm.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/previewPage.js
  assets/src/dashboard/components/storyAnimation/provider.js
  assets/src/dashboard/components/storyAnimation/test/WAAPIWrapper.js
  assets/src/dashboard/components/storyAnimation/test/provider.js
  assets/src/dashboard/constants/stories.js
Labels: cla: yes

#2265 Fullbleed and safe zones in AMP output
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/output/utils/styles.js
Labels: cla: yes

#2261 Nest page menu inside the canvas and support more return-to-canvas scenarios
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/karma/pageMenuActions.karma.js
  assets/src/edit-story/components/canvas/navLayer.js
  assets/src/edit-story/components/canvas/useCanvasKeys.js
  assets/src/edit-story/karma/_init.js
  assets/src/edit-story/karma/fixture.js
  assets/src/edit-story/karma/fixtureEvents.js
Labels: cla: yes

#2281 Quick bug fix to story anim tool
  assets/src/dashboard/app/views/storyAnimTool/components.js
  assets/src/dashboard/app/views/storyAnimTool/timeline/index.js
Labels: cla: yes

#2285 Make selection lines visible and fix safezone offset
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/karma/lasso.karma.js
  assets/src/edit-story/components/canvas/karma/selection.karma.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/selectionCanvas.js
Labels: cla: yes

#2274 Use `defaultProps` for `WithMask`
  assets/src/edit-story/masks/output.js
Labels: Type: Code Quality, cla: yes

#2287 Karma: move all fixture code in one package
  assets/src/edit-story/karma/fixture/db/getMediaResponse.js
  assets/src/edit-story/karma/fixture/events.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/karma/fixture/index.js
Labels: cla: yes

#2045 Fix popup stacking with modals
  assets/src/edit-story/components/popup/index.js
Labels: cla: yes

#2311 Dashboard: Bug fixes for color panel translation and detail template capitalization
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/templateNavBar/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Bug, cla: yes

#2246 Update Moveable to fix right-click handling + resizing
  package-lock.json
  package.json
Labels: cla: yes

#2325 Patch ESLint’s no-shadow rule
  .eslintrc
  assets/src/story-embed-block/block/test/embedPreview.js
  patches/eslint+7.2.0.patch
Labels: Type: Infrastructure, cla: yes

#2244 Delete element when it's completely outside of Canvas
  assets/src/edit-story/components/canvas/karma/multiSelectionMovable.karma.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/canvas/test/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/test/singleSelectionMovable.js
  assets/src/edit-story/utils/isTargetOutOfContainer.js
Labels: cla: yes

#1848 Remove fetch after upload
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/test/useUploadMedia.js
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
Labels: Group: Media, Type: Enhancement, cla: yes

#2289 Update ESLint to version 7
  package-lock.json
  package.json
  patches/eslint+7.2.0.patch
Labels: Type: Infrastructure, cla: yes

#2288 Add eslint-plugin-jasmine
  .eslintrc
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  assets/src/edit-story/karma/fixture/fixture.js
  package-lock.json
  package.json
Labels: Type: Infrastructure, cla: yes

#2251 Workspace: Hide Search Input based on feature flag
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/test/text/textPane.js
  includes/Story_Post_Type.php
Labels: Type: Enhancement, cla: yes

#2353 Remove dependency on state changes of uploading video id(s)
  assets/src/edit-story/app/media/mediaProvider.js
Labels: cla: yes

#2377 Add Background Wrapper and Migration to Dashboard Stories.
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/components/previewPage.js
Labels: cla: yes

#2349 Dashboard: Temporarily remove story actions that aren't ready yet
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/savedTemplates/savedTemplatesGridView/index.js
  assets/src/dashboard/app/views/savedTemplates/test/savedTemplates.js
  assets/src/dashboard/app/views/shared/stories/storyGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/storyMenu/index.js
  assets/src/dashboard/components/storyMenu/stories/index.js
  assets/src/dashboard/components/storyMenu/test/storyMenu.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/testUtils/index.js
  assets/src/dashboard/testUtils/renderWithTheme.js
  assets/src/dashboard/types.js
  includes/Dashboard.php
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2266 Remove unnecessary useCallback from useContextSelector
  assets/src/edit-story/utils/context.js
Labels: Type: Code Quality, cla: yes

#2280 Add media source taxonomy
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  includes/Database_Upgrader.php
  includes/Media.php
  tests/phpunit/tests/Media.php
  web-stories.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#2336 Add more metadata to frontend output
  includes/Discovery.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#1948 New behavior for playback controls and min element size
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/library/panes/media/mediaElement.js
  assets/src/edit-story/components/movable/moveStyle.js
  assets/src/edit-story/components/popup/index.js
  assets/src/edit-story/elements/media/index.js
  assets/src/edit-story/elements/shape/index.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/video/controls.js
  assets/src/edit-story/elements/video/frame.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/elements/video/karma/elementMinSizeAndPlayback.js
  package.json
Labels: cla: yes

#2383 Dashboard: Hide in progress template actions
  assets/src/dashboard/app/views/exploreTemplates/header/index.js
  assets/src/dashboard/app/views/exploreTemplates/header/stories/index.js
  assets/src/dashboard/app/views/exploreTemplates/header/test/header.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  includes/Dashboard.php
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2384 Dashboard: Hide bookmarks behind flag
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/components/templateNavBar/index.js
  assets/src/dashboard/components/templateNavBar/stories/index.js
  includes/Dashboard.php
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2183 Fix: Adding text presets crashes editor
  includes/Database_Upgrader.php
  tests/phpunit/tests/Database_Upgrader.php
  web-stories.php
Labels: cla: yes

#2329 Dashboard: Added preview button to story anim tool
  assets/src/dashboard/app/views/storyAnimTool/index.js
Labels: cla: yes

#1810 Allows edit text as soon as user type while selecting a text element
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/text/karma/frame.karma.js
  assets/src/edit-story/elements/text/test/frame.js
Labels: Elements: Text, Pod: Workspace, Type: Bug, cla: yes

#1925 Make background overlay editable
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/clearBackgroundElement.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/form/color/colorPreview.js
  assets/src/edit-story/components/form/color/getPreviewStyle.js
  assets/src/edit-story/components/form/color/test/getPreviewStyle.js
  assets/src/edit-story/components/panels/backgroundOverlay/convertOverlay.js
  assets/src/edit-story/components/panels/backgroundOverlay/index.js
  assets/src/edit-story/components/panels/backgroundOverlay/karma/backgroundOverlay.karma.js
  assets/src/edit-story/components/panels/backgroundOverlay/panel.js
  assets/src/edit-story/components/panels/backgroundOverlay/test/convertOverlay.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0023_convertOverlayPattern.js
  assets/src/edit-story/migration/migrations/v0023_convertOverlayPattern.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/output/utils/styles.js
  assets/src/edit-story/utils/backgroundOverlay.js
Labels: cla: yes

#2419 Fix multi-selection karma tests for different screen sizes
  assets/src/edit-story/components/canvas/karma/multiSelectionMovable.karma.js
Labels: cla: yes

#2382 Canvas keys: move to global and make improve focus trapping
  assets/src/edit-story/app/history/historyProvider.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/carousel/useCarouselKeys.js
  assets/src/edit-story/components/canvas/karma/carousel.karma.js
  assets/src/edit-story/components/canvas/karma/keys.karma.js
  assets/src/edit-story/components/canvas/useCanvasKeys.js
  assets/src/edit-story/components/canvas/useEditingElement.js
  assets/src/edit-story/components/form/button.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/form/radioGroup.js
  assets/src/edit-story/components/form/switch.js
  assets/src/edit-story/components/form/toggle.js
  assets/src/edit-story/components/form/toggleButton.js
  assets/src/edit-story/components/keyboard/index.js
  assets/src/edit-story/components/library/libraryTabs.js
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/karma/fixture/events.js
  assets/src/edit-story/karma/fixture/fixture.js
  karma.config.cjs
  package.json
Labels: cla: yes

#2330 Dashboard: Confirm Delete Dialog UI
  .storybook/preview.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/button/stories/index.js
  assets/src/dashboard/components/cardGridItem/index.js
  assets/src/dashboard/components/dialog/index.js
  assets/src/dashboard/components/dialog/stories/index.js
  assets/src/dashboard/components/dialog/test/dialog.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/modal/index.js
  assets/src/dashboard/components/modal/stories/index.js
  assets/src/dashboard/components/modal/test/modal.js
  assets/src/dashboard/constants/components.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/index.js
  assets/src/dashboard/theme.js
Labels: cla: yes

#2238 Color Preset updates for beta
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/panels/stylePreset/header.js
  assets/src/edit-story/components/panels/stylePreset/panel.js
  assets/src/edit-story/components/panels/stylePreset/presets.js
  assets/src/edit-story/components/panels/stylePreset/test/panel.js
  assets/src/edit-story/components/panels/stylePreset/test/presets.js
  assets/src/edit-story/components/panels/stylePreset/test/utils.js
  assets/src/edit-story/components/panels/stylePreset/utils.js
Labels: cla: yes

#2420 Dashboard: Animated first two pages of Entertainment template
  assets/images/templates/entertainment/ent_icon_logo.png
  assets/images/templates/entertainment/ent_icon_musicnote.png
  assets/images/templates/entertainment/ent_icon_wraparound.png
  assets/src/dashboard/templates/getTemplates.js
  assets/src/dashboard/templates/raw/cooking.json
  assets/src/dashboard/templates/raw/entertainment.json
  assets/src/dashboard/templates/raw/fitness.json
  assets/src/dashboard/templates/raw/wellbeing.json
Labels: cla: yes

#2290 Karma: support synthetic DND events
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  karma/karma-puppeteer-launcher/index.cjs
  karma/karma-puppeteer-launcher/mouseWithDnd.cjs
Labels: cla: yes

#2388 Fix media scroll performance regression
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/canvas/canvasUploadDropTarget.js
Labels: Type: Bug, cla: yes

#2270 Added uploaded date to edit dialog
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/app/media/utils/getResourceFromAttachment.js
  assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js
  assets/src/edit-story/components/library/panes/media/mediaEditDialog.js
  assets/src/edit-story/components/library/panes/media/stories/mediaEditDialog.js
  assets/src/edit-story/components/library/panes/media/stories/mediaElement.js
  assets/src/edit-story/theme.js
Labels: Group: Media, Type: Enhancement, cla: yes

#2500 Karma: re-enable Percy
  .github/workflows/continuous-integration-karma.yml
  assets/src/edit-story/components/canvas/karma/carousel.karma.js
  assets/src/edit-story/components/canvas/karma/multiSelectionMovable.karma.js
  assets/src/edit-story/karma/fixture/fixture.js
  karma.config.cjs
  karma/karma-puppeteer-launcher/index.cjs
  karma/karma-puppeteer-launcher/mouseWithDnd.cjs
  percy.config.yml
Labels: Type: Infrastructure, cla: yes

#2468 Preload API requests
  includes/Dashboard.php
  includes/edit-story.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#2282 Hide selection box on Text Element when dragging
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
Labels: Pod: Workspace, Type: Bug, cla: yes

#2504 Feature | Base Template Animations - Fashion [2213]
  assets/src/dashboard/animations/parts/components/fullSizeAbsolute.js
  assets/src/dashboard/templates/raw/fashion.json
Labels: cla: yes

#2546 Dashboard: Update router for new history version.
  assets/src/dashboard/app/router/routerProvider.js
  assets/src/dashboard/app/router/test/router.js
Labels: Group: Dashboard, P0, Pod: Dashboard & Templates, cla: yes

#2003 Fix editor crashing while using composed characters on Text Element
  assets/src/edit-story/components/richText/draftUtils.js
Labels: Elements: Text, Pod: Workspace, Type: Bug, cla: yes

#2544 Remove slash after imageBaseUrl
  assets/src/dashboard/templates/getTemplates.js
  includes/Dashboard.php
Labels: Pod: Dashboard & Templates, Type: Code Quality, cla: yes

#2324 Add logic for getting proper font variants.
  assets/src/edit-story/components/richText/getFontVariants.js
  assets/src/edit-story/components/richText/htmlManipulation.js
  assets/src/edit-story/output/test/story.js
  assets/src/edit-story/output/utils/getFontDeclarations.js
  assets/src/edit-story/output/utils/test/getFontDeclarations.js
Labels: Group: Fonts, Type: Enhancement, cla: yes

#2306 Adapt popup height to contents
  assets/src/edit-story/components/form/dateTime/datePicker.js
  assets/src/edit-story/components/form/dateTime/dateTime.js
  assets/src/edit-story/components/inspector/document/publish/publishTime.js
  assets/src/edit-story/components/popup/index.js
  assets/src/edit-story/components/popup/utils.js
Labels: cla: yes

#1994 Drop target prioritization
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/dropTargets/karma/order.karma.js
  assets/src/edit-story/components/dropTargets/provider.js
Labels: Pod: Workspace, Type: Enhancement, cla: yes

#2551 add a flag for the 3P media tab.
  includes/Story_Post_Type.php
Labels: cla: yes

#2379 Add default positioning for text.
  assets/src/edit-story/components/library/panes/text/textPresets.js
Labels: cla: yes

#2465 Embed Block: Fix center alignment
  assets/src/story-embed-block/block/edit.css
  includes/Embed_Block.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#2268 Dashboard: Integrating amp-animations into a generated amp-story
  .storybook/preview-head.html
  assets/src/dashboard/animations/outputs/animationOutput.js
  assets/src/dashboard/animations/outputs/types.js
  assets/src/dashboard/animations/parts/blinkOn/stories/index.js
  assets/src/dashboard/animations/parts/bounce/stories/index.js
  assets/src/dashboard/animations/parts/components/fullSizeAbsolute.js
  assets/src/dashboard/animations/parts/fade/stories/index.js
  assets/src/dashboard/animations/parts/flip/stories/index.js
  assets/src/dashboard/animations/parts/floatOn/stories/index.js
  assets/src/dashboard/animations/parts/index.js
  assets/src/dashboard/animations/parts/move/stories/index.js
  assets/src/dashboard/animations/parts/simpleAnimation.js
  assets/src/dashboard/animations/parts/spin/stories/index.js
  assets/src/dashboard/animations/parts/types.js
  assets/src/dashboard/animations/parts/zoom/stories/index.js
  assets/src/dashboard/components/storyAnimation/AMPWrapper.js
  assets/src/dashboard/components/storyAnimation/provider.js
  assets/src/edit-story/output/element.js
  assets/src/edit-story/output/page.js
  assets/src/edit-story/output/story.js
  assets/src/edit-story/output/test/page.js
  assets/src/edit-story/output/test/story.js
  assets/src/edit-story/output/utils/getStoryMarkup.js
  assets/src/edit-story/output/utils/styles.js
  assets/src/edit-story/output/utils/test/getStoryMarkup.js
  assets/src/edit-story/types.js
  includes/Story_Post_Type.php
Labels: cla: yes

#2415 Add default title when rendering story block on the frontend
  includes/Embed_Block.php
  tests/phpunit/tests/Embed_Block.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#2345 Allow sorting stories by author display names
  includes/REST_API/Stories_Controller.php
  phpstan.neon.dist
  tests/phpunit/tests/REST_API/Stories_Controller.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#2515 Add beta updater class
  .distignore
  .travis.yml
  __cdn__/service/plugin-updates.json
  includes/Plugin.php
  includes/Updater.php
  package.json
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#2576 Disable Percy for the time being
  .github/workflows/continuous-integration-karma.yml
Labels: cla: yes

#2565 Dashboard: Added animations to Entertainment pages 3 through 6
  assets/src/dashboard/templates/getTemplates.js
  assets/src/dashboard/templates/raw/entertainment.json
Labels: Group: Animations, Pod: Dashboard & Templates, cla: yes

#2552 Use correct icons for radios.
  assets/src/edit-story/components/form/radioGroup.js
Labels: Type: Bug, cla: yes

#2310 Dashboard: Save Story as Template
  assets/src/dashboard/app/api/apiProvider.js
  assets/src/dashboard/app/api/fetchAllFromPages.js
  assets/src/dashboard/app/api/test/useCategoryApi.js
  assets/src/dashboard/app/api/test/useTagsApi.js
  assets/src/dashboard/app/api/test/useUserApi.js
  assets/src/dashboard/app/api/useCategoriesApi.js
  assets/src/dashboard/app/api/useFontApi.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useTagsApi.js
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/api/useUserApi.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/reducer/templates.js
  assets/src/dashboard/app/reducer/test/templates.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  includes/Dashboard.php
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2582 Fix: Flags are now passed into getStoryMarkup
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/edit-story/app/story/actions/useAutoSave.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/app/story/utils/getStoryPropsToSave.js
  assets/src/edit-story/app/story/utils/test/getStoryPropsToSave.js
  assets/src/edit-story/output/utils/getStoryMarkup.js
  assets/src/edit-story/output/utils/test/getStoryMarkup.js
Labels: Pod: Dashboard & Templates, Type: Bug, cla: yes

#2594 hiding sort dropdown with boolean if flag is false
  assets/src/dashboard/app/views/exploreTemplates/header/index.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#2579 Dashboard: Alert UI Component
  assets/src/dashboard/components/alert/components.js
  assets/src/dashboard/components/alert/container.js
  assets/src/dashboard/components/alert/index.js
  assets/src/dashboard/components/alert/stories/index.js
  assets/src/dashboard/components/alert/test/index.js
  assets/src/dashboard/constants/components.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/types.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2593 Remove anonymous functions.
  includes/Media.php
  includes/Story_Post_Type.php
Labels: Pod: WP & Infra, Type: Code Quality, cla: yes

#2378 Workspace: New Safe Zone Design & Toggle
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/safe_zone.svg
Labels: Group: Canvas, Group: Carousel, P1, Pod: Dashboard & Templates, Pod: Workspace, Type: Bug, cla: yes

#2533 Enable Percy
  .github/workflows/continuous-integration-karma.yml
  assets/src/edit-story/components/canvas/karma/multiSelectionMovable.karma.js
Labels: cla: yes

#2625 Disable Carousel karma tests until flakiness can be resolved
  assets/src/edit-story/components/canvas/karma/carousel.karma.js
Labels: cla: yes

#2584 Keep styling when clearing rich text
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/richText/karma/itf.karma.js
  assets/src/edit-story/components/richText/provider.js
Labels: Elements: Text, Type: Enhancement, cla: yes

#2550 Dashboard: Update aspect ratio to 9:16
  assets/src/dashboard/app/views/exploreTemplates/content/index.js
  assets/src/dashboard/app/views/exploreTemplates/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/shared/stories/storyGridView.js
  assets/src/dashboard/app/views/shared/stories/templateGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/storyAnimTool/components.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/components/cardGallery/components.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGallery/stories/index.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGrid/stories/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/stories/index.js
  assets/src/dashboard/components/previewPage.js
  assets/src/dashboard/constants/pageStructure.js
  assets/src/dashboard/storybookUtils/index.js
  assets/src/dashboard/types.js
  assets/src/dashboard/utils/index.js
  assets/src/dashboard/utils/test/usePagePreviewSize.js
  assets/src/dashboard/utils/usePagePreviewSize.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#2622 Disable Percy again
  .github/workflows/continuous-integration-karma.yml
Labels: cla: yes

#2627 Enable Percy try 3
  .github/workflows/continuous-integration-karma.yml
Labels: cla: yes

#2614 Update storybook to latest beta
  .storybook/main.cjs
  .storybook/preview.js
  .storybook/stories/playground/index.js
  assets/src/edit-story/components/button/stories/index.js
  assets/src/edit-story/output/story.js
  package-lock.json
  package.json
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#2595 Use objects everywhere instead of static methods
  includes/Admin.php
  includes/Database_Upgrader.php
  includes/Discovery.php
  includes/Embed_Block.php
  includes/Fonts.php
  includes/Media.php
  includes/Plugin.php
  includes/REST_API/Fonts_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/Story_Renderer.php
  includes/Template_Post_Type.php
  includes/namespace.php
  tests/phpunit/tests/Database_Upgrader.php
  tests/phpunit/tests/Fonts.php
  tests/phpunit/tests/Media.php
  tests/phpunit/tests/Story_Post_Type.php
  tests/phpunit/tests/Story_Renderer.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#2256 Editor: Add error boundaries
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/errorBoundary/errorActions.js
  assets/src/edit-story/components/errorBoundary/index.js
  assets/src/edit-story/components/workspace/index.js
  webpack.config.cjs
Labels: Group: Editing, Pod: Workspace, Type: Enhancement, cla: yes

#2386 Karma: test containers for DOM lookup
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/karma/lasso.karma.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/karma/fixture/containers/canvas.js
  assets/src/edit-story/karma/fixture/containers/container.js
  assets/src/edit-story/karma/fixture/containers/editor.js
  assets/src/edit-story/karma/fixture/containers/index.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#2623 Extract repeated logic to traits
  includes/Dashboard.php
  includes/Discovery.php
  includes/Embed_Block.php
  includes/Media.php
  includes/Plugin.php
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Link_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/Story_Renderer.php
  includes/Traits/Assets.php
  includes/Traits/Document_Parser.php
  includes/Traits/Publisher.php
  includes/Traits/Types.php
  tests/phpunit/tests/Story_Renderer.php
Labels: Pod: WP & Infra, Skip Changelog, Type: Code Quality, cla: yes

#2598 Use only one set of color presets for text, shape, page background
  assets/src/dashboard/storybookUtils/formattedStoriesArray.js
  assets/src/edit-story/app/api/test/_utils.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/panels/stylePreset/colorPresetActions.js
  assets/src/edit-story/components/panels/stylePreset/header.js
  assets/src/edit-story/components/panels/stylePreset/panel.js
  assets/src/edit-story/components/panels/stylePreset/presetGroup.js
  assets/src/edit-story/components/panels/stylePreset/presets.js
  assets/src/edit-story/components/panels/stylePreset/stories/index.js
  assets/src/edit-story/components/panels/stylePreset/test/colorPresetActions.js
  assets/src/edit-story/components/panels/stylePreset/test/panel.js
  assets/src/edit-story/components/panels/stylePreset/test/presetGroup.js
  assets/src/edit-story/components/panels/stylePreset/test/presets.js
  assets/src/edit-story/components/panels/stylePreset/test/utils.js
  assets/src/edit-story/components/panels/stylePreset/utils.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/types.js
  composer.lock
  includes/Database_Upgrader.php
  includes/REST_API/Stories_Controller.php
  tests/phpunit/bootstrap.php
  tests/phpunit/includes/Private_Access.php
  tests/phpunit/tests/Database_Upgrader.php
  web-stories.php
Labels: Group: Presets, Type: Enhancement, cla: yes

#2604 Disable saving and previewing while uploading
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/autoSaveHandler/index.js
  assets/src/edit-story/components/autoSaveHandler/test/autoSaveHandler.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/test/buttons.js
Labels: Type: Enhancement, cla: yes

#2254 Improved error handling when adding links to elements
  assets/src/edit-story/components/panels/link/index.js
  assets/src/edit-story/components/panels/test/_utils.js
  assets/src/edit-story/components/panels/test/linkPanel.js
  assets/src/edit-story/utils/url.js
  includes/REST_API/Link_Controller.php
  tests/phpunit/tests/REST_API/Link_Controller.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#2556 Move Selection + change z-index to display selection on top of other layers.
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
Labels: Type: Enhancement, cla: yes

#2658 Hide elements tab
  assets/src/edit-story/components/library/libraryProvider.js
  includes/Story_Post_Type.php
Labels: cla: yes

#2554 Fix displaying whiteout in Text edit mode
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/elements/text/edit.js
Labels: cla: yes

#2645 Workspace: Add Tooltips to Carousel + Fix Icon Button display
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
Labels: Type: Enhancement, cla: yes

#2643 Make actions and filters unhookable
  includes/Plugin.php
  includes/namespace.php
Labels: Group: WordPress, Pod: WP & Infra, Skip Changelog, Type: Code Quality, cla: yes

#2666 Remove partial svg support
  includes/Media.php
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#2660 Enable editing and deleting media via new dropdown
  includes/Story_Post_Type.php
Labels: Group: Media, Type: Enhancement, cla: yes

#2621 Dashboard: Toaster UI
  assets/src/dashboard/components/alert/components.js
  assets/src/dashboard/components/alert/container.js
  assets/src/dashboard/components/alert/index.js
  assets/src/dashboard/components/alert/stories/index.js
  assets/src/dashboard/components/alert/test/index.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/toaster/index.js
  assets/src/dashboard/components/toaster/provider.js
  assets/src/dashboard/components/toaster/stories/index.js
  assets/src/dashboard/components/toaster/test/toaster.js
  assets/src/dashboard/components/toaster/test/useToastContext.js
  assets/src/dashboard/components/toaster/toaster.js
  assets/src/dashboard/components/toaster/useToastContext.js
  assets/src/dashboard/constants/components.js
  assets/src/dashboard/types.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2681 Karma: reduce flakes and better snapshots
  assets/src/edit-story/karma/_init.js
  karma/karma-puppeteer-launcher/index.cjs
  karma/karma-puppeteer-launcher/snapshot.cjs
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#2646 Dashboard: Display error messages in UI
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useTemplateApi.js
  assets/src/dashboard/app/index.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/reducer/templates.js
  assets/src/dashboard/app/reducer/test/stories.js
  assets/src/dashboard/app/reducer/test/templates.js
  assets/src/dashboard/app/views/index.js
  assets/src/dashboard/app/views/toaster/index.js
  assets/src/dashboard/app/views/toaster/stories/index.js
  assets/src/dashboard/components/alert/components.js
  assets/src/dashboard/components/alert/index.js
  assets/src/dashboard/components/alert/stories/index.js
  assets/src/dashboard/components/alert/test/index.js
  assets/src/dashboard/components/toaster/stories/index.js
  assets/src/dashboard/components/toaster/test/toaster.js
  assets/src/dashboard/components/toaster/toaster.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/types.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2682 Karma: reset the pointer between tests
  assets/src/edit-story/karma/_init.js
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#2460 Show link tooltip only on hover (first pass with old design)
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/elementLink/frame.js
  assets/src/edit-story/components/transform/transformProvider.js
Labels: cla: yes

#2574 Single blob shape + fix blob alignment
  assets/src/edit-story/masks/index.js
  assets/src/edit-story/migration/migrate.js
  assets/src/edit-story/migration/migrations/test/v0024_blobsToSingleBlob.js
  assets/src/edit-story/migration/migrations/v0024_blobsToSingleBlob.js
Labels: cla: yes

#2685 Dashboard: Update tooltip text for grid view
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/components/viewStyleBar/index.js
  assets/src/dashboard/components/viewStyleBar/stories/index.js
  assets/src/dashboard/components/viewStyleBar/test/viewStyleBar.js
  assets/src/dashboard/constants/index.js
Labels: Accessibility, Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#2313 Workspace: Search functionality inside new Font Picker
  assets/src/edit-story/components/fontPicker/fontPicker.js
  assets/src/edit-story/components/fontPicker/pickerContainer.js
  assets/src/edit-story/components/fontPicker/scrollList.js
  assets/src/edit-story/components/fontPicker/test/fontPicker.js
Labels: Group: Editing, Group: Fonts, P1, Pod: Dashboard & Templates, Pod: Workspace, Type: Enhancement, cla: yes

#2710 Workspace: Refactor useCanvas Selector
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/framesLayer.js
Labels: Skip Changelog, Type: Code Quality, cla: yes

#2686 Replace existing test containers for frames
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/karma/carousel.karma.js
  assets/src/edit-story/components/canvas/karma/keys.karma.js
  assets/src/edit-story/components/canvas/karma/multiSelectionMovable.karma.js
  assets/src/edit-story/components/canvas/karma/pageMenuActions.karma.js
  assets/src/edit-story/components/canvas/karma/selection.karma.js
  assets/src/edit-story/components/dropTargets/karma/order.karma.js
  assets/src/edit-story/components/richText/karma/itf.karma.js
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/elements/text/karma/frame.karma.js
  assets/src/edit-story/karma/fixture/containers/canvas.js
  assets/src/edit-story/karma/fixture/containers/container.js
Labels: cla: yes

#2712 Provide a separate type for TextOutputWithUnits to remove dev warnings
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/types.js
Labels: cla: yes

#2667 WordPress: add some filters to customize behavior
  includes/Dashboard.php
  includes/Story_Post_Type.php
  includes/Traits/Publisher.php
Labels: Group: WordPress, Type: Enhancement, cla: yes

#2620 Small UI refinements
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/inspector/inspectorTabs.js
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/panels/index.js
  assets/src/edit-story/components/panels/noSelection.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/handle.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/stylePreset/header.js
  assets/src/edit-story/components/panels/stylePreset/panel.js
  assets/src/edit-story/components/panels/stylePreset/presetGroup.js
  assets/src/edit-story/components/panels/stylePreset/presets.js
  assets/src/edit-story/components/panels/stylePreset/resize.js
  assets/src/edit-story/components/panels/stylePreset/stories/index.js
  assets/src/edit-story/components/panels/stylePreset/test/panel.js
Labels: Pod: Workspace, Type: Enhancement, cla: yes

#2748 request max stories possible per request
  assets/src/dashboard/constants/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#2751 Tag unit tests coverage
  .github/workflows/continuous-integration-unit-js.yml
Labels: cla: yes

#2722 Remove useMediaReducer folder and move reducer to media/local/reducer.js
  assets/src/edit-story/app/media/actions.js
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/types.js
  assets/src/edit-story/app/media/useMediaReducer.js
  assets/src/edit-story/app/media/useMediaReducer/index.js
Labels: cla: yes

#2715 Remove fetch.js and use window.fetch instead
  assets/src/edit-story/components/library/panes/media/media3p/api/apiFetcher.js
  assets/src/edit-story/components/library/panes/media/media3p/api/fetch.js
  assets/src/edit-story/components/library/panes/media/media3p/api/test/apiFetcher.js
Labels: cla: yes

#2730 Fix blob URLs after elements manipulation while uploading
  assets/src/edit-story/components/canvas/useUploadWithPreview.js
Labels: Type: Bug, cla: yes

#2711 Dashboard: Make sure story menus are always within confines of browser
  assets/src/dashboard/components/popoverMenu/popoverCard.js
  assets/src/dashboard/components/popoverMenu/stories/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Bug, cla: yes

#2698 Use WordPress date format for displaying dates
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/utils/getFormattedDisplayDate.js
  assets/src/dashboard/utils/test/getFormattedDisplayDate.js
  assets/src/edit-story/components/library/panes/media/mediaEditDialog.js
  includes/Dashboard.php
  includes/Story_Post_Type.php
  package-lock.json
  package.json
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Enhancement, cla: yes

#2746 Dashboard: Scroll to top of My Stories when Filter or View style is changed
  assets/src/dashboard/app/views/myStories/content/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, cla: yes

#2583 Karma: enable coverage reports
  .github/workflows/continuous-integration-karma.yml
  codecov.yml
  karma.config.cjs
  package-lock.json
  package.json
  webpack.config.test.cjs
Labels: Type: Infrastructure, cla: yes

#2734 Make dialog appearance more coherent
  assets/src/edit-story/components/dialog/index.js
  assets/src/edit-story/components/header/previewErrorDialog.js
  assets/src/edit-story/components/library/panes/media/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/mediaEditDialog.js
  assets/src/edit-story/theme.js
Labels: Group: Editing, Type: Enhancement, cla: yes

#2756 Dashboard: Refactor detail nav bar to reuse for stories
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/components/detailViewNavBar/index.js
  assets/src/dashboard/components/detailViewNavBar/stories/index.js
  assets/src/dashboard/components/detailViewNavBar/test/templateNavBar.js
  assets/src/dashboard/components/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Code Quality, cla: yes

#2725 Create the media3p reducer folder structure
  assets/src/edit-story/app/media/media3p/providerReducer.js
  assets/src/edit-story/app/media/media3p/reducer.js
  assets/src/edit-story/app/media/media3p/test/reducer.js
  assets/src/edit-story/app/media/useMediaReducer.js
Labels: cla: yes

#2764 Create media3p state provider structure
  assets/src/edit-story/app/media/context.js
  assets/src/edit-story/app/media/media3p/useContextValueProvider.js
  assets/src/edit-story/app/media/mediaProvider.js
  assets/src/edit-story/app/media/test/useMediaReducer.js
  assets/src/edit-story/app/media/useMedia.js
  assets/src/edit-story/app/media/useMediaReducer.js
  assets/src/edit-story/components/autoSaveHandler/test/autoSaveHandler.js
  assets/src/edit-story/components/header/test/buttons.js
  assets/src/edit-story/components/library/panes/media/stories/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/stories/mediaEditDialog.js
  assets/src/edit-story/components/library/panes/media/stories/mediaElement.js
  assets/src/edit-story/components/library/test/deleteDialog.js
  assets/src/edit-story/components/library/test/mediaEditDialog.js
Labels: cla: yes

#2803 Add useProviderContextValueProvider
  assets/src/edit-story/app/media/media3p/test/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/useProviderContextValueProvider.js
Labels: cla: yes

#2806 Remove excess 'External Dependencies' comment
  assets/src/edit-story/app/media/media3p/reducer.js
Labels: Skip Changelog, Type: Bug, cla: yes

#2744 Update icon for stories
  assets/src/story-embed-block/block/icon.svg
  assets/src/story-embed-block/block/index.js
  includes/Story_Post_Type.php
  package.json
  tests/phpunit/tests/Story_Post_Type.php
Labels: cla: yes

#2603 Dashboard: Applied design updates to Entertainment template
  assets/images/templates/entertainment/ent_page5_image1.jpg
  assets/images/templates/entertainment/ent_page8_image3.jpg
  assets/src/dashboard/templates/raw/entertainment.json
Labels: cla: yes

#2684 Dashboard: Applied design updates to Cooking template
  assets/images/templates/cooking/cooking_icon_logo.png
  assets/images/templates/cooking/cooking_page8_bg.jpg
  assets/images/templates/cooking/cooking_page8_image1.jpg
  assets/src/dashboard/templates/raw/cooking.json
Labels: cla: yes

#2812 Dashboard: Added new and updated images for templates
  assets/images/templates/beauty/beauty_page1_bg-alt.png
  assets/images/templates/beauty/beauty_page1_logo-generic.png
  assets/images/templates/diy/diy_page10_image1.jpg
  assets/images/templates/diy/diy_page10_image2.jpg
  assets/images/templates/diy/diy_page10_image3.jpg
  assets/images/templates/diy/diy_page7_bg.jpg
  assets/images/templates/fashion/fashion_page1_logo-generic.png
  assets/images/templates/fashion/fashion_page5_handbag-alt.png
  assets/images/templates/fitness/fitness_page1_bg-red.png
  assets/images/templates/fitness/fitness_page1_logo-generic.png
  assets/images/templates/fitness/fitness_page4_bg-red.png
  assets/images/templates/fitness/fitness_page5_bg-no-logo.png
  assets/images/templates/fitness/fitness_page6_watch-no-logo.png
  assets/images/templates/fitness/fitness_page7_bg-red.png
  assets/images/templates/fitness/fitness_page7_circle-border.png
  assets/images/templates/travel/travel_icon_logo.png
  assets/images/templates/wellbeing/wellbeing_icon_logo.png
  assets/images/templates/wellbeing/wellbeing_page10_image4.png
Labels: cla: yes

#2789 Dashboard: Update stories per request count to speed up time to first interaction
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/api/useUserApi.js
  assets/src/dashboard/constants/index.js
Labels: Group: Dashboard, Pod: Dashboard & Templates, Type: Performance, cla: yes
