Repository GoogleForCreators/web-stories-wp, pull requests merged in 2021-01, with the labels that each got.

#5740 Design Panel: Fix transparent color edit
  assets/src/edit-story/components/form/color/getPreviewStyle.js
  assets/src/edit-story/components/form/color/getPreviewText.js
  assets/src/edit-story/components/form/color/test/color.js
  assets/src/edit-story/components/form/color/test/getPreviewStyle.js
  assets/src/edit-story/components/form/color/test/getPreviewText.js
Labels: Group: Design Panel, Group: Patterns, Type: Bug, cla: yes

#5727 KSES: don’t strip page attachment URLs
  includes/KSES.php
  tests/phpunit/tests/KSES.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5739 Pre-Publish Panel: Prevent unintentional re-rendering
  assets/src/edit-story/components/inspector/inspectorProvider.js
  package-lock.json
  package.json
Labels: Group: Pre-Publish Panel, Type: Bug, Type: Performance, cla: yes

#5828 Panels: fix `aria-label` usage for `PanelTitle`
  assets/src/edit-story/components/inspector/prepublish/checklistTab.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/panel/simplePanel.js
Labels: Accessibility, Pod: WP & Infra, Type: Code Quality, cla: yes

#5832 Fix: document tab and font picker select
  assets/src/edit-story/components/inspector/inspectorProvider.js
  package-lock.json
  package.json
Labels: Group: Editing, P0, cla: yes

#5719 Use Moveable for Text Sets
  assets/src/edit-story/components/canvas/canvasElementDropzone.js
  assets/src/edit-story/components/canvas/test/getElementProperties.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/canvas/useInsertTextSet.js
  assets/src/edit-story/components/library/panes/shared/libraryMoveable.js
  assets/src/edit-story/components/library/panes/text/karma/textSets.cuj.karma.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/textSet.js
Labels: Group: Library, Pod: Prometheus, Type: Enhancement, cla: yes

#5784 Frontend: Add default social sharing configuration
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5695 Avoid duplicate poster generation
  assets/src/edit-story/app/media/local/useContextValueProvider.js
  assets/src/edit-story/components/canvas/useUploadWithPreview.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/mediaPicker/test/useMediaPicker.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/components/panels/design/poster/karma/videoPoster.karma.js
  bin/local-env/install-wordpress.sh
  tests/e2e/assets/example-1.jpg
  tests/e2e/assets/example-2.jpg
  tests/e2e/assets/example-3.png
  tests/e2e/assets/small-video-poster.jpg
  tests/e2e/specs/editor/media/insertWebMVideo.js
  tests/js/setup-globals.js
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#5762 Media: hide poster images in more places
  includes/Media.php
  includes/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/Media.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5827 Pre-Publish Checklist: Show Pre-Publish List Errors by Default.
  assets/src/edit-story/components/inspector/karma/inspectorTabs.karma.js
  assets/src/edit-story/components/inspector/prepublish/checklistTab.js
  assets/src/edit-story/karma/fixture/containers/checklistPanel.js
  assets/src/edit-story/karma/fixture/containers/inspector.js
Labels: Group: Pre-Publish Panel, Type: Enhancement, cla: yes

#5713 Apply Page Layouts
  assets/src/dashboard/app/views/exploreTemplates/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/savedTemplates/content/test/content.js
  assets/src/dashboard/app/views/savedTemplates/test/savedTemplates.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/storyAnimTool/index.js
  assets/src/dashboard/components/cardGallery/index.js
  assets/src/dashboard/components/cardGallery/test/cardGallery.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/index.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducer.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/index.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/replaceCurrentPage.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/test/replaceCurrentPage.js
  assets/src/edit-story/app/story/useStoryReducer/types.js
  assets/src/edit-story/components/library/panes/pageLayouts/confirmPageLayoutDialog.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayout.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayouts.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/pageLayouts/stories/confirmPageLayoutDialog.js
  assets/src/edit-story/components/library/panes/pageLayouts/test/pageLayoutsPane.js
  assets/src/edit-story/components/previewPage/index.js
  assets/src/edit-story/components/previewPage/previewErrorBoundary.js
  assets/src/edit-story/components/previewPage/previewPage.js
  assets/src/edit-story/components/previewPage/previewPageElements.js
  assets/src/edit-story/types.js
  assets/src/edit-story/utils/isDefaultPage.js
  assets/src/edit-story/utils/test/isDefaultPage.js
  includes/Story_Post_Type.php
Labels: Group: Library, Group: Page Layouts, Pod: Pea, Type: Enhancement, cla: yes

#5568 Prepublish Text Contrast Check
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/layout/layout.js
  assets/src/edit-story/app/prepublish/getPrepublishErrors.js
  assets/src/edit-story/app/prepublish/test/getPrepublishErrors.js
  assets/src/edit-story/app/prepublish/warning/accessibility.js
  assets/src/edit-story/app/prepublish/warning/index.js
  assets/src/edit-story/components/inspector/prepublish/prepublishChecklistProvider.js
  assets/src/edit-story/utils/getMediaBaseColor.js
Labels: Group: Pre-Publish Panel, Type: Enhancement, cla: yes

#5829 Add snapping for dragging elements from library
  assets/src/edit-story/components/library/panes/shared/libraryMoveable.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js
  assets/src/edit-story/components/library/test/shapes/shapePreview.js
  assets/src/edit-story/components/panels/design/link/karma/link.karma.js
Labels: Group: Library, Pod: Prometheus, Type: Enhancement, cla: yes

#5806 Animations: Added WAAPI polyfill to editor
  .storybook/preview.js
  assets/src/animation/components/provider.js
  assets/src/dashboard/index.js
Labels: Browser Issues, Group: Animations, Pod: Pea, Type: Bug, cla: yes

#5891 Display correct panels for 3rd-party gif background
  assets/src/edit-story/components/inspector/design/getDesignPanelsForSelection.js
Labels: Elements: GIF, Group: Design Panel, Pod: Prometheus, Type: Bug, cla: yes

#5850 Editor: Border Radius Support For Text Highlight Mode
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/elements/shared/index.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/output.js
  assets/src/edit-story/output/test/__snapshots__/textElement.js.snap
Labels: Elements: Text, Type: Enhancement, cla: yes

#5838 Page header adjustments
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/header/title.js
Labels: Group: Canvas, Group: Workspace, Type: Enhancement, cla: yes

#5839 Editor: Hidden Padding for Text Fill & Highlight Elements
  assets/src/edit-story/components/panels/design/textStyle/color.js
  assets/src/edit-story/components/panels/design/textStyle/padding.js
  assets/src/edit-story/components/panels/design/textStyle/test/textStyle.js
  assets/src/edit-story/components/panels/design/textStyle/utils.js
  assets/src/edit-story/components/panels/utils/metricsForTextPadding.js
  assets/src/edit-story/components/panels/utils/test/metricsForTextPadding.js
  assets/src/edit-story/constants.js
Labels: Elements: Text, Type: Enhancement, cla: yes

#5889 Page Layouts: Adds page type based naming and filtering
  assets/src/dashboard/templates/raw/beauty.json
  assets/src/dashboard/templates/raw/cooking.json
  assets/src/dashboard/templates/raw/diy.json
  assets/src/dashboard/templates/raw/entertainment.json
  assets/src/dashboard/templates/raw/fashion.json
  assets/src/dashboard/templates/raw/fitness.json
  assets/src/dashboard/templates/raw/travel.json
  assets/src/dashboard/templates/raw/wellbeing.json
  assets/src/dashboard/templates/test/raw.js
  assets/src/edit-story/components/library/panes/pageLayouts/constants.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayout.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/pageLayouts/test/pageLayoutsPane.js
Labels: Group: Page Layouts, Type: Enhancement, cla: yes

#5836 Editor/Pre-publish checklist: select offending elements from tab
  assets/src/edit-story/app/prepublish/guidance/test/text.js
  assets/src/edit-story/app/prepublish/guidance/text.js
  assets/src/edit-story/app/prepublish/types.js
  assets/src/edit-story/app/prepublish/warning/accessibility.js
  assets/src/edit-story/app/prepublish/warning/test/accessibility.js
  assets/src/edit-story/components/inspector/karma/prepublishSelect.karma.js
  assets/src/edit-story/components/inspector/prepublish/checklistTab.js
  assets/src/edit-story/components/inspector/stories/checklistTab.js
  assets/src/edit-story/karma/fixture/containers/checklistPanel.js
Labels: Group: Pre-Publish Panel, Pod: Pea, Type: Enhancement, cla: yes

#5853 Update Moveable when resizing window
  assets/src/edit-story/components/canvas/multiSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/useWindowResizeHandler.js
Labels: Group: Selection, Pod: Prometheus, Type: Bug, cla: yes

#5847 Address indexes as keys
  assets/src/edit-story/components/colorPicker/gradientLine.js
  assets/src/edit-story/components/keyboardShortcutsMenu/shortcutLabel.js
  assets/src/edit-story/components/panels/design/preset/presetGroup.js
Labels: Pod: Prometheus, Type: Enhancement, Type: Infrastructure, cla: yes

#5894 Fix z-index for media more button
  assets/src/edit-story/components/library/karma/mediaTab.karma.js
  assets/src/edit-story/components/library/panes/media/local/dropDownMenu.js
Labels: Group: Library, Group: Media, Type: Bug, cla: yes

#5892 Fix flaky tooltip test
  assets/src/edit-story/components/panels/design/link/karma/link.karma.js
Labels: Pod: Prometheus, Type: Bug, Type: Infrastructure, cla: yes

#5846 Use SAT for detecting lasso collision with elements
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/utils/createPolygon.js
  package-lock.json
  package.json
Labels: Group: Selection, Pod: Prometheus, Type: Bug, cla: yes

#5868 Improved check for is_amp_endpoint / amp_is_request not existing.
  includes/Story_Renderer/Embed.php
  includes/namespace.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Code Quality, cla: yes

#5916 Page Layouts: Translation Update To Page Titles
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js
Labels: Group: Page Layouts, Internationalization (I18N), Pod: Pea, Type: Code Quality, cla: yes

#5925 Documentation: Update Onboarding documentation
  docs/getting-started.md
  docs/local-environment.md
Labels: Type: Documentation, cla: yes

#5929 Fix index + keys for keyboard shortcuts.
  assets/src/edit-story/components/keyboardShortcutsMenu/shortcutLabel.js
Labels: Pod: Prometheus, Type: Bug, Type: Code Quality, cla: yes

#5930 Extend ESLint ruleset
  .eslintrc
  __mocks__/fs.js
  assets/src/animation/components/test/provider.js
  assets/src/dashboard/app/reducer/stories.js
  assets/src/dashboard/app/views/editorSettings/googleAdManager/test/googleAdManager.js
  assets/src/dashboard/app/views/editorSettings/googleAdSense/test/googleAdSense.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/test/googleAnalytics.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js
  assets/src/edit-story/app/prepublish/getPrepublishErrors.js
  assets/src/edit-story/app/prepublish/warning/accessibility.js
  assets/src/edit-story/components/autoSaveHandler/index.js
  assets/src/edit-story/components/canvas/karma/grideView.karma.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/useCanvasCopyPaste.js
  assets/src/edit-story/components/devTools/devTools.js
  assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  assets/src/edit-story/components/library/panes/pageLayouts/test/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/shared/pillGroup/useHandleRowVisibility.js
  assets/src/edit-story/components/library/test/mediaEditDialog.js
  assets/src/edit-story/components/panels/design/animation/effectInput.js
  assets/src/edit-story/components/panels/design/textStyle/getClosestFontWeight.js
  assets/src/edit-story/components/panels/design/textStyle/karma/textStyle.other.karma.js
  assets/src/edit-story/components/panels/panel/shared/test/handle.js
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/elements/text/karma/edit.karma.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/integrations/wordpress/components/metaBoxes/index.js
Labels: Pod: WP & Infra, Type: Code Quality, cla: yes

#5898 Simplify usage of assets CDN URL
  bin/commander.js
  bin/utils/index.js
  bin/utils/test/updateCdnUrl.js
  bin/utils/updateCdnUrl.js
  docs/README.md
  docs/cdn.md
  package.json
  web-stories.php
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5919 Frontend: Improve Twitter Card markup
  includes/Discovery.php
  tests/phpunit/tests/Discovery.php
Labels: Group: Discoverability, Type: Enhancement, cla: yes

#5871 It's 2021
  .eslintrc
Labels: Skip Changelog, cla: yes

#5852 Fix being able to add duplicate color presets
  assets/src/edit-story/components/panels/design/preset/test/utils.js
  assets/src/edit-story/components/panels/design/preset/utils.js
Labels: Group: Saved Colors, Group: Saved Styles, Pod: Prometheus, Type: Bug, cla: yes

#5917 Replace page layout images with image placeholders
  assets/images/editor/grid-placeholder.png
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/api/getAllPageLayouts.js
  assets/src/edit-story/app/api/test/apiProvider.js
  assets/src/edit-story/app/api/test/getAllPageLayouts.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/pageLayouts/test/pageLayoutsPane.js
  includes/Story_Post_Type.php
Labels: Group: Page Layouts, Type: Enhancement, cla: yes

#5922 Page Layouts: Fix repeating dialog
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayout.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/pageLayouts/test/pageLayoutsPane.js
Labels: Accessibility, Group: Page Layouts, Type: Bug, cla: yes

#5924 Prepublish checklist - Add an underline and title to clickable elements
  assets/src/edit-story/components/inspector/karma/prepublishSelect.karma.js
  assets/src/edit-story/components/inspector/prepublish/checklistTab.js
Labels: Bug Bash 1.3.1, Group: Pre-Publish Panel, Pod: Pea, cla: yes

#5928 Pre-Publish: Use threshold for cover image ratio comparison.
  assets/src/edit-story/app/prepublish/error/metadata.js
  assets/src/edit-story/app/prepublish/error/test/metadata.js
  assets/src/edit-story/utils/greatestCommonDivisor.js
  assets/src/edit-story/utils/test/greatestCommonDivisor.js
Labels: Group: Pre-Publish Panel, Type: Bug, cla: yes

#5934 Bug: Extra safety measures in text pane
  assets/src/edit-story/components/library/panes/text/textSets/textSets.js
Labels: Group: Text Sets, Type: Enhancement, cla: yes

#5866 Update npm cache configuration for workflows
  .github/workflows/continuous-integration-build.yml
  .github/workflows/continuous-integration-bundle-size.yml
  .github/workflows/continuous-integration-e2e.yml
  .github/workflows/continuous-integration-gh-pages.yml
  .github/workflows/continuous-integration-karma-dashboard.yml
  .github/workflows/continuous-integration-karma-edit-story.yml
  .github/workflows/continuous-integration-lint-css.yml
  .github/workflows/continuous-integration-lint-js.yml
  .github/workflows/continuous-integration-lint-md.yml
  .github/workflows/continuous-integration-unit-js.yml
  .github/workflows/update-google-fonts.yml
  .github/workflows/update-templates.yml
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#5856 Dashboard: Settings Support GA4 Measurement ID for Analytics
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/utils/test/validateGoogleAnalyticsIdFormat.js
  assets/src/dashboard/utils/validateGoogleAnalyticsIdFormat.js
  tests/e2e/utils/setAnalyticsCode.js
Labels: Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#5907 Text Sets: Update rogue text set to use border instead of shapes
  assets/src/edit-story/components/library/panes/text/textSets/raw/cover.json
Labels: Group: Text Sets, Type: Enhancement, cla: yes

#5906 Editor: Update Text Presets to Latest Designs
  assets/src/edit-story/components/library/panes/text/karma/textPane.karma.js
  assets/src/edit-story/components/library/panes/text/textPresets.js
Labels: Group: Text Sets, Type: Enhancement, cla: yes

#5932 Design Panel: replace purples with blues in Animation panel
  assets/src/edit-story/components/panels/design/animation/directionRadioInput.js
  assets/src/edit-story/components/panels/design/animation/effectChooser.js
Labels: Group: Animations, Type: Enhancement, cla: yes

#5927 Pre-Publish Checklist: Remove page icon
  assets/src/edit-story/components/inspector/prepublish/checklistTab.js
Labels: Group: Pre-Publish Panel, Pod: Pea, Type: Bug, cla: yes

#5899 Templates: Update Some Images to Shapes
  assets/src/animation/parts/move/index.js
  assets/src/dashboard/templates/raw/beauty.json
  assets/src/dashboard/templates/raw/diy.json
  assets/src/dashboard/templates/raw/entertainment.json
  assets/src/dashboard/templates/raw/fashion.json
  assets/src/dashboard/templates/raw/travel.json
  assets/src/dashboard/templates/raw/wellbeing.json
  assets/src/edit-story/masks/index.js
Labels: Group: Templates, Type: Enhancement, cla: yes

#5931 CDN: Remove some now unnneeded template assets
  public/static/main/images/templates/beauty/beauty_page_4_heart.png
  public/static/main/images/templates/diy/diy_icon_fb.png
  public/static/main/images/templates/diy/diy_icon_insta.png
  public/static/main/images/templates/diy/diy_icon_tw.png
  public/static/main/images/templates/diy/diy_icon_yt.png
  public/static/main/images/templates/entertainment/ent_icon_musicnote.png
  public/static/main/images/templates/entertainment/ent_icon_white_star.png
  public/static/main/images/templates/entertainment/ent_icon_wraparound.png
  public/static/main/images/templates/fashion/fashion_page2_arrow.png
  public/static/main/images/templates/fashion/fashion_page5_arrow.png
  public/static/main/images/templates/travel/travel_icon_fb.png
  public/static/main/images/templates/travel/travel_icon_insta.png
  public/static/main/images/templates/travel/travel_icon_tw.png
  public/static/main/images/templates/travel/travel_icon_yt.png
  public/static/main/images/templates/wellbeing/wellbeing_icon_arrow_head_dark.png
  public/static/main/images/templates/wellbeing/wellbeing_icon_arrow_head_light.png
  public/static/main/images/templates/wellbeing/wellbeing_icon_fb.png
  public/static/main/images/templates/wellbeing/wellbeing_icon_insta.png
  public/static/main/images/templates/wellbeing/wellbeing_icon_twitter.png
  public/static/main/images/templates/wellbeing/wellbeing_icon_youtube.png
Labels: Pod: WP & Infra, Skip Changelog, Website, cla: yes

#5938 Remove assets after every e2e teset.
  tests/e2e/specs/editor/media/insertMediaFromDialog.js
  tests/e2e/specs/editor/media/insertMediaFromLibrary.js
  tests/e2e/specs/editor/media/insertMovVideo.js
  tests/e2e/specs/editor/media/svg.js
  tests/e2e/utils/uploadFile.js
Labels: cla: yes

#5939 Telemetry: Let links open in new tab
  assets/src/tracking/trackClick.js
Labels: Group: Telemetry, Type: Enhancement, cla: yes

#5933 Settings: Improve Site Kit detection logic
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/stories/index.js
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/test/googleAnalytics.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/karma/fixture.js
  includes/Dashboard.php
Labels: Group: Analytics, Group: Settings, Type: Enhancement, cla: yes

#5959 Delete user meta on plugin uninstall
  includes/uninstall.php
  tests/phpunit/tests/Uninstall.php
  uninstall.php
Labels: cla: yes

#5854 Dates: Fix timezone inconsistencies
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/test/useStoryApi.js
  assets/src/dashboard/app/serializers/savedTemplates.js
  assets/src/dashboard/app/serializers/stories.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/date/getRelativeDisplayDate.js
  assets/src/date/index.js
  assets/src/date/test/getRelativeDisplayDate.js
  assets/src/edit-story/app/story/effects/test/useLoadStory.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/header/buttons/publish.js
  assets/src/edit-story/components/header/test/buttons.js
Labels: Group: Dashboard, Group: Dates, Group: Workspace, Pod: WP & Infra, Type: Bug, cla: yes

#5867 Design Panel: Color presets redesign
  assets/src/edit-story/components/panels/design/preset/colorAdd.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorPreset.js
  assets/src/edit-story/components/panels/design/preset/header.js
  assets/src/edit-story/components/panels/design/preset/presetGroup.js
  assets/src/edit-story/components/panels/design/preset/presetPanel.js
  assets/src/edit-story/components/panels/design/preset/presets.js
  assets/src/edit-story/components/panels/design/preset/stylePreset/stylePreset.js
  assets/src/edit-story/components/panels/design/preset/test/colorPresetActions.js
  assets/src/edit-story/components/panels/design/preset/test/colorPresetPanel.js
  assets/src/edit-story/components/panels/design/preset/test/stylePresetPanel.js
  assets/src/edit-story/components/panels/design/preset/test/utils.js
  assets/src/edit-story/components/panels/design/preset/utils.js
  assets/src/edit-story/constants/index.js
  assets/src/edit-story/icons/color_add.svg
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/remove.svg
Labels: Group: Design Panel, Group: Saved Colors, Group: Saved Styles, Pod: Prometheus, cla: yes

#5973 Editor FTUE: Quick tips flag
  includes/Experiments.php
Labels: PHP, Skip Changelog, Type: Enhancement, cla: yes

#5976 Page Layouts: Enable by default
  assets/src/dashboard/templates/getTemplates.js
  includes/Experiments.php
Labels: Group: Page Layouts, Pod: Pea, Type: Enhancement, cla: yes

#5975 Prepare 1.3.0 release
  readme.txt
  web-stories.php
Labels: Release, cla: yes

#5979 Page Layouts: Only run `isDefaultPage` if `currentPage` is not null
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayouts.js
Labels: Group: Page Layouts, Type: Bug, cla: yes

#5970 FTUE: REST API endpoint for tips
  includes/Plugin.php
  includes/Tracking.php
  includes/User_Preferences.php
  includes/uninstall.php
  tests/phpunit/tests/Tracking.php
  tests/phpunit/tests/Uninstall.php
  tests/phpunit/tests/User_Preferences.php
Labels: Group: WordPress, PHP, Pod: WP & Infra, Type: Infrastructure, cla: yes

#5849 E2E Tests: Improve media-related tests
  bin/local-env/install-wordpress.sh
  tests/e2e/specs/editor/media/insertMediaFromDialog.js
  tests/e2e/specs/editor/media/insertMediaFromLibrary.js
  tests/e2e/specs/editor/media/insertMovVideo.js
  tests/e2e/specs/editor/media/insertWebMVideo.js
  tests/e2e/specs/editor/media/svg.js
  tests/e2e/utils/deleteMedia.js
  tests/e2e/utils/index.js
  tests/e2e/utils/uploadFile.js
  tests/e2e/utils/uploadMedia.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5967 Editor: ensure global variables are defined
  includes/Story_Post_Type.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5986 Text Sets: Automate Migration
  .github/workflows/update-templates.yml
  bin/commander.js
  package.json
Labels: Group: Text Sets, Pod: WP & Infra, Type: Infrastructure, cla: yes

#5994 Video Optimization: Add media source
  includes/Database_Upgrader.php
  includes/Media.php
  tests/phpunit/tests/Database_Upgrader.php
  web-stories.php
Labels: Group: Transcoding, Pod: WP & Infra, cla: yes

#5995 Update enshrined/svg-sanitize to 0.14.0.
  composer.json
  composer.lock
Labels: Dependencies, PHP, cla: yes

#5997 Frontend: Add support for WordPress 5.7 Robots API
  includes/Discovery.php
  phpstan.neon.dist
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5942 Only show design safe zone if actually dragging
  assets/src/edit-story/components/canvas/utils/useSnapping.js
Labels: Group: Selection, Pod: Prometheus, Type: Enhancement, cla: yes

#6005 Templates: add missing i18n
  assets/src/dashboard/templates/index.js
Labels: Group: Templates, Internationalization (I18N), Type: Enhancement, cla: yes

#5936 Bug: wrap all local storage setting in try catch
  assets/src/dashboard/app/views/shared/useTelemetryOptIn.js
  assets/src/edit-story/utils/localStore.js
Labels: Browser Issues, Group: Design Panel, Type: Enhancement, cla: yes

#6013 Composer: Fix PHP-CSS-Parser patching
  composer.json
  composer.lock
  web-stories.php
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#5960 Shapes: Fix drop-targeting for flipped elements
  assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/masks/frame.js
Labels: Elements: Shape, Group: Masking, Pod: Prometheus, Type: Bug, cla: yes

#5946 Design System: Add Checkbox component
  assets/src/design-system/components/checkbox/index.js
  assets/src/design-system/components/checkbox/stories/index.js
  assets/src/design-system/components/checkbox/test/index.js
  assets/src/design-system/components/index.js
  assets/src/design-system/theme/colors.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#6009 Exclude stories from WordPress search results
  includes/Story_Post_Type.php
Labels: Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#6054 Bookend: Remove Facebook sharing option
  includes/Story_Renderer/HTML.php
  tests/phpunit/tests/Story_Renderer/HTML.php
Labels: AMP Output, Pod: WP & Infra, Type: Bug, Type: Infrastructure, cla: yes

#6016 Remove Page Layouts feature flag
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/karma/fixture/fixture.js
  includes/Experiments.php
Labels: Group: Page Layouts, Type: Code Quality, cla: yes

#6017 Media: Fix conflict with Safe SVG plugin
  includes/SVG.php
Labels: Group: Media, Group: WordPress, Pod: WP & Infra, cla: yes

#6001 Update PR template to include checklist
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-checklist.yml
Labels: Skip Changelog, Type: Infrastructure, cla: yes

#6038 Telemetry: Send data to new GA4 property
  assets/src/tracking/enableTracking.js
  assets/src/tracking/shared.js
  includes/Tracking.php
  tests/phpunit/tests/Tracking.php
Labels: Group: Telemetry, Pod: WP & Infra, Type: Enhancement, cla: yes

#5798 Video Optimization: Implement foundation for client-side video transcoding
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/media/utils/useTranscodeVideo.js
  assets/src/edit-story/app/uploader/test/useUploader.js
  assets/src/edit-story/app/uploader/useUploader.js
  includes/Experiments.php
  includes/Story_Post_Type.php
  package-lock.json
  package.json
Labels: Elements: Video, Group: Media, Type: Performance, cla: yes

#6060 Analytics: Improve Site Kit detection to check if its tracking snippet is inserted
  includes/Integrations/Site_Kit.php
  tests/e2e/plugins/site-kit-mock.php
  tests/phpunit/tests/Integrations/Site_Kit.php
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#6064 Update lock file
  package-lock.json
Labels: Dependencies, Pod: WP & Infra, cla: yes

#6063 E2E Tests: Fix flakey Publishing Flow test
  tests/e2e/specs/editor/publishingFlow.js
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes

#5943 Telemetry: Implement User Timings Tracking
  assets/src/dashboard/templates/getTemplates.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/text/textSets/utils.js
  assets/src/tracking/getTimeTracker.js
  assets/src/tracking/index.js
  assets/src/tracking/test/getTimeTracker.js
Labels: Group: Telemetry, Type: Enhancement, cla: yes

#5870 Telemetry: Improve error tracking
  assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/errorBoundary/index.js
  assets/src/edit-story/components/library/panes/media/local/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js
  assets/src/edit-story/utils/getMediaBaseColor.js
  assets/src/edit-story/utils/localStore.js
  assets/src/tracking/enableTracking.js
  assets/src/tracking/index.js
  assets/src/tracking/initializeErrorReporting.js
  assets/src/tracking/initializeTracking.js
  assets/src/tracking/shared.js
  assets/src/tracking/test/trackError.js
  assets/src/tracking/trackError.js
  includes/Tracking.php
  tests/phpunit/tests/Tracking.php
Labels: Group: Telemetry, Type: Enhancement, cla: yes

#6072 Fix ffmpeg chunk name
  assets/src/edit-story/app/media/utils/useTranscodeVideo.js
Labels: Pod: WP & Infra, Type: Code Quality, cla: yes

#5679 Stabilize Custom Meta Boxes Support
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/story/effects/test/useSaveMetaBoxes.js
  assets/src/edit-story/app/story/effects/useSaveMetaBoxes.js
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/carousel/carouselMenu.js
  assets/src/edit-story/components/header/buttons/update.js
  assets/src/edit-story/components/layout/index.js
  assets/src/edit-story/editorApp.js
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/widgets.svg
  assets/src/edit-story/integrations/wordpress/metaBoxes/context.js
  assets/src/edit-story/integrations/wordpress/metaBoxes/index.js
  assets/src/edit-story/integrations/wordpress/metaBoxes/metaBoxesArea.js
  assets/src/edit-story/integrations/wordpress/metaBoxes/metaBoxesProvider.js
  assets/src/edit-story/integrations/wordpress/metaBoxes/useMetaBoxes.js
  includes/Experiments.php
  includes/Meta_Boxes.php
  tests/e2e/specs/editor/metaBoxes.js
Labels: Group: Integration, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#5920 Dashboard: Fix WordPress Admin Menu Scroll. Remove Squish for Dashboard Header.
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/editorSettings/index.js
  assets/src/dashboard/app/views/exploreTemplates/header/index.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/savedTemplates/header/index.js
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/dashboard/components/layout/fixed.js
  assets/src/dashboard/components/layout/index.js
  assets/src/dashboard/components/layout/provider.js
  assets/src/dashboard/components/layout/scrollable.js
  assets/src/dashboard/components/layout/squishable.js
  assets/src/dashboard/components/layout/test/useLayoutContext.js
  assets/src/dashboard/components/layout/useAddSquishVar.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/scrollToTop/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/style.css
  assets/src/dashboard/utils/cssLerp.js
Labels: Group: Dashboard, Type: Bug, Type: UX Quality, cla: yes

#5968 Enable clicking through masked elements' empty frame area
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/karma/selection.karma.js
  assets/src/edit-story/masks/display.js
  assets/src/edit-story/masks/frame.js
Labels: Elements, Group: Canvas, Pod: Prometheus, Type: Enhancement, cla: yes

#5944 Pre-publish Checklist: Update strings
  assets/src/edit-story/app/prepublish/constants.js
  assets/src/edit-story/app/prepublish/error/test/metadata.js
  assets/src/edit-story/app/prepublish/guidance/test/general.js
  assets/src/edit-story/app/prepublish/guidance/test/media.js
  assets/src/edit-story/app/prepublish/test/__snapshots__/getPrepublishErrors.js.snap
  assets/src/edit-story/app/prepublish/test/getPrepublishErrors.js
Labels: Group: Pre-Publish Panel, Internationalization (I18N), Type: Enhancement, cla: yes

#6091 Video Optimization: User Setting in REST API
  includes/User_Preferences.php
  tests/phpunit/tests/User_Preferences.php
Labels: Group: Video Optimization, Group: WordPress, PHP, Pod: WP & Infra, Type: Infrastructure, cla: yes

#6090 Infrastructure: Allow specifying PHP version for local dev environment
  bin/local-env/docker-compose.yml
  docs/environment-variables.md
  docs/local-environment.md
Labels: Pod: WP & Infra, Skip Changelog, Type: Infrastructure, cla: yes
