Repository GoogleForCreators/web-stories-wp, pull requests merged in 2021-03, with the labels that each got.

#6486 Pre-Publish Checklist: Fix TypeError: `backgroundColor` is not iterable
  assets/src/edit-story/app/prepublish/getPrepublishErrors.js
  assets/src/edit-story/app/prepublish/guidance/media.js
  assets/src/edit-story/app/prepublish/warning/accessibility.js
Labels: Group: Pre-Publish Panel, P1, Pod: Pea, Type: Bug, cla: yes

#6507 Help Center: Make Help Button `Tertiary`
  assets/src/edit-story/components/helpCenter/toggle/index.js
Labels: Group: FTUE, Pod: Pea, Type: Enhancement, cla: yes

#6508 Help Center: Update Link Text
  assets/src/edit-story/components/helpCenter/constants.js
Labels: Group: FTUE, Pod: Pea, Type: Enhancement, cla: yes

#6417 Dashboard: Update filter bar to use Design System
  assets/src/dashboard/app/views/exploreTemplates/header/test/header.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/myStories/header/test/header.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/savedTemplates/header/test/header.js
  assets/src/dashboard/app/views/savedTemplates/test/savedTemplates.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/dashboard/components/viewStyleBar/index.js
  assets/src/dashboard/constants/stories.js
  assets/src/dashboard/constants/templates.js
  assets/src/dashboard/karma/fixture.js
  assets/src/dashboard/utils/test/useDashboardResultsLabel.js
  assets/src/dashboard/utils/useDashboardResultsLabel.js
  assets/src/design-system/components/dropDown/index.js
  assets/src/design-system/components/dropDown/select/components.js
  assets/src/design-system/components/dropDown/select/index.js
  assets/src/design-system/components/menu/list/components.js
  assets/src/design-system/components/menu/list/defaultListItem.js
  assets/src/design-system/components/menu/menu.js
  assets/src/design-system/components/popup/index.js
  packages/e2e-tests/src/specs/dashboard/documentTitle.js
  packages/e2e-tests/src/specs/dashboard/templates/useTemplate.js
  packages/e2e-tests/src/specs/wordpress/adminMenu.js
  packages/i18n/src/translateWithMarkup.js
Labels: Package: Dashboard, Package: Design System, Pod: Pea, cla: yes

#6509 Help Center: Fix Arrow/All Tips style
  assets/src/edit-story/components/helpCenter/navigator/bottomNavigation.js
Labels: Group: FTUE, Pod: Pea, Type: Enhancement, cla: yes

#6484 Design System: Typography updates from Figma
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/design-system/components/banner/index.js
  assets/src/design-system/components/banner/stories/index.js
  assets/src/design-system/components/typography/link/index.js
  assets/src/design-system/components/typography/text/index.js
  assets/src/design-system/components/typography/text/stories/index.js
  assets/src/design-system/theme/typography.js
Labels: Group: Dashboard, Group: Design System, Pod: Pea, cla: yes

#6420 Library: only render tabs when active
  assets/src/edit-story/components/library/libraryLayout.js
  assets/src/edit-story/components/library/libraryProvider.js
  assets/src/edit-story/components/library/test/useLibrary.js
Labels: Group: Library, Pod: Pea, Type: Performance, cla: yes

#6565 Masks: avoid passing flip prop down to div element
  assets/src/edit-story/masks/frame.js
Labels: Group: Canvas, Group: Masking, Type: Code Quality, cla: yes

#6547 Workspace: Redesign scrollbars
  assets/src/dashboard/theme.js
  assets/src/design-system/components/menu/components.js
  assets/src/design-system/components/popup/index.js
  assets/src/design-system/theme/global/index.js
  assets/src/design-system/theme/global/overrideScrollbarCSS.js
  assets/src/design-system/theme/helpers/index.js
  assets/src/design-system/theme/helpers/scrollbar.js
  assets/src/design-system/theme/stories/index.js
  assets/src/edit-story/components/carousel/carouselList.js
  assets/src/edit-story/components/form/advancedDropDown/list/styled.js
  assets/src/edit-story/components/panels/design/animation/effectChooser.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorPresetActions.js
  assets/src/edit-story/components/popup/index.js
  assets/src/edit-story/constants/index.js
  assets/src/edit-story/theme.js
Labels: Group: Workspace, Pod: Pea, Type: Enhancement, cla: yes

#6561 Redesign: Media Input
  assets/src/design-system/components/index.js
  assets/src/design-system/components/mediaInput/constants.js
  assets/src/design-system/components/mediaInput/index.js
  assets/src/design-system/components/mediaInput/landscape.svg
  assets/src/design-system/components/mediaInput/stories/image.jpg
  assets/src/design-system/components/mediaInput/stories/index.js
  assets/src/design-system/storybookUtils/sampleData.js
Labels: Group: Design Panel, Group: Media, Type: Enhancement, cla: yes

#6546 Performance: Split editor/dashboard bundles into chunks with webpack
  .github/workflows/continuous-integration-bundle-size.yml
  docs/environment-variables.md
  includes/Traits/Assets.php
  package-lock.json
  package.json
  tests/phpunit/tests/Dashboard.php
  tests/phpunit/tests/Story_Post_Type.php
  webpack.config.cjs
  webpack.config.test.cjs
Labels: Type: Performance, cla: yes

#6575 Make Carousel into a package.
  package-lock.json
  package.json
  packages/stories-carousel/README.md
  packages/stories-carousel/package.json
  packages/stories-carousel/src/index.js
  webpack.config.cjs
Labels: cla: yes

#6576 Make lightbox in a package
  package-lock.json
  package.json
  packages/stories-lightbox/README.md
  packages/stories-lightbox/package.json
  packages/stories-lightbox/src/index.js
  packages/stories-lightbox/src/web-stories-lightbox.js
  webpack.config.cjs
Labels: cla: yes

#6577 Make widget into a package.
  package-lock.json
  package.json
  packages/widget/README.md
  packages/widget/package.json
  packages/widget/src/stories-widget.js
  webpack.config.cjs
Labels: cla: yes

#6578 Make tinymce into a package.
  .eslintrc
  package-lock.json
  package.json
  packages/tinymce-button/README.md
  packages/tinymce-button/package.json
  packages/tinymce-button/src/components/Modal.js
  packages/tinymce-button/src/components/controls/Toggle.js
  packages/tinymce-button/src/components/test/Modal.js
  packages/tinymce-button/src/components/test/__snapshots__/Modal.js.snap
  packages/tinymce-button/src/components/test/controls/Toggle.js
  packages/tinymce-button/src/components/test/controls/__snapshots__/Toggle.js.snap
  packages/tinymce-button/src/containers/Modal.js
  packages/tinymce-button/src/index.js
  packages/tinymce-button/src/store/actions.js
  packages/tinymce-button/src/store/default.js
  packages/tinymce-button/src/store/index.js
  packages/tinymce-button/src/store/name.js
  packages/tinymce-button/src/store/reducers.js
  packages/tinymce-button/src/store/selectors.js
  packages/tinymce-button/src/store/test/actions.js
  packages/tinymce-button/src/store/test/default.js
  packages/tinymce-button/src/store/test/name.js
  packages/tinymce-button/src/store/test/selectors.js
  packages/tinymce-button/src/utils/globals.js
  packages/tinymce-button/src/utils/index.js
  packages/tinymce-button/src/utils/test/index.js
  webpack.config.cjs
Labels: cla: yes

#6583 Change is_amp to trait.
  includes/Stories_Renderer/Carousel_Renderer.php
  includes/Stories_Renderer/Renderer.php
  includes/Story_Renderer/Embed.php
  includes/Traits/Amp.php
  includes/namespace.php
Labels: cla: yes

#6534 Redesign: Generic panel
  assets/src/design-system/theme/colors.js
  assets/src/design-system/theme/constants/typography.js
  assets/src/design-system/theme/typography.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/panels/panel/shared/title.js
  assets/src/edit-story/components/panels/panel/test/simplePanel.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6569 Add chip component to design system
  assets/src/design-system/components/chip/index.js
  assets/src/design-system/components/chip/stories/index.js
  assets/src/design-system/components/chip/test/index.js
  assets/src/design-system/components/index.js
Labels: cla: yes

#6567 Bugfix: Fix RTL toggle
  assets/src/design-system/components/toggle/index.js
Labels: Group: Design System, Group: Workspace, Internationalization (I18N), Pod: Pea, Type: Bug, cla: yes

#6594 Redesign: Fixed border colors
  assets/src/design-system/theme/colors.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6589 Fix various nits in #6543
  assets/images/widget/carousel-icon.png
  assets/src/web-stories-block/block/api/apiProvider.js
  assets/src/web-stories-block/block/api/useStoryApi.js
  assets/src/web-stories-block/block/api/useUserApi.js
  assets/src/web-stories-block/block/block-types/latest-stories/edit.js
  assets/src/web-stories-block/block/block-types/selected-stories/edit.js
  assets/src/web-stories-block/block/block-types/selected-stories/selectStories.js
  assets/src/web-stories-block/block/block-types/selected-stories/storyPicker.js
  assets/src/web-stories-block/block/components/typeaheadAuthorSearch.js
  assets/src/web-stories-block/block/deprecated.js
  assets/src/web-stories-block/block/edit.js
  assets/src/web-stories-block/block/index.js
  assets/src/web-stories-block/block/storiesFilters.js
  assets/src/web-stories-block/block/transforms.js
  assets/src/web-stories-block/css/core-themes/twentyeleven.css
  assets/src/web-stories-block/css/core-themes/twentyfifteen.css
  assets/src/web-stories-block/css/core-themes/twentyfourteen.css
  assets/src/web-stories-block/css/core-themes/twentyseventeen.css
  assets/src/web-stories-block/css/core-themes/twentysixteen.css
  assets/src/web-stories-block/css/core-themes/twentyten.css
  assets/src/web-stories-block/css/core-themes/twentytwelve.css
  assets/src/web-stories-block/css/core-themes/twentytwenty.css
  assets/src/web-stories-block/css/core-themes/twentytwentyone.css
  assets/src/web-stories-block/css/views/carousel.css
  assets/src/web-stories-block/icons/carousel-arrow-next.svg
  assets/src/web-stories-block/icons/carousel-arrow-prev.svg
  assets/src/web-stories-block/icons/carousel-arrow.svg
  assets/src/web-stories-block/index.js
  includes/Model/Story.php
  includes/Plugin.php
  includes/Stories_Renderer/Renderer.php
  includes/TinyMCE.php
  includes/Traits/Stories_Script_Data.php
  includes/Widgets/Stories.php
  package-lock.json
  package.json
  packages/date/package.json
  packages/tinymce-button/src/components/Modal.js
  packages/tinymce-button/src/components/controls/Toggle.js
  packages/tinymce-button/src/index.js
  packages/widget/package.json
  packages/widget/src/index.js
  tests/phpunit/tests/Dashboard.php
  webpack.config.cjs
Labels: Type: Enhancement, cla: yes

#6574 Redesign: Link Panel
  assets/src/design-system/components/input/index.js
  assets/src/design-system/components/mediaInput/index.js
  assets/src/design-system/components/mediaInput/stories/index.js
  assets/src/edit-story/components/form/link.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/panels/design/link/karma/link.karma.js
  assets/src/edit-story/components/panels/design/link/link.js
  assets/src/edit-story/components/panels/design/poster/karma/videoPoster.karma.js
  assets/src/edit-story/components/panels/design/poster/test/videoPoster.js
  assets/src/edit-story/components/panels/design/poster/videoPoster.js
  assets/src/edit-story/components/panels/document/publish/publish.js
  assets/src/edit-story/karma/fixture/containers/designPanel/link.js
  assets/src/edit-story/karma/fixture/containers/designPanel/videoPoster.js
Labels: Group: Design Panel, Group: Links, Pod: Prometheus, Type: Enhancement, cla: yes

#6562 Settings: revert support for GA4 measurement IDs
  assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js
  assets/src/dashboard/utils/test/validateGoogleAnalyticsIdFormat.js
  assets/src/dashboard/utils/validateGoogleAnalyticsIdFormat.js
Labels: Group: Analytics, Group: Dashboard, Group: Settings, Type: Enhancement, cla: yes

#6602 Storybook: add RTL addon
  .storybook/main.cjs
  .storybook/preview.js
  package-lock.json
  package.json
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6542 KSES: fix HTML attributes inadvertently being removed
  includes/KSES.php
  tests/phpunit/tests/KSES.php
Labels: Group: WordPress, P1, Pod: WP & Infra, Type: Bug, cla: yes

#6591 Redesign: Update filter panel
  assets/src/edit-story/components/canvas/karma/backgroundCopyPaste.karma.js
  assets/src/edit-story/components/inspector/design/getDesignPanelsForSelection.js
  assets/src/edit-story/components/panels/design/filter/convertOverlay.js
  assets/src/edit-story/components/panels/design/filter/filter.js
  assets/src/edit-story/components/panels/design/filter/index.js
  assets/src/edit-story/components/panels/design/filter/karma/filter.karma.js
  assets/src/edit-story/components/panels/design/filter/test/convertOverlay.js
  assets/src/edit-story/components/panels/design/index.js
  assets/src/edit-story/components/panels/design/types.js
  assets/src/edit-story/karma/fixture/containers/designPanel/filter.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/edit-story/utils/backgroundOverlay.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6603 Video Optimization: Improve default ffmpeg configuration
  assets/src/edit-story/app/media/utils/useTranscodeVideo.js
Labels: Group: Media, Group: Video Optimization, Pod: WP & Infra, Type: Enhancement, Type: Performance, cla: yes

#6539 Updated library search component
  assets/src/design-system/components/index.js
  assets/src/design-system/components/search/index.js
  assets/src/design-system/components/search/input/components.js
  assets/src/design-system/components/search/input/index.js
  assets/src/design-system/components/search/test/input.js
  assets/src/edit-story/components/colorPicker/editablePreview.js
  assets/src/edit-story/components/library/common/searchInput.js
  assets/src/edit-story/components/library/common/test/searchInput.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6606 Performance: Omit ?ver=<hash> for chunk requests
  includes/Traits/Assets.php
Labels: Type: Performance, cla: yes

#6538 Dashboard: Update stories list view to use new components from design system
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/inlineInputForm/index.js
  assets/src/dashboard/components/input/index.js
  assets/src/dashboard/components/input/stories/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/design-system/theme/breakpoint.js
Labels: Group: Dashboard, Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#6516 Dashboard: Story views - Replace old popover component with new context menu component
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/savedTemplates/content/index.js
  assets/src/dashboard/app/views/shared/savedTemplateGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/popoverMenu/story-menu-generator.js
  assets/src/dashboard/components/popoverMenu/test/story-menu-generator.js
  assets/src/dashboard/components/storyMenu/index.js
  assets/src/dashboard/components/storyMenu/test/storyMenu.js
  assets/src/dashboard/types.js
  assets/src/design-system/components/contextMenu/animatedContextMenu.js
  assets/src/design-system/components/contextMenu/contextMenu.js
  assets/src/design-system/components/contextMenu/index.js
  assets/src/design-system/components/contextMenu/menu.js
  assets/src/design-system/components/contextMenu/menuItem.js
  assets/src/design-system/components/contextMenu/test/contextMenu.js
  assets/src/design-system/components/index.js
Labels: Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#6611 Replace incorrect semicolon
  assets/src/design-system/components/mediaInput/index.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#6568 Redesign: color swatch
  assets/src/design-system/components/index.js
  assets/src/design-system/components/swatch/index.js
  assets/src/design-system/components/swatch/stories/index.js
  assets/src/design-system/components/swatch/swatch.js
  assets/src/design-system/utils/index.js
  assets/src/design-system/utils/patterns/generatePatternStyles.js
  assets/src/design-system/utils/patterns/getOpaquePattern.js
  assets/src/design-system/utils/patterns/hasGradient.js
  assets/src/design-system/utils/patterns/hasOpacity.js
  assets/src/design-system/utils/patterns/index.js
  assets/src/design-system/utils/patterns/test/generatePatternStyles.js
  assets/src/design-system/utils/patterns/test/getOpaquePattern.js
  assets/src/design-system/utils/patterns/test/hasOpacity.js
  assets/src/edit-story/components/form/color/colorInput.js
  assets/src/edit-story/components/form/color/test/colorInput.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/color.js
  assets/src/edit-story/components/panels/design/preset/test/colorPresetPanel.js
  assets/src/edit-story/components/panels/design/preset/test/utils.js
  assets/src/edit-story/components/panels/design/preset/utils.js
  assets/src/edit-story/constants/index.js
Labels: Pod: Prometheus, Type: Code Quality, Type: Enhancement, cla: yes

#6524 Redesign: grid view
  assets/src/design-system/components/popup/index.js
  assets/src/design-system/theme/breakpoint.js
  assets/src/edit-story/components/carousel/carouselMenu.js
  assets/src/edit-story/components/carousel/carouselPage.js
  assets/src/edit-story/components/carousel/carouselPagePreview.js
  assets/src/edit-story/components/carousel/gridview/index.js
  assets/src/edit-story/components/carousel/gridview/karma/gridView.karma.js
  assets/src/edit-story/components/carousel/pagepreview/index.js
  assets/src/edit-story/components/colorPicker/editablePreview.js
  assets/src/edit-story/components/modal/index.js
  assets/src/edit-story/components/reorderable/reorderable.js
  assets/src/edit-story/karma/fixture/containers/editor.js
  assets/src/edit-story/karma/fixture/containers/gridView.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6626 [Block] Minor issues
  assets/src/web-stories-block/block/block-types/latest-stories/edit.js
  assets/src/web-stories-block/block/block-types/selected-stories/selectStories.js
  includes/Block/Web_Stories_Block.php
  includes/Stories_Renderer/Renderer.php
  includes/Widgets/Stories.php
  tests/phpunit/tests/Stories_Renderer/Carousel_Renderer.php
  tests/phpunit/tests/Stories_Renderer/Generic_Renderer.php
  tests/phpunit/tests/Widgets/Stories.php
Labels: cla: yes

#6614 Dashboard: hide admin notices
  assets/src/dashboard/style.css
Labels: Group: Dashboard, Group: WordPress, P3, Package: Dashboard, Pod: WP & Infra, Type: Bug, cla: yes

#6625 Embeds: Use placeholder when poster image is missing
  assets/src/web-stories-block/block/components/storyCard.js
  assets/src/web-stories-block/block/test/storyCard.js
  assets/src/web-stories-block/css/common.css
  assets/src/web-stories-block/css/views/circles.css
  includes/Model/Story.php
  includes/Stories_Renderer/Carousel_Renderer.php
  includes/Stories_Renderer/Generic_Renderer.php
  includes/Stories_Renderer/Renderer.php
  includes/Story_Query.php
  tests/phpunit/tests/Stories_Renderer/Carousel_Renderer.php
  tests/phpunit/tests/Stories_Renderer/Generic_Renderer.php
  tests/phpunit/tests/Stories_Renderer/Renderer.php
Labels: Type: Enhancement, cla: yes

#6627 Add some basic widget validation.
  includes/Widgets/Stories.php
Labels: cla: yes

#6620 Templates: Fix typo in Travel template
  packages/templates/src/raw/travel.json
Labels: Group: Templates, Type: Bug, cla: yes

#6579 Redesign: no selection "panel"
  assets/src/edit-story/components/inspector/design/designPanels.js
  assets/src/edit-story/components/inspector/design/getDesignPanelsForSelection.js
  assets/src/edit-story/components/panels/design/index.js
  assets/src/edit-story/components/panels/design/noSelection/index.js
  assets/src/edit-story/components/panels/design/noSelection/noSelection.js
  assets/src/edit-story/components/panels/design/types.js
  assets/src/edit-story/components/panels/panel/panel.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6592 Redesign: Update layer style panel
  assets/src/design-system/components/input/index.js
  assets/src/edit-story/components/panels/design/layerStyle/layerStyle.js
  assets/src/edit-story/components/panels/design/layerStyle/test/layerStyle.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/panels/panel/shared/title.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6571 Updated alignment buttons, icons and tooltips
  assets/src/edit-story/components/panels/design/alignment/alignment.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6628 Add custom icon to stories widget
  includes/Customizer.php
  includes/Widgets/Stories.php
  packages/widget/src/index.js
  packages/widget/src/style.css
  webpack.config.cjs
Labels: Type: Enhancement, cla: yes

#6616 Dashboard: Empty State Redesign
  assets/src/dashboard/app/views/exploreTemplates/content/index.js
  assets/src/dashboard/app/views/exploreTemplates/content/test/content.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/test/content.js
  assets/src/dashboard/app/views/savedTemplates/content/index.js
  assets/src/dashboard/app/views/shared/emptyContentMessage.js
  assets/src/design-system/images/desert_bw.svg
  assets/src/design-system/images/desert_color.svg
  assets/src/design-system/images/index.js
  assets/src/design-system/images/stories/index.js
Labels: Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#6608 Redesign: Text box panel
  assets/src/design-system/components/input/numericInput.js
  assets/src/design-system/components/input/test/useNumericInput.js
  assets/src/design-system/components/input/useNumericInput.js
  assets/src/design-system/components/pill/pillGroup.js
  assets/src/edit-story/components/panels/design/borderRadius/karma/borderRadius.karma.js
  assets/src/edit-story/components/panels/design/poster/karma/videoPoster.karma.js
  assets/src/edit-story/components/panels/design/textBox/color.js
  assets/src/edit-story/components/panels/design/textBox/padding.js
  assets/src/edit-story/components/panels/design/textBox/test/textBox.js
  assets/src/edit-story/icons/index.js
  assets/src/edit-story/icons/turning_line.svg
  assets/src/edit-story/karma/fixture/containers/designPanel/textBox.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6588 Dashboard: Grid design updates
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/views/myStories/karma/myStories.karma.js
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/shared/savedTemplateGridView.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/app/views/shared/templateGridView.js
  assets/src/dashboard/app/views/templateDetails/components.js
  assets/src/dashboard/components/cardGrid/index.js
  assets/src/dashboard/components/cardGridItem/cardPreview.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/components/cardGridItem/focusableGridItem.js
  assets/src/dashboard/components/cardGridItem/test/cardTitle.js
  assets/src/dashboard/components/contentGutter/index.js
  assets/src/dashboard/components/link/index.js
  assets/src/dashboard/components/link/stories/index.js
  assets/src/dashboard/components/scrollToTop/index.js
  assets/src/dashboard/components/table/index.js
  assets/src/dashboard/constants/pageStructure.js
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/usePagePreviewSize.js
  assets/src/design-system/components/button/button.js
  assets/src/design-system/components/typography/headline/index.js
  assets/src/design-system/theme/colors.js
  assets/src/design-system/theme/global/index.js
  assets/src/design-system/theme/global/overrideFocusOutline.js
Labels: Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#6607 Fix large font for saved styles
  assets/src/edit-story/components/panels/design/preset/stylePreset/styleItem.js
  assets/src/edit-story/components/panels/panel/shared/title.js
Labels: Group: Saved Styles, Pod: Prometheus, Type: Bug, cla: yes

#6431 FTUE: Smart persisted expanded state
  assets/src/edit-story/components/helpCenter/index.js
  assets/src/edit-story/components/helpCenter/menu/header.js
  assets/src/edit-story/components/helpCenter/popup.js
  assets/src/edit-story/components/helpCenter/useHelpCenter/effects.js
  assets/src/edit-story/components/helpCenter/useHelpCenter/index.js
  assets/src/edit-story/components/helpCenter/useHelpCenter/test/effects.js
  assets/src/edit-story/utils/localStore.js
Labels: Group: FTUE, Pod: Pea, Type: Enhancement, cla: yes

#6587 Stickers: Discovery POC
  assets/src/edit-story/elements/elementTypes.js
  assets/src/edit-story/elements/sticker/display.js
  assets/src/edit-story/elements/sticker/icon.js
  assets/src/edit-story/elements/sticker/index.js
  assets/src/edit-story/elements/sticker/layer.js
  assets/src/edit-story/elements/sticker/output.js
  assets/src/edit-story/stickers/index.js
  assets/src/edit-story/stickers/sampleSticker.js
  assets/src/edit-story/types.js
Labels: Elements: Stickers, Pod: Pea, cla: yes

#6598 Redesign: Page background
  assets/src/edit-story/components/dropTargets/karma/background.karma.js
  assets/src/edit-story/components/inspector/design/getDesignPanelsForSelection.js
  assets/src/edit-story/components/panels/design/backgroundSizePosition/backgroundSizePosition.js
  assets/src/edit-story/components/panels/design/index.js
  assets/src/edit-story/components/panels/design/pageBackground/index.js
  assets/src/edit-story/components/panels/design/pageBackground/pageBackground.js
  assets/src/edit-story/components/panels/design/pageStyle/index.js
  assets/src/edit-story/components/panels/design/pageStyle/pageStyle.js
  assets/src/edit-story/components/panels/design/sizePosition/test/sizePosition.js
  assets/src/edit-story/components/panels/design/types.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/panels/shared/flipControls.js
  assets/src/edit-story/elements/image/layer.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6570 Implemented new design for tab view
  assets/src/design-system/theme/global/overrideFocusOutline.js
  assets/src/design-system/theme/helpers/outline.js
  assets/src/edit-story/components/inspector/inspectorLayout.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
  assets/src/edit-story/components/inspector/karma/inspectorTabs.karma.js
  assets/src/edit-story/components/inspector/karma/prepublishSelect.karma.js
  assets/src/edit-story/components/library/karma/libraryTabs.karma.js
  assets/src/edit-story/components/library/libraryLayout.js
  assets/src/edit-story/components/library/panes/text/textIcon.js
  assets/src/edit-story/components/tabview/index.js
  assets/src/edit-story/components/tabview/stories/index.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6604 Editor: Border Radius panel redesign
  assets/src/design-system/components/input/index.js
  assets/src/edit-story/components/panels/design/borderRadius/borderRadius.js
  assets/src/edit-story/components/panels/design/borderRadius/karma/borderRadius.karma.js
  assets/src/edit-story/karma/fixture/containers/designPanel/borderRadius.js
Labels: Group: Borders, Group: Design Panel, Group: Workspace, Pod: Pea, Pod: Prometheus, Type: Enhancement, cla: yes

#6277 Redesign Page Header
  assets/src/edit-story/components/circularProgress/index.js
  assets/src/edit-story/components/header/buttons/buttonWithChecklistWarning.js
  assets/src/edit-story/components/header/buttons/index.js
  assets/src/edit-story/components/header/buttons/preview.js
  assets/src/edit-story/components/header/buttons/publish.js
  assets/src/edit-story/components/header/buttons/switchToDraft.js
  assets/src/edit-story/components/header/buttons/update.js
  assets/src/edit-story/constants/index.js
  packages/e2e-test-utils/src/previewStory.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6619 Redesign: Page attachment panel
  assets/src/edit-story/components/canvas/pageAttachment/karma/pageAttachment.cuj.karma.js
  assets/src/edit-story/components/form/link.js
  assets/src/edit-story/components/inspector/design/getDesignPanelsForSelection.js
  assets/src/edit-story/components/panels/design/link/karma/link.karma.js
  assets/src/edit-story/components/panels/design/pageAttachment/pageAttachment.js
Labels: Group: Design Panel, Group: Page Attachment, Group: Workspace, P1, Pod: Pea, Pod: Prometheus, Type: Enhancement, cla: yes

#6636 Redesign: border width panel
  assets/src/design-system/components/input/index.js
  assets/src/edit-story/components/panels/design/border/borderWidth.js
  assets/src/edit-story/components/panels/design/border/karma/border.karma.js
  assets/src/edit-story/karma/fixture/containers/designPanel/border.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6641 Redesign: fix page bg panel media icon
  assets/src/edit-story/components/panels/design/pageBackground/pageBackground.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Bug, cla: yes

#6660 Stop scrolling when lightbox is open
  assets/src/web-stories-block/css/lightbox.css
  includes/Stories_Renderer/Renderer.php
  packages/stories-lightbox/src/web-stories-lightbox.js
Labels: Group: Blocks, Type: Enhancement, cla: yes

#6658 Ensure RTL versions of all CSS files exist
  assets/src/story-embed-block/block/edit.css
  includes/Traits/Assets.php
  package-lock.json
  package.json
  webpack.config.cjs
Labels: Internationalization (I18N), Pod: WP & Infra, Type: Infrastructure, cla: yes

#6655 Redesign: Saved styles panel adjustments
  assets/src/edit-story/components/panels/design/preset/stylePreset/styleGroup.js
  assets/src/edit-story/components/panels/design/preset/stylePreset/styleItem.js
  assets/src/edit-story/components/panels/design/preset/test/utils.js
  assets/src/edit-story/constants/index.js
Labels: Group: Design Panel, Group: Saved Styles, Pod: Prometheus, Type: Enhancement, cla: yes

#6599 Dashboard: Template Detail Redesign Updates
  assets/src/dashboard/app/views/templateDetails/components.js
  assets/src/dashboard/app/views/templateDetails/content/detailsGallery/index.js
  assets/src/dashboard/app/views/templateDetails/content/index.js
  assets/src/dashboard/app/views/templateDetails/content/relatedGrid/index.js
  assets/src/dashboard/app/views/templateDetails/header/index.js
  assets/src/dashboard/app/views/templateDetails/header/stories/index.js
  assets/src/dashboard/app/views/templateDetails/header/test/header.js
  assets/src/dashboard/app/views/templateDetails/index.js
  assets/src/dashboard/app/views/templateDetails/karma/templateDetails.karma.js
  assets/src/dashboard/components/bookmark-chip/index.js
  assets/src/dashboard/components/bookmark-chip/stories/index.js
  assets/src/dashboard/components/bookmark-chip/test/bookmark-chip.js
  assets/src/dashboard/components/button/index.js
  assets/src/dashboard/components/button/paginationButton.js
  assets/src/dashboard/components/button/stories/index.js
  assets/src/dashboard/components/cardGallery/components.js
  assets/src/dashboard/components/detailViewNavBar/index.js
  assets/src/dashboard/components/detailViewNavBar/stories/index.js
  assets/src/dashboard/components/detailViewNavBar/test/templateNavBar.js
  assets/src/dashboard/components/dropdown/index.js
  assets/src/dashboard/components/dropdown/stories/index.js
  assets/src/dashboard/components/dropdown/test/dropdown.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/pill/colorSwatch.js
  assets/src/dashboard/components/pill/components.js
  assets/src/dashboard/components/pill/defaultPill.js
  assets/src/dashboard/components/pill/floatingPill.js
  assets/src/dashboard/components/pill/index.js
  assets/src/dashboard/components/pill/stories/index.js
  assets/src/dashboard/components/pill/test/pill.js
  assets/src/dashboard/components/popoverPanel/index.js
  assets/src/dashboard/components/popoverPanel/stories/index.js
  assets/src/dashboard/components/popoverPanel/test/popverPanel.js
  assets/src/dashboard/theme.js
  packages/e2e-tests/src/specs/dashboard/documentTitle.js
Labels: Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#6664 Redesign: temporary advancedDropdown style adjustments
  assets/src/edit-story/components/form/advancedDropDown/dropDown.js
  assets/src/edit-story/components/panels/document/publish/publishTime.js
Labels: Group: Fonts, Pod: Prometheus, Type: Enhancement, cla: yes

#6541 Media Upload Queue
  assets/src/edit-story/app/media/local/actions.js
  assets/src/edit-story/app/media/local/reducer.js
  assets/src/edit-story/app/media/local/typedefs.js
  assets/src/edit-story/app/media/local/types.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
  assets/src/edit-story/app/media/media3p/api/test/useMedia3pApi.js
  assets/src/edit-story/app/media/pagination/actions.js
  assets/src/edit-story/app/media/pagination/reducer.js
  assets/src/edit-story/app/media/test/useUploadMedia.js
  assets/src/edit-story/app/media/useUploadMedia.js
  assets/src/edit-story/app/media/utils/createResource.js
  assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js
  assets/src/edit-story/app/media/utils/getResourceFromMedia3p.js
  assets/src/edit-story/app/media/utils/getTypeFromMime.js
  assets/src/edit-story/app/media/utils/index.js
  assets/src/edit-story/app/media/utils/test/getResourceFromMedia3p.js
  assets/src/edit-story/app/media/utils/test/useTranscodeVideo.js
  assets/src/edit-story/app/media/utils/useMediaUploadQueue/index.js
  assets/src/edit-story/app/media/utils/useMediaUploadQueue/reducer.js
  assets/src/edit-story/app/media/utils/useMediaUploadQueue/test/reducer.js
  assets/src/edit-story/app/media/utils/useMediaUploadQueue/test/useMediaUploadQueue.js
  assets/src/edit-story/app/media/utils/useTranscodeVideo.js
  assets/src/edit-story/app/media/utils/useUploadVideoFrame.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducer.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/deleteElementsByResourceId.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/index.js
  assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsByResourceId.js
  assets/src/edit-story/app/story/useStoryReducer/test/updateElementsByResourceId.js
  assets/src/edit-story/app/story/useStoryReducer/types.js
  assets/src/edit-story/app/uploader/test/useUploader.js
  assets/src/edit-story/app/uploader/useUploader.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/canvas/useUploadWithPreview.js
  assets/src/edit-story/components/library/panes/media/local/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/library/panes/media/local/stories/deleteDialog.js
  assets/src/edit-story/components/library/test/mediaEditDialog.js
  assets/src/edit-story/elements/media/imageDisplay.js
  assets/src/edit-story/elements/media/useAverageColor.js
  assets/src/edit-story/elements/video/controls.js
  assets/src/edit-story/types.js
  assets/src/edit-story/utils/blobs.js
Labels: Group: Media, Group: Video Optimization, Pod: WP & Infra, Type: Enhancement, cla: yes

#6566 Media Library: Display tooltips if transcoding is in progress
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
Labels: Group: Media, Group: Video Optimization, Type: Enhancement, cla: yes

#6673 Remove is_site_kit_plugin_installed method
  includes/Dashboard.php
Labels: PHP, Pod: WP & Infra, Type: Code Quality, cla: yes

#6659 Redesign: Adjust panels CSS
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorAdd.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/emptyPanel.js
  assets/src/edit-story/components/panels/design/preset/presetPanel.js
  assets/src/edit-story/components/panels/document/publish/publish.js
  assets/src/edit-story/components/panels/panel/shared/title.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6668 Design System: Decrease transition time
  assets/src/design-system/components/button/constants.js
  assets/src/design-system/components/pill/pill.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#6670 Design System: Firefox bugfix for context menus
  assets/src/dashboard/app/views/editorSettings/karma/editorSettings.karma.js
  assets/src/design-system/components/contextMenu/menu.js
Labels: Group: Design System, Pod: Pea, Type: Bug, cla: yes

#6677 ESLint: Enable react/jsx-boolean-value rule
  .eslintrc
  assets/src/dashboard/app/views/editorSettings/adManagement/adNetwork/index.js
  assets/src/dashboard/app/views/exploreTemplates/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/stories/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/previewStory/index.js
  assets/src/dashboard/app/views/previewStory/stories/previewStory.js
  assets/src/dashboard/app/views/savedTemplates/content/stories/index.js
  assets/src/dashboard/app/views/savedTemplates/index.js
  assets/src/dashboard/app/views/shared/test/telemetryBanner.js
  assets/src/dashboard/components/cardGridItem/test/cardTitle.js
  assets/src/dashboard/components/fileUpload/test/fileUpload.js
  assets/src/dashboard/components/infiniteScroller/test/infiniteScroller.js
  assets/src/dashboard/components/pageStructure/menuButton.js
  assets/src/design-system/components/banner/index.js
  assets/src/design-system/components/dialog/test/dialog.js
  assets/src/design-system/components/dropDown/test/dropDown.js
  assets/src/design-system/components/dropDown/test/select.js
  assets/src/design-system/components/modal/test/modal.js
  assets/src/design-system/components/popup/test/popup.js
  assets/src/design-system/components/tooltip/stories/index.js
  assets/src/edit-story/app/snackbar/snackbarContainer.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/pageAttachment/index.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/index.js
  assets/src/edit-story/components/carousel/pagepreview/index.js
  assets/src/edit-story/components/circularProgress/index.js
  assets/src/edit-story/components/colorPicker/colorPicker.js
  assets/src/edit-story/components/form/dropDown/index.js
  assets/src/edit-story/components/form/test/numeric.js
  assets/src/edit-story/components/form/test/switch.js
  assets/src/edit-story/components/helpCenter/toggle/test/index.js
  assets/src/edit-story/components/keyboardShortcutsMenu/index.js
  assets/src/edit-story/components/library/common/test/searchInput.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/components/library/panes/media/common/test/paginatedMediaGallery.js
  assets/src/edit-story/components/library/panes/media/local/deleteDialog.js
  assets/src/edit-story/components/library/panes/media/local/dropDownMenu.js
  assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js
  assets/src/edit-story/components/library/panes/media/local/stories/missingUploadPermissionDialog.js
  assets/src/edit-story/components/library/panes/media/media3p/test/media3pPane.js
  assets/src/edit-story/components/library/panes/pageLayouts/test/pageLayoutsPane.js
  assets/src/edit-story/components/library/panes/shared/libraryMoveable.js
  assets/src/edit-story/components/library/test/text/textPane.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorPresetActions.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorPresetPanel.js
  assets/src/edit-story/components/panels/design/textStyle/style.js
  assets/src/edit-story/components/panels/document/publish/publishTime.js
  assets/src/edit-story/components/popup/test/popup.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/media/editCropMoveable.js
  assets/src/edit-story/elements/media/editPanMoveable.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/karma/fixture/fixture.js
  assets/src/karma-fixture/componentStub.js
  assets/src/story-embed-block/block/test/embedPlaceholder.js
  assets/src/story-embed-block/block/test/embedPreview.js
Labels: P2, Pod: WP & Infra, Type: Infrastructure, cla: yes

#6682 Widget: PHP Tests
  includes/Widgets/Stories.php
  tests/phpunit/tests/Widgets/Stories.php
Labels: PHP, Type: Code Quality, cla: yes

#6674 WordPress 5.7 Compatibility
  composer.json
  composer.lock
  phpstan.neon.dist
  readme.txt
  tests/phpunit/tests/AMP/Meta_Sanitizer.php
  tests/phpunit/tests/Admin.php
  tests/phpunit/tests/Database_Upgrader.php
  tests/phpunit/tests/Discovery.php
  tests/phpunit/tests/Media.php
  tests/phpunit/tests/REST_API/Stories_Media_Controller.php
  tests/phpunit/tests/SVG.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: WordPress, P2, Pod: WP & Infra, Type: Infrastructure, cla: yes

#6666 Redesign: Mixed value handling for panels with new design
  assets/src/design-system/components/hex/getPreviewText.js
  assets/src/design-system/components/hex/index.js
  assets/src/design-system/components/mediaInput/index.js
  assets/src/design-system/utils/constants.js
  assets/src/edit-story/components/form/color/colorInput.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/panels/design/layerStyle/layerStyle.js
  assets/src/edit-story/components/panels/design/layerStyle/test/layerStyle.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6729 Improve Actions hygiene
  .github/workflows/cancel-previous-workflows.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-integration-build.yml
  .github/workflows/continuous-integration-bundle-size.yml
  .github/workflows/continuous-integration-e2e.yml
  .github/workflows/continuous-integration-gh-pages.yml
  .github/workflows/continuous-integration-lint-css.yml
  .github/workflows/continuous-integration-lint-js.yml
  .github/workflows/continuous-integration-lint-md.yml
  .github/workflows/continuous-integration-lint-php.yml
  .github/workflows/continuous-integration-unit-js.yml
  .github/workflows/continuous-integration-unit-php.yml
Labels: cla: yes

#6676 Link Panel: issues with special characters
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Link_Controller.php
  includes/Traits/Document_Parser.php
  tests/phpunit/data/characters.example.com.html
  tests/phpunit/tests/REST_API/Link_Controller.php
Labels: Group: Design Panel, Pod: WP & Infra, Type: Bug, cla: yes

#6711 Widget notice errors
  includes/Widgets/Stories.php
  tests/phpunit/tests/Widgets/Stories.php
Labels: cla: yes

#6733 Further improve GitHub Actions workflows
  .github/workflows/build-and-deploy.yml
  .github/workflows/bundle-size-check.yml
  .github/workflows/continuous-integration-lint-css.yml
  .github/workflows/continuous-integration-lint-md.yml
  .github/workflows/deploy-storybook.yml
  .github/workflows/lint-css-js-md.yml
  .github/workflows/lint-php.yml
  .github/workflows/pr-checklist.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-karma-dashboard.yml
  .github/workflows/tests-karma-editor.yml
  .github/workflows/tests-unit-js.yml
  .github/workflows/tests-unit-php.yml
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6732 TinyMCE Button: PHP Tests
  includes/TinyMCE.php
  tests/phpunit/tests/TinyMCE.php
Labels: Group: Classic Editor, Pod: WP & Infra, Type: Infrastructure, cla: yes

#6736 Infrastructure: Move embed.css to the other CSS files
  assets/src/web-stories-block/css/embed.css
  includes/Embed_Base.php
  webpack.config.cjs
Labels: cla: yes

#6709 Widget: E2E Tests
  packages/e2e-tests/src/specs/wordpress/widget.js
Labels: cla: yes

#6705 Classic Editor: E2E tests for TinyMCE button
  packages/e2e-tests/src/specs/wordpress/tinymce.js
  packages/tinymce-button/src/index.js
Labels: Group: Classic Editor, Package: E2E Tests, Pod: WP & Infra, Type: Infrastructure, cla: yes

#6750 E2E Tests: Pin docker image at previous version to fix CI
  bin/local-env/docker-compose.yml
  bin/local-env/install-wordpress.sh
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6751 More GitHub Actions improvements
  .github/workflows/build-and-deploy.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-storybook.yml
  .github/workflows/lint-css-js-md.yml
  .github/workflows/lint-php.yml
  .github/workflows/pr-checklist.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-karma-dashboard.yml
  .github/workflows/tests-karma-editor.yml
  .github/workflows/tests-unit-js.yml
  .github/workflows/tests-unit-php.yml
  .github/workflows/update-google-fonts.yml
  .github/workflows/update-templates.yml
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6692 Design System: Fix DropDown fonts
  assets/src/design-system/components/dropDown/select/index.js
Labels: Bug Bash 1.5.0-A, Group: Dashboard, Group: Design System, Pod: Pea, Type: Bug, cla: yes

#6693 Dashboard: Story List View Title Font Size Update to 14px
  assets/src/dashboard/app/views/shared/storyListView.js
Labels: Bug Bash 1.5.0-A, Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#6695 Dashboard: Update CTA border width
  assets/src/dashboard/components/pageStructure/navigationComponents.js
Labels: Bug Bash 1.5.0-A, Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#6698 Dashboard: Template Details Gallery Radius
  assets/src/dashboard/components/cardGallery/components.js
Labels: Bug Bash 1.5.0-A, Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#6697 Dashboard: Checkbox cursor updated to pointer
  assets/src/dashboard/app/views/editorSettings/components.js
  assets/src/dashboard/app/views/shared/telemetryBanner.js
  assets/src/design-system/components/checkbox/index.js
Labels: Bug Bash 1.5.0-A, Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#6681 Design System: Add loading animation
  assets/src/design-system/components/index.js
  assets/src/design-system/components/loadingSpinner/index.js
  assets/src/design-system/components/loadingSpinner/stories/index.js
  assets/src/design-system/components/loadingSpinner/test/loadingSpinner.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#6699 Design System: Add Radio Button
  assets/src/design-system/components/index.js
  assets/src/design-system/components/input/stories/index.js
  assets/src/design-system/components/radio/index.js
  assets/src/design-system/components/radio/radio.js
  assets/src/design-system/components/radio/stories/index.js
  assets/src/design-system/components/radio/test/radio.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#6771 Rewind story in the lightbox
  includes/Traits/Theme_Support.php
  packages/stories-lightbox/src/web-stories-lightbox.js
  tests/phpunit/tests/Customizer.php
Labels: cla: yes

#6773 ESLint: Fix npm script config
  package.json
  patches/eslint+7.22.0.patch
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6654 Redesign: Implemented dropdowns
  assets/src/design-system/components/dropDown/index.js
  assets/src/design-system/components/menu/components.js
  assets/src/design-system/components/menu/menu.js
  assets/src/edit-story/app/media/local/types.js
  assets/src/edit-story/app/media/local/useContextValueProvider.js
  assets/src/edit-story/components/library/panes/media/local/dropDownMenu.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorPresetActions.js
  assets/src/edit-story/components/panels/design/preset/karma/colorPickerActions.karma.js
  assets/src/edit-story/elements/video/karma/autoplay.karma.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6703 Make sure the saved colour presets are always unique
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/panels/design/preset/test/utils.js
  assets/src/edit-story/components/panels/design/preset/useAddPreset.js
  assets/src/edit-story/components/panels/design/preset/utils.js
  assets/src/edit-story/utils/getUniquePresets.js
  assets/src/edit-story/utils/test/getUniquePresets.js
Labels: Group: Saved Colors, Pod: Prometheus, Type: Bug, cla: yes

#6781 Classic Editor: ensure TinyMCE integration can be localized
  includes/TinyMCE.php
  tests/phpunit/tests/TinyMCE.php
Labels: Group: Classic Editor, Type: Enhancement, cla: yes

#6694 Animations: Background Pan and Zoom Effect
  assets/src/animation/constants.js
  assets/src/animation/effects/backgroundPanAndZoom/animationProps.js
  assets/src/animation/effects/backgroundPanAndZoom/index.js
  assets/src/animation/effects/backgroundZoom/index.js
  assets/src/animation/parts/index.js
  assets/src/animation/parts/zoom/index.js
  assets/src/animation/utils/getMediaOrigin.js
  assets/src/animation/utils/index.js
  assets/src/animation/utils/test/getMediaOrigin.js
  assets/src/edit-story/components/form/dropDown/list.js
  assets/src/edit-story/components/panels/design/animation/animation.js
  assets/src/edit-story/components/panels/design/animation/effectChooser.js
  assets/src/edit-story/components/panels/design/animation/effectChooserElements.js
  assets/src/edit-story/components/panels/design/animation/effectInput.js
  assets/src/edit-story/components/panels/design/animation/effectPanel.js
  includes/Experiments.php
Labels: Group: Animations, Package: Animation, Pod: Pea, Type: Enhancement, cla: yes

#6810 Fix: Editor crash on text sets
  assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js
Labels: Group: Workspace, P0, Pod: Pea, Type: Bug, cla: yes

#6799 Design System: Add Switch Component
  assets/src/design-system/components/index.js
  assets/src/design-system/components/switch/index.js
  assets/src/design-system/components/switch/stories/index.js
  assets/src/design-system/components/switch/test/switch.js
  assets/src/design-system/theme/helpers/outline.js
Labels: Group: Design System, Pod: Pea, Pod: Prometheus, Type: Enhancement, cla: yes

#6488 Infrastructure: Finalize release automation script
  .github/ISSUE_TEMPLATE/release-plugin.md
  .github/workflows/plugin-release.yml
  package-lock.json
  packages/commander/package.json
  packages/commander/src/index.js
  readme.txt
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6822 Blocks: fix infinite loop in select stories dialog
  assets/src/web-stories-block/block/block-types/selected-stories/storyPicker.js
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#6829 Update readme.txt for v1.5.0
  readme.txt
Labels: Type: Infrastructure, cla: yes

#6847 Fix loading when rearranging stories
  assets/src/web-stories-block/block/block-types/selected-stories/storyPicker.js
Labels: Group: Blocks, Group: WordPress, Pod: WP & Infra, Type: Bug, cla: yes

#6737 Redesign: Video Settings Panel
  assets/src/edit-story/components/panels/design/videoOptions/test/videoOptions.js
  assets/src/edit-story/components/panels/design/videoOptions/videoOptions.js
  assets/src/edit-story/components/panels/panel/shared/content.js
  assets/src/edit-story/components/panels/panel/shared/title.js
Labels: cla: yes

#6738 Generate video posters in parallel to transcoding and uploading
  assets/src/edit-story/app/media/test/useUploadMedia.js
  assets/src/edit-story/app/media/useUploadMedia.js
  assets/src/edit-story/app/media/utils/getFirstFrameOfVideo.js
  assets/src/edit-story/app/media/utils/getImageDimensions.js
  assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js
  assets/src/edit-story/app/media/utils/preloadImage.js
  assets/src/edit-story/app/media/utils/test/useFFmpeg.js
  assets/src/edit-story/app/media/utils/useFFmpeg.js
  assets/src/edit-story/app/media/utils/useMediaUploadQueue/index.js
  assets/src/edit-story/app/media/utils/useMediaUploadQueue/test/useMediaUploadQueue.js
  assets/src/edit-story/app/media/utils/useTranscodeVideo.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/selectElement.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/setSelectedElements.js
  assets/src/edit-story/app/story/useStoryReducer/test/addElementToSelection.js
  assets/src/edit-story/app/story/useStoryReducer/test/setSelectedElementsById.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/selection.js
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/canvas/useUploadWithPreview.js
  assets/src/edit-story/components/dropTargets/provider.js
  assets/src/edit-story/components/library/panes/media/common/mediaElement.js
  assets/src/edit-story/constants/index.js
  assets/src/edit-story/elements/media/edit.js
  assets/src/edit-story/elements/video/controls.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/elements/video/icon.js
  assets/src/edit-story/utils/blobs.js
  packages/tracking/src/enableTracking.js
Labels: Elements: Video, Group: Media, Group: Video Optimization, Type: Enhancement, cla: yes

#6830 JavaScript Tests: Use useEffect instead of useLayoutEffect
  tests/js/setup-mocks.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6820 E2E Tests: Suppress 404s in Embed Block test
  packages/e2e-tests/src/specs/wordpress/webStoriesBlock.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6785 E2E Tests: stabilize Percy snapshot by avoiding random file names
  package-lock.json
  packages/e2e-test-utils/package.json
  packages/e2e-test-utils/src/uploadFile.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6749 Design panel: Video Captions Panel Redesign
  assets/src/edit-story/components/panels/design/captions/captions.js
  assets/src/edit-story/components/panels/design/captions/test/captions.js
Labels: Group: Design Panel, P2, Pod: Pea, Pod: Prometheus, Type: Enhancement, cla: yes

#6754 Dashboard: Add loading spinner to dashboard views
  assets/src/dashboard/app/views/exploreTemplates/content/index.js
  assets/src/dashboard/app/views/exploreTemplates/header/index.js
  assets/src/dashboard/app/views/exploreTemplates/index.js
  assets/src/dashboard/app/views/myStories/content/index.js
  assets/src/dashboard/app/views/myStories/content/storiesView/index.js
  assets/src/dashboard/app/views/myStories/content/test/storiesView.js
  assets/src/dashboard/app/views/myStories/header/index.js
  assets/src/dashboard/app/views/myStories/index.js
  assets/src/dashboard/app/views/savedTemplates/content/index.js
  assets/src/dashboard/app/views/shared/bodyViewOptions.js
  assets/src/dashboard/app/views/shared/storyListView.js
  assets/src/dashboard/components/index.js
  assets/src/dashboard/components/infiniteScroller/index.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/utils/test/useStoryView.js
  assets/src/dashboard/utils/useStoryView.js
Labels: Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#6772 Media: Ensure user feedback when inserting unsupported file types via WordPress media modal
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/library/panes/media/local/mediaPane.js
  assets/src/edit-story/components/mediaPicker/useMediaPicker.js
  assets/src/edit-story/components/panels/design/captions/captions.js
  assets/src/edit-story/components/panels/design/link/link.js
  assets/src/edit-story/components/panels/design/link/test/link.js
  assets/src/edit-story/components/panels/design/poster/karma/videoPoster.karma.js
  assets/src/edit-story/components/panels/design/poster/test/videoPoster.js
  assets/src/edit-story/components/panels/design/poster/videoPoster.js
  assets/src/edit-story/components/panels/document/publish/publish.js
  assets/src/edit-story/components/panels/document/publish/test/publish.js
  assets/src/edit-story/karma/fixture/fixture.js
  includes/Story_Post_Type.php
  includes/Traits/Types.php
Labels: Bug Bash 1.5.0-A, Group: Media, Pod: WP & Infra, Type: Bug, cla: yes

#6780 Design System: Quaternary button
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/navigationComponents.js
  assets/src/design-system/components/button/button.js
  assets/src/design-system/components/button/constants.js
  assets/src/design-system/theme/colors.js
Labels: Group: Dashboard, Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#6817 Fix panel title colours and focus
  assets/src/design-system/components/button/button.js
  assets/src/edit-story/components/panels/panel/shared/title.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6774 Redesign: Publishing panel
  assets/src/design-system/components/dropDown/select/components.js
  assets/src/design-system/components/mediaInput/index.js
  assets/src/design-system/components/mediaInput/stories/index.js
  assets/src/edit-story/app/prepublish/constants.js
  assets/src/edit-story/app/prepublish/error/test/metadata.js
  assets/src/edit-story/app/prepublish/test/__snapshots__/getPrepublishErrors.js.snap
  assets/src/edit-story/components/form/advancedDropDown/dropDown.js
  assets/src/edit-story/components/form/media.js
  assets/src/edit-story/components/form/required.js
  assets/src/edit-story/components/inspector/karma/inspectorTabs.karma.js
  assets/src/edit-story/components/panels/design/link/link.js
  assets/src/edit-story/components/panels/design/poster/videoPoster.js
  assets/src/edit-story/components/panels/design/textStyle/fontPicker.js
  assets/src/edit-story/components/panels/document/publish/author.js
  assets/src/edit-story/components/panels/document/publish/publish.js
  assets/src/edit-story/components/panels/document/publish/publishTime.js
Labels: Group: Design Panel, Group: Document Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6784 Redesign: Excerpt panel
  assets/src/design-system/components/textArea/index.js
  assets/src/edit-story/components/form/textArea.js
  assets/src/edit-story/components/panels/document/excerpt/excerpt.js
  assets/src/edit-story/components/panels/document/excerpt/test/excerpt.js
Labels: Group: Document Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6777 Stickers: Respect Aspect Ratio on Input Size Update
  assets/src/edit-story/components/panels/design/sizePosition/sizePosition.js
  assets/src/edit-story/components/panels/design/sizePosition/test/sizePosition.js
  assets/src/edit-story/elements/sticker/display.js
  assets/src/edit-story/elements/sticker/layer.js
  assets/src/edit-story/elements/sticker/output.js
  assets/src/edit-story/stickers/index.js
  assets/src/edit-story/stickers/sampleSticker.js
Labels: Elements: Stickers, Group: Dashboard, Pod: Pea, Type: Enhancement, cla: yes

#6831 Design System: Update checkmark on toggle
  assets/src/design-system/components/toggle/index.js
Labels: Group: Design System, Pod: Pea, Type: Enhancement, cla: yes

#6861 FTUE: Find missing 'done' svg
  assets/src/edit-story/components/helpCenter/quickTip/doneCheckmark.svg
  assets/src/edit-story/components/helpCenter/quickTip/index.js
Labels: Group: FTUE, P1, Pod: Pea, Type: Bug, cla: yes

#6730 Document Panel: Status Panel Redesign
  assets/src/design-system/components/input/index.js
  assets/src/design-system/components/radio/radio.js
  assets/src/edit-story/components/form/radioGroup/index.js
  assets/src/edit-story/components/form/shared/useRadioNavigation.js
  assets/src/edit-story/components/form/stories/radioGroup.js
  assets/src/edit-story/components/form/test/radioGroup.js
  assets/src/edit-story/components/panels/document/status/status.js
  assets/src/edit-story/components/panels/document/status/test/status.js
Labels: Group: Design System, Group: Document Panel, P2, Pod: Pea, Type: Enhancement, cla: yes

#6786 Elements Panel: Update 'Text Set' buttons
  assets/src/design-system/components/button/button.js
  assets/src/design-system/components/button/index.js
  assets/src/design-system/components/button/stories/index.js
  assets/src/edit-story/components/library/panes/text/textSets/textSet.js
  assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js
Labels: Group: Library, Group: Text Sets, P2, Pod: Pea, Type: Enhancement, cla: yes

#6794 Document Panel: Update permalink panel
  assets/src/design-system/components/typography/link/index.js
  assets/src/edit-story/components/panels/document/slug/slug.js
  assets/src/edit-story/components/panels/document/slug/test/slug.js
Labels: Group: Document Panel, P2, Pod: Pea, Pod: Prometheus, Type: Enhancement, cla: yes

#6236 Adjust zoom
  assets/src/edit-story/app/layout/useZoomSetting.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/carousel/zoomSelector/zoomSelector.js
  assets/src/edit-story/constants/index.js
Labels: Pod: Prometheus, Status: Stale, Type: Task, cla: yes

#6727 Dashboard: Fix conflicting min-width
  assets/src/dashboard/app/views/shared/pageHeading.js
  assets/src/dashboard/components/contentGutter/index.js
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/dashboard/components/pageStructure/menuButton.js
  assets/src/dashboard/style.css
  assets/src/dashboard/theme.js
  assets/src/dashboard/utils/usePagePreviewSize.js
Labels: Bug Bash 1.5.0-A, Group: Dashboard, Pod: Pea, Type: Bug, cla: yes

#6892 Plugin Release: minor workflow tweaks
  .github/workflows/plugin-release.yml
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6898 Heading Levels causing e2e test failures
  assets/src/dashboard/components/pageStructure/index.js
  assets/src/edit-story/components/form/radioGroup/index.js
  assets/src/edit-story/components/helpCenter/menu/header.js
  assets/src/edit-story/components/keyboardShortcutsMenu/headerShortcut.js
  assets/src/edit-story/components/keyboardShortcutsMenu/shortcutMenuSection.js
Labels: Accessibility, Group: Workspace, Pod: Pea, Type: Bug, cla: yes

#6855 Test fix: Re-enable poster image test for keyboard
  assets/src/edit-story/components/panels/design/poster/karma/videoPoster.karma.js
  assets/src/edit-story/karma/fixture/containers/designPanel/videoPoster.js
Labels: Pod: Prometheus, Type: Bug, Type: Infrastructure, cla: yes

#6497 Editor: Implement MVP for Post Locking (Story Locking)
  assets/src/dashboard/app/api/test/apiProvider.js
  assets/src/dashboard/app/api/useStoryApi.js
  assets/src/dashboard/app/serializers/stories.js
  assets/src/dashboard/app/views/shared/storyGridView.js
  assets/src/dashboard/components/cardGridItem/cardTitle.js
  assets/src/dashboard/constants/index.js
  assets/src/dashboard/karma/fixture.js
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/api/test/apiProvider.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/components/postLock/index.js
  assets/src/edit-story/components/postLock/postLock.js
  assets/src/edit-story/components/postLock/postLockDialog.js
  assets/src/edit-story/components/postLock/postTakeOverDialog.js
  assets/src/edit-story/components/postLock/shared.js
  assets/src/edit-story/components/postLock/stories/postLockDialog.js
  assets/src/edit-story/components/postLock/stories/postTakeOverDialog.js
  assets/src/edit-story/components/postLock/test/postLock.js
  assets/src/edit-story/editorApp.js
  assets/src/edit-story/karma/fixture/fixture.js
  includes/Dashboard.php
  includes/Experiments.php
  includes/Plugin.php
  includes/REST_API/Stories_Base_Controller.php
  includes/REST_API/Stories_Lock_Controller.php
  includes/Story_Post_Type.php
  includes/templates/admin/edit-story.php
  packages/e2e-tests/src/plugins/locked-post-mock.php
  packages/e2e-tests/src/specs/wordpress/postLocking.js
  tests/phpunit/tests/REST_API/Stories_Controller.php
  tests/phpunit/tests/REST_API/Stories_Lock_Controller.php
  tests/phpunit/tests/Story_Post_Type.php
Labels: Group: Post Locking, Group: WordPress, Pod: WP & Infra, Type: Enhancement, cla: yes

#6769 Redesign: Shape library buttons
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/panes/shapes/shapePreview.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/shared/libraryMoveable.js
  assets/src/edit-story/components/panels/design/link/link.js
Labels: Group: Library, Pod: Prometheus, Type: Enhancement, cla: yes

#6821 Redesign: Animation panel
  assets/src/design-system/components/dropDown/index.js
  assets/src/design-system/components/dropDown/select/components.js
  assets/src/edit-story/components/panels/design/animation/animation.js
  assets/src/edit-story/components/panels/design/animation/constants.js
  assets/src/edit-story/components/panels/design/animation/directionRadioInput.js
  assets/src/edit-story/components/panels/design/animation/effectChooser.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown.js
  assets/src/edit-story/components/panels/design/animation/effectChooserElements.js
  assets/src/edit-story/components/panels/design/animation/effectInput.js
  assets/src/edit-story/components/panels/design/animation/effectPanel.js
  assets/src/edit-story/components/panels/design/animation/test/directionRadioInput.js
Labels: Group: Animations, Group: Design Panel, Pod: Prometheus, cla: yes

#6824 Document Panel: Update Page Advancement Panel
  assets/src/design-system/components/switch/index.js
  assets/src/edit-story/components/form/stories/switch.js
  assets/src/edit-story/components/form/switch.js
  assets/src/edit-story/components/form/test/switch.js
  assets/src/edit-story/components/panels/document/pageAdvancement/pageAdvancement.js
  assets/src/edit-story/components/panels/document/pageAdvancement/test/pageAdvancement.js
Labels: Group: Design System, Group: Document Panel, P2, Pod: Pea, Pod: Prometheus, Type: Enhancement, cla: yes

#6901 Stickers: Hidden Library Panel
  assets/src/edit-story/components/canvas/useInsertElement.js
  assets/src/edit-story/components/library/panes/shapes/shapePreview.js
  assets/src/edit-story/components/library/panes/shapes/shapesPane.js
  assets/src/edit-story/components/library/panes/shapes/stickerButton.js
  includes/Experiments.php
Labels: Elements: Stickers, Package: Editor, Pod: Pea, cla: yes

#6915 Fix accessibility issue in E2E test
  assets/src/design-system/components/switch/index.js
Labels: cla: yes

#6704 Redesign: Video accessibility panel
  assets/src/edit-story/components/form/textArea.js
  assets/src/edit-story/components/inspector/design/getDesignPanelsForSelection.js
  assets/src/edit-story/components/panels/design/index.js
  assets/src/edit-story/components/panels/design/poster/index.js
  assets/src/edit-story/components/panels/design/poster/test/videoPoster.js
  assets/src/edit-story/components/panels/design/poster/videoPoster.js
  assets/src/edit-story/components/panels/design/types.js
  assets/src/edit-story/components/panels/design/videoAccessibility/karma/videoPoster.karma.js
  assets/src/edit-story/components/panels/design/videoAccessibility/test/videoAccessibility.js
  assets/src/edit-story/components/panels/design/videoAccessibility/videoAccessibility.js
  assets/src/edit-story/elements/video/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/index.js
  assets/src/edit-story/karma/fixture/containers/designPanel/videoPoster.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6905 Stickers: Documentation For Adding Stickers to Stories & Codebase
  docs/external-template-creation.md
Labels: Elements: Stickers, Pod: Pea, Type: Documentation, cla: yes

#6895 Add links to plugin row meta
  includes/Admin/PluginActionLinks.php
  includes/Admin/PluginRowMeta.php
  includes/Plugin.php
  tests/phpunit/tests/Admin/PluginActionLinks.php
  tests/phpunit/tests/Admin/PluginRowMeta.php
Labels: Group: WordPress, P2, Pod: WP & Infra, Type: Enhancement, cla: yes

#6880 Redesign: Video element Play/Stop buttons
  assets/src/design-system/icons/index.js
  assets/src/design-system/icons/play_filled.svg
  assets/src/design-system/icons/stop_filled.svg
  assets/src/edit-story/elements/video/controls.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6890 Fix using arrow keys for all numeric inputs in the design panel
  assets/src/edit-story/components/form/color/opacityInput.js
  assets/src/edit-story/components/panels/design/border/borderWidth.js
  assets/src/edit-story/components/panels/design/sizePosition/sizePosition.js
  assets/src/edit-story/components/panels/design/sizePosition/test/sizePosition.js
  assets/src/edit-story/components/panels/design/textBox/padding.js
  assets/src/edit-story/components/panels/design/textStyle/font.js
Labels: Pod: Prometheus, Type: Bug, cla: yes

#6891 Redesign: Page header button updates
  assets/src/edit-story/components/header/buttons/buttonWithChecklistWarning.js
  assets/src/edit-story/components/header/buttons/preview.js
  assets/src/edit-story/components/header/buttons/switchToDraft.js
  assets/src/edit-story/components/header/buttons/update.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6112 Add canvas zoom
  .github/workflows/pr-checklist.yml
  assets/src/design-system/theme/helpers/scrollbar.js
  assets/src/edit-story/app/canvas/canvasProvider.js
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/layout/layoutProvider.js
  assets/src/edit-story/app/layout/useScrollOffset.js
  assets/src/edit-story/app/layout/useZoomSetting.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/karma/backgroundCopyPaste.karma.js
  assets/src/edit-story/components/canvas/karma/lasso.karma.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/multiSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/pagemenu/pageMenu.js
  assets/src/edit-story/components/canvas/pagenav/index.js
  assets/src/edit-story/components/canvas/singleSelectionMoveable/index.js
  assets/src/edit-story/components/canvas/test/_utils.js
  assets/src/edit-story/components/canvas/utils/useSnapping.js
  assets/src/edit-story/components/canvas/utils/useUpdateSelectionRectangle.js
  assets/src/edit-story/components/carousel/carouselMenu.js
  assets/src/edit-story/components/carousel/zoomSelector/index.js
  assets/src/edit-story/components/carousel/zoomSelector/zoomSelector.js
  assets/src/edit-story/components/dropTargets/karma/order.karma.js
  assets/src/edit-story/components/inspector/prepublish/prepublishChecklistProvider.js
  assets/src/edit-story/components/library/panes/shared/libraryMoveable.js
  assets/src/edit-story/components/library/panes/text/textSets/textSet.js
  assets/src/edit-story/components/library/text/fontPreview.js
  assets/src/edit-story/components/panels/design/filter/karma/filter.karma.js
  assets/src/edit-story/constants/index.js
  assets/src/edit-story/elements/media/scalePanel.js
  assets/src/edit-story/elements/video/controls.js
  assets/src/edit-story/karma/copyAndPaste.cuj.karma.js
  assets/src/edit-story/style.css
  includes/Experiments.php
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6916 Internationalization: Fix JavaScript string extraction
  packages/i18n/src/index.js
Labels: Internationalization (I18N), P0, Pod: WP & Infra, Type: Bug, Type: Infrastructure, cla: yes

#6908 Redesign: Filter button form component
  assets/src/edit-story/components/canvas/karma/backgroundCopyPaste.karma.js
  assets/src/edit-story/components/form/filterToggle/filterToggle.js
  assets/src/edit-story/components/form/filterToggle/index.js
  assets/src/edit-story/components/form/filterToggle/stories/index.js
  assets/src/edit-story/components/form/index.js
  assets/src/edit-story/components/form/toggleButton.js
  assets/src/edit-story/components/panels/design/filter/convertOverlay.js
  assets/src/edit-story/components/panels/design/filter/filter.js
  assets/src/edit-story/components/panels/design/filter/karma/filter.karma.js
  assets/src/edit-story/components/panels/design/filter/test/convertOverlay.js
  assets/src/edit-story/karma/fixture/containers/designPanel/filter.js
Labels: Group: Design Panel, Pod: Prometheus, Type: Enhancement, cla: yes

#6918 Replace tildes in filenames with dashes
  webpack.config.cjs
Labels: P1, Type: Bug, Type: Infrastructure, cla: yes

#6816 Set up infrastructure to trigger help center tips
  assets/src/edit-story/app/helpCenter/context.js
  assets/src/edit-story/app/helpCenter/index.js
  assets/src/edit-story/app/helpCenter/provider.js
  assets/src/edit-story/app/helpCenter/useHelpCenter/effects.js
  assets/src/edit-story/app/helpCenter/useHelpCenter/index.js
  assets/src/edit-story/app/helpCenter/useHelpCenter/test/effects.js
  assets/src/edit-story/app/helpCenter/useHelpCenter/test/useHelpCenter.js
  assets/src/edit-story/app/index.js
  assets/src/edit-story/app/userOnboarding/index.js
  assets/src/edit-story/app/userOnboarding/test/useUserOnboarding.js
  assets/src/edit-story/app/userOnboarding/useUserOnboarding.js
  assets/src/edit-story/components/canvas/utils/useSnapping.js
  assets/src/edit-story/components/helpCenter/constants.js
  assets/src/edit-story/components/helpCenter/index.js
  assets/src/edit-story/editorApp.js
Labels: Group: FTUE, Group: Workspace, P2, Pod: Pea, Type: Enhancement, cla: yes

#6759 Library: Update text preset buttons
  assets/src/edit-story/components/library/common/section.js
  assets/src/edit-story/components/library/panes/text/karma/textPane.karma.js
  assets/src/edit-story/components/library/panes/text/textPane.js
  assets/src/edit-story/components/library/panes/text/textPresets.js
  assets/src/edit-story/components/library/test/text/textPane.js
  assets/src/edit-story/components/library/text/fontPreview.js
  assets/src/edit-story/components/panels/design/preset/karma/stylePresets.karma.js
Labels: Group: Library, P2, Pod: Pea, Pod: Prometheus, Type: Enhancement, cla: yes

#6934 Infrastructure: further unify webpack config
  webpack.config.cjs
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes

#6888 Redesign: Animation Dropdown
  assets/src/design-system/components/dropDown/select/components.js
  assets/src/design-system/components/menu/components.js
  assets/src/design-system/components/menu/list/listGroupings.js
  assets/src/edit-story/components/panels/design/animation/animation.js
  assets/src/edit-story/components/panels/design/animation/effectChooser.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown/dropdownConstants.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown/dropdownItem.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown/effectChooserDropdown.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown/effectChooserElements.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown/index.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown/styles.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown/types.js
  assets/src/edit-story/components/panels/design/animation/effectChooserDropdown/utils.js
  assets/src/edit-story/components/panels/design/animation/effectInput.js
  assets/src/edit-story/components/panels/design/animation/karma/animation.karma.js
  assets/src/edit-story/components/panels/design/animation/stories/directionRadioInput.js
  assets/src/edit-story/components/panels/design/animation/stories/effectChooser.js
  assets/src/edit-story/components/panels/design/animation/test/effectChooser.js
  assets/src/edit-story/karma/copyAndPaste.cuj.karma.js
Labels: Group: Workspace, Pod: Pea, Type: Code Quality, Type: Enhancement, cla: yes

#6947 Fix Karma tests related to dropdown
  assets/src/edit-story/components/canvas/karma/backgroundCopyPaste.karma.js
  assets/src/edit-story/components/dropTargets/karma/order.karma.js
  assets/src/edit-story/components/library/karma/mediaTab.karma.js
  assets/src/edit-story/components/library/panes/text/karma/textPane.karma.js
  assets/src/edit-story/components/panels/design/animation/karma/animation.karma.js
  assets/src/edit-story/components/panels/design/filter/karma/filter.karma.js
  assets/src/edit-story/components/panels/design/link/karma/link.karma.js
  assets/src/edit-story/components/panels/design/textStyle/karma/textStyle.other.karma.js
  assets/src/edit-story/components/richText/karma/inlineSelection.karma.js
  assets/src/edit-story/components/richText/karma/inlineStyleOverride.karma.js
  assets/src/edit-story/components/richText/karma/multiSelection.karma.js
  assets/src/edit-story/components/richText/karma/singleSelection.karma.js
  assets/src/edit-story/elements/image/karma/resourceLoading.karma.js
Labels: Pod: Pea, Type: Bug, Type: Code Quality, cla: yes

#6859 Design Panel: Bugfix - reset stored height of saved colors panel
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorPreset.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorPresetPanel.js
  assets/src/edit-story/components/panels/design/preset/constants.js
  assets/src/edit-story/components/panels/design/preset/header.js
  assets/src/edit-story/components/panels/design/preset/karma/colorPresets.karma.js
  assets/src/edit-story/components/panels/design/preset/karma/stylePresets.karma.js
  assets/src/edit-story/components/panels/design/preset/presetPanel.js
  assets/src/edit-story/components/panels/design/preset/stylePreset/styleGroup.js
  assets/src/edit-story/components/panels/design/preset/stylePreset/stylePreset.js
  assets/src/edit-story/components/panels/design/preset/test/colorPresetPanel.js
  assets/src/edit-story/components/panels/design/preset/test/stylePresetPanel.js
  assets/src/edit-story/components/panels/design/preset/test/utils.js
  assets/src/edit-story/components/panels/design/preset/useDeletePreset.js
  assets/src/edit-story/components/panels/design/preset/useKeyboardNavigation.js
  assets/src/edit-story/components/panels/design/preset/utils.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Group: Design Panel, Pod: Pea, Type: Bug, cla: yes

#6919 Stickers: Test out Behavior in Page Layouts
  assets/src/edit-story/stickers/beautyHeart.js
  assets/src/edit-story/stickers/index.js
  packages/templates/src/raw/beauty.json
  packages/templates/src/test/raw.js
Labels: Elements: Stickers, Group: Page Layouts, Package: Editor, Pod: Pea, cla: yes

#6896 Fix Color Picker positioning
  assets/src/edit-story/components/form/color/colorInput.js
  assets/src/edit-story/components/panels/design/preset/colorPreset/colorPresetActions.js
  assets/src/edit-story/components/panels/shared/getColorPickerActions.js
  assets/src/edit-story/components/popup/index.js
Labels: Pod: Prometheus, Type: Enhancement, cla: yes

#6945 Docs: Add developer documentation for the Web Stories embeds
  docs/README.md
  docs/web-stories-embeds.md
Labels: Type: Documentation, cla: yes

#6900 Karma Tests: reduce error output on CI
  assets/src/dashboard/dataUtils/formattedStoriesArray.js
  assets/src/dashboard/karma/apiProviderFixture.js
  assets/src/dashboard/karma/fixture.js
  assets/src/design-system/components/input/numericInput.js
  assets/src/design-system/components/slider/index.js
  assets/src/edit-story/components/form/link.js
  assets/src/edit-story/components/postLock/postLock.js
  assets/src/edit-story/components/postLock/postLockDialog.js
  assets/src/edit-story/karma/fixture/fixture.js
Labels: Pod: WP & Infra, Type: Infrastructure, cla: yes
