Repository GoogleForCreators/web-stories-wp, pull requests merged in 2022-07, with the labels that each got.

#11799 Editor: Replace deep clone dependency with native structured clone
  .browserslistrc
  babel.config.cjs
  package-lock.json
  packages/story-editor/package.json
  packages/story-editor/src/app/story/effects/useHistoryEntry.js
Labels: Type: Enhancement, Type: Code Quality, Pod: Prometheus, Package: Story Editor

#11857 Fixing PropType for ToggleButton
  packages/story-editor/src/components/toggleButton/index.js
Labels: Type: Code Quality, Pod: Pea, Package: Story Editor

#11867 Code Quality: Reference `@wordpress/data` stores by store definition
  .eslintrc
  package-lock.json
  packages/stories-block/package.json
  packages/stories-block/src/block/block-types/single-story/edit.js
  packages/stories-block/src/block/components/storyPicker/fetchSelectedStories.js
  packages/stories-block/src/block/components/storyPicker/selectStories.js
  packages/stories-block/src/block/components/storyPicker/storyPicker.js
Labels: Group: WordPress, Type: Code Quality, Pod: WP, Group: Blocks

#11868 ESLint: Add `@wordpress/i18n-no-flanking-whitespace` rule
  .eslintrc
  packages/i18n/src/translateToExclusiveList.js
  packages/i18n/src/translateToInclusiveList.js
  packages/story-editor/src/components/canvas/mediaRecordingLayer.js
  packages/story-editor/src/components/library/panes/media/local/deleteDialog.js
Labels: Type: Code Quality

#11775 Hotlinking: Allow story poster image to be hotlinked
  includes/Discovery.php
  includes/Experiments.php
  includes/Model/Story.php
  includes/REST_API/Stories_Base_Controller.php
  includes/Story_Post_Type.php
  includes/templates/admin/edit-story.php
  packages/design-system/src/components/mediaInput/index.js
  packages/e2e-tests/src/plugins/web-stories-hotlink.php
  packages/e2e-tests/src/specs/editor/media/hotlinking.js
  packages/stories-block/src/block/components/storiesPreview.js
  packages/stories-block/src/block/components/storyPicker/storyPreview.js
  packages/story-editor/src/app/story/actions/test/useAutoSave.js
  packages/story-editor/src/app/story/utils/getStoryPropsToSave.js
  packages/story-editor/src/app/story/utils/test/getStoryPropsToSave.js
  packages/story-editor/src/components/form/media.js
  packages/story-editor/src/components/form/useHotlink.js
  packages/story-editor/src/components/hotlinkModal/hotlinkModal.js
  packages/story-editor/src/components/hotlinkModal/useHotlinkModal.js
  packages/story-editor/src/components/hotlinkModal/utils.js
  packages/story-editor/src/components/publishModal/content/storyPreview.js
  packages/story-editor/src/components/publishModal/test/storyPreview.js
  packages/story-editor/src/types.js
  packages/wp-dashboard/src/api/constants/index.js
  packages/wp-dashboard/src/api/utils/reshapeStoryObject.js
  packages/wp-dashboard/src/api/utils/test/reshapeStoryObject.js
  packages/wp-story-editor/src/api/constants/index.js
  packages/wp-story-editor/src/api/pageTemplate.js
  packages/wp-story-editor/src/api/story.js
  packages/wp-story-editor/src/api/test/pageTemplates.js
  packages/wp-story-editor/src/api/utils/transformStoryResponse.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
  tests/phpunit/integration/tests/Discovery.php
  tests/phpunit/integration/tests/Model/Story.php
  tests/phpunit/integration/tests/REST_API/Stories_Controller.php
  tests/phpunit/integration/tests/Story_Post_Type.php
Labels: Type: Enhancement, P2, Group: Document Panel, Pod: WP, Package: Story Editor

#11837 Shortpixel Image Optimizer Incompatibility
  .phpstorm.meta.php
  includes/Integrations/ShortPixel.php
  includes/Plugin.php
  tests/phpunit/integration/tests/Integrations/ShortPixel.php
Labels: Type: Bug, Group: Integration, Group: WordPress, Pod: WP

#11829 Allow "conditionally" calling some custom hooks
  packages/story-editor/src/components/library/panes/media/local/dropDownMenu.js
  packages/story-editor/src/components/panels/shared/media/dropDownMenu.js
  packages/story-editor/src/components/panels/utils/dropDownKeyEvents.js
Labels: Type: Enhancement, Type: Code Quality, Pod: Prometheus, Group: Workspace

#11802 When removing a layer from a group, it can appear still inside the group
  packages/story-editor/src/app/rightClickMenu/items/layerUngroup.js
  packages/story-editor/src/app/story/useStoryReducer/actions.js
  packages/story-editor/src/app/story/useStoryReducer/reducer.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/addGroup.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/index.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/removeElementFromGroup.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/test/utils.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/utils.js
  packages/story-editor/src/app/story/useStoryReducer/test/addGroup.js
  packages/story-editor/src/app/story/useStoryReducer/test/removeElementFromGroup.js
  packages/story-editor/src/app/story/useStoryReducer/types.js
  packages/story-editor/src/components/panels/design/layer/layerList.js
Labels: Type: Bug, Pod: Prometheus, Group: Workspace, Group: Layers

#11849 Canvas: Show base color / blurhash while resource is loading
  packages/element-library/src/gif/display.js
  packages/element-library/src/media/display.js
  packages/element-library/src/media/imageDisplay.js
  packages/element-library/src/video/display.js
  packages/element-library/src/video/trim.js
  packages/story-editor/src/components/canvas/displayElement.js
  packages/story-editor/src/components/canvas/renderResourcePlaceholder.js
Labels: Type: Enhancement, Group: Media, P2, Elements: Video, Elements: Image, Group: Canvas, Pod: WP, Elements: GIF

#11792 Hotlinking: Allow Link icon to be hotlinked
  includes/Experiments.php
  packages/story-editor/src/components/canvas/pageAttachment/index.js
  packages/story-editor/src/components/elementLink/frame.js
  packages/story-editor/src/components/form/linkIcon.js
Labels: Type: Enhancement, Pod: WP, Group: Page Attachment

#11884 Fix layer re-arrangement inside groups using shortcuts
  packages/story-editor/src/app/canvas/useCanvasKeys.js
  packages/story-editor/src/app/canvas/utils/getLayerArrangementProps.js
  packages/story-editor/src/app/canvas/utils/test/getLayerArrangementProps.js
  packages/story-editor/src/app/story/useStoryReducer/actions.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/arrangeElement.js
  packages/story-editor/src/app/story/useStoryReducer/test/arrangeElement.js
Labels: Type: Bug, Pod: Prometheus

#11907 Refined tests for element rearrange
  packages/story-editor/src/app/story/useStoryReducer/reducers/arrangeElement.js
  packages/story-editor/src/app/story/useStoryReducer/test/arrangeElement.js
Labels: Type: Code Quality, Pod: Prometheus

#11905 Headings: Suggested edits to TextAccessibilityPanel
  packages/output/src/utils/getTextElementTagNames.js
  packages/story-editor/src/components/panels/design/textAccessibility/textAccessibility.js
Labels: Group: Style Panel, Group: Workspace

#11853 Canvas: Video poster not rendering in Safari
  .eslintrc
  packages/element-library/src/gif/display.js
  packages/element-library/src/media/util.js
  packages/element-library/src/video/display.js
  packages/element-library/src/video/trim.js
  packages/element-library/src/video/util.js
Labels: Group: Media, Elements: Video, Group: Canvas

#11851 Dashboard: Incorporate the rest of the filters into FiltersProvider
  packages/dashboard/src/app/views/exploreTemplates/content/index.js
  packages/dashboard/src/app/views/exploreTemplates/content/test/content.js
  packages/dashboard/src/app/views/exploreTemplates/filters/TemplateFiltersProvider/index.js
  packages/dashboard/src/app/views/exploreTemplates/filters/test/templateFiltersProvider.js
  packages/dashboard/src/app/views/exploreTemplates/filters/useTemplateFilters.js
  packages/dashboard/src/app/views/exploreTemplates/header/index.js
  packages/dashboard/src/app/views/exploreTemplates/header/test/header.js
  packages/dashboard/src/app/views/exploreTemplates/index.js
  packages/dashboard/src/app/views/exploreTemplates/karma/exploreTemplates.karma.js
  packages/dashboard/src/app/views/exploreTemplates/modal/templateDetails/karma/templateDetails.karma.js
  packages/dashboard/src/app/views/filters/provider.js
  packages/dashboard/src/app/views/filters/reducer.js
  packages/dashboard/src/app/views/filters/test/reducer.js
  packages/dashboard/src/app/views/filters/types.js
  packages/dashboard/src/app/views/myStories/content/index.js
  packages/dashboard/src/app/views/myStories/content/listView/index.js
  packages/dashboard/src/app/views/myStories/content/storiesView/index.js
  packages/dashboard/src/app/views/myStories/content/test/content.js
  packages/dashboard/src/app/views/myStories/content/test/storiesView.js
  packages/dashboard/src/app/views/myStories/filters/StoryFiltersProvider/author/useAuthorFilter.js
  packages/dashboard/src/app/views/myStories/filters/StoryFiltersProvider/index.js
  packages/dashboard/src/app/views/myStories/filters/StoryFiltersProvider/taxonomy/useTaxonomyFilters.js
  packages/dashboard/src/app/views/myStories/filters/test/provider.js
  packages/dashboard/src/app/views/myStories/filters/test/storyFiltersProvider.js
  packages/dashboard/src/app/views/myStories/filters/test/useAuthorFilter.js
  packages/dashboard/src/app/views/myStories/filters/test/useTaxonomyFilter.js
  packages/dashboard/src/app/views/myStories/filters/useStoryFilters.js
  packages/dashboard/src/app/views/myStories/header/index.js
  packages/dashboard/src/app/views/myStories/header/storyStatusToggle.js
  packages/dashboard/src/app/views/myStories/header/test/header.js
  packages/dashboard/src/app/views/myStories/index.js
  packages/dashboard/src/app/views/myStories/karma/myStories.karma.js
  packages/dashboard/src/app/views/shared/bodyViewOptions.js
  packages/dashboard/src/app/views/shared/pageHeading.js
  packages/dashboard/src/app/views/shared/sortDropDown.js
  packages/dashboard/src/components/interfaceSkeleton/index.js
  packages/dashboard/src/constants/stories.js
  packages/dashboard/src/constants/templates.js
  packages/dashboard/src/karma/apiProviderFixture.js
  packages/dashboard/src/utils/test/useStoryView.js
  packages/dashboard/src/utils/test/useTemplateView.js
  packages/dashboard/src/utils/useStoryView.js
  packages/dashboard/src/utils/useTemplateView.js
  packages/design-system/src/components/search/search.js
  packages/design-system/src/components/search/useSearch.js
  packages/wp-dashboard/src/api/story.js
Labels: Type: Enhancement, Pod: Pea, Package: Dashboard

#11887 Audio Recording
  packages/design-system/src/icons/camera_off.svg
  packages/design-system/src/icons/index.js
  packages/elements/src/types.js
  packages/story-editor/src/app/highlights/quickActions/useQuickActions.js
  packages/story-editor/src/app/highlights/states.js
  packages/story-editor/src/app/media/useUploadMedia.js
  packages/story-editor/src/app/media/utils/useFFmpeg.js
  packages/story-editor/src/app/uploader/test/useUploader.js
  packages/story-editor/src/app/uploader/useUploader.js
  packages/story-editor/src/components/canvas/mediaRecordingLayer.js
  packages/story-editor/src/components/library/panes/media/local/mediaRecording/mediaRecording.js
  packages/story-editor/src/components/mediaRecording/audio.js
  packages/story-editor/src/components/mediaRecording/constants.js
  packages/story-editor/src/components/mediaRecording/footer.js
  packages/story-editor/src/components/mediaRecording/index.js
  packages/story-editor/src/components/mediaRecording/karma/mediaRecording.karma.js
  packages/story-editor/src/components/mediaRecording/provider.js
  packages/story-editor/src/components/panels/document/backgroundAudio/backgroundAudio.js
  packages/story-editor/src/karma/fixture/containers/canvas.js
  packages/story-editor/src/karma/fixture/containers/library/index.js
  packages/story-editor/src/karma/fixture/containers/quickActionMenu.js
Labels: Type: Enhancement, Group: Media, Pod: Prometheus

#11880 Media: Add initial Tenor stickers support
  includes/Experiments.php
  packages/story-editor/src/app/media/media3p/constants.js
  packages/story-editor/src/app/media/media3p/providerConfiguration.js
  packages/story-editor/src/app/media/media3p/reducer.js
  packages/story-editor/src/app/media/media3p/useFetchCategoriesEffect.js
  packages/story-editor/src/app/media/media3p/useFetchMediaEffect.js
  packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js
  packages/story-editor/src/app/media/utils/test/getResourceFromMedia3p.js
  packages/story-editor/src/components/library/panes/media/common/innerElement.js
Labels: Type: Enhancement, Group: Media, Pod: WP, Group: 3P Media

#11926 AMP Sanitization: use `wp_replace_insecure_home_url` function
  includes/Renderer/Story/HTML.php
  tests/phpunit/integration/tests/Renderer/Story/HTML.php
Labels: P2, Group: WordPress, AMP Output, Pod: WP

#11915 Media: Extend list of transcodable videos
  packages/story-editor/src/app/media/constants.js
Labels: Type: Bug, Group: Media, Pod: WP

#11937 Media Hotlinking: Enable new features by default
  includes/Experiments.php
Labels: Type: Enhancement, Group: Media

#11893 Fix auto-setting rotated background
  packages/story-editor/src/app/rightClickMenu/useLayerSelect.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/useDrag.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/useResize.js
  packages/story-editor/src/components/canvas/test/singleSelectionMoveable.js
  packages/story-editor/src/components/canvas/utils/useFullbleedMediaAsBackground.js
  packages/story-editor/src/utils/isTargetCoveringContainer.js
  packages/story-editor/src/utils/useElementPolygon.js
Labels: Type: Bug

#11939 Fix background audio setting & mic-only device support
  packages/story-editor/src/app/highlights/states.js
  packages/story-editor/src/components/mediaRecording/footer.js
  packages/story-editor/src/components/mediaRecording/provider.js
  packages/story-editor/src/components/panels/design/pageBackgroundAudio/backgroundAudio.js
  packages/story-editor/src/components/panels/document/backgroundAudio/backgroundAudio.js
Labels: Type: Bug, Group: Media, Pod: Prometheus

#11961 Add changelog for v1.23.0
  readme.txt
Labels: Type: Release

#11964 Enable semantic headings UI by default
  includes/Experiments.php
Labels: Type: Enhancement, Group: Style Panel

#11963 Enable media recording feature by default
  includes/Experiments.php
Labels: Type: Enhancement

#11927 Webpack: Include React Refresh plugin for all React entry points
  webpack.config.cjs
Labels: Type: Infrastructure, Pod: WP, Group: Blocks

#11984 Panels: fix excessive tracking events
  packages/story-editor/src/components/panels/panel/panel.js
Labels: Type: Bug, Group: Style Panel, Group: Document Panel, Group: Telemetry

#11983 Fix Karma tests
  packages/story-editor/src/components/canvas/layout.js
  packages/story-editor/src/components/panels/design/textStyle/karma/stylePresets.karma.js
  packages/story-editor/src/constants/index.js
Labels: Type: Bug, Group: Canvas, Pod: Prometheus

#11982 Fix story poster meta fallback
  includes/Model/Story.php
  packages/wp-story-editor/src/api/story.js
  packages/wp-story-editor/src/api/test/story.js
  tests/phpunit/integration/tests/Model/Story.php
Labels: Type: Bug, Needs Tests

#11986 CI: Use number of re-run attempts for Percy nonce
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-karma-dashboard.yml
  .github/workflows/tests-karma-editor.yml
Labels: Type: Infrastructure, Pod: WP

#11962 CI: GitHub Actions Security Hardening
  .github/workflows/add-milestone.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/cleanup-pr-assets.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-storybook.yml
  .github/workflows/lint-css-js-md.yml
  .github/workflows/lint-i18n.yml
  .github/workflows/lint-php.yml
  .github/workflows/npm-release.yml
  .github/workflows/plugin-release.yml
  .github/workflows/scorecards.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-karma-dashboard.yml
  .github/workflows/tests-karma-editor.yml
  .github/workflows/tests-unit-js.yml
  .github/workflows/tests-unit-php.yml
  .github/workflows/update-browserslist.yml
  .github/workflows/update-google-fonts.yml
  .github/workflows/update-product-schema.yml
  .github/workflows/update-templates.yml
Labels: Type: Infrastructure, Pod: WP

#11913 Shopping: Support drag & drop from library
  packages/story-editor/src/components/library/panes/shared/libraryMoveable.js
  packages/story-editor/src/components/library/panes/shopping/constants.js
  packages/story-editor/src/components/library/panes/shopping/karma/shopping.karma.js
  packages/story-editor/src/components/library/panes/shopping/product.js
  packages/story-editor/src/components/library/panes/shopping/productImage.js
  packages/story-editor/src/components/library/panes/shopping/shoppingPane.js
Labels: Type: Enhancement, Pod: WP, Group: Library, Group: Shopping, Bug Bash: 1.22.0

#11966 Code Quality: remove `incrementalSearchDebounceMedia` experiment
  includes/Experiments.php
  packages/story-editor/src/components/library/common/searchInput.js
  packages/story-editor/src/components/library/common/test/searchInput.js
  packages/story-editor/src/components/library/panes/media/local/mediaPane.js
  packages/story-editor/src/components/library/panes/media/media3p/media3pPane.js
  packages/story-editor/src/flags.js
Labels: Type: Code Quality, Pod: WP

#12017 Add Jest test for custom font selection
  packages/wp-dashboard/src/components/editorSettings/customFonts/test/customFonts.js
Labels: Type: Infrastructure, Pod: WP

#12001 Editor: Fixed delay before trimming a new recording
  packages/story-editor/src/components/videoTrim/useVideoNode.js
Labels: Type: Bug, Pod: Prometheus

#12019 3P Media: Enable stickers support by default
  includes/Experiments.php
Labels: Type: Enhancement, Pod: WP, Group: 3P Media

#11782 E2E Tests: Fix and skip flakey tests, improve debug output
  .github/workflows/tests-e2e.yml
  package-lock.json
  package.json
  packages/e2e-test-utils/src/customFonts.js
  packages/e2e-test-utils/src/index.js
  packages/e2e-tests/src/config/bootstrap.js
  packages/e2e-tests/src/jest.config.js
  packages/e2e-tests/src/puppeteerEnvironment.js
  packages/e2e-tests/src/specs/dashboard/dashboard.js
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/shoppingProvider.js
  packages/e2e-tests/src/specs/dashboard/templates/useTemplate.js
  packages/e2e-tests/src/specs/editor/backgroundAudio.js
  packages/e2e-tests/src/specs/editor/editor.js
  packages/e2e-tests/src/specs/editor/fontCheck/fontCheckMetrics.js
  packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js
  packages/e2e-tests/src/specs/editor/pendingStories.js
  packages/e2e-tests/src/specs/editor/prePublishChecklist/adminUser.js
  packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js
  packages/e2e-tests/src/specs/editor/publishingFlow.js
  packages/e2e-tests/src/specs/editor/saveStory.js
  packages/e2e-tests/src/specs/editor/shopping/productMenu.js
  packages/e2e-tests/src/specs/editor/shopping/woocommerce.js
  packages/e2e-tests/src/specs/editor/statusCheck.js
  packages/e2e-tests/src/specs/editor/storyDetailsModal/adminUser.js
  packages/e2e-tests/src/specs/editor/taxonomy.js
  packages/e2e-tests/src/specs/wordpress/archive.js
  packages/e2e-tests/src/specs/wordpress/blockWidget.js
  packages/e2e-tests/src/specs/wordpress/corsCheck.js
  packages/e2e-tests/src/specs/wordpress/webStoriesBlock.js
  packages/e2e-tests/src/specs/wordpress/widget.js
  patches/puppeteer+14.1.1.patch
  patches/puppeteer+15.5.0.patch
Labels: Type: Infrastructure, Pod: WP

#12020 Code Quality: Remove `mediaRecording` feature flag code
  includes/Experiments.php
  packages/story-editor/src/app/rightClickMenu/menus/emptyStateMenu.js
  packages/story-editor/src/components/library/panes/media/local/mediaRecording/mediaRecording.js
Labels: Group: Media, Type: Code Quality, Pod: WP

#12027 Code Quality: Remove showSemanticHeadings feature flag code
  includes/Experiments.php
  packages/story-editor/src/components/panels/design/textAccessibility/textAccessibility.js
Labels: Type: Code Quality, Pod: WP

#12030 Fix issues with uploading and hotlinking story poster
  includes/Admin/Dashboard.php
  includes/REST_API/Stories_Controller.php
  includes/Story_Post_Type.php
  includes/templates/admin/edit-story.php
  packages/story-editor/src/app/story/actions/test/useAutoSave.js
  packages/story-editor/src/app/story/utils/getStoryPropsToSave.js
  packages/story-editor/src/app/story/utils/test/getStoryPropsToSave.js
  packages/story-editor/src/components/canvas/displayLayer.js
  packages/wp-dashboard/src/api/constants/index.js
  packages/wp-dashboard/src/api/utils/reshapeStoryObject.js
  packages/wp-dashboard/src/api/utils/test/reshapeStoryObject.js
  packages/wp-story-editor/src/api/constants/index.js
  packages/wp-story-editor/src/api/story.js
  packages/wp-story-editor/src/api/test/story.js
  packages/wp-story-editor/src/api/utils/transformStoryResponse.js
  tests/phpunit/integration/tests/REST_API/Stories_Controller.php
Labels: Type: Bug, Group: WordPress

#12031 Text Sets: make use of custom heading levels
  packages/text-sets/src/raw/cover.json
Labels: Type: Enhancement, Elements: Text, Pod: WP, Group: Text Sets, Bug Bash: 1.18.0

#12000 Media Recording: Add Pause/Resume Support
  packages/story-editor/src/components/mediaRecording/durationIndicator.js
  packages/story-editor/src/components/mediaRecording/footer.js
  packages/story-editor/src/components/mediaRecording/progressBar.js
  packages/story-editor/src/components/mediaRecording/provider.js
Labels: Type: Enhancement, Group: Media

#11940 Include border into the element selection line
  packages/element-library/src/text/edit.js
  packages/story-editor/src/app/canvas/canvasProvider.js
  packages/story-editor/src/app/canvas/utils/createPolygon.js
  packages/story-editor/src/components/canvas/displayElement.js
  packages/story-editor/src/components/canvas/editElement.js
  packages/story-editor/src/components/canvas/frameElement.js
  packages/story-editor/src/components/canvas/karma/selection.karma.js
  packages/story-editor/src/components/canvas/multiSelectionMoveable/index.js
  packages/story-editor/src/components/canvas/multiSelectionMoveable/useDrag.js
  packages/story-editor/src/components/canvas/multiSelectionMoveable/useResize.js
  packages/story-editor/src/components/canvas/multiSelectionMoveable/useRotate.js
  packages/story-editor/src/components/canvas/selectionCanvas.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/index.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/useResize.js
  packages/story-editor/src/components/panels/design/border/borderWidth.js
  packages/story-editor/src/components/panels/design/textStyle/karma/stylePresets.karma.js
  packages/story-editor/src/utils/useElementPolygon.js
  packages/units/src/dimensions.js
  packages/units/src/unitsProvider.js
Labels: Type: Enhancement, Pod: Prometheus, Group: Borders
