Repository GoogleForCreators/web-stories-wp, pull requests merged in 2022-11, with the labels that each got.

#12569 Code Quality: Move `prepare_links()` to its own method in taxonomies controller
  includes/REST_API/Stories_Taxonomies_Controller.php
Labels: PHP, Type: Code Quality

#12554 Add "Copy story data" button to error boundary screen
  packages/story-editor/src/components/errorBoundary/copyStoryDataToClipboard.js
  packages/story-editor/src/components/errorBoundary/errorActions.js
Labels: Type: Enhancement, Group: Settings, Pod: WP, Type: Support

#12561 Editor: Remove errant 'Edit' option from media menu
  packages/story-editor/src/components/form/linkIcon.js
  packages/story-editor/src/components/form/media.js
  packages/story-editor/src/components/panels/design/videoAccessibility/karma/videoPoster.karma.js
  packages/story-editor/src/components/panels/design/videoAccessibility/test/videoAccessibility.js
  packages/story-editor/src/karma/fixture/containers/designPanel/videoPoster.js
Labels: Type: Bug, Group: Links, Pod: WP, Group: Page Attachment

#12577 Global Page Advancement: use global values when creating templates
  includes/Admin/Dashboard.php
  packages/wp-dashboard/src/api/story.js
  tests/phpunit/integration/tests/Admin/Dashboard.php
Labels: Type: Enhancement, Pod: Prometheus

#12564 Block: Fix carousel width & whitespace issues
  packages/stories-block/src/css/common.css
  packages/stories-block/src/css/variables.css
  packages/stories-block/src/css/views/circles.css
Labels: Type: Bug, Group: Blocks

#12567 E2E tests: Ready for 6.1
  .github/workflows/tests-e2e.yml
  bin/local-env/install-wordpress.sh
  readme.txt
Labels: Type: Infrastructure, Pod: WP, Package: E2E Tests

#12602 Correctly use registered option defaults
  includes/Settings.php
  tests/phpunit/integration/tests/Admin/Editor.php
  tests/phpunit/integration/tests/Settings.php
Labels: Type: Bug, PHP, Group: WordPress, Pod: WP

#12607 Run unit tests only against PHP 7.4+
  .github/workflows/tests-unit-php.yml
Labels: Type: Infrastructure, Pod: WP

#12556 Video Trimming: Avoid crash due to missing `tracks` property
  packages/element-library/src/video/trim.js
Labels: Type: Bug, Group: Media, Elements: Video, Pod: WP

#12606 E2E Tests: Run against WordPress 5.9+
  .github/workflows/tests-e2e.yml
  bin/local-env/install-wordpress.sh
  packages/e2e-tests/src/specs/editor/shopping/productMenu.js
  packages/e2e-tests/src/specs/editor/shopping/woocommerce.js
  packages/e2e-tests/src/specs/wordpress/archive.js
  packages/e2e-tests/src/specs/wordpress/blockWidget.js
Labels: Type: Infrastructure, Type: Task, Pod: WP, Package: E2E Tests

#12608 Run unit tests against WordPress 5.9+
  .github/workflows/tests-unit-php.yml
Labels: Type: Infrastructure, Pod: WP

#12617 Unit tests: use PHP 8.0 for coverage report
  .github/workflows/tests-unit-php.yml
Labels: Type: Infrastructure, Pod: WP

#12611 Correctly filter revision fields for story revisions
  includes/Story_Revisions.php
  tests/phpunit/integration/tests/Story_Revisions.php
Labels: Type: Bug, Group: WordPress, Pod: WP

#12627 TypeScript: `dashboard` config provider
  packages/dashboard/package.json
  packages/dashboard/src/app/api/test/apiProvider.js
  packages/dashboard/src/app/config/configProvider.tsx
  packages/dashboard/src/app/config/context.ts
  packages/dashboard/src/app/config/index.ts
  packages/dashboard/src/app/config/useConfig.ts
  packages/dashboard/src/getDefaultConfig.js
  packages/dashboard/src/karma/fixture.js
  packages/dashboard/src/testUtils/renderWithProviders.js
  packages/dashboard/src/types/configProvider.ts
  packages/dashboard/tsconfig.json
  packages/templates/src/index.ts
  tsconfig.json
Labels: Type: Infrastructure, Type: Code Quality, Pod: Prometheus

#12647 Update doc block link to amp var substitutions
  includes/Analytics.php
Labels: Type: Code Quality

#12623 Fix Karma tests
  packages/story-editor/src/components/canvas/shoppingPageAttachment/index.js
  packages/story-editor/src/components/floatingMenu/elements/karma/shopping.karma.js
  packages/story-editor/src/components/library/panes/text/karma/textSets.cuj.karma.js
  patches/html-to-image+1.10.8.patch
Labels: Type: Bug, Pod: Prometheus

#12645 Fix Story Duration Default
  packages/story-editor/src/app/story/effects/useLoadStory.js
  packages/story-editor/src/components/panels/document/pageAdvancement/pageAdvancement.js
  packages/story-editor/src/components/panels/shared/generalPageAdvancement.js
  packages/wp-dashboard/src/components/editorSettings/pageAdvancement/index.js
Labels: Type: Bug, Group: Settings, Pod: Prometheus

#12578 Autosaves: Delete local backup after auto-saving to DB
  packages/story-editor/src/components/localAutoSaveHandler/localAutoSave.js
  packages/story-editor/src/components/localAutoSaveHandler/test/localAutoSaveHandler.js
Labels: Type: Bug, Pod: Prometheus

#12612 Bump `Requires PHP` value
  .github/workflows/lint-php.yml
  composer.json
  composer.lock
  phpcs.xml.dist
  web-stories.php
Labels: Type: Infrastructure, Pod: WP

#12616 Use `rest_namespace` for post types and taxonomies
  includes/Post_Type_Base.php
  includes/REST_API/Font_Controller.php
  includes/REST_API/Stories_Autosaves_Controller.php
  includes/REST_API/Stories_Base_Controller.php
  includes/REST_API/Stories_Lock_Controller.php
  includes/REST_API/Stories_Media_Controller.php
  includes/REST_API/Stories_Taxonomies_Controller.php
  includes/REST_API/Stories_Terms_Controller.php
Labels: Type: Code Quality

#12613 Bump `Requires at least` value
  composer.json
  phpcs.xml.dist
  readme.txt
  web-stories.php
Labels: Type: Infrastructure, Pod: WP

#12615 Block: Use `getUsers` with capability query
  includes/REST_API/Stories_Users_Controller.php
  packages/stories-block/src/block/components/storyPicker/selectStories.js
  tests/phpunit/integration/tests/REST_API/Stories_Users_Controller.php
Labels: Type: Enhancement, P2, Group: WordPress, Type: Code Quality, Pod: WP, Group: Blocks

#12675 Rest route pulls using wrong post_type
  includes/Post_Type_Base.php
Labels: Type: Bug, Pod: WP

#12671 Update get authors call to use capabilities
  includes/Admin/Dashboard.php
  includes/Admin/Editor.php
  includes/templates/admin/edit-story.php
  packages/wp-dashboard/src/api/authors.js
  packages/wp-story-editor/src/api/authors.js
Labels: Pod: WP

#12677 Fix recent PHPStan errors
  composer.lock
  includes/Admin/TinyMCE.php
  includes/Assets.php
  includes/Embed_Base.php
  includes/KSES.php
  includes/Media/Media_Source_Taxonomy.php
  includes/Story_Revisions.php
Labels: Type: Code Quality

#12649 Block: Fix stories selector styling issues
  packages/stories-block/src/block/edit.css
Labels: Type: Bug, Pod: WP, Group: Blocks

#12673 TypeScript: Convert `APIProvider`
  packages/story-editor/src/app/api/apiProvider.tsx
  packages/story-editor/src/app/api/context.ts
  packages/story-editor/src/app/api/index.ts
  packages/story-editor/src/app/api/useAPI.ts
  packages/story-editor/src/app/config/context.ts
  packages/story-editor/src/types/apiProvider.ts
  packages/story-editor/src/types/configProvider.ts
  packages/story-editor/tsconfig.json
Labels: Type: Infrastructure, Type: Code Quality, Pod: Prometheus

#12684 Eyedropper: handle rgb string when getting the eyedropper color
  packages/story-editor/src/components/eyedropper/useEyeDropperApi.js
  patches/html-to-image+1.10.8.patch
Labels: Type: Bug, Pod: Prometheus

#12710 Media Hotlinking: trim leading/trailing whitespace
  packages/story-editor/src/components/hotlinkModal/useHotlinkModal.js
Labels: Type: Bug, Group: Media, Pod: WP

#12706 Improve AMP sanitization for title tags and meta descriptions
  includes/AMP/Integration/AMP_Story_Sanitizer.php
  includes/AMP/Sanitization.php
  includes/AMP/Story_Sanitizer.php
  includes/AMP/Traits/Sanitization_Utils.php
  includes/Admin/Admin.php
  includes/Admin/Cross_Origin_Isolation.php
  includes/Decoder.php
  includes/Discovery.php
  includes/Integrations/AMP.php
  includes/Integrations/ShortPixel.php
  includes/KSES.php
  includes/Migrations/Yoast_Reindex_Stories.php
  includes/REST_API/Hotlinking_Controller.php
  includes/Renderer/Story/HTML.php
  tests/phpunit/integration/tests/Admin/Cross_Origin_Isolation.php
  tests/phpunit/integration/tests/Discovery.php
  tests/phpunit/unit/tests/AMP/Story_Sanitizer.php
Labels: Type: Enhancement, Group: Integration, Group: WordPress, AMP Output, Pod: WP

#12653 Do not unnecessarily fetch stories/taxonomies
  packages/dashboard/src/app/views/exploreTemplates/filters/useTemplateFilters.js
  packages/dashboard/src/app/views/exploreTemplates/index.js
  packages/dashboard/src/app/views/filters/provider.js
  packages/dashboard/src/app/views/filters/reducer.js
  packages/dashboard/src/app/views/myStories/index.js
  packages/dashboard/src/components/interfaceSkeleton/index.js
  packages/dashboard/src/karma/apiProviderFixture.js
  packages/wp-dashboard/src/components/telemetryBanner/index.js
Labels: Type: Enhancement, Group: Dashboard, Type: Performance

#12674 TypeScript: convert `HistoryProvider`
  packages/design-system/package.json
  packages/design-system/src/components/keyboard/context.ts
  packages/design-system/src/components/keyboard/index.js
  packages/design-system/src/components/keyboard/index.ts
  packages/design-system/src/components/keyboard/keyboard.tsx
  packages/design-system/src/components/keyboard/keys.ts
  packages/design-system/src/components/keyboard/utils.ts
  packages/design-system/src/index.js
  packages/design-system/src/theme/index.js
  packages/design-system/src/types.ts
  packages/design-system/src/types/keyboard.ts
  packages/design-system/tsconfig.json
  packages/react/src/useBatchingCallback.ts
  packages/story-editor/src/app/history/context.ts
  packages/story-editor/src/app/history/historyProvider.tsx
  packages/story-editor/src/app/history/index.ts
  packages/story-editor/src/app/history/reducer.ts
  packages/story-editor/src/app/history/test/reducer.js
  packages/story-editor/src/app/history/useHistory.ts
  packages/story-editor/src/app/history/useHistoryReducer.ts
  packages/story-editor/src/types/historyProvider.ts
  packages/story-editor/src/utils/usePreventWindowUnload.ts
  packages/story-editor/tsconfig.json
  tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12736 Shopping: change product object type
  includes/REST_API/Products_Controller.php
Labels: Type: Bug, Group: Integration, Group: WordPress, Pod: WP

#12713 Show a success message when restoring a revision
  includes/Admin/Editor.php
  packages/wp-story-editor/src/components/index.js
  packages/wp-story-editor/src/components/revisionMessage/index.js
  packages/wp-story-editor/src/components/revisionMessage/revisionMessage.js
  packages/wp-story-editor/src/components/revisionMessage/test/revisionMessage.js
  packages/wp-story-editor/src/index.js
Labels: Type: Enhancement, Group: WordPress, Pod: WP, Group: Workspace, Package: WP Story Editor

#12730 TypeScript: Convert `currentUserProvider` provider
  package-lock.json
  packages/story-editor/src/app/currentUser/context.ts
  packages/story-editor/src/app/currentUser/currentUserProvider.tsx
  packages/story-editor/src/app/currentUser/index.ts
  packages/story-editor/src/app/currentUser/useCurrentUser.ts
  packages/story-editor/src/types/configProvider.ts
  packages/story-editor/src/types/currentUserProvider.ts
  packages/story-editor/tsconfig.json
  packages/wp-story-editor/src/components/postLock/postLock.js
Labels: Type: Code Quality, Package: Story Editor

#12708 Block: Fix issues with rearranging stories in Firefox
  packages/stories-block/src/block/components/storyPicker/itemOverlay.js
  packages/stories-block/src/block/components/storyPicker/sortStories.js
  packages/stories-block/src/block/components/storyPicker/storyPreview.js
Labels: Type: Bug, Group: WordPress, Browser Issues, Pod: WP, Group: Blocks

#12741 Code Quality: Remove `enablePostLockingTakeOver` feature flag code
  includes/Experiments.php
  packages/wp-story-editor/src/components/postLock/postLock.js
  packages/wp-story-editor/src/components/postLock/postLockDialog.js
  packages/wp-story-editor/src/components/postLock/stories/postLockDialog.js
  packages/wp-story-editor/src/components/postLock/test/postLock.js
Labels: Group: WordPress, Type: Code Quality, Pod: WP, Group: Story Locking

#12759 Fix incorrect `<meta charset>` tags
  includes/AMP/Output_Buffer.php
  includes/Renderer/Story/HTML.php
  tests/phpunit/integration/tests/Renderer/Story/HTML.php
Labels: Type: Bug, Group: WordPress, AMP Output, Pod: WP
