Repository GoogleForCreators/web-stories-wp, pull requests merged in 2022-09, with the labels that each got.

#12199 Enable autosaves for non-drafts
  packages/story-editor/src/components/autoSaveHandler/index.js
Labels: Type: Enhancement, Group: WordPress, Group: Workspace

#12169 Convert `moveable` package to TypeScript
  .eslintrc
  package-lock.json
  package.json
  packages/design-system/package.json
  packages/design-system/src/index.ts
  packages/design-system/src/theme/index.ts
  packages/design-system/tsconfig.json
  packages/moveable/package.json
  packages/moveable/src/areEventsDragging.ts
  packages/moveable/src/cropStyle.ts
  packages/moveable/src/index.ts
  packages/moveable/src/moveStyle.ts
  packages/moveable/src/moveable.tsx
  packages/moveable/src/overlay/context.ts
  packages/moveable/src/overlay/index.tsx
  packages/moveable/src/overlay/withOverlay.tsx
  packages/moveable/src/typings/styled-components.d.ts
  packages/moveable/src/typings/svg-imports.d.ts
  packages/moveable/tsconfig.json
  packages/react/package.json
  packages/react/src/useCombinedRefs.ts
  tsconfig.json
Labels: Type: Infrastructure, Type: Code Quality, Package: Moveable

#12200 Convert `patterns` package to TypeScript
  packages/patterns/package.json
  packages/patterns/src/convertToCSS.ts
  packages/patterns/src/createSolid.ts
  packages/patterns/src/createSolidFromString.ts
  packages/patterns/src/generatePatternStyles.ts
  packages/patterns/src/getHexFromSolid.ts
  packages/patterns/src/getHexFromSolidArray.ts
  packages/patterns/src/getHexFromValue.ts
  packages/patterns/src/getOpaquePattern.ts
  packages/patterns/src/getPreviewText.ts
  packages/patterns/src/getSolidFromHex.ts
  packages/patterns/src/hasGradient.ts
  packages/patterns/src/hasOpacity.ts
  packages/patterns/src/index.ts
  packages/patterns/src/isHexColorString.ts
  packages/patterns/src/isPatternEqual.ts
  packages/patterns/src/types.ts
  packages/patterns/tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12213 Convert `fonts` package to TypeScript
  packages/fonts/package.json
  packages/fonts/src/constants.ts
  packages/fonts/src/index.ts
  packages/fonts/src/types.ts
  packages/fonts/src/utils/getFontCSS.ts
  packages/fonts/src/utils/getGoogleFontURL.ts
  packages/fonts/src/utils/index.ts
  packages/fonts/tsconfig.json
  tsconfig.json
Labels: Type: Infrastructure, Type: Code Quality, Package: Fonts

#12212 Convert `url` package to TypeScript
  packages/url/package.json
  packages/url/src/addQueryArgs.ts
  packages/url/src/index.ts
  packages/url/src/url.ts
  packages/url/tsconfig.json
  tsconfig.json
Labels: Type: Infrastructure, Type: Code Quality, Package: URL

#12222 Code: Fixed references for `patterns` package
  packages/patterns/tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12218 Code: Converted `dom` package to TypeScript
  packages/dom/package.json
  packages/dom/src/ensureFontLoaded.ts
  packages/dom/src/escapeHTML.ts
  packages/dom/src/index.ts
  packages/dom/src/loadStylesheet.ts
  packages/dom/src/stripHTML.ts
  packages/dom/tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12202 Convert `transform` package to TypeScript
  packages/react/src/context.ts
  packages/transform/package.json
  packages/transform/src/context.ts
  packages/transform/src/index.ts
  packages/transform/src/transformProvider.tsx
  packages/transform/src/types.ts
  packages/transform/src/useTransform.ts
  packages/transform/src/useTransformHandler.ts
  packages/transform/tsconfig.json
  tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12209 Remove `objectWithout` usage from `elements` package
  .eslintrc
  package-lock.json
  packages/design-system/src/utils/index.js
  packages/design-system/src/utils/objectWithout.js
  packages/elements/package.json
  packages/elements/src/utils/createNewElement.js
  packages/elements/src/utils/duplicatePage.js
  packages/patterns/src/getOpaquePattern.ts
Labels: Type: Code Quality, Package: Design System, Package: Elements

#12224 Code: Converted `date` package to TypeScript
  packages/date/package.json
  packages/date/src/convertFormatString.ts
  packages/date/src/format.ts
  packages/date/src/formatDate.ts
  packages/date/src/formatDistance.ts
  packages/date/src/formatTime.ts
  packages/date/src/getOptions.ts
  packages/date/src/getRelativeDisplayDate.ts
  packages/date/src/getTimeZoneString.ts
  packages/date/src/index.ts
  packages/date/src/is12Hour.ts
  packages/date/src/settings.ts
  packages/date/src/test/getTimeZoneString.js
  packages/date/src/toUTCDate.ts
  packages/date/src/typings/date-fns/index.d.ts
  packages/date/tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12237 Dashboard: Remove elements dependency
  packages/wp-dashboard/package.json
  packages/wp-dashboard/src/index.js
Labels: Group: WordPress, Type: Code Quality, Pod: WP, Package: WP Dashboard

#12242 Videos: Set poster image quality to 0.82.
  packages/media/src/getCanvasBlob.ts
Labels: Type: Enhancement, Group: Media, Elements: Video

#12243 Fixed layer karma tests
  packages/story-editor/src/components/canvas/karma/selection.karma.js
  packages/story-editor/src/components/floatingMenu/karma/video.karma.js
  packages/story-editor/src/components/panels/layer/karma/layer.karma.js
Labels: Type: Code Quality, Pod: Prometheus

#12247 TypeScript: Convert `wp-utils` package
  packages/wp-utils/package.json
  packages/wp-utils/src/bindToCallbacks.ts
  packages/wp-utils/src/index.ts
  packages/wp-utils/src/snakeToCamelCase.ts
  packages/wp-utils/tsconfig.json
  tsconfig.json
Labels: Type: Infrastructure, Type: Code Quality

#12217 Media: Remove media frame on close
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/useMediaPicker.js
Labels: Group: Media, Group: WordPress, Type: Code Quality, Pod: WP

#12197 Editor: Add link to revisions
  includes/Admin/Editor.php
  includes/REST_API/Stories_Controller.php
  includes/templates/admin/edit-story.php
  packages/design-system/src/icons/history.svg
  packages/design-system/src/icons/index.js
  packages/story-editor/src/app/story/actions/useSaveStory.js
  packages/story-editor/src/app/story/effects/useLoadStory.js
  packages/wp-story-editor/src/api/constants/index.js
  packages/wp-story-editor/src/api/story.js
  packages/wp-story-editor/src/api/utils/transformStoryResponse.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
  packages/wp-story-editor/src/components/documentPane/publish/test/publish.js
Labels: Type: Enhancement, Group: WordPress, Pod: WP, Group: Workspace

#12267 Fix preview issues with auto-drafts
  packages/story-editor/src/app/story/actions/useSaveStory.js
  packages/story-editor/src/components/checklist/checks/storyAmpValidationErrors.js
Labels: Type: Bug, Group: WordPress, Group: Workspace

#12268 Fix TinyMCE classic editor integration
  package-lock.json
  packages/tinymce-button/package.json
  packages/tinymce-button/src/components/Modal.js
  packages/tinymce-button/src/components/test/Modal.js
  packages/tinymce-button/src/containers/Modal.js
  packages/tinymce-button/src/index.js
  packages/tinymce-button/src/store/default.js
  packages/tinymce-button/src/store/index.js
  packages/tinymce-button/src/store/name.js
  packages/tinymce-button/src/store/selectors.js
  packages/tinymce-button/src/store/test/default.js
  packages/tinymce-button/src/store/test/name.js
  packages/tinymce-button/src/store/test/selectors.js
  packages/tinymce-button/src/utils/globals.js
  packages/tinymce-button/src/utils/index.js
  packages/tinymce-button/src/utils/test/index.js
Labels: Type: Bug, Pod: WP, Group: Classic Editor, Package: TinyMCE Button

#12266 Make floating menu direction-aware
  packages/story-editor/src/components/floatingMenu/layer.js
Labels: Type: Bug, Pod: Prometheus

#12298 Add changelog for v1.25.0
  readme.txt
Labels: Type: Documentation

#12299 Fix null destructuring
  packages/element-library/src/text/edit.js
Labels: Type: Bug, Elements: Text, Pod: Prometheus

#12067 Media Recording: Add Background Blur
  package-lock.json
  packages/dashboard/src/karma/fixture.js
  packages/design-system/src/icons/background_blur.svg
  packages/design-system/src/icons/background_blur_off.svg
  packages/design-system/src/icons/index.js
  packages/design-system/src/utils/localStore.js
  packages/media/src/index.ts
  packages/story-editor/package.json
  packages/story-editor/src/app/highlights/quickActions/useQuickActions.js
  packages/story-editor/src/components/canvas/karma/keys.karma.js
  packages/story-editor/src/components/canvas/mediaRecordingLayer.js
  packages/story-editor/src/components/library/panes/pageTemplates/karma/defaultPageTemplates.karma.js
  packages/story-editor/src/components/library/panes/pageTemplates/karma/savedPageTemplates.karma.js
  packages/story-editor/src/components/mediaRecording/blur.js
  packages/story-editor/src/components/mediaRecording/components.js
  packages/story-editor/src/components/mediaRecording/constants.js
  packages/story-editor/src/components/mediaRecording/footer.js
  packages/story-editor/src/components/mediaRecording/playbackMedia.js
  packages/story-editor/src/components/mediaRecording/provider.js
  packages/story-editor/src/components/mediaRecording/settingsModal.js
  packages/story-editor/src/components/mediaRecording/useTrim.js
  packages/story-editor/src/components/secondaryPopup/index.js
  packages/story-editor/src/karma/element-library/text/edit.karma.js
  packages/story-editor/src/karma/fixture/fixture.js
  tests/js/setup-mocks.js
Labels: Type: Enhancement, Group: Media, Pod: Prometheus

#12214 Improve story appearance on the revisions screen
  .phpstorm.meta.php
  includes/Model/Story.php
  includes/Plugin.php
  includes/Story_Post_Type.php
  includes/Story_Revisions.php
  includes/templates/frontend/single-web-story.php
  tests/phpunit/integration/tests/Model/Story.php
  tests/phpunit/integration/tests/Story_Post_Type.php
  tests/phpunit/integration/tests/Story_Revisions.php
Labels: Type: Enhancement, PHP, Group: WordPress

#12156 Media: Video Cropping Prototype
  includes/Experiments.php
  packages/story-editor/src/app/media/local/useContextValueProvider.js
  packages/story-editor/src/app/media/useUploadMedia.js
  packages/story-editor/src/app/media/utils/useFFmpeg.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/constants.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/reducer.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/test/useMediaUploadQueue.js
  packages/story-editor/src/app/media/utils/useProcessMedia.js
  packages/story-editor/src/app/rightClickMenu/constants.js
  packages/story-editor/src/app/rightClickMenu/hooks/useLayerActions.js
  packages/story-editor/src/app/rightClickMenu/menus/foregroundMediaMenu.js
  packages/story-editor/src/utils/getCropParams.js
  packages/story-editor/src/utils/isOffCanvas.js
  packages/story-editor/src/utils/test/getCropParams.js
  packages/story-editor/src/utils/test/isOffCanvas.js
Labels: Group: Media, Elements: Video, Pod: WP, Group: Video Optimization

#12303 Code Quality: Remove used file
  packages/story-editor/src/components/panels/design/videoOptions/useVideoElementTranscoding.js
Labels: Type: Code Quality

#12272 Improved Autosaves: Enable new feature by default
  includes/Experiments.php
Labels: Type: Enhancement, Pod: WP

#12161 Run tests against PHP 8.2
  .github/workflows/tests-unit-php.yml
  tests/phpunit/integration/tests/Shopping/Shopify_Query.php
  tests/phpunit/unit/tests/Shopping/Mock_Product.php
Labels: PHP, Group: WordPress, Pod: WP

#12296 E2E Tests Improvements
  .github/workflows/tests-e2e.yml
  package-lock.json
  package.json
  packages/e2e-test-utils/src/addTextElement.js
  packages/e2e-test-utils/src/visitSettings.js
  packages/e2e-tests/src/config/bootstrap.js
  packages/e2e-tests/src/jest.config.js
  packages/e2e-tests/src/specs/dashboard/documentTitle.js
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/dataRemovalSettings.js
  packages/e2e-tests/src/specs/dashboard/templates/useTemplate.js
  packages/e2e-tests/src/specs/editor/floatingMenu.js
  packages/e2e-tests/src/specs/editor/fontCheck/fontCheck.js
  packages/e2e-tests/src/specs/editor/fontCheck/fontCheckMetrics.js
  packages/e2e-tests/src/specs/editor/media/hotlinking.js
  packages/e2e-tests/src/specs/editor/media/insert3PMedia.js
  packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js
  packages/e2e-tests/src/specs/editor/passwordProtected.js
  packages/e2e-tests/src/specs/editor/prePublishChecklist/adminUser.js
  packages/e2e-tests/src/specs/editor/storyDetailsModal/adminUser.js
  packages/e2e-tests/src/specs/editor/storyDetailsModal/contributorUser.js
  packages/e2e-tests/src/specs/integrations/amp.js
  packages/e2e-tests/src/specs/wordpress/adminMenu.js
  packages/e2e-tests/src/utils/constants.js
  packages/jest-resolver/src/index.cjs
  patches/expect-puppeteer+6.1.1.patch
  patches/puppeteer+15.5.0.patch
Labels: Type: Infrastructure, Pod: WP

#12317 Fix revisions count check
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
Labels: Type: Bug, Group: WordPress, Pod: WP

#12316 Media Recording: Fix Canvas audio/controls
  packages/story-editor/src/components/mediaRecording/playPauseButton.js
  packages/story-editor/src/components/mediaRecording/playbackMedia.js
  packages/story-editor/src/components/mediaRecording/videoMode.js
Labels: Type: Bug, Group: Media, Pod: Prometheus

#12328 Code: Removed enabled feature flag for design menu
  includes/Experiments.php
  packages/story-editor/src/components/canvas/canvasLayout.js
  packages/story-editor/src/components/canvas/karma/elementKeyboardNavigation.js
  packages/story-editor/src/components/floatingMenu/elements/karma/border.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/borderRadius.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/flip.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/loop.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/more.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/opacity.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/shopping.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/text.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/textAlign.karma.js
  packages/story-editor/src/components/floatingMenu/karma/floatingMenu.karma.js
  packages/story-editor/src/components/floatingMenu/karma/image.karma.js
  packages/story-editor/src/components/floatingMenu/karma/shape.karma.js
  packages/story-editor/src/components/floatingMenu/karma/sticker.karma.js
  packages/story-editor/src/components/floatingMenu/karma/text.karma.js
  packages/story-editor/src/components/floatingMenu/karma/video.karma.js
  packages/story-editor/src/components/library/panes/shopping/karma/shopping.karma.js
Labels: Type: Code Quality, Pod: Prometheus

#12327 Code: Removed unused feature flags
  includes/Experiments.php
  packages/story-editor/src/components/checklist/karma/checklist.karma.js
  packages/story-editor/src/components/mediaRecording/karma/mediaRecording.karma.js
  packages/story-editor/src/components/panels/design/animation/effectChooserDropdown/dropdownConstants.js
  packages/story-editor/src/components/panels/design/animation/effectChooserDropdown/effectChooserDropdown.js
  packages/story-editor/src/components/panels/design/textStyle/karma/textStyle.other.karma.js
Labels: Type: Code Quality, Pod: Prometheus

#12329 Code: Removed enabled feature flag for new layer features
  includes/Experiments.php
  packages/story-editor/src/app/rightClickMenu/items/layerLock.js
  packages/story-editor/src/app/rightClickMenu/items/layerName.js
  packages/story-editor/src/app/rightClickMenu/items/layerUngroup.js
  packages/story-editor/src/app/rightClickMenu/menus/groupMenu.js
  packages/story-editor/src/app/rightClickMenu/menus/multipleElementsMenu.js
  packages/story-editor/src/components/canvas/karma/selection.karma.js
  packages/story-editor/src/components/panels/layer/elementLayer.js
  packages/story-editor/src/components/panels/layer/elementLayerActions.js
  packages/story-editor/src/components/panels/layer/groupLayer.js
  packages/story-editor/src/components/panels/layer/groupLayerActions.js
  packages/story-editor/src/components/panels/layer/karma/layer.karma.js
  packages/story-editor/src/components/panels/layer/layer.js
Labels: Type: Code Quality, Pod: Prometheus

#12318 Editor and output: Custom page advancement
  includes/Experiments.php
  packages/design-system/src/utils/panelTypes.js
  packages/output/src/page.js
  packages/output/src/story.js
  packages/output/src/test/page.js
  packages/story-editor/src/components/panels/design/index.js
  packages/story-editor/src/components/panels/design/pageAdvancement/customPageAdvancement.js
  packages/story-editor/src/components/panels/design/pageAdvancement/index.js
  packages/story-editor/src/components/panels/document/pageAdvancement/pageAdvancement.js
  packages/story-editor/src/components/panels/shared/generalPageAdvancement.js
  packages/story-editor/src/components/style/getDesignPanelsForSelection.js
  packages/story-editor/src/components/style/useDesignPanels.js
Labels: Type: Enhancement, Pod: Prometheus

#12321 Media: Clean up linked post meta on attachment deletion
  includes/Media/Video/Muting.php
  includes/Media/Video/Optimization.php
  tests/phpunit/integration/tests/Media/Video/Muting.php
  tests/phpunit/integration/tests/Media/Video/Optimization.php
Labels: Group: Media, Group: WordPress, Pod: WP

#12338 Fix audio recording issues
  packages/story-editor/src/components/mediaRecording/audio.js
  packages/story-editor/src/components/mediaRecording/provider.js
Labels: Type: Bug, Group: Media, Pod: Prometheus

#12355 Editor: Fix BlurHash generation
  packages/media/src/preloadImage.ts
  packages/story-editor/src/utils/getBlurHashFromImage.js
Labels: Type: Bug, Group: Media, Pod: WP

#12348 Checklist: Fix AMP validation false positive
  packages/story-editor/src/components/checklist/checks/storyAmpValidationErrors.js
Labels: Type: Bug, Group: Editor Checklist

#12346 Dashboard: Fix template insertion
  includes/REST_API/Stories_Base_Controller.php
  includes/Story_Post_Type.php
  package-lock.json
  packages/e2e-tests/src/specs/dashboard/templates/useTemplate.js
  packages/wp-dashboard/package.json
  packages/wp-dashboard/src/api/story.js
  tests/phpunit/integration/tests/Story_Post_Type.php
Labels: Type: Bug, Group: Templates

#12349 Video Cropping: Add post meta for original
  .phpstorm.meta.php
  includes/Media/Cropping.php
  includes/Plugin.php
  includes/uninstall.php
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/reducer.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/test/reducer.js
  packages/story-editor/src/app/media/utils/useProcessMedia.js
  packages/wp-story-editor/src/api/media.js
  tests/phpunit/integration/tests/Media/Cropping.php
  tests/phpunit/integration/tests/Uninstall.php
Labels: Group: Media, Group: WordPress, Pod: WP

#12344 Code: Improved codebase by minimizing package interdependency
  packages/animation/package.json
  packages/animation/src/effects/backgroundPan/index.js
  packages/animation/src/effects/backgroundPanAndZoom/index.js
  packages/animation/src/effects/backgroundZoom/index.js
  packages/animation/src/utils/index.js
  packages/element-library/package.json
  packages/element-library/src/media/edit.js
  packages/element-library/src/media/scalePanel.js
  packages/elements/src/types.js
  packages/elements/src/utils/getElementOffsets.js
  packages/elements/src/utils/getElementOrigin.js
  packages/elements/src/utils/index.js
  packages/elements/src/utils/test/getElementOrigin.js
  packages/media/src/index.ts
  packages/rich-text/src/usePasteTextContent.ts
  packages/story-editor/src/app/canvas/useCanvasCopyPaste.js
  packages/story-editor/src/components/canvas/editElement.js
  packages/story-editor/src/components/panels/design/animation/animation.js
  packages/story-editor/src/components/videoTrim/generateVideoStrip.js
  packages/story-editor/src/components/videoTrim/useRailBackground.js
Labels: Type: Code Quality, Pod: Prometheus

#12364 Lightbox: ensure story player always has dimensions
  packages/stories-block/src/css/lightbox.css
Labels: Type: Bug, Group: Blocks

#12366 Shopping: Move products logic to story model
  includes/Discovery.php
  includes/Model/Story.php
  includes/Shopping/Product.php
  includes/Shopping/Product_Meta.php
  tests/phpunit/integration/tests/Discovery.php
  tests/phpunit/integration/tests/Model/Story.php
  tests/phpunit/integration/tests/Shopping/Product.php
Labels: Type: Code Quality, Group: Shopping

#12353 Date Picker: show timezone abbreviation if possible
  includes/Locale.php
  packages/date/src/settings.ts
  packages/story-editor/src/components/form/dateTime/timePicker.js
  packages/story-editor/src/components/form/dateTime/timeZone.js
  tests/phpunit/integration/tests/Locale.php
Labels: Type: Enhancement, Group: Document Panel, Group: Workspace

#12356 Code Quality: Remove `tenorStickers` feature flag code
  includes/Experiments.php
  packages/story-editor/src/app/media/media3p/providerConfiguration.js
Labels: Type: Code Quality, Pod: WP

#12403 Custom Fonts: Remove posts on uninstall
  includes/uninstall.php
  tests/phpunit/integration/tests/Uninstall.php
Labels: Type: Bug, Group: WordPress, Group: Fonts, Pod: WP

#12404 Karma: Fix main branch tests
  packages/story-editor/src/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  packages/story-editor/src/karma/fixture/containers/library/index.js
Labels: Type: Infrastructure, Pod: Prometheus

#12357 Code Quality: Remove `improvedAutosaves` feature flag code
  includes/Admin/Editor.php
  includes/Experiments.php
  packages/story-editor/src/components/autoSaveCheck/index.js
  packages/story-editor/src/components/autoSaveHandler/index.js
  packages/story-editor/src/components/autoSaveHandler/test/autoSaveHandler.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
Labels: Type: Code Quality, Pod: WP
