Repository GoogleForCreators/web-stories-wp, pull requests merged in 2022-12, with the labels that each got.

#12738 Layers visibility
  packages/animation/src/components/provider.tsx
  packages/animation/src/types/element.ts
  packages/design-system/src/icons/index.js
  packages/design-system/src/icons/visibility.svg
  packages/design-system/src/icons/visibility_off.svg
  packages/elements/src/types/element.ts
  packages/masks/src/frame.tsx
  packages/output/src/element.js
  packages/output/src/page.js
  packages/output/src/utils/getAutoAdvanceAfter.js
  packages/output/src/utils/getLongestMediaElement.js
  packages/story-editor/src/app/rightClickMenu/constants.js
  packages/story-editor/src/app/rightClickMenu/items/index.js
  packages/story-editor/src/app/rightClickMenu/items/layerHide.js
  packages/story-editor/src/app/rightClickMenu/menus/foregroundMediaMenu.js
  packages/story-editor/src/app/rightClickMenu/menus/productMenu.js
  packages/story-editor/src/app/rightClickMenu/menus/shapeMenu.js
  packages/story-editor/src/app/rightClickMenu/menus/stickerMenu.js
  packages/story-editor/src/app/rightClickMenu/menus/textMenu.js
  packages/story-editor/src/components/canvas/displayElement.js
  packages/story-editor/src/components/canvas/displayLayer.js
  packages/story-editor/src/components/canvas/frameElement.js
  packages/story-editor/src/components/canvas/pagemenu/pageMenu.js
  packages/story-editor/src/components/canvas/selectionCanvas.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/index.js
  packages/story-editor/src/components/panels/layer/elementLayer.js
  packages/story-editor/src/components/panels/layer/elementLayerActions.js
  packages/story-editor/src/components/panels/layer/groupLayer.js
  packages/story-editor/src/components/panels/layer/groupLayerActions.js
  packages/story-editor/src/components/panels/layer/karma/layer.karma.js
  packages/story-editor/src/components/panels/layer/layer.js
  packages/story-editor/src/components/panels/layer/layerComponents.js
Labels: Type: Enhancement, Pod: Prometheus, Group: Layers

#12780 Enables page level advancement settings by default
  includes/Experiments.php
Labels: Type: Enhancement, Pod: Prometheus

#12786 Remove `dg/bypass-finals` dependency
  composer.json
  composer.lock
  tests/phpunit/integration/bootstrap.php
Labels: Type: Infrastructure, Pod: WP

#12757 TypeScript: Layout Provider from `story-editor` package
  packages/design-system/src/theme/constants/index.ts
  packages/design-system/src/theme/helpers/scrollbar.js
  packages/design-system/src/types.ts
  packages/story-editor/src/app/layout/context.js
  packages/story-editor/src/app/layout/context.ts
  packages/story-editor/src/app/layout/index.ts
  packages/story-editor/src/app/layout/layoutProvider.tsx
  packages/story-editor/src/app/layout/useCarouselDrawer.ts
  packages/story-editor/src/app/layout/useLayout.ts
  packages/story-editor/src/app/layout/useZoomSetting.ts
  packages/story-editor/src/components/canvas/layout.js
  packages/story-editor/src/components/canvas/pageSideMenu.js
  packages/story-editor/src/components/canvas/test/useInsertElement.js
  packages/story-editor/src/components/canvas/useInsertElement.js
  packages/story-editor/src/components/colorPicker/colorPicker.js
  packages/story-editor/src/components/eyedropper/index.js
  packages/story-editor/src/components/footer/carousel/carouselDrawer.js
  packages/story-editor/src/components/footer/carousel/carouselDrawerIcon.js
  packages/story-editor/src/components/footer/carousel/carouselLayout.js
  packages/story-editor/src/components/footer/carousel/useCarouselScroll.js
  packages/story-editor/src/components/footer/useFooterHeight.js
  packages/story-editor/src/components/footer/zoomSelector/zoomSelector.js
  packages/story-editor/src/components/library/panes/media/common/styles.js
  packages/story-editor/src/components/library/panes/shared/libraryMoveable.js
  packages/story-editor/src/constants/index.ts
  packages/story-editor/src/types/index.ts
  packages/story-editor/src/types/layoutProvider.ts
  packages/story-editor/tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12790 Fix `user_posts_count_public` return type
  includes/REST_API/Stories_Users_Controller.php
Labels: Type: Bug, Group: WordPress, Pod: WP

#12761 TypeScript: convert `fontProvider`
  packages/element-library/tsconfig.json
  packages/elements/src/types/data.ts
  packages/elements/src/types/element.ts
  packages/fonts/package.json
  packages/fonts/src/types.ts
  packages/output/tsconfig.json
  packages/story-editor/src/app/font/actions/useLoadFontFiles.ts
  packages/story-editor/src/app/font/constants.ts
  packages/story-editor/src/app/font/context.ts
  packages/story-editor/src/app/font/fontProvider.tsx
  packages/story-editor/src/app/font/index.ts
  packages/story-editor/src/app/font/test/actions/useLoadFontFiles.ts
  packages/story-editor/src/app/font/types.ts
  packages/story-editor/src/app/font/useFont.js
  packages/story-editor/src/app/font/useFont.ts
  packages/story-editor/src/components/fontPicker/index.js
  packages/story-editor/src/components/library/panes/text/textSets/stories/textSet.js
  packages/story-editor/src/components/library/panes/text/textSets/test/textSet.js
  packages/story-editor/src/components/library/panes/text/textSets/test/textSetsPane.js
  packages/story-editor/src/components/library/test/text/textPane.js
  packages/story-editor/src/components/panels/design/textStyle/test/fontPicker.js
  packages/story-editor/src/components/panels/design/textStyle/test/textBox.js
  packages/story-editor/src/components/panels/design/textStyle/test/textStyle.js
  packages/story-editor/src/karma/fixture/fixture.js
  packages/story-editor/src/utils/cleanForSlug.ts
  packages/story-editor/tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12815 Floating menu: fix sub-menu font size
  packages/design-system/src/components/contextMenu/components/item.js
  packages/story-editor/src/components/floatingMenu/elements/settings.js
Labels: Type: Bug, Pod: Prometheus

#12808 Text Style: Remove incorrect scrollbar
  packages/story-editor/src/components/panels/design/textStyle/stylePresets.js
Labels: Type: Bug, Pod: Prometheus

#12841 Workspace: Fix type guards to avoid crash when adding media
  package-lock.json
  packages/elements/package.json
  packages/elements/src/utils/elementIs.ts
  packages/story-editor/src/app/story/useStoryReducer/reducers/addElements.ts
  packages/story-editor/src/app/story/useStoryReducer/reducers/deleteElementsByResourceId.ts
  packages/story-editor/src/app/story/useStoryReducer/reducers/duplicateGroup.ts
  packages/story-editor/src/app/story/useStoryReducer/reducers/setBackgroundElement.ts
  packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByFontFamily.ts
  packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByResourceId.ts
  packages/story-editor/src/app/story/useStoryReducer/test/setBackgroundElement.js
Labels: Type: Bug, Pod: Prometheus

#12851 Improve heading check in tag name sanitizer
  includes/AMP/Traits/Sanitization_Utils.php
  tests/phpunit/unit/tests/AMP/Story_Sanitizer.php
Labels: Type: Bug, AMP Output

#12865 Fix `isBackgroundable` check
  packages/elements/src/utils/elementIs.ts
Labels: Elements, Type: Code Quality, Package: Elements

#12810 Quick Actions: Open style tab after adding a text element
  packages/story-editor/src/app/highlights/quickActions/test/useQuickActions.js
  packages/story-editor/src/app/highlights/quickActions/useQuickActions.js
  packages/story-editor/src/components/canvas/karma/quickActions.karma.js
Labels: Type: Bug, Pod: Prometheus

#12840 Fixed tooltips for element links
  packages/design-system/src/components/tooltip/index.js
  packages/design-system/src/icons/external_link.svg
  packages/design-system/src/icons/index.js
  packages/story-editor/src/components/elementLink/frame.js
  packages/url/src/test/url.ts
  packages/url/src/url.ts
Labels: Type: Bug, Pod: Prometheus

#12867 Hide tooltip while design menu settings are open
  packages/story-editor/src/components/floatingMenu/elements/settings.js
  packages/story-editor/src/components/floatingMenu/elements/shared/icon.js
Labels: Type: Bug, Pod: Prometheus

#12791 Code Quality: Use `noop` in more places
  packages/story-editor/src/app/font/context.ts
  packages/story-editor/src/app/helpCenter/context.ts
  packages/story-editor/src/app/layout/context.ts
  packages/story-editor/src/components/canvas/useInsertElement.js
  packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/check.js
  packages/story-editor/src/components/colorPicker/colorPicker.js
  packages/story-editor/src/components/colorPicker/header.js
  packages/story-editor/src/components/colorPicker/useDeleteColor.js
  packages/story-editor/src/components/form/context.js
  packages/story-editor/src/components/helpCenter/menu/tips.js
  packages/story-editor/src/components/helpCenter/navigator/utils.js
  packages/story-editor/src/components/helpCenter/toggle/index.js
  packages/story-editor/src/components/library/panes/media/common/mediaElement.js
  packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js
  packages/story-editor/src/components/mediaRecording/audio.js
  packages/story-editor/src/components/mediaRecording/playPauseButton.js
  packages/story-editor/src/components/mediaRecording/playbackMedia.js
  packages/story-editor/src/components/mediaRecording/stories/settingsModal.js
  packages/story-editor/src/components/panels/design/pageBackground/pageBackground.js
  packages/story-editor/src/components/panels/design/textStyle/textStyle.js
  packages/story-editor/src/components/panels/shared/media/audioPlayer.js
  packages/story-editor/src/components/panels/shared/media/backgroundAudioPanelContent.js
  packages/story-editor/src/components/panels/shared/media/captionsPanelContent.js
  packages/story-editor/src/components/previewPage/previewPage.js
  packages/story-editor/src/components/reorderable/reorderableSeparator.js
  packages/story-editor/src/components/reorderable/useReordering.js
  packages/story-editor/src/components/styleManager/header.js
  packages/story-editor/src/components/tabview/index.js
  packages/story-editor/src/components/videoTrim/slider.js
  packages/story-editor/src/components/videoTrim/useVideoNode.js
  packages/story-editor/src/utils/usePreventWindowUnload.ts
Labels: Type: Code Quality

#12852 Fixed error in video play/pause button after trimming
  packages/element-library/src/video/playPauseButton.js
Labels: Type: Bug, Pod: Prometheus
