Repository GoogleForCreators/web-stories-wp, pull requests merged in 2022-03, with the labels that each got.

#10753 Shapes: avoid excess styled-components classes
  packages/story-editor/src/elements/shape/icon.js
Labels: Type: Code Quality, Pod: Pea

#10755 Karma: Remove front pattern from config
  karma-story-editor.config.cjs
Labels: Type: Infrastructure, Type: Code Quality, Pod: Pea

#10603 Links: Add special handling for Instagram when retrieving metadata
  includes/REST_API/Link_Controller.php
  tests/phpunit/integration/tests/REST_API/Link_Controller.php
Labels: P2, Group: WordPress, Group: Links, Group: Document Panel, Pod: WP

#10756 Remove ESLint no-shadow patch
  .eslintrc
  package-lock.json
  package.json
  patches/eslint+8.8.0.dev.patch
Labels: Type: Infrastructure, Type: Code Quality, Pod: WP

#10736 Performance tracking: verify `events` entry type is supported
  packages/story-editor/src/utils/usePerformanceTracking.js
Labels: Type: Bug, Pod: Prometheus

#10739 Improve Semantic Headings Algorithm
  includes/AMP/Traits/Sanitization_Utils.php
  packages/story-editor/src/output/utils/getTextElementTagNames.js
  packages/story-editor/src/output/utils/test/getTextElementTagNames.js
  tests/phpunit/unit/tests/AMP/Story_Sanitizer.php
Labels: Type: Enhancement, Elements: Text

#10759 Floating menu: Replace media button
  packages/story-editor/src/components/floatingMenu/elements/index.js
  packages/story-editor/src/components/floatingMenu/elements/karma/swapMedia.karma.js
  packages/story-editor/src/components/floatingMenu/elements/swapImage.js
  packages/story-editor/src/components/floatingMenu/elements/swapMedia.js
  packages/story-editor/src/components/floatingMenu/menus/image.js
  packages/story-editor/src/components/floatingMenu/menus/video.js
  packages/story-editor/src/karma/fixture/containers/designMenu.js
Labels: Type: Enhancement, Pod: Prometheus

#10758 Semantic Headings: Remove feature flag code completely
  includes/AMP/Integration/AMP_Story_Sanitizer.php
  includes/AMP/Sanitization.php
  includes/AMP/Story_Sanitizer.php
  includes/AMP/Traits/Sanitization_Utils.php
  includes/Experiments.php
  includes/Integrations/AMP.php
  packages/story-editor/src/output/page.js
  tests/phpunit/unit/tests/AMP/Story_Sanitizer.php
Labels: Type: Code Quality, Pod: WP

#10763 Karma: Fix flakey Percy snapshots due to mutating config
  package-lock.json
  packages/dashboard/src/dashboard.js
  packages/dashboard/src/getDefaultConfig.js
  packages/dashboard/src/karma/integrationLayerTesting/config.karma.js
  packages/story-editor/src/components/canvas/pageAttachment/test/pageAttachment.js
  packages/story-editor/src/components/form/color/test/color.js
  packages/story-editor/src/components/form/color/test/colorInput.js
  packages/story-editor/src/getDefaultConfig.js
  packages/story-editor/src/karma/integrationLayerTesting/config.karma.js
  packages/story-editor/src/storyEditor.js
Labels: Pod: Pea

#10765 Background Audio: Enable new features by default
  includes/Experiments.php
  packages/story-editor/src/output/page.js
  packages/story-editor/src/output/test/page.js
  packages/wp-story-editor/src/api/utils/getResourceFromAttachment.js
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/utils/getResourceFromMediaPicker.js
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/utils/test/getResourceFromMediaPicker.js
Labels: Type: Enhancement, Pod: WP

#10794 Code Quality: Don’t set `webStories.domReady` global
  includes/templates/admin/dashboard.php
  includes/templates/admin/edit-story.php
  packages/wp-dashboard/src/index.js
  packages/wp-story-editor/src/index.js
Labels: Group: WordPress, Type: Code Quality

#10731 New Story Details Modal: Upload/Edit Featured Media From Cover Preview
  packages/design-system/src/components/mediaInput/constants.js
  packages/design-system/src/components/mediaInput/index.js
  packages/story-editor/src/components/publishModal/content/storyPreview.js
  packages/story-editor/src/components/publishModal/karma/publishModal.karma.js
  packages/story-editor/src/components/publishModal/test/content.js
  packages/story-editor/src/components/publishModal/test/storyPreview.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
Labels: Type: Enhancement, Pod: Pea, Package: Story Editor

#10786 Floating Menu: add font size functionality
  packages/story-editor/src/components/floatingMenu/elements/fontSize.js
  packages/story-editor/src/components/floatingMenu/elements/karma/text.karma.js
  packages/story-editor/src/components/panels/design/textStyle/font.js
Labels: Type: Enhancement, P1, Group: Canvas, Pod: Pea, Group: Workspace

#10712 Video Trimming: Don't change state for other instances
  packages/story-editor/src/app/media/local/useContextValueProvider.js
  packages/story-editor/src/app/media/useUploadMedia.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/reducer.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/test/useMediaUploadQueue.js
  packages/story-editor/src/app/media/utils/useProcessMedia.js
  packages/story-editor/src/components/panels/design/videoOptions/test/videoOptions.js
  packages/story-editor/src/components/panels/design/videoOptions/videoOptions.js
Labels: Type: Enhancement, Group: Media, Pod: WP

#10801 Telemetry: track whether WooCommerce is active
  includes/Tracking.php
Labels: Type: Enhancement, Group: Telemetry

#10780 Insertion Library: Fix menu focus when using keyboard
  packages/story-editor/src/components/library/panes/media/common/insertionMenu.js
  packages/story-editor/src/components/library/panes/media/common/mediaElement.js
  packages/story-editor/src/components/library/panes/media/local/dropDownMenu.js
Labels: Type: Enhancement, Accessibility, Pod: Prometheus

#10785 Editor: Added loop control to design menu
  packages/story-editor/src/components/floatingMenu/elements/karma/loop.karma.js
  packages/story-editor/src/components/floatingMenu/elements/loop.js
  packages/story-editor/src/components/panels/shared/loopPanelContent.js
  packages/story-editor/src/karma/fixture/containers/designMenu.js
  packages/story-editor/src/karma/fixture/containers/designPanel/index.js
  packages/story-editor/src/karma/fixture/containers/designPanel/videoOptions.js
Labels: Type: Enhancement, Pod: Prometheus

#10807 Design System: Allow variable width for context menu
  packages/design-system/src/components/contextMenu/index.js
  packages/design-system/src/components/contextMenu/menu.js
  packages/story-editor/src/components/canvas/emptyStateLayer.js
Labels: Type: Enhancement, Pod: Pea, Group: Design System, Group: Context Menu

#10764 Saved Templates: remove virtual scroll
  packages/story-editor/src/components/library/panes/pageTemplates/defaultPageTemplate.js
  packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplateList.js
  packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplates.js
  packages/story-editor/src/components/library/panes/pageTemplates/savedPageTemplate.js
  packages/story-editor/src/components/library/panes/pageTemplates/savedTemplates.js
  packages/story-editor/src/components/library/panes/pageTemplates/templateList.js
  packages/story-editor/src/components/library/panes/shared/index.js
  packages/story-editor/src/utils/useRovingTabIndex/index.js
  packages/story-editor/src/utils/useRovingTabIndex/nestedNavigation.js
Labels: Type: Bug, Type: Code Quality, Pod: Pea

#10795 Story Locking: Enable baseline implementation by default
  includes/Experiments.php
Labels: Type: Enhancement, Group: WordPress, Pod: WP, Group: Story Locking

#10796 Quick Action Menus: Remove Newly Redundant Actions
  packages/story-editor/src/app/highlights/quickActions/test/useQuickActions.js
  packages/story-editor/src/app/highlights/quickActions/useQuickActions.js
  packages/story-editor/src/components/canvas/karma/quickActions.karma.js
Labels: Type: Enhancement, Pod: Pea, Group: Workspace, Package: Story Editor

#10760 UI Simplification: Move the right sidebar functionality to the left sidebar as tabs
  packages/story-editor/src/app/highlights/provider.js
  packages/story-editor/src/app/highlights/states.js
  packages/story-editor/src/components/canvas/karma/backgroundCopyPaste.karma.js
  packages/story-editor/src/components/canvas/karma/fullbleedMediaAsBackground.karma.js
  packages/story-editor/src/components/canvas/karma/keys.karma.js
  packages/story-editor/src/components/canvas/karma/quickActions.karma.js
  packages/story-editor/src/components/canvas/karma/rightClickMenu.karma.js
  packages/story-editor/src/components/canvas/karma/selection.karma.js
  packages/story-editor/src/components/colorPicker/karma/colorPicker.karma.js
  packages/story-editor/src/components/colorPicker/karma/eyedropper.karma.js
  packages/story-editor/src/components/dropTargets/karma/dropTarget.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/flip.karma.js
  packages/story-editor/src/components/footer/carousel/karma/carouselDrawer.karma.js
  packages/story-editor/src/components/form/color/colorInput.js
  packages/story-editor/src/components/inspector/constants.js
  packages/story-editor/src/components/inspector/index.js
  packages/story-editor/src/components/inspector/inspectorProvider.js
  packages/story-editor/src/components/layout/index.js
  packages/story-editor/src/components/library/libraryProvider.js
  packages/story-editor/src/components/library/panes/pageTemplates/karma/savedPageTemplates.karma.js
  packages/story-editor/src/components/library/panes/text/karma/textPane.karma.js
  packages/story-editor/src/components/library/panes/text/karma/textSets.cuj.karma.js
  packages/story-editor/src/components/panels/design/alignment/karma/alignment.karma.js
  packages/story-editor/src/components/panels/design/animation/karma/animation.karma.js
  packages/story-editor/src/components/panels/design/border/karma/border.karma.js
  packages/story-editor/src/components/panels/design/filter/karma/filter.karma.js
  packages/story-editor/src/components/panels/design/layer/karma/layer.karma.js
  packages/story-editor/src/components/panels/design/link/karma/link.karma.js
  packages/story-editor/src/components/panels/design/pageBackground/karma/pageBackground.karma.js
  packages/story-editor/src/components/panels/design/sizePosition/karma/borderRadius.karma.js
  packages/story-editor/src/components/panels/design/sizePosition/karma/sizePosition.karma.js
  packages/story-editor/src/components/panels/design/textStyle/karma/contrast.karma.js
  packages/story-editor/src/components/panels/design/textStyle/karma/stylePresets.karma.js
  packages/story-editor/src/components/panels/design/textStyle/karma/textStyle.other.karma.js
  packages/story-editor/src/components/panels/design/textStyle/stylePresets.js
  packages/story-editor/src/components/panels/design/videoAccessibility/karma/videoPoster.karma.js
  packages/story-editor/src/components/workspace/index.js
  packages/story-editor/src/constants/index.js
  packages/story-editor/src/elements/text/karma/edit.karma.js
  packages/story-editor/src/karma/copyAndPaste.cuj.karma.js
  packages/story-editor/src/karma/duplicate.cuj.karma.js
  packages/story-editor/src/karma/fixture/containers/inspector.js
  packages/story-editor/src/karma/richText/inlineSelection.karma.js
  packages/story-editor/src/karma/richText/inlineStyleOverride.karma.js
  packages/story-editor/src/karma/richText/multiSelection.karma.js
  packages/story-editor/src/karma/richText/singleSelection.karma.js
Labels: Type: Enhancement, Pod: Prometheus, Group: Workspace

#10810 Code Quality: Camel case arguments of media callbacks
  packages/story-editor/src/app/media/utils/test/useProcessMedia.js
  packages/story-editor/src/app/media/utils/useDetectBaseColor.js
  packages/story-editor/src/app/media/utils/useDetectBlurhash.js
  packages/story-editor/src/app/media/utils/useDetectVideoHasAudio.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js
  packages/story-editor/src/app/media/utils/useProcessMedia.js
  packages/story-editor/src/app/media/utils/useUploadVideoFrame.js
  packages/story-editor/src/app/uploader/useUploader.js
  packages/story-editor/src/components/library/panes/media/local/mediaEditDialog.js
  packages/story-editor/src/components/library/panes/pageTemplates/savedPageTemplate.js
  packages/story-editor/src/components/library/test/mediaEditDialog.js
  packages/wp-story-editor/src/api/media.js
  packages/wp-story-editor/src/api/test/media.js
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/useMediaPicker.js
Labels: Type: Code Quality, Package: Story Editor, Package: WP Story Editor

#10814 Code Quality: Camel case arguments of user callbacks
  packages/story-editor/src/app/currentUser/currentUserProvider.js
  packages/story-editor/src/app/helpCenter/provider.js
  packages/story-editor/src/app/media/utils/test/useFFmpeg.js
  packages/story-editor/src/app/media/utils/useFFmpeg.js
  packages/story-editor/src/components/library/panes/media/local/videoOptimizationDialog.js
  packages/story-editor/src/components/panels/design/videoOptions/test/videoOptions.js
  packages/story-editor/src/karma/fixture/fixture.js
  packages/wp-story-editor/src/api/user.js
Labels: Type: Code Quality, Package: Story Editor, Package: WP Story Editor

#10805 Update Composer dependencies and PHPStan configuration
  composer.json
  composer.lock
  includes/AMP/Optimization.php
  includes/AMP/Traits/Sanitization_Utils.php
  includes/Infrastructure/ServiceContainer/SimpleServiceContainer.php
  phpstan.neon.dist
  tests/phpstan/src/GetTermsDynamicFunctionReturnTypeExtension.php
  tests/phpstan/src/ServiceContainerDynamicReturnTypeExtension.php
  tests/phpstan/src/ServicesDynamicReturnTypeExtension.php
  tests/phpunit/integration/tests/AMP/Sanitization.php
Labels: Type: Infrastructure, Dependencies, Pod: WP

#10737 Media: Use `react-photo-album` for media library
  package-lock.json
  packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js
  packages/story-editor/package.json
  packages/story-editor/src/components/library/panes/media/common/innerElement.js
  packages/story-editor/src/components/library/panes/media/common/mediaGallery.js
  packages/story-editor/src/components/library/panes/media/common/styles.js
  packages/story-editor/src/components/library/panes/media/common/test/paginatedMediaGallery.js
  packages/story-editor/src/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  packages/story-editor/src/components/library/panes/media/media3p/test/accessibility.js
  packages/story-editor/src/components/library/panes/media/media3p/test/media3pPane.js
  patches/react-photo-gallery+8.0.0.patch
Labels: Type: Enhancement, Group: Media, Dependencies, Group: Library

#10548 Video Element: Extract reusable captions component
  packages/story-editor/src/elements/video/captions.js
  packages/story-editor/src/elements/video/display.js
  packages/story-editor/src/elements/video/output.js
  packages/story-editor/src/elements/video/trim.js
Labels: Elements: Video, Type: Code Quality

#10830 Add tests for fonts used in templates / text sets
  .github/workflows/tests-unit-js.yml
  packages/templates/src/test/raw.js
  packages/text-sets/src/test/raw.js
Labels: Group: Templates, Type: Infrastructure, Group: Fonts, Pod: WP, Group: Text Sets

#10766 Story Details Modal: Publish + Checklist Button Parity
  packages/e2e-tests/src/specs/editor/pendingStories.js
  packages/e2e-tests/src/specs/editor/storyDetailsModal/adminUser.js
  packages/e2e-tests/src/specs/editor/storyDetailsModal/contributorUser.js
  packages/story-editor/src/components/audioPlayer/index.js
  packages/story-editor/src/components/checklist/checkpointContext/checkpointContext.js
  packages/story-editor/src/components/form/tags/tag.js
  packages/story-editor/src/components/header/buttons/buttonWithChecklistWarning.js
  packages/story-editor/src/components/header/buttons/publish.js
  packages/story-editor/src/components/header/buttons/test/publish.js
  packages/story-editor/src/components/panels/shared/backgroundAudioPanelContent.js
  packages/story-editor/src/components/publishModal/content/checklistButton.js
  packages/story-editor/src/components/publishModal/header/index.js
  packages/story-editor/src/components/publishModal/publishModal.js
  packages/story-editor/src/components/publishModal/stories/index.js
  packages/story-editor/src/components/publishModal/test/header.js
  packages/story-editor/src/constants/zIndex.js
  packages/wp-story-editor/src/components/header/buttons/test/buttons.js
Labels: Type: Bug, Pod: Pea, Story Details

#10854 Prepare 1.18.1 release
  packages/wp-story-editor/src/api/utils/getResourceFromAttachment.js
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/utils/getResourceFromMediaPicker.js
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/utils/test/getResourceFromMediaPicker.js
  readme.txt
Labels: Type: Release

#10856 Editor: Fixed layer order of design menu relative to edit layer
  packages/story-editor/src/components/floatingMenu/menu.js
Labels: Type: Bug, Pod: Prometheus

#10818 Add `jsconfig.json` configuration file
  .distignore
  .phpstorm.config.js
  jsconfig.json
Labels: Type: Infrastructure, Pod: WP

#10784 Editor: Added video transcoding buttons to design menu
  packages/design-system/src/icons/muted.svg
  packages/story-editor/src/app/media/utils/useVideoElementTranscoding.js
  packages/story-editor/src/components/floatingMenu/elements/mute.js
  packages/story-editor/src/components/floatingMenu/elements/test/mute.js
  packages/story-editor/src/components/floatingMenu/elements/test/trim.js
  packages/story-editor/src/components/floatingMenu/elements/trim.js
  packages/story-editor/src/components/library/panes/media/common/innerElement.js
  packages/story-editor/src/components/panels/design/videoOptions/useVideoElementTranscoding.js
  packages/story-editor/src/components/panels/design/videoOptions/videoOptions.js
Labels: Type: Enhancement, Pod: Prometheus

#10844 Floating menu: Text color
  packages/story-editor/src/components/floatingMenu/elements/karma/text.karma.js
  packages/story-editor/src/components/floatingMenu/elements/shared/color.js
  packages/story-editor/src/components/floatingMenu/elements/textColor.js
  packages/story-editor/src/components/floatingMenu/layer.js
  packages/story-editor/src/components/form/color/colorInput.js
  packages/story-editor/src/karma/fixture/containers/designMenu.js
Labels: Type: Enhancement

#10860 Floating Menu: Font Size, fix text element selection size
  packages/story-editor/src/components/floatingMenu/elements/fontSize.js
Labels: Type: Bug, Pod: Pea, Group: Floating Menu

#10848 Split FontPicker into two
  packages/story-editor/src/components/fontPicker/index.js
  packages/story-editor/src/components/panels/design/textStyle/font.js
  packages/story-editor/src/components/panels/design/textStyle/test/textBox.js
  packages/story-editor/src/components/panels/design/textStyle/test/textStyle.js
  packages/story-editor/src/components/panels/shared/test/_utils.js
  packages/story-editor/src/components/storyFontPicker/index.js
Labels: Group: Fonts, Type: Code Quality, Group: Design Panel

#10823 Publish Modal: Fix issues with apostrophes in site name
  includes/AMP/Traits/Sanitization_Utils.php
  includes/Admin/Editor.php
  includes/Model/Story.php
  tests/phpunit/integration/tests/Admin/Editor.php
Labels: Type: Bug, Group: WordPress, AMP Output, Type: Code Quality, Group: Workspace

#10874 Floating Menus: Deduplicate Replace Media
  packages/story-editor/src/components/floatingMenu/elements/index.js
  packages/story-editor/src/components/floatingMenu/elements/karma/swapMedia.karma.js
  packages/story-editor/src/components/floatingMenu/elements/swapMedia.js
  packages/story-editor/src/components/floatingMenu/menus/image.js
  packages/story-editor/src/components/floatingMenu/menus/video.js
Labels: Type: Enhancement, Group: Canvas, Pod: Pea, Group: Workspace, Group: Floating Menu

#10861 Floating Menu: Render Depth Resolved
  packages/design-system/src/components/contextMenu/contextMenu.js
  packages/design-system/src/components/contextMenu/styled.js
  packages/story-editor/src/components/canvas/editLayer.js
  packages/story-editor/src/components/canvas/layout.js
  packages/story-editor/src/components/canvas/navLayer.js
  packages/story-editor/src/components/canvas/pageSideMenu.js
  packages/story-editor/src/components/checklist/checklist.js
  packages/story-editor/src/components/floatingMenu/elements/karma/text.karma.js
  packages/story-editor/src/components/floatingMenu/menu.js
  packages/story-editor/src/components/footer/carousel/carouselLayout.js
  packages/story-editor/src/components/footer/primaryMenu.js
  packages/story-editor/src/components/helpCenter/index.js
  packages/story-editor/src/components/keyboardShortcutsMenu/index.js
  packages/story-editor/src/constants/zIndex.js
Labels: Type: Bug, Pod: Pea, Group: Floating Menu

#10840 Floating Menus: Add Font Family
  packages/design-system/src/components/datalist/container.js
  packages/design-system/src/components/datalist/datalist.js
  packages/design-system/src/components/datalist/list/list.js
  packages/design-system/src/components/datalist/list/styled.js
  packages/story-editor/src/components/floatingMenu/elements/fontFamily.js
  packages/story-editor/src/components/fontPicker/index.js
  packages/story-editor/src/components/panels/design/textStyle/font.js
  packages/story-editor/src/components/panels/design/textStyle/karma/textStyle.other.karma.js
  packages/story-editor/src/elements/text/util.js
Labels: Type: Enhancement, Group: Canvas, Pod: Pea, Group: Workspace, Group: Floating Menu

#10719 UI Simplification: Allow applying Presets
  includes/Experiments.php
  packages/story-editor/src/components/library/panes/text/fontPreview.js
  packages/story-editor/src/components/library/panes/text/karma/savedStyles.karma.js
  packages/story-editor/src/components/library/panes/text/karma/textPane.karma.js
  packages/story-editor/src/components/library/panes/text/stylePresets/stylePresets.js
  packages/story-editor/src/components/library/panes/text/textPresets.js
  packages/story-editor/src/components/panels/design/layer/karma/layer.karma.js
  packages/story-editor/src/components/panels/design/textStyle/karma/stylePresets.karma.js
  packages/story-editor/src/components/panels/design/textStyle/karma/textStyle.other.karma.js
  packages/story-editor/src/karma/richText/_utils.js
  packages/story-editor/src/utils/presetUtils.js
Labels: Type: Enhancement, Pod: Prometheus

#10881 Use deterministic image sources for fixtures
  __static__/asteroid.png
  __static__/beach.jpg
  __static__/blue-marble.jpg
  __static__/curiosity.jpg
  __static__/earth.jpg
  __static__/featured-media-1.png
  __static__/featured-media-2.png
  __static__/featured-media-3.png
  __static__/mars.jpg
  __static__/ranger9.png
  __static__/saturn.jpg
  __static__/transparent.png
  packages/dashboard/src/app/views/myStories/content/test/storiesView.js
  packages/dashboard/src/dataUtils/formattedStoriesArray.js
  packages/dashboard/src/dataUtils/formattedTemplatesArray.js
  packages/story-editor/src/components/publishModal/test/storyPreview.js
  packages/story-editor/src/dataUtils/formattedTemplatesArray.js
Labels: Type: Infrastructure, Type: Code Quality, Pod: Pea

#10879 Floating Menu: Add opacity input
  packages/story-editor/src/components/floatingMenu/elements/karma/opacity.karma.js
  packages/story-editor/src/components/floatingMenu/elements/layerOpacity.js
  packages/story-editor/src/components/panels/design/sizePosition/opacity.js
  packages/story-editor/src/karma/fixture/containers/designMenu.js
Labels: Type: Enhancement, Group: Canvas, Pod: Pea, Group: Workspace, Group: Floating Menu

#10859 Editor: Add text alignment control in design menu
  packages/design-system/src/components/contextMenu/components/icon.js
  packages/story-editor/src/components/floatingMenu/elements/karma/textAlign.karma.js
  packages/story-editor/src/components/floatingMenu/elements/shared/icon.js
  packages/story-editor/src/components/floatingMenu/elements/shared/toggleButton.js
  packages/story-editor/src/components/floatingMenu/elements/textAlign.js
  packages/story-editor/src/karma/fixture/containers/designMenu.js
  packages/story-editor/src/karma/fixture/containers/designPanel/textStyle.js
Labels: Type: Enhancement, Pod: Prometheus

#10870 Editor: Fixed empty story state when there is an attachment
  packages/story-editor/src/app/story/utils/isEmptyStory.js
  packages/story-editor/src/app/story/utils/test/isEmptyStory.js
Labels: Type: Bug, Pod: Prometheus

#10847 Sidebar: New Layers Panel
  packages/story-editor/src/components/canvas/karma/rightClickMenu.karma.js
  packages/story-editor/src/components/canvas/pageAttachment/index.js
  packages/story-editor/src/components/floatingMenu/elements/karma/border.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/borderRadius.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/loop.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/textAlign.karma.js
  packages/story-editor/src/components/footer/footerLayout.js
  packages/story-editor/src/components/footer/layers/index.js
  packages/story-editor/src/components/footer/layers/layers.js
  packages/story-editor/src/components/footer/primaryMenu.js
  packages/story-editor/src/components/inspector/design/designInspector.js
  packages/story-editor/src/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  packages/story-editor/src/components/library/panes/text/karma/textPane.karma.js
  packages/story-editor/src/components/panels/design/layer/karma/layer.karma.js
  packages/story-editor/src/components/panels/design/layer/layer.js
  packages/story-editor/src/components/panels/design/layer/layerList.js
  packages/story-editor/src/components/panels/design/layer/layerPanel.js
  packages/story-editor/src/components/panels/design/textStyle/karma/stylePresets.karma.js
  packages/story-editor/src/components/secondaryPopup/index.js
  packages/story-editor/src/components/secondaryPopup/navigationWrapper.js
  packages/story-editor/src/components/tablist/stories/index.js
  packages/story-editor/src/components/toggleButton/index.js
  packages/story-editor/src/karma/fixture/containers/designPanel/index.js
  packages/story-editor/src/karma/fixture/containers/designPanel/layers.js
  packages/story-editor/src/karma/fixture/containers/footer.js
Labels: Type: Enhancement, Pod: Prometheus, Group: Workspace

#10894 Sidebar: Fix e2e tests
  includes/data/stories/demo.json
  packages/e2e-test-utils/src/publishStory.js
  packages/e2e-tests/src/specs/dashboard/templates/useTemplate.js
  packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js
  packages/e2e-tests/src/specs/editor/prePublishChecklist/contributorUser.js
  packages/story-editor/src/components/panels/design/textStyle/karma/stylePresets.karma.js
  packages/wp-dashboard/src/api/story.js
Labels: Type: Bug, Type: Infrastructure, Pod: Pea, Group: Workspace

#10915 Update Rollup config
  package-lock.json
  package.json
  rollup.config.js
Labels: Type: Infrastructure, Pod: WP

#10899 Allow selecting page when in Empty Story state
  packages/story-editor/src/components/canvas/emptyStateLayer.js
  packages/story-editor/src/components/canvas/pageAttachment/karma/pageAttachment.cuj.karma.js
  packages/story-editor/src/components/colorPicker/karma/colorPicker.karma.js
  packages/story-editor/src/components/panels/design/link/karma/link.karma.js
Labels: Type: Bug, Pod: Prometheus

#10875 Floating menu: Add Text formatting toggles
  packages/story-editor/src/components/floatingMenu/elements/karma/text.karma.js
  packages/story-editor/src/components/floatingMenu/elements/shared/index.js
  packages/story-editor/src/components/floatingMenu/elements/shared/useTextToggle.js
  packages/story-editor/src/components/floatingMenu/elements/toggleBold.js
  packages/story-editor/src/components/floatingMenu/elements/toggleItalics.js
  packages/story-editor/src/components/floatingMenu/elements/toggleUnderline.js
  packages/story-editor/src/karma/fixture/containers/designMenu.js
Labels: Type: Enhancement, Pod: Prometheus

#10921 Dev Container: Switch to MariaDB
  .gitignore
  bin/local-env/docker-compose.yml
  bin/local-env/includes.sh
Labels: Type: Infrastructure, Pod: WP

#10901 Fix story locking e2e test
  packages/e2e-tests/src/specs/wordpress/postLocking.js
Labels: Type: Infrastructure, Pod: WP

#10922 Code Quality: Remove errant `fontWeight` references
  packages/story-editor/src/components/library/panes/text/fontPreview.js
  packages/story-editor/src/components/library/panes/text/textPresets.js
  packages/story-editor/src/components/library/panes/text/textSets/stories/textSet.js
  packages/story-editor/src/components/library/panes/text/textSets/test/textSet.js
  packages/story-editor/src/elements/text/test/util.js
  packages/story-editor/src/karma/fixture/db/singleSavedTemplate.js
  packages/story-editor/src/output/test/_utils/constants.js
  packages/story-editor/src/output/utils/test/fontDeclarations.js
  packages/story-editor/src/output/utils/test/getTextElementTagNames.js
Labels: Elements: Text, Type: Code Quality, Group: Text Sets, Group: Text Presets

#10927 Fix `web_stories_hide_auto_generated_attachments` filter
  includes/Media/Media_Source_Taxonomy.php
  tests/phpunit/integration/tests/Media/Media_Source_Taxonomy.php
Labels: Type: Bug, Group: WordPress, Pod: WP

#10937 Improve handling of corrupt page templates data
  packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js
  packages/story-editor/src/components/library/panes/pageTemplates/templateList.js
  packages/wp-story-editor/src/api/pageTemplate.js
  packages/wp-story-editor/src/api/test/pageTemplates.js
Labels: Type: Bug, Group: WordPress, Pod: WP, Group: Library, Group: Page Templates

#10949 CORS Check: Add telemetry
  packages/wp-story-editor/src/components/corsCheck/corsCheck.js
Labels: Type: Enhancement, Group: Telemetry, Group: Status Check

#10920 Context menus: Move tooltip out of the MenuIcon component
  packages/design-system/src/components/contextMenu/components/icon.js
  packages/story-editor/src/components/canvas/pageSideMenu.js
  packages/story-editor/src/components/floatingMenu/elements/shared/icon.js
  packages/story-editor/src/components/floatingMenu/elements/textAlign.js
Labels: Type: Bug, Pod: Prometheus

#10948 Dashboard: remove some unused constants
  packages/dashboard/src/constants/components.js
Labels: Group: Dashboard, Type: Code Quality

#10956 Remove video trimming feature flag
  includes/Experiments.php
  packages/story-editor/src/components/videoTrim/test/useVideoTrimMode.js
  packages/story-editor/src/components/videoTrim/useVideoTrimMode.js
Labels: Type: Code Quality, Pod: Prometheus

#10955 Remove enableThumbnailCaching feature flag from code
  includes/Experiments.php
  packages/story-editor/src/components/footer/pagepreview/index.js
Labels: Type: Code Quality, Pod: Prometheus

#10972 Explore Templates: Restore Story Creation From Template
  package-lock.json
  packages/dashboard/package.json
  packages/dashboard/src/dashboard.js
  packages/wp-dashboard/src/api/story.js
Labels: Type: Bug, Elements, Pod: Pea, Package: Dashboard

#10939 Define default padding in presets
  packages/story-editor/src/components/library/panes/text/textPresets.js
Labels: Type: Bug, Pod: Prometheus

#10902 Editor: Add alignment buttons to design menu
  packages/story-editor/src/components/floatingMenu/elements/elementAlignment.js
  packages/story-editor/src/components/panels/design/alignment/alignment.js
  packages/story-editor/src/components/panels/design/alignment/test/useAlignment.js
  packages/story-editor/src/components/panels/design/alignment/useAlignment.js
Labels: Type: Enhancement, Pod: Prometheus

#10957 Autoset as Background: Show snackbar message only once
  packages/design-system/src/utils/localStore.js
  packages/story-editor/src/components/canvas/utils/useFullbleedMediaAsBackground.js
Labels: Type: Enhancement, Pod: Prometheus

#10965 Enable CORS check by default
  includes/Experiments.php
Labels: Type: Enhancement, Group: Media, P2, Pod: WP

#10951 Floating Menu: Shapes background color picker
  packages/story-editor/src/components/floatingMenu/elements/shapeColor.js
  packages/story-editor/src/components/form/color/color.js
Labels: Type: Enhancement, Group: Canvas, Pod: Pea, Group: Workspace, Group: Floating Menu

#10858 UI Simplification: Floating menu - hook up 'More' button
  packages/story-editor/src/app/highlights/states.js
  packages/story-editor/src/components/floatingMenu/elements/karma/more.karma.js
  packages/story-editor/src/components/floatingMenu/elements/more.js
  packages/story-editor/src/components/inspector/design/designInspector.js
  packages/story-editor/src/components/inspector/inspectorProvider.js
  packages/story-editor/src/karma/fixture/containers/designMenu.js
Labels: Type: Enhancement, Status: Blocked, Group: Canvas, Pod: Pea, Group: Workspace, Group: Floating Menu

#10952 Floating Menus: Add Event Tracking
  packages/story-editor/src/components/floatingMenu/elements/borderRadius.js
  packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js
  packages/story-editor/src/components/floatingMenu/elements/dismiss.js
  packages/story-editor/src/components/floatingMenu/elements/elementAlignment.js
  packages/story-editor/src/components/floatingMenu/elements/fontSize.js
  packages/story-editor/src/components/floatingMenu/elements/loop.js
  packages/story-editor/src/components/floatingMenu/elements/mute.js
  packages/story-editor/src/components/floatingMenu/elements/shared/useFlip.js
  packages/story-editor/src/components/floatingMenu/elements/trim.js
  packages/story-editor/src/components/floatingMenu/menus/multiple.js
  packages/story-editor/src/components/panels/design/alignment/useAlignment.js
  packages/story-editor/src/components/storyFontPicker/index.js
Labels: Type: Enhancement, Pod: Pea, Group: Floating Menu

#10986 Storybook: Fix element registration error in storybook
  .storybook/stories/playground/story-editor/index.js
Labels: Type: Bug

#10994 Fix: Karma tests due to element type registration
  packages/story-editor/src/components/footer/carousel/karma/carouselNavigation.karma.js
  packages/story-editor/src/karma/fixture/fixture.js
Labels: Type: Infrastructure

#10886 Text Sets: Update text set using Open Sans Condensed
  packages/text-sets/src/raw/step.json
  packages/text-sets/src/test/raw.js
Labels: Type: Enhancement, Group: Fonts, Pod: WP, Group: Text Sets

#10961 E2E Tests: Add tests for adding captions
  packages/e2e-tests/src/assets/test.vtt
  packages/e2e-tests/src/specs/editor/backgroundAudio.js
  packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js
Labels: Type: Enhancement, P2, Pod: WP, Group: Background Audio

#10989 Floating Menus: Enable Experiment
  includes/Experiments.php
  packages/e2e-tests/src/specs/dashboard/templates/useTemplate.js
Labels: Type: Enhancement, Pod: Pea, Group: Floating Menu

#10889 Documentation for editor and dashboard integration
  docs/README.md
  docs/third-party-integration/dashboard/README.md
  docs/third-party-integration/dashboard/api-callbacks.md
  docs/third-party-integration/dashboard/getting-started.md
  docs/third-party-integration/dashboard/integration-layer.md
  docs/third-party-integration/dashboard/tutorial.md
  docs/third-party-integration/story-editor/README.md
  docs/third-party-integration/story-editor/api-callbacks.md
  docs/third-party-integration/story-editor/getting-started.md
  docs/third-party-integration/story-editor/integration-layer.md
  docs/third-party-integration/story-editor/tutorial.md
Labels: Type: Documentation

#11039 Design System: Remove unused icons
  packages/design-system/src/icons/arrow_down_left.svg
  packages/design-system/src/icons/arrow_down_right.svg
  packages/design-system/src/icons/arrow_leftright.svg
  packages/design-system/src/icons/arrow_updown.svg
  packages/design-system/src/icons/arrow_updown_small.svg
  packages/design-system/src/icons/arrow_upleft.svg
  packages/design-system/src/icons/arrow_upright.svg
  packages/design-system/src/icons/bookmark.svg
  packages/design-system/src/icons/box6.svg
  packages/design-system/src/icons/distribute_horizontal_chevron.svg
  packages/design-system/src/icons/dots_fill.svg
  packages/design-system/src/icons/dots_square.svg
  packages/design-system/src/icons/double_chevron_left.svg
  packages/design-system/src/icons/double_chevron_right.svg
  packages/design-system/src/icons/gear.svg
  packages/design-system/src/icons/index.js
  packages/design-system/src/icons/magnifier_minus.svg
  packages/design-system/src/icons/magnifier_plus.svg
  packages/design-system/src/icons/steps_down.svg
  packages/design-system/src/icons/steps_up.svg
  packages/story-editor/src/components/colorPicker/gradientPicker.js
  packages/story-editor/src/components/floatingMenu/elements/flipHorizontal.js
  packages/story-editor/src/components/floatingMenu/elements/flipVertical.js
  packages/story-editor/src/components/form/color/stories/index.js
  packages/story-editor/src/components/panels/shared/flipControls.js
Labels: Type: Code Quality, Group: Design System, Package: Design System

#11025 Floating Menu: Fix "Saved Color" (gradient) as border color causes crash
  packages/story-editor/src/components/colorPicker/basicColorPicker.js
  packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js
Labels: Type: Bug, Pod: Pea, Bug Bash: 1.19.0

#11017 Editor: add focus styling to title input
  packages/story-editor/src/components/header/title.js
Labels: Type: Bug, Pod: Pea, Group: Workspace, Group: Design System

#10918 Custom Fonts: Improve Accessibility on Settings screen
  packages/e2e-test-utils/src/customFonts.js
  packages/e2e-test-utils/src/index.js
  packages/e2e-tests/src/assets/OpenSansCondensed-Bold.ttf
  packages/e2e-tests/src/assets/OpenSansCondensed-LightItalic.ttf
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js
  packages/e2e-tests/src/specs/editor/fontCheck/fontCheck.js
  packages/wp-dashboard/src/components/editorSettings/customFonts/index.js
Labels: Type: Enhancement, Group: Fonts, Group: Settings, Pod: WP

#11050 Font picker: fix preview of custom fonts
  packages/story-editor/src/app/font/fontProvider.js
  packages/story-editor/src/components/fontPicker/index.js
Labels: Type: Bug, Group: Fonts

#11021 Floating Menus: Shapes, only show border options when locked
  packages/story-editor/src/components/floatingMenu/elements/borderRadius.js
  packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js
  packages/story-editor/src/components/floatingMenu/elements/karma/border.karma.js
  packages/story-editor/src/components/floatingMenu/elements/karma/borderRadius.karma.js
  packages/story-editor/src/components/floatingMenu/menus/shape.js
Labels: Type: Bug, Pod: Pea, Group: Floating Menu

#10996 Custom Fonts: Add error handling for duplicates
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js
  packages/wp-dashboard/src/api/hooks/useFontsApi.js
  packages/wp-dashboard/src/components/editorSettings/customFonts/index.js
Labels: Type: Enhancement, P2, Group: Fonts, Group: Settings, Pod: WP

#11031 Saved Page Templates: fix repeated image uploads
  packages/story-editor/src/components/library/libraryProvider.js
  packages/story-editor/src/components/library/panes/pageTemplates/savedPageTemplate.js
Labels: Type: Bug, Group: Library, Group: Page Templates

#11033 Design System: fix getoffset calculation for Popups
  packages/design-system/src/components/popup/utils/getOffset.js
  packages/story-editor/src/components/form/color/color.js
  packages/story-editor/src/components/form/color/colorInput.js
  packages/story-editor/src/components/form/color/constants.js
  packages/story-editor/src/components/panels/design/textStyle/stylePresets.js
Labels: Type: Bug, Pod: Pea, Group: Workspace, Group: Design System, Bug Bash: 1.19.0

#11057 Floating menu: Hide on drag/resize/rotate
  packages/story-editor/src/components/floatingMenu/layer.js
  packages/story-editor/src/components/floatingMenu/menu.js
Labels: Type: Enhancement, Pod: Pea, Group: Floating Menu

#11013 Design System: Datalist a11y
  packages/design-system/src/components/datalist/container.js
  packages/design-system/src/components/datalist/datalist.js
  packages/design-system/src/components/datalist/searchInput.js
  packages/story-editor/src/components/fontPicker/index.js
  packages/wp-story-editor/src/components/documentPane/publish/author.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
Labels: Type: Bug, Accessibility, Pod: Pea

#11064 Quick Actions: when no actions present don't render menu
  packages/story-editor/src/components/canvas/karma/quickActions.karma.js
  packages/story-editor/src/components/canvas/pageSideMenu.js
Labels: Type: Bug, Pod: Pea, Group: Quick Action Menu

#11066 Text Sets: Remove extraneous properties
  packages/text-sets/src/raw/contact.json
  packages/text-sets/src/raw/cover.json
  packages/text-sets/src/raw/editorial.json
  packages/text-sets/src/raw/list.json
  packages/text-sets/src/raw/quote.json
  packages/text-sets/src/raw/section_header.json
  packages/text-sets/src/raw/step.json
  packages/text-sets/src/raw/table.json
  packages/text-sets/src/test/raw.js
Labels: Pod: WP, Group: Text Sets

#10993 E2E Tests: Fix withExperimentalFeatures util
  packages/e2e-test-utils/src/customFonts.js
  packages/e2e-test-utils/src/experimentalFeatures.js
  packages/e2e-test-utils/src/index.js
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js
  packages/e2e-tests/src/specs/editor/fontCheck/fontCheck.js
Labels: Type: Infrastructure, Pod: WP

#11067 Background Audio: Do not always loop audio in the editor
  packages/story-editor/src/components/audioPlayer/index.js
  packages/story-editor/src/components/panels/shared/backgroundAudioPanelContent.js
Labels: Type: Bug, Pod: WP, Group: Background Audio, Bug Bash: 1.19.0

#11083 Dynamically import `opentype.js` in `getFontDataFromUrl`
  packages/wp-dashboard/src/components/editorSettings/customFonts/utils/getFontDataFromUrl.js
Labels: P2, Group: Fonts, Type: Performance, Type: Code Quality

#11080 Update Composer dependencies
  composer.lock
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Link_Controller.php
Labels: Dependencies, Type: Code Quality

#11086 Dashboard: dynamically import templates package
  packages/dashboard/src/app/api/useTemplateApi.js
  packages/dashboard/src/components/navProvider.js
  packages/dashboard/src/components/pageStructure/leftRail.js
  packages/dashboard/src/components/pageStructure/test/pageStructure.js
Labels: Group: Dashboard, Type: Code Quality

#11087 Custom Fonts: Error handling for failed delete
  packages/wp-dashboard/src/api/hooks/useFontsApi.js
  packages/wp-dashboard/src/components/editorSettings/customFonts/index.js
  packages/wp-dashboard/src/constants/textConstants.js
Labels: Type: Bug, Group: Fonts, Group: Settings, Pod: WP

#11097 Add changelog for v1.19.0
  readme.txt
Labels: Type: Documentation, Type: Release

#11090 Context Menu: Prevent auto focus when already focused
  packages/design-system/src/components/contextMenu/menu.js
  packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js
  packages/story-editor/src/components/floatingMenu/menus/shape.js
Labels: Type: Bug, Pod: Pea, Group: Context Menu, Group: Floating Menu

#11115 Storybook: Set screen height to story editor
  .storybook/stories/playground/story-editor/index.js
Labels: Type: Bug

#11076 E2E Tests: Add Percy coverage for dropdown on dashboard
  package-lock.json
  package.json
  packages/e2e-tests/src/specs/dashboard/dashboard.js
Labels: Type: Task, Group: Settings, Pod: WP, Package: E2E Tests

#11095 Docs: Update with latest changes
  docs/third-party-integration/dashboard/api-callbacks.md
  docs/third-party-integration/dashboard/integration-layer.md
  docs/third-party-integration/story-editor/getting-started.md
  docs/third-party-integration/story-editor/integration-layer.md
  docs/third-party-integration/story-editor/tutorial.md
Labels: Type: Documentation

#11100 Custom fonts: enable font check by default
  includes/Experiments.php
Labels: Type: Enhancement, Group: Fonts

#11114 Floating Menu: Fix "Saved Color" (gradient) as border color causes crash (Again)
  packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js
  packages/story-editor/src/components/form/color/color.js
  packages/story-editor/src/components/form/color/test/color.js
Labels: Type: Bug, Pod: Pea, Group: Floating Menu

#11075 Floating Menu: Fix Border Color Updates
  packages/story-editor/src/components/colorPicker/colorPicker.js
  packages/story-editor/src/components/colorPicker/customColorPicker.js
  packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js
Labels: Type: Bug, Pod: Pea, Group: Floating Menu, Bug Bash: 1.19.0

#11098 Fonts: remove unneeded values being saved to story data
  packages/migration/src/migrate.js
  packages/migration/src/migrations/test/v0041_removeFontProperties.js
  packages/migration/src/migrations/v0041_removeFontProperties.js
  packages/story-editor/src/components/panels/design/textStyle/test/textStyle.js
  packages/story-editor/src/components/storyFontPicker/index.js
Labels: Group: Fonts, Type: Code Quality, Group: Migrations, Package: Story Editor, Package: Migration

#11125 Custom Fonts: Fix keyboard handling test path
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js
Labels: Type: Code Quality, Package: Fonts, Package: E2E Tests

#11132 Code Quality: Remove `customFonts` and `notifyDeletedFonts` feature flag code
  docs/third-party-integration/story-editor/integration-layer.md
  includes/Experiments.php
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js
  packages/e2e-tests/src/specs/editor/fontCheck/fontCheck.js
  packages/story-editor/src/app/font/fontProvider.js
  packages/wp-dashboard/src/components/editorSettings/editorSettings.js
  packages/wp-story-editor/src/components/fontCheck/index.js
Labels: Type: Code Quality, Pod: WP

#11124 Canvas: Remove empty text elements when exiting editing mode
  packages/element-library/src/text/edit.js
  packages/rich-text/src/editor.js
  packages/story-editor/src/components/canvas/editElement.js
  packages/story-editor/src/karma/element-library/text/edit.karma.js
Labels: Type: Enhancement, Elements: Text, Pod: Prometheus

#11069 Video: Improved handling of video play button
  packages/element-library/src/video/playPauseButton.js
Labels: Type: Enhancement, Elements: Video, Pod: WP

#11099 Fix issues related to selecting all text
  packages/rich-text/src/editor.js
  packages/rich-text/src/util.js
  packages/story-editor/src/karma/element-library/text/edit.karma.js
Labels: Type: Bug, Elements: Text, Pod: Prometheus, Group: Keyboard Shortcuts

#11133 Code Quality: Remove `enhancedPageBackgroundAudio` feature flag code
  docs/third-party-integration/story-editor/integration-layer.md
  includes/Experiments.php
  packages/story-editor/src/components/panels/design/pageBackgroundAudio/backgroundAudio.js
  packages/story-editor/src/components/panels/design/pageBackgroundAudio/test/backgroundAudio.js
Labels: Type: Code Quality, Pod: WP
