Repository GoogleForCreators/web-stories-wp, pull requests merged in 2022-08, with the labels that each got.

#12063 Multipage Canvas: Enable the flag by default
  includes/Experiments.php
Labels: Type: Enhancement, Group: Canvas, Pod: Prometheus

#12065 Code: Moved layer panel to proper folder structure
  packages/story-editor/src/components/footer/layers/layers.js
  packages/story-editor/src/components/panels/design/index.js
  packages/story-editor/src/components/panels/layer/constants.js
  packages/story-editor/src/components/panels/layer/group.js
  packages/story-editor/src/components/panels/layer/index.js
  packages/story-editor/src/components/panels/layer/karma/layer.karma.js
  packages/story-editor/src/components/panels/layer/layer.js
  packages/story-editor/src/components/panels/layer/layerList.js
  packages/story-editor/src/components/panels/layer/layerPanel.js
  packages/story-editor/src/components/panels/layer/reorderableGroup.js
  packages/story-editor/src/components/panels/layer/shapeMaskWrapper.js
  packages/story-editor/src/components/panels/layer/useGroupSelection.js
  packages/story-editor/src/components/panels/layer/useLayerSelection.js
  packages/story-editor/src/components/panels/layer/useLayers.js
  packages/story-editor/src/components/reorderable/reorderableSeparator.js
  packages/story-editor/src/components/thumbnail/thumbnail.js
Labels: Type: Code Quality, Pod: Prometheus

#12035 Templates: use custom heading levels
  packages/templates/src/raw/12-hours-in-barcelona/template.json
  packages/templates/src/raw/a-day-in-the-life/template.json
  packages/templates/src/raw/ace-hotel-kyoto-review/template.json
  packages/templates/src/raw/album-releases/template.json
  packages/templates/src/raw/all-about-cars/template.json
  packages/templates/src/raw/almodos-films/template.json
  packages/templates/src/raw/an-artists-legacy/template.json
  packages/templates/src/raw/art-books-gift-guide/template.json
  packages/templates/src/raw/baking-bread-guide/template.json
  packages/templates/src/raw/belly-fat-workout/template.json
  packages/templates/src/raw/buying-art-on-the-internet/template.json
  packages/templates/src/raw/celebrity-life-story/template.json
  packages/templates/src/raw/celebrity-q-and-a/template.json
  packages/templates/src/raw/diy-home-office/template.json
  packages/templates/src/raw/doers-get-more-done/template.json
  packages/templates/src/raw/elegant-travel-itinerary/template.json
  packages/templates/src/raw/experience-thailand/template.json
  packages/templates/src/raw/fashion-inspiration/template.json
  packages/templates/src/raw/fashion-on-the-go/template.json
  packages/templates/src/raw/fitness-apps-ranked/template.json
  packages/templates/src/raw/food-and-stuff/template.json
  packages/templates/src/raw/fresh-and-bright/template.json
  packages/templates/src/raw/google-music-studio-tour/template.json
  packages/templates/src/raw/hawaii-travel-packing-list/template.json
  packages/templates/src/raw/honeymooning-in-italy/template.json
  packages/templates/src/raw/house-hunting/template.json
  packages/templates/src/raw/how-contact-tracing-works/template.json
  packages/templates/src/raw/how-video-calls-saved-the-day/template.json
  packages/templates/src/raw/indoor-garden-oasis/template.json
  packages/templates/src/raw/kitchen-makeover/template.json
  packages/templates/src/raw/kitchen-stories/template.json
  packages/templates/src/raw/laptop-buying-guide/template.json
  packages/templates/src/raw/los-angeles-city-guide/template.json
  packages/templates/src/raw/magazine-article/template.json
  packages/templates/src/raw/modernist-travel-guide/template.json
  packages/templates/src/raw/new-york-party-round-up/template.json
  packages/templates/src/raw/no-days-off/template.json
  packages/templates/src/raw/one-day-city-itinerary/template.json
  packages/templates/src/raw/plant-based-dyes/template.json
  packages/templates/src/raw/pride-month-watchlist/template.json
  packages/templates/src/raw/sangria-artichoke/template.json
  packages/templates/src/raw/series-best-of/template.json
  packages/templates/src/raw/simple-tech-tutorial/template.json
  packages/templates/src/raw/skin-care-at-home/template.json
  packages/templates/src/raw/sleep/template.json
  packages/templates/src/raw/street-style-on-the-go/template.json
  packages/templates/src/raw/summer-adventure-guide/template.json
  packages/templates/src/raw/summer-fashion-collection/template.json
  packages/templates/src/raw/technology-advice/template.json
  packages/templates/src/raw/tips-for-throwing-an-outdoor-luau/template.json
  packages/templates/src/raw/tv-show-recap/template.json
  packages/templates/src/raw/ultimate-comparison/template.json
  packages/templates/src/raw/vintage-chairs-buying-guide/template.json
  packages/templates/src/raw/ways-to-eat-avocado/template.json
  packages/templates/src/raw/weekly-entertainment/template.json
Labels: Type: Enhancement, Pod: Prometheus

#12044 Fix font loading
  packages/fonts/src/utils/getGoogleFontURL.js
Labels: Type: Bug, Group: Fonts, Pod: Prometheus

#12045 3P Media: Add category filter for Coverr
  packages/story-editor/src/app/media/media3p/providerConfiguration.js
Labels: Type: Enhancement, Pod: WP, Group: 3P Media

#12062 Editor: Add Semantic Headings to the right click menu of Text Elements
  packages/design-system/src/components/contextMenu/stories/index.js
  packages/story-editor/src/app/rightClickMenu/constants.js
  packages/story-editor/src/app/rightClickMenu/hooks/useHeadingSelect.js
  packages/story-editor/src/app/rightClickMenu/menus/textMenu.js
  packages/story-editor/src/components/canvas/karma/rightClickMenu.karma.js
  packages/story-editor/src/components/panels/design/textAccessibility/textAccessibility.js
  packages/story-editor/src/constants/headings.js
  packages/story-editor/src/constants/index.js
Labels: Type: Enhancement, Elements: Text, Package: Story Editor, NewsCorp

#12042 Media: Fix broken video muting
  packages/media/src/fetchRemoteFile.js
  packages/media/src/getFileBasename.js
  packages/media/src/getFileName.js
  packages/media/src/getFileNameFromUrl.js
  packages/media/src/getFileNameWithExt.js
  packages/media/src/index.js
  packages/media/src/test/getFileBasename.js
  packages/story-editor/src/app/media/utils/getResourceFromLocalFile.js
  packages/story-editor/src/app/media/utils/useFFmpeg.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js
  packages/story-editor/src/app/media/utils/useUploadVideoFrame.js
  packages/story-editor/src/app/uploader/useUploader.js
Labels: Type: Bug, Group: Media, Elements: Video

#12061 Templates: improve text element usage
  packages/templates/src/raw/12-hours-in-barcelona/template.json
  packages/templates/src/raw/ace-hotel-kyoto-review/template.json
  packages/templates/src/raw/diy-home-office/template.json
  packages/templates/src/raw/experience-thailand/template.json
  packages/templates/src/raw/fresh-and-bright/template.json
  packages/templates/src/raw/hawaii-travel-packing-list/template.json
  packages/templates/src/raw/kitchen-makeover/template.json
  packages/templates/src/raw/kitchen-stories/template.json
  packages/templates/src/raw/los-angeles-city-guide/template.json
  packages/templates/src/raw/modernist-travel-guide/template.json
  packages/templates/src/raw/pizzas-in-nyc/template.json
  packages/templates/src/raw/series-best-of/template.json
  packages/templates/src/raw/summer-adventure-guide/template.json
Labels: Type: Enhancement, Pod: Prometheus

#12022 Editor: Changed video recording trim to happen before insertion
  packages/media/src/generateVideoStrip.js
  packages/story-editor/src/app/highlights/quickActions/useQuickActions.js
  packages/story-editor/src/components/canvas/mediaRecordingLayer.js
  packages/story-editor/src/components/mediaRecording/components.js
  packages/story-editor/src/components/mediaRecording/footer.js
  packages/story-editor/src/components/mediaRecording/mediaRecording.js
  packages/story-editor/src/components/mediaRecording/playbackMedia.js
  packages/story-editor/src/components/mediaRecording/processingOverlay.js
  packages/story-editor/src/components/mediaRecording/provider.js
  packages/story-editor/src/components/mediaRecording/useTrim.js
  packages/story-editor/src/components/mediaRecording/useTrimmedReplay.js
Labels: Type: Enhancement, Pod: Prometheus

#12060 E2E Tests: Ensure WP updates to latest minor
  bin/local-env/install-wordpress.sh
Labels: Type: Infrastructure, Pod: WP, Package: E2E Tests

#10783 TypeScript: Add initial infrastructure
  .distignore
  .eslintrc
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint-css-js-md.yml
  .github/workflows/lint-i18n.yml
  .github/workflows/tests-karma-dashboard.yml
  .github/workflows/tests-karma-editor.yml
  .github/workflows/tests-unit-js.yml
  .gitignore
  .npmpackagejsonlintrc.json
  babel.config.cjs
  package-lock.json
  package.json
  packages/eslint-import-resolver/src/index.cjs
  packages/story-editor/src/components/checklist/karma/checklist.karma.js
  packages/story-editor/src/components/library/test/__snapshots__/termsDialog.js.snap
  packages/tracking/package.json
  packages/tracking/src/constants.ts
  packages/tracking/src/disableTracking.ts
  packages/tracking/src/enableTracking.ts
  packages/tracking/src/getTimeTracker.ts
  packages/tracking/src/index.ts
  packages/tracking/src/initializeErrorReporting.ts
  packages/tracking/src/initializeTracking.ts
  packages/tracking/src/isTrackingEnabled.ts
  packages/tracking/src/shared.js
  packages/tracking/src/shared.ts
  packages/tracking/src/track.ts
  packages/tracking/src/trackClick.ts
  packages/tracking/src/trackError.ts
  packages/tracking/src/trackEvent.ts
  packages/tracking/src/trackScreenView.ts
  packages/tracking/src/trackTiming.ts
  packages/tracking/tsconfig.json
  rollup.config.js
  tests/js/jest.config.js
  tsconfig.json
  tsconfig.shared.json
  webpack.config.cjs
Labels: Type: Infrastructure, Type: Code Quality, Package: Tracking

#12091 Media3P: Add hardening for missing media URLs
  packages/story-editor/src/app/media/media3p/useFetchMediaEffect.js
  packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js
Labels: Type: Bug, Group: Media, Pod: WP, Group: 3P Media

#12021 Code Quality: Remove hotlinking feature flag code
  includes/Experiments.php
  packages/e2e-tests/src/specs/editor/media/hotlinking.js
  packages/story-editor/src/components/canvas/pageAttachment/karma/pageAttachment.cuj.karma.js
  packages/story-editor/src/components/form/linkIcon.js
  packages/story-editor/src/components/header/buttons/test/publish.js
  packages/story-editor/src/components/panels/design/videoAccessibility/karma/videoPoster.karma.js
  packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js
  packages/story-editor/src/components/publishModal/content/storyPreview.js
  packages/story-editor/src/components/publishModal/test/storyPreview.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
  packages/wp-story-editor/src/components/header/buttons/test/buttons.js
Labels: Group: Media, Type: Code Quality, Pod: WP

#12122 Add changelog for v1.24.0
  readme.txt
Labels: Type: Documentation, Type: Release

#12124 Enable media recording trimming flag
  includes/Experiments.php
Labels: Type: Enhancement, Group: Media, Pod: Prometheus

#12096 Autosaves: Set up initial infrastructure
  includes/Experiments.php
  packages/story-editor/src/components/autoSaveHandler/index.js
Labels: Type: Enhancement, Group: Editing, Group: WordPress, Pod: WP

#11985 Media: Fix empty button after cropping
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/useMediaPicker.js
Labels: Type: Bug, Group: Media, Group: WordPress, Pod: WP

#12142 Karma: Disable flaky poster image keyboard test
  packages/story-editor/src/components/panels/design/videoAccessibility/karma/videoPoster.karma.js
Labels: Type: Task, Pod: Prometheus

#12098 Add message when Autosave exists
  includes/Admin/Editor.php
  packages/story-editor/src/components/autoSaveCheck/autoSaveDialog.js
  packages/story-editor/src/components/autoSaveCheck/index.js
  packages/story-editor/src/components/autoSaveCheck/stories/autoSaveDialog.js
  packages/story-editor/src/index.js
  packages/wp-story-editor/src/index.js
Labels: Type: Enhancement, Group: Editing, Pod: WP, Group: Workspace

#12159 Output: optimize `fix_malformed_script_link_tags()` regex
  includes/Renderer/Story/HTML.php
Labels: Type: Bug, PHP, Group: WordPress, AMP Output, Pod: WP

#12160 Sanitization: clone node before importing
  includes/AMP/Traits/Sanitization_Utils.php
  tests/phpunit/unit/tests/AMP/Story_Sanitizer.php
Labels: Type: Bug, Group: WordPress, AMP Output, Pod: WP

#12162 Discovery: always print document title
  includes/Discovery.php
  tests/phpunit/integration/tests/Discovery.php
Labels: Type: Bug, Group: Discoverability, Group: Integration, PHP, Group: WordPress, Pod: WP

#12140 Add back 'auto-draft' status
  packages/story-editor/src/app/story/effects/useLoadStory.js
  packages/story-editor/src/app/story/storyProvider.js
  packages/story-editor/src/components/header/buttons/preview.js
  packages/story-editor/src/components/header/buttons/update.js
  packages/story-editor/src/components/localAutoSaveHandler/localAutoSave.js
  packages/story-editor/src/components/localAutoSaveHandler/test/localAutoSaveHandler.js
  packages/story-editor/src/karma/fixture/components/header/buttons/index.js
  packages/wp-story-editor/src/components/header/buttons/index.js
Labels: Type: Code Quality, Pod: Prometheus

#12165 Code Quality: enable a few useful ESLint rules
  .eslintrc
  packages/dashboard/src/app/router/test/route.js
  packages/dashboard/src/app/views/exploreTemplates/content/test/content.js
  packages/dashboard/src/app/views/exploreTemplates/header/test/header.js
  packages/dashboard/src/app/views/myStories/content/test/content.js
  packages/dashboard/src/app/views/myStories/content/test/storiesView.js
  packages/dashboard/src/app/views/myStories/header/test/header.js
  packages/dashboard/src/components/viewStyleBar/test/viewStyleBar.js
  packages/dashboard/src/utils/test/useDashboardResultsLabel.js
  packages/dashboard/src/utils/test/useStoryView.js
  packages/dashboard/src/utils/test/useTemplateView.js
  packages/design-system/src/components/datalist/datalist.js
  packages/design-system/src/components/dropDown/index.js
  packages/design-system/src/components/dropDown/test/useDropDown.js
  packages/design-system/src/components/dropDown/useDropDown.js
  packages/design-system/src/components/input/index.js
  packages/design-system/src/components/keyboard/gridview/utils.js
  packages/design-system/src/components/mediaInput/index.js
  packages/design-system/src/components/menu/test/useDropDownMenu.js
  packages/design-system/src/components/search/test/useSearch.js
  packages/design-system/src/components/switch/index.js
  packages/design-system/src/components/textArea/index.js
  packages/design-system/src/components/tooltip/test/tooltip.js
  packages/karma-fixture/src/init.js
  packages/karma-puppeteer-client/src/client.js
  packages/media/src/getCanvasBlob.js
  packages/story-editor/src/app/media/local/reducers/setupState.js
  packages/story-editor/src/app/media/media3p/api/apiFetcher.js
  packages/story-editor/src/components/canvas/test/useCanvasKeys.js
  packages/story-editor/src/components/checklist/karma/firstPageAnimation.karma.js
  packages/story-editor/src/components/dropTargets/karma/dropTarget.karma.js
  packages/story-editor/src/components/library/panes/media/common/mediaElement.js
  packages/story-editor/src/components/library/panes/shared/virtualizedPanelGrid/test/useVirtualizedGridNavigation.js
  packages/story-editor/src/components/panels/design/animation/karma/animation.karma.js
  packages/story-editor/src/components/panels/design/textStyle/test/textBox.js
  packages/story-editor/src/components/panels/design/textStyle/test/textStyle.js
  packages/story-editor/src/components/panels/utils/test/metricsForTextPadding.js
  packages/story-editor/src/utils/getBlurHashFromImage.js
  packages/story-editor/src/utils/idleCallback.js
  packages/story-editor/src/utils/test/getInUseFonts.js
  packages/tinymce-button/src/index.js
  packages/wp-dashboard/src/components/editorSettings/adManagement/adNetwork/test/adNetwork.js
  packages/wp-dashboard/src/components/editorSettings/adManagement/googleAdManager/test/googleAdManager.js
  packages/wp-dashboard/src/components/editorSettings/adManagement/googleAdSense/test/googleAdSense.js
  packages/wp-dashboard/src/components/editorSettings/adManagement/test/adManagement.js
  packages/wp-dashboard/src/components/editorSettings/archive/test/archive.js
  packages/wp-dashboard/src/components/editorSettings/dataRemoval/test/DataRemovalSettings.js
  packages/wp-dashboard/src/components/editorSettings/googleAnalytics/test/googleAnalytics.js
  packages/wp-dashboard/src/components/editorSettings/mediaOptimization/test/mediaOptimizationSettings.js
  packages/wp-dashboard/src/components/editorSettings/shopping/test/shopping.js
  packages/wp-dashboard/src/components/editorSettings/shopping/test/shoppingProvider.js
  packages/wp-dashboard/src/components/editorSettings/telemetry/test/telemetrySettings.js
  packages/wp-dashboard/src/components/editorSettings/test/editorSettings.js
  packages/wp-dashboard/src/components/editorSettings/videoCache/test/videoCache.js
  tsconfig.shared.json
Labels: Type: Code Quality, Pod: WP

#12123 Media: Better prepend uploading items to library
  packages/story-editor/src/app/media/local/reducers/prependMedia.js
  packages/story-editor/src/app/media/local/reducers/setMediaType.js
  packages/story-editor/src/app/media/local/test/reducer.js
  packages/story-editor/src/app/media/local/useContextValueProvider.js
  packages/story-editor/src/app/media/pagination/reducer.js
  packages/story-editor/src/app/media/pagination/test/reducer.js
  packages/story-editor/src/app/media/useUploadMedia.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/test/useMediaUploadQueue.js
  packages/story-editor/src/components/library/panes/media/common/mediaGallery.js
  packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js
  packages/story-editor/src/components/library/panes/media/local/mediaPane.js
Labels: Type: Enhancement, Group: Media

#12095 Floating Menu: Allow fixing / disabling the element menu
  packages/design-system/src/icons/box_with_dots.svg
  packages/design-system/src/icons/index.js
  packages/design-system/src/utils/localStore.js
  packages/story-editor/src/app/canvas/canvasProvider.js
  packages/story-editor/src/app/highlights/states.js
  packages/story-editor/src/components/floatingMenu/constants.js
  packages/story-editor/src/components/floatingMenu/elements/index.js
  packages/story-editor/src/components/floatingMenu/elements/settings.js
  packages/story-editor/src/components/floatingMenu/karma/floatingMenu.karma.js
  packages/story-editor/src/components/floatingMenu/karma/image.karma.js
  packages/story-editor/src/components/floatingMenu/karma/shape.karma.js
  packages/story-editor/src/components/floatingMenu/karma/sticker.karma.js
  packages/story-editor/src/components/floatingMenu/karma/text.karma.js
  packages/story-editor/src/components/floatingMenu/karma/video.karma.js
  packages/story-editor/src/components/floatingMenu/layer.js
  packages/story-editor/src/components/floatingMenu/menus/image.js
  packages/story-editor/src/components/floatingMenu/menus/multiple.js
  packages/story-editor/src/components/floatingMenu/menus/product.js
  packages/story-editor/src/components/floatingMenu/menus/shape.js
  packages/story-editor/src/components/floatingMenu/menus/sticker.js
  packages/story-editor/src/components/floatingMenu/menus/text.js
  packages/story-editor/src/components/floatingMenu/menus/video.js
  packages/story-editor/src/components/footer/primaryMenu.js
  packages/story-editor/src/components/footer/toolbarToggle.js
  packages/story-editor/src/constants/index.js
Labels: Type: Enhancement, Pod: Prometheus

#12195 Media Library: Fix media reducer
  packages/story-editor/src/app/media/pagination/reducer.js
Labels: Type: Bug, Group: Media, Group: 3P Media
