Repository GoogleForCreators/web-stories-wp, pull requests merged in 2022-01, with the labels that each got.

#10000 Karma: Fixed tests using background images
  packages/story-editor/src/components/canvas/karma/backgroundCopyPaste.karma.js
  packages/story-editor/src/karma/copyAndPaste.cuj.karma.js
  packages/story-editor/src/karma/fixture/containers/designPanel/sizePosition.js
Labels: Type: Bug, Pod: Prometheus

#10016 Karma: Add missing blurhash to media library items
  packages/story-editor/src/karma/fixture/db/getMediaResponse.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10011 Karma: Fix Page Attachment + Link test
  packages/story-editor/src/components/panels/design/link/karma/link.karma.js
Labels: Type: Bug, Pod: Prometheus

#9998 Pre-Publish Checklist: Remove hover on + X more thumbnail
  packages/story-editor/src/components/checklistCard/styles.js
Labels: Type: Bug, Pod: Pea, Group: Pre-Publish Checklist

#9900 Right Click Menu: Clear multiple element styles
  packages/story-editor/src/app/rightClickMenu/constants.js
  packages/story-editor/src/app/rightClickMenu/provider.js
  packages/story-editor/src/app/rightClickMenu/test/useRightClickMenu.js
  packages/story-editor/src/components/canvas/karma/rightClickMenu.karma.js
  packages/story-editor/src/karma/fixture/containers/designPanel/shapeStyle.js
Labels: Type: Enhancement, cla: yes, Pod: Pea, Group: Context Menu

#10066 Collapse Footer Popups When Element is Trimming or Cropping
  packages/story-editor/src/components/footer/secondaryMenu.js
Labels: Type: Bug, Pod: Pea, Group: Pre-Publish Checklist, Group: Help Center, Package: Story Editor

#10091 Composer: allow third-party plugins to be run
  composer.json
  composer.lock
Labels: Dependencies, PHP

#9989 Video Trimmer: Fix for blank frames in video trimmer frames strip
  packages/media/src/generateVideoStrip.js
Labels: Type: Bug, Group: Media

#9945 Editor: Fixed updating existing resource when retrimming a video
  packages/story-editor/src/app/media/utils/useProcessMedia.js
Labels: Type: Bug, Pod: Prometheus

#10082 Decoupling: Fix `updateCurrentUser` error when browsing help center tip
  packages/story-editor/src/app/currentUser/currentUserProvider.js
  packages/story-editor/src/app/helpCenter/provider.js
Labels: Package: Story Editor

#10097 Karma: enable test for inline style override
  packages/story-editor/src/components/richText/karma/inlineStyleOverride.karma.js
Labels: Type: Bug, Pod: Prometheus

#10026 Dashboard: Support deep linking for template details
  packages/dashboard/src/app/serializers/templates.js
  packages/dashboard/src/app/serializers/test/templates.js
  packages/dashboard/src/app/views/exploreTemplates/content/test/content.js
  packages/dashboard/src/app/views/exploreTemplates/index.js
  packages/dashboard/src/app/views/exploreTemplates/modal/templateDetails/karma/templateDetails.karma.js
  packages/dashboard/src/app/views/myStories/content/test/content.js
  packages/dashboard/src/app/views/myStories/content/test/storiesView.js
  packages/dashboard/src/app/views/myStories/header/test/header.js
  packages/dashboard/src/components/interfaceSkeleton/index.js
  packages/dashboard/src/dataUtils/formattedTemplatesArray.js
  packages/story-editor/src/dataUtils/formattedTemplatesArray.js
Labels: Type: Enhancement, Group: Templates, Group: Dashboard, Pod: Pea

#10023 Media: Fix video poster not rendering in Safari
  packages/story-editor/src/components/library/panes/media/common/innerElement.js
  packages/story-editor/src/components/library/panes/media/common/mediaElement.js
Labels: Type: Bug, Group: Media, P2, Browser Issues, Pod: WP & Infra

#10152 Remove cs2pr from PHPStan's output
  .github/workflows/lint-php.yml
Labels: Type: Infrastructure

#10156 Actually run New Relic compat integration
  .phpstorm.meta.php
  includes/Plugin.php
Labels: Type: Bug, Group: Integration, AMP Output

#10101 E2E Tests: Run tests against WP 5.9 RC1
  .github/workflows/tests-e2e.yml
  packages/e2e-test-utils/src/trashAllTerms.js
  packages/e2e-test-utils/src/visitBlockWidgetScreen.js
  packages/e2e-tests/src/config/bootstrap.js
  packages/e2e-tests/src/specs/wordpress/blockWidget.js
Labels: Type: Infrastructure, Pod: WP & Infra, Package: E2E Tests

#9743 Media: Add `decoding=async` to all images
  packages/dashboard/src/app/views/exploreTemplates/content/templateGridItem.js
  packages/dashboard/src/app/views/myStories/content/storyGridItem/index.js
  packages/dashboard/src/app/views/myStories/content/storyGridItem/storyDisplayContent.js
  packages/dashboard/src/app/views/myStories/content/storyListItem/index.js
  packages/dashboard/src/components/cardGallery/index.js
  packages/design-system/src/components/mediaInput/index.js
  packages/story-editor/src/components/footer/pagepreview/index.js
  packages/story-editor/src/components/library/panes/media/common/innerElement.js
  packages/story-editor/src/components/library/panes/media/local/mediaEditDialog.js
  packages/story-editor/src/components/library/panes/pageTemplates/defaultPageTemplate.js
  packages/story-editor/src/components/library/panes/text/textSets/textSet.js
  packages/story-editor/src/elements/media/visibleImage.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
  packages/wp-story-editor/src/components/postLock/postLockDialog.js
  packages/wp-story-editor/src/components/postLock/postTakeOverDialog.js
Labels: cla: yes, Group: Media, P2, Type: Performance, Pod: WP & Infra, Group: Library, Package: Media

#10125 Media: Fix video drag an drop upload in Safari
  packages/media/src/seekVideo.js
Labels: Type: Bug, Group: Media, P1, Browser Issues, Pod: WP & Infra

#10095 Fix Karma tests / disconnect issues
  karma-story-editor.config.cjs
  packages/design-system/src/components/input/index.js
  packages/karma-puppeteer-launcher/src/index.cjs
  packages/story-editor/src/app/font/actions/useLoadFontFiles.js
  packages/story-editor/src/components/checklist/karma/checklist.karma.js
  packages/story-editor/src/components/dropTargets/karma/dropTarget.karma.js
  packages/story-editor/src/components/eyedropper/index.js
  packages/story-editor/src/components/footer/gridview/karma/gridView.karma.js
  packages/story-editor/src/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  packages/story-editor/src/components/library/panes/text/karma/textSets.cuj.karma.js
  packages/story-editor/src/components/panels/design/link/karma/link.karma.js
  packages/story-editor/src/components/panels/design/textStyle/karma/stylePresets.karma.js
  packages/story-editor/src/components/panels/design/textStyle/karma/textStyle.other.karma.js
Labels: Type: Bug, P1, Type: Infrastructure, Pod: Pea

#10056 Editor: Enable improved video captions by default
  includes/Experiments.php
Labels: Type: Enhancement

#9822 History: Allow ignoring element properties
  package-lock.json
  packages/story-editor/package.json
  packages/story-editor/src/app/history/historyProvider.js
  packages/story-editor/src/app/history/useHistoryReducer.js
  packages/story-editor/src/app/story/effects/useHistoryEntry.js
  packages/story-editor/src/app/story/utils/deleteNestedKeys.js
  packages/story-editor/src/app/story/utils/test/deleteNestedKeys.js
Labels: Type: Enhancement, cla: yes, Pod: Prometheus

#10127 Editor: Fix double scrollbars while zoomed
  packages/story-editor/src/components/canvas/layout.js
Labels: Type: Bug, Pod: Prometheus

#10134 UI Simplification: Add Design panel button to replace background media
  packages/story-editor/src/components/form/index.js
  packages/story-editor/src/components/form/mediaUploadButton.js
  packages/story-editor/src/components/library/panes/media/local/mediaPane.js
  packages/story-editor/src/components/panels/design/pageBackground/pageBackground.js
  packages/story-editor/src/components/panels/design/pageBackground/test/pageBackground.js
Labels: Type: Enhancement, Pod: Prometheus

#10028 Fix Color Picker: Saving text background color saves text color instead
  packages/story-editor/src/components/colorPicker/basicColorList.js
  packages/story-editor/src/components/colorPicker/basicColorPicker.js
  packages/story-editor/src/components/colorPicker/colorAdd.js
  packages/story-editor/src/components/colorPicker/colorPicker.js
  packages/story-editor/src/components/colorPicker/karma/colorPicker.karma.js
  packages/story-editor/src/components/panels/design/textStyle/backgroundColor.js
  packages/story-editor/src/karma/fixture/containers/designPanel/textStyle.js
  packages/story-editor/src/utils/presetUtils.js
  packages/story-editor/src/utils/useAddPreset.js
Labels: Type: Bug, Group: Saved Colors

#10128 Editor: Fixed zoomed scroll in RTL
  packages/story-editor/src/components/canvas/layout.js
Labels: Type: Bug, Pod: Prometheus

#10044 Performance: Clean Up Excessive pageHash Updates
  packages/story-editor/src/app/story/storyProvider.js
  packages/story-editor/src/utils/usePageAsCanvas.js
Labels: Type: Performance, Pod: Pea, Package: Story Editor

#10163 E2E Tests: Test against WP 5.9-RC2
  .github/workflows/tests-e2e.yml
Labels: Type: Infrastructure, Pod: WP & Infra, Package: E2E Tests

#10104 Templates: convert some PNG images to JPEG
  packages/templates/src/raw/12-hours-in-barcelona/template.json
  packages/templates/src/raw/ace-hotel-kyoto-review/template.json
  packages/templates/src/raw/album-releases/template.json
  packages/templates/src/raw/almodos-films/template.json
  packages/templates/src/raw/an-artists-legacy/template.json
  packages/templates/src/raw/art-books-gift-guide/template.json
  packages/templates/src/raw/baking-bread-guide/template.json
  packages/templates/src/raw/beauty-quiz/template.json
  packages/templates/src/raw/belly-fat-workout/template.json
  packages/templates/src/raw/buying-art-on-the-internet/template.json
  packages/templates/src/raw/elegant-travel-itinerary/template.json
  packages/templates/src/raw/fashion-inspiration/template.json
  packages/templates/src/raw/fashion-on-the-go/template.json
  packages/templates/src/raw/hawaii-travel-packing-list/template.json
  packages/templates/src/raw/honeymooning-in-italy/template.json
  packages/templates/src/raw/how-contact-tracing-works/template.json
  packages/templates/src/raw/how-video-calls-saved-the-day/template.json
  packages/templates/src/raw/kitchen-stories/template.json
  packages/templates/src/raw/los-angeles-city-guide/template.json
  packages/templates/src/raw/magazine-article/template.json
  packages/templates/src/raw/modernist-travel-guide/template.json
  packages/templates/src/raw/new-york-party-round-up/template.json
  packages/templates/src/raw/one-day-city-itinerary/template.json
  packages/templates/src/raw/pizzas-in-nyc/template.json
  packages/templates/src/raw/plant-based-dyes/template.json
  packages/templates/src/raw/rock-music-festival/template.json
  packages/templates/src/raw/sangria-artichoke/template.json
  packages/templates/src/raw/self-care-guide/template.json
  packages/templates/src/raw/sleep/template.json
  packages/templates/src/raw/street-style-on-the-go/template.json
  packages/templates/src/raw/summer-adventure-guide/template.json
  packages/templates/src/raw/summer-fashion-collection/template.json
  packages/templates/src/raw/sustainability-tips/template.json
  packages/templates/src/raw/technology-advice/template.json
  packages/templates/src/raw/tips-for-throwing-an-outdoor-luau/template.json
  packages/templates/src/raw/tv-show-recap/template.json
  packages/templates/src/raw/ultimate-comparison/template.json
  packages/templates/src/raw/ways-to-eat-avocado/template.json
Labels: Type: Enhancement, Group: Templates, Type: Performance, Pod: WP & Infra

#10096 Disable Update button if there are no changes to be saved
  packages/story-editor/src/components/header/buttons/test/update.js
  packages/story-editor/src/components/header/buttons/update.js
Labels: Type: Bug, Group: Workspace

#10169 Replace `useComposeRefs` with `useCombinedRefs`
  package-lock.json
  packages/design-system/src/components/contextMenu/menu.js
  packages/design-system/src/utils/index.js
  packages/design-system/src/utils/useComposeRefs.js
  packages/react/package.json
  packages/react/src/test/useCombinedRefs.js
Labels: P2, Type: Code Quality, Pod: WP & Infra, Package: React

#10008 Templates: Keyboard Nav Karma tests
  packages/story-editor/src/components/library/panes/pageTemplates/karma/defaultPageTemplates.karma.js
Labels: Type: Bug, Pod: Pea

#10172 Update Tested up to to 5.9
  readme.txt
Labels: P1, Type: Task, Pod: WP & Infra

#10063 Checklist: Offer page reload option when toggling Video Optimization setting
  packages/wp-story-editor/src/components/checklist/accessibility/videoOptimizationCheckbox/index.js
  packages/wp-story-editor/src/components/checklist/accessibility/videoOptimizationCheckbox/test/index.js
Labels: Type: Enhancement, Pod: Pea, Group: Pre-Publish Checklist, Group: Video Optimization

#10183 Code Quality: Stable callback reference for useCombinedRef
  packages/react/src/useCombinedRefs.js
Labels: Type: Code Quality

#10184 Library: Remove `showTextAndShapesSearchInput` experiment
  includes/Experiments.php
  packages/story-editor/src/components/library/panes/shapes/shapesPane.js
  packages/story-editor/src/components/library/panes/text/textPane.js
Labels: Type: Code Quality, Group: Library

#10188 Editor: Remove irrelevant `evt.persist()`
  packages/story-editor/src/app/canvas/canvasProvider.js
  packages/story-editor/src/utils/useDoubleClick.js
Labels: Type: Code Quality, Pod: Prometheus

#10081 Decoupling: Move help center footer to `wp-story-editor`
  packages/story-editor/src/components/footer/secondaryMenu.js
  packages/story-editor/src/components/helpCenter/companion/index.js
  packages/story-editor/src/components/helpCenter/index.js
  packages/story-editor/src/components/helpCenter/menu/index.js
  packages/wp-story-editor/src/components/helpCenter/footer/index.js
  packages/wp-story-editor/src/components/helpCenter/index.js
  packages/wp-story-editor/src/components/layout/index.js
Labels: Type: Enhancement, Package: Story Editor, Package: WP Story Editor

#10190 Design system: Make icon list searchable
  packages/design-system/src/icons/stories/index.js
Labels: Type: Documentation, Pod: Prometheus

#10024 Animations: Refactor animation state to improve performance
  packages/animation/src/components/WAAPIWrapper.js
  packages/animation/src/components/fullSizeAbsolute.js
  packages/animation/src/components/provider.js
  packages/animation/src/components/test/WAAPIWrapper.js
  packages/animation/src/components/types.js
  packages/animation/src/effects/flyIn/index.js
  packages/animation/src/effects/rotateIn/index.js
  packages/animation/src/effects/whooshIn/index.js
  packages/animation/src/effects/zoom/index.js
  packages/animation/src/parts/index.js
  packages/animation/src/parts/simpleAnimation.js
  packages/animation/src/parts/spin/index.js
  packages/animation/src/parts/test/index.js
  packages/animation/src/parts/types.js
  packages/story-editor/src/components/canvas/displayLayer.js
  packages/story-editor/src/components/canvas/karma/backgroundCopyPaste.karma.js
  packages/story-editor/src/components/canvas/karma/multiSelectionMovable.karma.js
  packages/story-editor/src/components/colorPicker/karma/eyedropper.karma.js
  packages/story-editor/src/components/dropTargets/karma/dropTarget.karma.js
  packages/story-editor/src/components/dropTargets/karma/order.karma.js
  packages/story-editor/src/components/previewPage/previewPage.js
Labels: Type: Enhancement, Group: Animations, Type: Performance, Type: Code Quality, Pod: Pea, Package: Animation

#10181 Explore Templates: fix RTL arrow directions
  packages/dashboard/src/app/views/exploreTemplates/modal/templateDetails/content/index.js
Labels: Type: Bug, Group: Templates, Bug Bash: 1.16.0

#10186 Use karma-parallel for running tests on CI
  .github/workflows/tests-karma-editor.yml
  karma-story-editor.config.cjs
  package-lock.json
  package.json
  packages/dashboard/src/dataUtils/formattedTemplatesArray.js
  patches/karma-parallel+0.3.1.patch
Labels: Type: Infrastructure, Pod: WP & Infra

#10202 Unit Tests: Fix proptype error in StoryMenu unit tests
  packages/dashboard/src/components/storyMenu/test/storyMenu.js
Labels: Type: Code Quality, Pod: Pea

#10162 Media Library: Fix video drag & drop and crash upon deletion
  packages/story-editor/src/components/library/panes/media/common/innerElement.js
  packages/story-editor/src/components/library/panes/media/common/mediaElement.js
Labels: Type: Bug, Group: Media, Group: Library

#10180 Pre-Publish Checklist: Flaky Karma Test
  packages/story-editor/src/components/checklist/karma/checklist.karma.js
Labels: Type: Bug, Type: Code Quality, Pod: Pea, Group: Pre-Publish Checklist

#10208 Karma: make parallel runs opt-in
  karma-story-editor.config.cjs
Labels: Type: Infrastructure, Pod: WP & Infra

#10198 Run JS unit tests and e2e tests in parallel on CI
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit-js.yml
  codecov.yml
  package-lock.json
  package.json
  packages/e2e-tests/package.json
  packages/e2e-tests/src/jest.config.js
  packages/e2e-tests/src/specs/dashboard/adminMenu.js
  packages/e2e-tests/src/specs/dashboard/dashboard.js
  packages/e2e-tests/src/specs/dashboard/documentTitle.js
  packages/jest-parallel-sequencer/README.md
  packages/jest-parallel-sequencer/package.json
  packages/jest-parallel-sequencer/src/index.js
  tests/js/jest.config.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10206 Editor: Fix image src desync
  packages/story-editor/src/components/canvas/karma/backgroundCopyPaste.karma.js
  packages/story-editor/src/components/dropTargets/karma/dropTarget.karma.js
  packages/story-editor/src/components/dropTargets/karma/order.karma.js
  packages/story-editor/src/elements/media/imageDisplay.js
Labels: Type: Bug, Pod: Prometheus

#10211 Enable new `AmpStoryCssOptimizer` transformer
  composer.json
  composer.lock
  includes/AMP/Optimization.php
  tests/phpunit/integration/tests/AMP/Optimization.php
  web-stories.php
Labels: Type: Enhancement, AMP Output, Type: Performance, Pod: WP & Infra

#10058 Pre-Publish Checklist: Add expand 'hidden page' functionality
  packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js
  packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooSmall.js
  packages/story-editor/src/components/checklist/checks/imageElementMissingAlt.js
  packages/story-editor/src/components/checklist/checks/imageElementResolution.js
  packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/component.js
  packages/story-editor/src/components/checklist/checks/pageTooLittleText.js
  packages/story-editor/src/components/checklist/checks/pageTooManyLinks.js
  packages/story-editor/src/components/checklist/checks/pageTooMuchText.js
  packages/story-editor/src/components/checklist/checks/shared/index.js
  packages/story-editor/src/components/checklist/checks/shared/test/thumbnailWrapper.js
  packages/story-editor/src/components/checklist/checks/shared/thumbnailWrapper.js
  packages/story-editor/src/components/checklist/checks/shared/videoChecklistCard.js
  packages/story-editor/src/components/checklist/checks/textElementFontSizeTooSmall.js
  packages/story-editor/src/components/checklist/checks/videoElementLength.js
  packages/story-editor/src/components/checklist/checks/videoElementMissingCaptions.js
  packages/story-editor/src/components/checklist/checks/videoElementMissingDescription.js
  packages/story-editor/src/components/checklist/checks/videoElementMissingPoster.js
  packages/story-editor/src/components/checklist/checks/videoElementResolution.js
  packages/story-editor/src/components/checklist/checks/videoOptimization.js
  packages/story-editor/src/components/checklistCard/checklistCard.js
  packages/story-editor/src/components/checklistCard/constants.js
  packages/story-editor/src/components/checklistCard/stories/index.js
  packages/story-editor/src/components/checklistCard/styles.js
  packages/story-editor/src/components/tablist/stories/index.js
  packages/story-editor/src/components/thumbnail/overflowThumbnail.js
Labels: Type: Enhancement, Pod: Pea, Group: Pre-Publish Checklist

#10219 Embeds: Use native `<img>` instead of `<amp-img>`
  includes/Renderer/Stories/Renderer.php
  packages/stories-block/src/css/common.css
  packages/stories-block/src/css/views/circles.css
Labels: Type: Enhancement, AMP Output

#10237 Code Quality: remove `enableCORSProxy` feature flag code
  includes/Experiments.php
  includes/REST_API/Hotlinking_Controller.php
  packages/story-editor/src/components/library/panes/media/local/karma/hotlink.karma.js
  packages/story-editor/src/components/panels/design/link/test/link.js
  packages/story-editor/src/utils/useCORSProxy.js
Labels: Type: Code Quality, Pod: WP & Infra

#10230 Add changelog for v1.16.0 release
  readme.txt
Labels: Type: Documentation, Type: Release

#10218 Media Library: Fix lingering BlurHash for videos
  packages/story-editor/src/components/library/panes/media/common/mediaElement.js
Labels: Type: Bug, Group: Media, Elements: Video, Pod: WP & Infra, Group: Library, Bug Bash: 1.16.0

#10193 Explore Templates: Reset image state in modal
  packages/dashboard/src/app/views/exploreTemplates/modal/templateDetails/content/index.js
Labels: Type: Bug, Group: Dashboard, Type: Performance, Pod: Pea, Bug Bash: 1.16.0

#10078 Page Templates: Fix dropdown select in library pane
  packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js
Labels: Type: Bug, Type: Code Quality, Group: Library, Group: Page Templates

#10247 Media Library: don't use item index as `key` prop
  packages/story-editor/src/components/library/panes/media/common/mediaGallery.js
Labels: Type: Bug, Group: Media, Group: Library

#10242 Video Trimmer: don't use `railBackgroundImage` if `null`
  packages/story-editor/src/components/videoTrim/videoTrimmer.js
Labels: Type: Bug, Group: Media, Elements: Video, Type: Code Quality

#10217 Allow completely disabling/hiding default templates
  includes/Admin/Dashboard.php
  includes/Admin/Editor.php
  packages/dashboard/src/app/views/myStories/content/index.js
  packages/dashboard/src/app/views/myStories/index.js
  packages/dashboard/src/components/interfaceSkeleton/index.js
  packages/dashboard/src/components/pageStructure/leftRail.js
  packages/dashboard/src/karma/fixture.js
  packages/e2e-tests/src/plugins/web-stories-disable-default-templates.php
  packages/e2e-tests/src/specs/dashboard/templates/useTemplate.js
  packages/e2e-tests/src/specs/editor/templates.js
  packages/story-editor/src/components/library/libraryProvider.js
  packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js
  packages/story-editor/src/defaultConfig.js
  packages/story-editor/src/karma/fixture/fixture.js
Labels: Type: Enhancement, Group: Templates, P2, Group: Dashboard, Pod: WP & Infra

#10076 Decoupling: Hide 'copy story url' from dashboard menu when url is `undefined`
  packages/dashboard/src/app/views/myStories/content/storiesView/index.js
  packages/dashboard/src/app/views/myStories/content/storyGridItem/index.js
  packages/dashboard/src/app/views/myStories/content/storyGridView/index.js
  packages/dashboard/src/app/views/myStories/content/storyListItem/index.js
  packages/dashboard/src/components/popoverMenu/story-menu-generator.js
  packages/dashboard/src/components/popoverMenu/test/story-menu-generator.js
  packages/dashboard/src/constants/stories.js
  packages/dashboard/src/types.js
Labels: Group: Dashboard, Package: Dashboard

#10264 Karma: Fix Page Templates Test Failure
  packages/story-editor/src/karma/fixture/containers/library/pageTemplates.js
  packages/story-editor/src/karma/integrationLayerTesting/optionalCallbacks.karma.js
Labels: Type: Bug, Pod: Pea, Group: Page Templates

#10267 Change namespace of animation package
  package-lock.json
  packages/animation/package.json
  packages/dashboard/package.json
  packages/story-editor/package.json
  packages/story-editor/src/app/canvas/useCanvasKeys.js
  packages/story-editor/src/app/helpCenter/provider.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/setSelectedElements.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/updateElements.js
  packages/story-editor/src/app/story/useStoryReducer/test/restore.js
  packages/story-editor/src/app/story/useStoryReducer/test/setSelectedElementsById.js
  packages/story-editor/src/app/story/useStoryReducer/test/updateAnimationState.js
  packages/story-editor/src/app/story/useStoryReducer/test/updateSelectedElements.js
  packages/story-editor/src/app/story/useStoryReducer/useStoryReducer.js
  packages/story-editor/src/components/canvas/displayElement.js
  packages/story-editor/src/components/canvas/displayLayer.js
  packages/story-editor/src/components/canvas/framesLayer.js
  packages/story-editor/src/components/canvas/pagemenu/animationToggle.js
  packages/story-editor/src/components/canvas/selection.js
  packages/story-editor/src/components/inspector/design/designInspector.js
  packages/story-editor/src/components/panels/design/animation/animation.js
  packages/story-editor/src/components/panels/design/animation/directionRadioInput.js
  packages/story-editor/src/components/panels/design/animation/effectChooserDropdown/dropdownConstants.js
  packages/story-editor/src/components/panels/design/animation/effectChooserDropdown/types.js
  packages/story-editor/src/components/panels/design/animation/effectChooserDropdown/utils/updateDynamicProps.js
  packages/story-editor/src/components/panels/design/animation/effectInput.js
  packages/story-editor/src/components/panels/design/animation/effectPanel.js
  packages/story-editor/src/components/panels/design/animation/karma/animation.karma.js
  packages/story-editor/src/components/panels/design/animation/stories/directionRadioInput.js
  packages/story-editor/src/components/panels/design/animation/stories/effectChooser.js
  packages/story-editor/src/components/panels/design/animation/test/directionRadioInput.js
  packages/story-editor/src/components/panels/design/animation/test/effectInput.js
  packages/story-editor/src/components/previewPage/previewPage.js
  packages/story-editor/src/elements/media/edit.js
  packages/story-editor/src/elements/media/scalePanel.js
  packages/story-editor/src/output/element.js
  packages/story-editor/src/output/page.js
  packages/story-editor/src/output/test/textElement.js
  packages/story-editor/src/types.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10268 Change namespace of dashboard package
  .storybook/preview.js
  .storybook/stories/playground/dashboard/index.js
  package-lock.json
  package.json
  packages/dashboard/package.json
  packages/wp-dashboard/package.json
  packages/wp-dashboard/src/api/hooks/useFontsApi.js
  packages/wp-dashboard/src/api/hooks/useMediaApi.js
  packages/wp-dashboard/src/api/hooks/usePagesApi.js
  packages/wp-dashboard/src/api/hooks/usePublisherLogosApi.js
  packages/wp-dashboard/src/api/hooks/useSettingsApi.js
  packages/wp-dashboard/src/api/hooks/useUserApi.js
  packages/wp-dashboard/src/api/story.js
  packages/wp-dashboard/src/api/test/editorSettingsApi.js
  packages/wp-dashboard/src/components/editorSettings/archive/index.js
  packages/wp-dashboard/src/components/editorSettings/components.js
  packages/wp-dashboard/src/components/editorSettings/editorSettings.js
  packages/wp-dashboard/src/components/editorSettings/publisherLogo/index.js
  packages/wp-dashboard/src/components/editorSettings/publisherLogo/stories/index.js
  packages/wp-dashboard/src/components/layout/index.js
  packages/wp-dashboard/src/components/telemetryBanner/index.js
  packages/wp-dashboard/src/effects/useAdminSubMenu.js
  packages/wp-dashboard/src/effects/useTelemetryOptIn.js
  packages/wp-dashboard/src/index.js
  packages/wp-dashboard/src/testUtils/renderWithProviders.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10269 Change namespace of date package
  package-lock.json
  packages/dashboard/package.json
  packages/dashboard/src/app/api/useTemplateApi.js
  packages/dashboard/src/app/serializers/templates.js
  packages/dashboard/src/app/serializers/test/templates.js
  packages/dashboard/src/app/views/myStories/content/storyGridItem/index.js
  packages/dashboard/src/app/views/myStories/content/storyListItem/index.js
  packages/dashboard/src/app/views/myStories/karma/myStoriesList.karma.js
  packages/dashboard/src/components/pageStructure/leftRail.js
  packages/dashboard/src/dataUtils/formattedStoriesArray.js
  packages/dashboard/src/dataUtils/formattedTemplatesArray.js
  packages/dashboard/src/karma/apiProviderFixture.js
  packages/date/package.json
  packages/story-editor/package.json
  packages/story-editor/src/components/form/dateTime/timeZone.js
  packages/story-editor/src/components/header/buttons/publish.js
  packages/story-editor/src/components/header/buttons/update.js
  packages/story-editor/src/components/library/panes/media/local/mediaEditDialog.js
  packages/story-editor/src/dataUtils/formattedTemplatesArray.js
  packages/templates/package.json
  packages/templates/src/test/raw.js
  packages/wp-dashboard/package.json
  packages/wp-dashboard/src/index.js
  packages/wp-story-editor/package.json
  packages/wp-story-editor/src/components/documentPane/publish/publishTime.js
  packages/wp-story-editor/src/index.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10271 Change namespace of fonts package
  .storybook/stories/playground/story-editor/api/fonts.js
  package-lock.json
  package.json
  packages/dashboard/src/components/scrollToTop/index.js
  packages/fonts/package.json
  packages/story-editor/package.json
  packages/story-editor/src/app/font/actions/useLoadFontFiles.js
  packages/story-editor/src/app/font/fontProvider.js
  packages/story-editor/src/app/font/utils.js
  packages/story-editor/src/components/form/link.js
  packages/story-editor/src/components/keyboardShortcutsMenu/index.js
  packages/story-editor/src/components/library/test/text/textPane.js
  packages/story-editor/src/components/library/test/text/textTab.js
  packages/story-editor/src/components/panels/design/textStyle/test/fontPicker.js
  packages/story-editor/src/output/utils/fontDeclarations.js
  packages/wp-dashboard/package.json
  packages/wp-dashboard/src/components/editorSettings/customFonts/index.js
  packages/wp-dashboard/src/components/editorSettings/customFonts/utils/getFontDataFromUrl.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10277 Change namespace of migration package
  .storybook/stories/playground/story-editor/api/story.js
  package-lock.json
  package.json
  packages/dashboard/package.json
  packages/migration/package.json
  packages/story-editor/package.json
  packages/story-editor/src/app/story/effects/useLoadStory.js
  packages/story-editor/src/components/checklist/karma/checklist.karma.js
  packages/story-editor/src/components/devTools/devTools.js
  packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js
  packages/story-editor/src/components/library/panes/pageTemplates/templateSave.js
  packages/story-editor/src/karma/fixture/db/storyResponse.js
  packages/story-editor/src/karma/fixture/fixture.js
  packages/templates/package.json
  packages/templates/src/getTemplates.js
  packages/text-sets/package.json
  packages/text-sets/src/loadTextSets.js
  packages/wp-story-editor/package.json
  packages/wp-story-editor/src/api/story.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10265 Add missing metadata to some packages
  .distignore
  package-lock.json
  packages/animation/.npmignore
  packages/animation/package.json
  packages/dashboard/.npmignore
  packages/dashboard/package.json
  packages/date/.npmignore
  packages/date/package.json
  packages/design-system/.npmignore
  packages/design-system/package.json
  packages/fonts/.npmignore
  packages/fonts/package.json
  packages/i18n/.npmignore
  packages/i18n/package.json
  packages/media/.npmignore
  packages/media/package.json
  packages/migration/.npmignore
  packages/migration/package.json
  packages/patterns/.npmignore
  packages/patterns/package.json
  packages/react/.npmignore
  packages/react/package.json
  packages/stickers/.npmignore
  packages/stickers/package.json
  packages/story-editor/.npmignore
  packages/story-editor/package.json
  packages/templates/.npmignore
  packages/templates/package.json
  packages/text-sets/.npmignore
  packages/text-sets/package.json
  packages/tracking/.npmignore
  packages/tracking/package.json
  packages/units/.npmignore
  packages/units/package.json
Labels: Type: Infrastructure, Pod: WP & Infra

#10209 Telemetry: Remove trackEvent call on mount
  packages/dashboard/src/utils/useStoryView.js
  packages/story-editor/src/components/library/panes/media/media3p/media3pPane.js
  packages/story-editor/src/components/library/panes/text/textSets/textSetsPane.js
Labels: Type: Bug, Pod: Pea, Group: Telemetry

#10284 Change namespace of templates package
  package-lock.json
  packages/dashboard/package.json
  packages/dashboard/src/app/api/useTemplateApi.js
  packages/dashboard/src/components/pageStructure/leftRail.js
  packages/story-editor/package.json
  packages/story-editor/src/app/api/apiProvider.js
  packages/story-editor/src/app/api/test/apiProvider.js
  packages/templates/package.json
Labels: Type: Infrastructure, Pod: WP & Infra

#10281 Karma: Fix Drop Target Handle Image Dragged from Library
  packages/story-editor/src/components/dropTargets/karma/dropTarget.karma.js
Labels: Type: Code Quality, Pod: Pea

#10283 Change namespace of story-editor package
  .storybook/preview.js
  .storybook/stories/playground/story-editor/header/buttons/index.js
  .storybook/stories/playground/story-editor/header/buttons/preview.js
  .storybook/stories/playground/story-editor/header/buttons/saveButton.js
  .storybook/stories/playground/story-editor/header/index.js
  .storybook/stories/playground/story-editor/index.js
  package-lock.json
  package.json
  packages/story-editor/package.json
  packages/wp-dashboard/package.json
  packages/wp-dashboard/src/api/story.js
  packages/wp-story-editor/package.json
  packages/wp-story-editor/src/api/story.js
  packages/wp-story-editor/src/components/checklist/accessibility/index.js
  packages/wp-story-editor/src/components/checklist/accessibility/videoOptimizationCheckbox/index.js
  packages/wp-story-editor/src/components/checklist/accessibility/videoOptimizationCheckbox/test/index.js
  packages/wp-story-editor/src/components/checklist/design/index.js
  packages/wp-story-editor/src/components/checklist/priority/index.js
  packages/wp-story-editor/src/components/checklist/priority/storyMissingPublisherName.js
  packages/wp-story-editor/src/components/documentPane/index.js
  packages/wp-story-editor/src/components/documentPane/publish/author.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
  packages/wp-story-editor/src/components/documentPane/publish/publishTime.js
  packages/wp-story-editor/src/components/documentPane/publish/test/publish.js
  packages/wp-story-editor/src/components/documentPane/status/status.js
  packages/wp-story-editor/src/components/documentPane/status/test/status.js
  packages/wp-story-editor/src/components/header/buttons/index.js
  packages/wp-story-editor/src/components/header/buttons/test/buttons.js
  packages/wp-story-editor/src/components/header/index.js
  packages/wp-story-editor/src/components/layout/index.js
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/test/useMediaPicker.js
  packages/wp-story-editor/src/components/mediaUpload/mediaPicker/useMediaPicker.js
  packages/wp-story-editor/src/components/metaBoxes/menuItem/index.js
  packages/wp-story-editor/src/components/metaBoxes/metaBoxes.js
  packages/wp-story-editor/src/components/metaBoxes/metaBoxesArea.js
  packages/wp-story-editor/src/components/metaBoxes/metaBoxesProvider.js
  packages/wp-story-editor/src/components/metaBoxes/test/useSaveMetaBoxes.js
  packages/wp-story-editor/src/components/metaBoxes/useSaveMetaBoxes.js
  packages/wp-story-editor/src/components/postLock/postLock.js
  packages/wp-story-editor/src/components/postLock/postLockDialog.js
  packages/wp-story-editor/src/components/postLock/postTakeOverDialog.js
  packages/wp-story-editor/src/components/postLock/test/postLock.js
  packages/wp-story-editor/src/components/postPublishDialog/index.js
  packages/wp-story-editor/src/components/postPublishDialog/stories/postPublishDialog.js
  packages/wp-story-editor/src/components/postPublishDialog/test/postPublishDialog.js
  packages/wp-story-editor/src/components/statusCheck/statusCheck.js
  packages/wp-story-editor/src/components/statusCheck/statusCheckFailed.js
  packages/wp-story-editor/src/components/statusCheck/test/statusCheck.js
  packages/wp-story-editor/src/components/statusCheck/utils.js
  packages/wp-story-editor/src/index.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10290 Code Quality: Lint `package.json` files
  .distignore
  .github/workflows/lint-css-js-md.yml
  .gitignore
  .npmpackagejsonlintrc.json
  package-lock.json
  package.json
  packages/activation-notice/package.json
  packages/animation/package.json
  packages/commander/package.json
  packages/dashboard/package.json
  packages/date/package.json
  packages/design-system/package.json
  packages/e2e-test-utils/package.json
  packages/e2e-tests/package.json
  packages/fonts/package.json
  packages/glider/package.json
  packages/i18n/package.json
  packages/imgareaselect/package.json
  packages/jest-amp/package.json
  packages/jest-parallel-sequencer/package.json
  packages/jest-puppeteer-amp/package.json
  packages/karma-failed-tests-reporter/package.json
  packages/karma-fixture/package.json
  packages/karma-puppeteer-client/package.json
  packages/karma-puppeteer-launcher/package.json
  packages/media/package.json
  packages/migration/package.json
  packages/patterns/package.json
  packages/react/package-lock.json
  packages/react/package.json
  packages/stickers/package.json
  packages/stories-block/package.json
  packages/stories-carousel/package.json
  packages/stories-lightbox/package.json
  packages/story-editor/package.json
  packages/templates/package.json
  packages/text-sets/package.json
  packages/tinymce-button/package.json
  packages/tracking/package.json
  packages/units/package.json
  packages/widget/package.json
  packages/wp-dashboard/package.json
  packages/wp-story-editor/package.json
Labels: Type: Infrastructure, Type: Code Quality, Pod: WP & Infra

#10296 Decoupling: Add karma tests for story editor integration layer
  packages/design-system/src/utils/deepMerge.js
  packages/design-system/src/utils/test/deepMerge.js
  packages/story-editor/src/karma/integrationLayerTesting/config.karma.js
Labels: Type: Infrastructure, Package: Story Editor

#10299 Tag linked issues with ZenHub release after merging
  .github/workflows/add-milestone.yml
Labels: Type: Infrastructure, Pod: WP & Infra

#10001 Media: refactor upload logic to reduce complexity
  packages/story-editor/src/app/media/utils/getResourceFromLocalFile.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/reducer.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/test/reducer.js
Labels: Group: Media, Type: Code Quality, Pod: WP & Infra

#9944 Karma: Improve output to reduce noise
  package-lock.json
  package.json
  packages/dashboard/src/app/api/useStoryApi.js
  packages/dashboard/src/app/views/myStories/index.js
  packages/dashboard/src/dataUtils/formattedTemplatesArray.js
  packages/design-system/src/components/checkbox/index.js
  packages/design-system/src/components/input/index.js
  packages/design-system/src/components/popup/index.js
  packages/design-system/src/components/snackbar/snackbarMessage.js
  packages/design-system/src/components/tooltip/index.js
  packages/react/src/useResizeEffect.js
  packages/story-editor/src/app/currentUser/currentUserProvider.js
  packages/story-editor/src/app/media/local/useContextValueProvider.js
  packages/story-editor/src/components/canvas/displayLayer.js
  packages/story-editor/src/components/canvas/karma/quickActions.karma.js
  packages/story-editor/src/components/canvas/karma/rightClickMenu.karma.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/index.js
  packages/story-editor/src/components/canvas/utils/useUpdateSelectionRectangle.js
  packages/story-editor/src/components/checklist/checklistContent/designChecks.js
  packages/story-editor/src/components/checklist/checklistContent/priorityChecks.js
  packages/story-editor/src/components/checklist/karma/checklist.karma.js
  packages/story-editor/src/components/checklist/karma/prepublishSelect.karma.js
  packages/story-editor/src/components/elementLink/frame.js
  packages/story-editor/src/components/footer/karma/zoomSelector.karma.js
  packages/story-editor/src/components/form/color/colorInput.js
  packages/story-editor/src/components/helpCenter/menu/tips.js
  packages/story-editor/src/components/helpCenter/navigator/bottomNavigation.js
  packages/story-editor/src/components/library/libraryProvider.js
  packages/story-editor/src/components/library/panes/media/media3p/karma/mediaFetching.karma.js
  packages/story-editor/src/components/panels/design/link/karma/link.karma.js
  packages/story-editor/src/components/panels/design/link/link.js
  packages/story-editor/src/components/popup/index.js
  packages/story-editor/src/dataUtils/formattedTemplatesArray.js
  packages/story-editor/src/elements/media/display.js
  packages/story-editor/src/elements/media/visibleImage.js
  packages/story-editor/src/elements/video/karma/elementMinSizeAndPlayback.karma.js
  packages/story-editor/src/elements/video/playPauseButton.js
  packages/story-editor/src/karma/fixture/fixture.js
  patches/puppeteer+10.4.0.patch
  patches/puppeteer+13.1.1.patch
Labels: Type: Infrastructure, Pod: WP & Infra

#10240 History: reduce polluting history
  packages/story-editor/src/app/story/effects/useHistoryEntry.js
  packages/story-editor/src/app/story/utils/deleteNestedKeys.js
  packages/story-editor/src/app/story/utils/test/deleteNestedKeys.js
Labels: Type: Enhancement, Pod: Prometheus

#10262 Performance: Remove Extraneous Re-Renders in Frames Layer
  packages/story-editor/src/app/canvas/canvasProvider.js
  packages/story-editor/src/components/canvas/frameElement.js
  packages/story-editor/src/components/canvas/framesLayer.js
  packages/story-editor/src/components/canvas/test/_utils.js
  packages/story-editor/src/components/transform/useTransformHandler.js
Labels: Type: Performance, Pod: Pea, Package: Story Editor

#10342 Fix video captions appearance on frontend
  packages/story-editor/src/output/utils/styles.js
Labels: Group: Media, Elements: Video, AMP Output, Pod: WP & Infra, Type: UX Quality

#10337 Media: Don't set transcoding state for non-videos
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js
  packages/story-editor/src/app/media/utils/useMediaUploadQueue/test/useMediaUploadQueue.js
Labels: Type: Bug, Group: Media, Pod: WP & Infra, Group: Video Optimization

#10362 Fix broken media in storybook
  .storybook/stories/playground/story-editor/getDummyMedia.js
Labels: Type: Infrastructure, Package: Story Editor

#10294 Context Menu: Remove 'clear styles' functionality
  docs/right-click-menu.md
  packages/story-editor/src/app/rightClickMenu/constants.js
  packages/story-editor/src/app/rightClickMenu/provider.js
  packages/story-editor/src/app/rightClickMenu/test/useRightClickMenu.js
  packages/story-editor/src/app/rightClickMenu/test/utils.js
  packages/story-editor/src/app/rightClickMenu/utils.js
  packages/story-editor/src/components/canvas/karma/rightClickMenu.karma.js
  packages/story-editor/src/elements/gif/constants.js
  packages/story-editor/src/elements/image/constants.js
  packages/story-editor/src/elements/shape/constants.js
  packages/story-editor/src/elements/text/constants.js
  packages/story-editor/src/elements/video/constants.js
Labels: Type: Enhancement, Pod: Pea, Group: Context Menu

#9851 Shapes: Add simple border option
  packages/story-editor/src/app/story/useStoryReducer/reducers/combineElements.js
  packages/story-editor/src/app/story/useStoryReducer/test/combineElements.js
  packages/story-editor/src/components/canvas/displayElement.js
  packages/story-editor/src/components/panels/design/border/border.js
  packages/story-editor/src/components/panels/design/border/borderWidth.js
  packages/story-editor/src/components/panels/design/border/karma/border.karma.js
  packages/story-editor/src/components/panels/design/sizePosition/karma/borderRadius.karma.js
  packages/story-editor/src/components/panels/design/sizePosition/radius.js
  packages/story-editor/src/elements/media/display.js
  packages/story-editor/src/elements/shape/display.js
  packages/story-editor/src/elements/shared/index.js
  packages/story-editor/src/masks/borderedMaskedElement.js
  packages/story-editor/src/masks/constants.js
  packages/story-editor/src/masks/display.js
  packages/story-editor/src/masks/index.js
  packages/story-editor/src/masks/output.js
  packages/story-editor/src/output/test/page.js
  packages/story-editor/src/utils/elementBorder.js
Labels: Type: Enhancement

#10367 Move migration CLI to scripts folder
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  packages/migration/.npmignore
  packages/migration/package.json
  packages/migration/rollup.config.migrate.js
  packages/migration/scripts/cli.js
  packages/migration/scripts/utils/test/updateTemplates.js
  packages/migration/scripts/utils/updateTemplates.js
Labels: Type: Infrastructure, Pod: WP & Infra

#10241 Context Menu: New elements should be selected after duplication
  packages/story-editor/src/app/canvas/useCanvasKeys.js
  packages/story-editor/src/app/rightClickMenu/provider.js
  packages/story-editor/src/app/story/useStoryReducer/actions.js
  packages/story-editor/src/app/story/useStoryReducer/reducer.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/duplicateElementById.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/duplicateElementsById.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/index.js
  packages/story-editor/src/app/story/useStoryReducer/reducers/setSelectedElements.js
  packages/story-editor/src/app/story/useStoryReducer/test/duplicatElementById.js
  packages/story-editor/src/app/story/useStoryReducer/test/duplicateElementsById.js
  packages/story-editor/src/app/story/useStoryReducer/types.js
  packages/story-editor/src/components/canvas/karma/cloneSelection.karma.js
  packages/story-editor/src/components/panels/design/layer/layer.js
Labels: Type: Enhancement, Pod: Pea, Group: Context Menu, Bug Bash: 1.16.0

#10288 Background Audio: Add Initial Captions Support
  includes/Experiments.php
  packages/migration/src/migrate.js
  packages/migration/src/migrations/v0039_backgroundAudioFormatting.js
  packages/story-editor/src/app/story/utils/test/getStoryPropsToSave.js
  packages/story-editor/src/components/panels/design/captions/captions.js
  packages/story-editor/src/components/panels/design/pageBackgroundAudio/backgroundAudio.js
  packages/story-editor/src/components/panels/design/pageBackgroundAudio/test/backgroundAudio.js
  packages/story-editor/src/components/panels/document/backgroundAudio/backgroundAudio.js
  packages/story-editor/src/components/panels/document/backgroundAudio/test/backgroundAudio.js
  packages/story-editor/src/components/panels/shared/backgroundAudioPanelContent.js
  packages/story-editor/src/components/panels/shared/captionsPanelContent.js
  packages/story-editor/src/output/page.js
  packages/story-editor/src/output/story.js
  packages/story-editor/src/output/test/__snapshots__/page.js.snap
  packages/story-editor/src/output/test/page.js
  packages/story-editor/src/output/test/story.js
  packages/story-editor/src/output/utils/HiddenAudio.js
  packages/story-editor/src/output/utils/getUsedAmpExtensions.js
  packages/story-editor/src/output/utils/test/getUsedAmpExtensions.js
  packages/story-editor/src/types.js
Labels: Group: Media, Group: Document Panel, Pod: WP & Infra, Type: Support, Group: Background Audio

#10371 Background Audio: Add unit test for migration
  packages/migration/src/migrations/test/v0039_backgroundAudioFormatting.js
Labels: Type: Enhancement, Group: Media, Pod: WP & Infra, Group: Migrations, Package: Migration

#10383 Editor: Stop crashing when pulling in video element
  packages/story-editor/src/components/popup/index.js
Labels: Type: Bug, Elements: Video, Group: Canvas, Group: Workspace, Bug Bash: 1.17.0

#10390 Update tests after WordPress 5.9 release
  .github/workflows/tests-e2e.yml
  composer.json
  composer.lock
  includes/Integrations/Jetpack.php
  includes/Post_Type_Base.php
  includes/REST_API/Font_Controller.php
  includes/REST_API/Stories_Base_Controller.php
  includes/REST_API/Stories_Terms_Controller.php
Labels: Type: Infrastructure, Pod: WP & Infra

#10369 E2E Tests: Optimize workflow for parallel runs
  .github/workflows/tests-e2e.yml
  package.json
Labels: Type: Infrastructure, Pod: WP & Infra

#10343 Improve save-blocking media uploading checks
  packages/story-editor/src/components/autoSaveHandler/index.js
  packages/story-editor/src/components/autoSaveHandler/test/autoSaveHandler.js
  packages/story-editor/src/components/form/radioGroup/index.js
  packages/story-editor/src/components/header/buttons/preview.js
  packages/story-editor/src/components/header/buttons/publish.js
  packages/story-editor/src/components/header/buttons/switchToDraft.js
  packages/story-editor/src/components/header/buttons/test/publish.js
  packages/story-editor/src/components/header/buttons/test/switchToDraft.js
  packages/story-editor/src/components/header/buttons/update.js
  packages/story-editor/src/components/library/panes/media/media3p/test/media3pPane.js
  packages/story-editor/src/components/panels/design/captions/captions.js
  packages/story-editor/src/components/panels/design/captions/test/captions.js
  packages/story-editor/src/components/panels/shared/captionsPanelContent.js
  packages/story-editor/src/index.js
  packages/story-editor/src/utils/test/useIsUploadingToStory.js
  packages/story-editor/src/utils/useIsUploadingToStory.js
  packages/wp-story-editor/src/components/documentPane/status/status.js
Labels: Type: Enhancement, Group: Media, Pod: WP & Infra

#10370 UI Simplification: Consider aspect ratio lock when resizing
  packages/story-editor/src/components/canvas/singleSelectionMoveable/index.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/useResize.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/useRotate.js
  packages/story-editor/src/components/library/panes/shapes/shapePreview.js
  packages/story-editor/src/components/panels/design/sizePosition/karma/sizePosition.karma.js
  packages/story-editor/src/elements/image/constants.js
  packages/story-editor/src/elements/text/constants.js
  packages/story-editor/src/elements/text/updateForResizeEvent.js
Labels: Type: Enhancement, Pod: Prometheus

#10005 Add filter to allow custom attributes on Web Stories rendering
  includes/Renderer/Stories/Renderer.php
  tests/phpunit/integration/tests/Renderer/Stories/Renderer.php
Labels: Type: Enhancement, Group: WordPress, Pod: WP & Infra, Group: Blocks

#10360 Explore Templates: adjust modal size
  packages/dashboard/src/app/views/exploreTemplates/modal/index.js
Labels: Type: Enhancement, Group: Dashboard, Pod: Pea

#10389 Support `tel:` and `mailto:` links
  packages/design-system/src/utils/test/url.js
  packages/design-system/src/utils/url.js
  packages/story-editor/src/components/panels/design/link/link.js
  packages/story-editor/src/components/panels/design/pageAttachment/pageAttachment.js
Labels: Type: Enhancement, Group: Links, Group: Page Attachment

#10401 Background Audio: Support non-looping audio
  packages/story-editor/src/components/panels/design/pageBackgroundAudio/backgroundAudio.js
  packages/story-editor/src/components/panels/design/pageBackgroundAudio/test/backgroundAudio.js
  packages/story-editor/src/components/panels/design/videoOptions/videoOptions.js
  packages/story-editor/src/components/panels/document/pageAdvancement/pageAdvancement.js
  packages/story-editor/src/components/panels/shared/backgroundAudioPanelContent.js
  packages/story-editor/src/components/panels/shared/loopPanelContent.js
  packages/story-editor/src/constants/index.js
  packages/story-editor/src/output/page.js
  packages/story-editor/src/output/test/__snapshots__/page.js.snap
  packages/story-editor/src/output/test/page.js
  packages/story-editor/src/output/utils/HiddenAudio.js
  packages/story-editor/src/output/utils/getAutoAdvanceAfter.js
  packages/story-editor/src/output/utils/test/getAutoAdvanceAfter.js
  packages/story-editor/src/types.js
Labels: Type: Enhancement, Group: Media, P2, Group: Document Panel, Pod: WP & Infra, Group: Background Audio

#10404 Editor: First stage of floating menu bar
  includes/Experiments.php
  packages/story-editor/src/app/canvas/canvasProvider.js
  packages/story-editor/src/app/layout/useZoomSetting.js
  packages/story-editor/src/components/canvas/canvasLayout.js
  packages/story-editor/src/components/canvas/editElement.js
  packages/story-editor/src/components/canvas/layout.js
  packages/story-editor/src/components/canvas/multiSelectionMoveable/index.js
  packages/story-editor/src/components/canvas/selection.js
  packages/story-editor/src/components/canvas/singleSelectionMoveable/index.js
  packages/story-editor/src/components/floatingMenu/index.js
  packages/story-editor/src/components/floatingMenu/layer.js
  packages/story-editor/src/components/floatingMenu/menu.js
  packages/story-editor/src/constants/index.js
Labels: Type: Enhancement, Pod: Prometheus
