Repository GoogleForCreators/web-stories-wp, pull requests merged in 2023-07, with the labels that each got.

#13410 Settings: Properly display page titles with HTML entities in them
  packages/wp-dashboard/package.json
  packages/wp-dashboard/src/api/hooks/usePagesApi.js
Labels: Type: Bug, Group: WordPress, Group: Settings, P3

#13413 Bump WP version requirement to 6.1
  .github/workflows/tests-unit-php.yml
  composer.lock
  includes/REST_API/Font_Controller.php
  includes/REST_API/Publisher_Logos_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/REST_API/Stories_Lock_Controller.php
  includes/REST_API/Stories_Media_Controller.php
  packages/e2e-test-utils/src/visitBlockWidgetScreen.js
  packages/stories-block/src/block/components/storyCard.js
  packages/stories-block/src/block/components/storyPicker/storyPreview.js
  packages/stories-block/src/block/components/test/storyCard.js
  phpcs.xml.dist
  readme.txt
  tests/phpstan/bootstrap.php
  tests/phpunit/integration/tests/REST_API/Stories_Controller.php
  tests/phpunit/integration/tests/REST_API/Stories_Media_Controller.php
  web-stories.php
Labels: Type: Task, Group: WordPress, Type: Code Quality

#13427 WordPress 6.3 Compatibility
  .github/workflows/tests-e2e.yml
  composer.lock
  includes/Page_Template_Post_Type.php
  includes/Story_Post_Type.php
  packages/e2e-tests/src/specs/wordpress/webStoriesBlock.js
  readme.txt
  web-stories.php
Labels: Type: Enhancement, Type: Code Quality, Package: E2E Tests

#13430 Fix: Remove `WP_Post` type hint from `prefill_post_content`
  includes/Admin/Admin.php
Labels: Type: Bug, Group: Integration, Group: WordPress, P3

#13432 Shortcode: Properly handle case where no attributes are passed
  includes/Shortcode/Embed_Shortcode.php
Labels: Type: Bug, P2, Group: WordPress, Group: Shortcodes
