Repository GoogleForCreators/web-stories-wp, pull requests merged in 2023-11, with the labels that each got.

#13493 Block: Fix issues with stories not appearing in lightbox
  packages/stories-lightbox/src/web-stories-lightbox.js
Labels: Type: Bug, AMP Format, P3, Group: Blocks

#13492 Update dependencies
  .github/workflows/tests-e2e.yml
  .storybook/main.cjs
  README.md
  babel.config.cjs
  karma-dashboard.config.cjs
  karma-story-editor.config.cjs
  package-lock.json
  package.json
  packages/commander/package.json
  packages/dashboard/src/app/views/myStories/karma/myStoriesList.karma.js
  packages/e2e-tests/package.json
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/analytics.js
  packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js
  packages/migration/package.json
  packages/story-editor/src/components/checklist/karma/checklist.karma.js
  packages/story-editor/src/components/checklist/karma/prepublishSelect.karma.js
Labels: Type: Infrastructure

#13495 Layers: Prevent crash when undoing layer grouping
  packages/story-editor/src/components/panels/layer/groupLayer.js
  packages/story-editor/src/components/panels/layer/groupLayerActions.js
Labels: Type: Bug, P2, Group: Layers
