Repository GoogleForCreators/web-stories-wp, pull requests merged in 2023-01, with the labels that each got.

#12904 Remove obsolete composer patches
  composer.json
  composer.lock
  patches/phpunit-mock-objects.patch
Labels: Type: Infrastructure

#12894 TypeScript: Convert `popupProvider` from `design-system`
  packages/design-system/src/contexts/index.ts
  packages/design-system/src/contexts/popup/context.ts
  packages/design-system/src/contexts/popup/popupProvider.ts
  packages/design-system/src/contexts/popup/usePopup.ts
  packages/design-system/src/types.ts
  packages/design-system/tsconfig.json
Labels: Type: Code Quality, Pod: Prometheus

#12846 Block: Use `useSelect` for data fetching
  packages/stories-block/src/block/block-types/latest-stories/edit.js
  packages/stories-block/src/block/components/authorSelection.js
  packages/stories-block/src/block/components/storyPicker/fetchSelectedStories.js
Labels: Type: Code Quality

#12872 Fix page template poster image generation
  includes/Admin/Dashboard.php
  includes/templates/admin/edit-story.php
  packages/story-editor/src/components/library/panes/pageTemplates/savedPageTemplate.js
  packages/wp-dashboard/src/api/constants/index.js
  packages/wp-story-editor/src/api/constants/index.js
  packages/wp-story-editor/src/api/pageTemplate.js
Labels: Type: Bug, Pod: Prometheus

#12869 Shapes: Simplified circle path
  packages/masks/src/constants.ts
Labels: Type: Bug, Pod: Prometheus

#12864 Don’t run db upgrader for fresh sites
  includes/Database_Upgrader.php
  includes/Infrastructure/ServiceBasedPlugin.php
  includes/Infrastructure/ServiceContainer.php
  includes/Infrastructure/ServiceContainer/SimpleServiceContainer.php
  includes/Integrations/Jetpack.php
  includes/Media/Media_Source_Taxonomy.php
  includes/Media/Video/Poster.php
  includes/Migrations/Add_Media_Source_Editor.php
  includes/Migrations/Add_Media_Source_Gif_Conversion.php
  includes/Migrations/Add_Media_Source_Page_Template.php
  includes/Migrations/Add_Media_Source_Recording.php
  includes/Migrations/Add_Media_Source_Source_Image.php
  includes/Migrations/Add_Media_Source_Source_Video.php
  includes/Migrations/Add_Media_Source_Video_Optimization.php
  includes/Migrations/Migration_Meta_To_Term.php
  includes/Migrations/Yoast_Reindex_Stories.php
  includes/Post_Type_Base.php
  includes/User/Capabilities.php
  tests/phpunit/integration/includes/Capabilities_Setup.php
  tests/phpunit/integration/tests/Infrastructure/ServiceBasedPluginTest.php
  tests/phpunit/integration/tests/REST_API/Embed_Controller.php
  tests/phpunit/integration/tests/Story_Archive.php
  tests/phpunit/integration/tests/Story_Post_Type.php
  tests/phpunit/integration/tests/User/Capabilities.php
Labels: Type: Enhancement, Group: WordPress, Pod: WP

#12908 PHPCS: Implement `StaticClosure` rule
  phpcs.xml.dist
  tests/phpunit/integration/tests/AMP/Sanitization.php
  tests/phpunit/integration/tests/Infrastructure/LazilyInstantiatedServiceTest.php
Labels: Type: Code Quality

#12839 Autosave: trigger autosave regardless of being idle
  packages/story-editor/src/components/autoSaveHandler/index.js
  packages/story-editor/src/components/autoSaveHandler/test/autoSaveHandler.js
Labels: Type: Bug, Pod: Prometheus

#12890 TypeScript: Convert canvas provider
  .eslintrc
  packages/design-system/src/contexts/snackbar/useSnackbar.ts
  packages/design-system/src/types.ts
  packages/design-system/src/types/snackbar.ts
  packages/design-system/src/utils/getKeyboardMovement.ts
  packages/element-library/src/test/index.js
  packages/elements/src/types/element.ts
  packages/elements/src/utils/elementIs.ts
  packages/elements/src/utils/getDefinitionForType.ts
  packages/react/src/useBatchingCallback.ts
  packages/rich-text/src/index.ts
  packages/rich-text/src/provider.tsx
  packages/rich-text/src/types.ts
  packages/story-editor/src/app/canvas/canvasProvider.tsx
  packages/story-editor/src/app/canvas/constants.ts
  packages/story-editor/src/app/canvas/context.ts
  packages/story-editor/src/app/canvas/index.ts
  packages/story-editor/src/app/canvas/useAddPastedElements.ts
  packages/story-editor/src/app/canvas/useCanvas.ts
  packages/story-editor/src/app/canvas/useCanvasBoundingBox.ts
  packages/story-editor/src/app/canvas/useCanvasCopyPaste.ts
  packages/story-editor/src/app/canvas/useCanvasKeys.ts
  packages/story-editor/src/app/canvas/useEditingElement.ts
  packages/story-editor/src/app/canvas/utils/getLayerArrangementProps.ts
  packages/story-editor/src/app/layout/useLayout.ts
  packages/story-editor/src/app/story/useStoryReducer/actions.ts
  packages/story-editor/src/components/canvas/displayElement.js
  packages/story-editor/src/components/canvas/useFocusCanvas.ts
  packages/story-editor/src/components/canvas/useInsertElement.ts
  packages/story-editor/src/components/canvas/useUploadWithPreview.d.ts
  packages/story-editor/src/components/canvas/utils/getElementProperties.ts
  packages/story-editor/src/components/library/panes/text/textPresets.ts
  packages/story-editor/src/types/canvasProvider.ts
  packages/story-editor/src/types/index.ts
  packages/story-editor/src/types/layoutProvider.ts
  packages/story-editor/src/types/storyProvider.ts
  packages/story-editor/src/utils/copyPaste.tsx
  packages/story-editor/tsconfig.json
Labels: Type: Infrastructure, Type: Code Quality, Pod: Prometheus

#12907 TypeScript: Convert `dashboard` router provider
  .storybook/main.cjs
  packages/dashboard/src/app/router/context.ts
  packages/dashboard/src/app/router/index.ts
  packages/dashboard/src/app/router/route.ts
  packages/dashboard/src/app/router/routerProvider.tsx
  packages/dashboard/src/app/router/test/router.js
  packages/dashboard/src/app/router/useRouteHistory.ts
  packages/dashboard/src/constants/components.ts
  packages/dashboard/src/constants/index.ts
  packages/dashboard/src/constants/pageStructure.ts
  packages/dashboard/src/constants/stories.ts
  packages/dashboard/src/constants/templates.ts
  packages/dashboard/src/icons/index.ts
  packages/dashboard/src/icons/svg-imports.d.ts
  packages/dashboard/src/types/index.ts
  packages/dashboard/src/types/routerProvider.ts
  packages/dashboard/tsconfig.json
  webpack.config.cjs
Labels: Type: Code Quality, Pod: Prometheus

#12699 TypeScript: Convert taxonomy provider
  packages/elements/src/types/index.ts
  packages/elements/src/types/story.ts
  packages/elements/src/types/taxonomies.ts
  packages/story-editor/src/app/api/useAPI.ts
  packages/story-editor/src/app/story/utils/getStoryPropsToSave.ts
  packages/story-editor/src/app/taxonomy/context.ts
  packages/story-editor/src/app/taxonomy/index.ts
  packages/story-editor/src/app/taxonomy/taxonomyProvider.js
  packages/story-editor/src/app/taxonomy/taxonomyProvider.tsx
  packages/story-editor/src/app/taxonomy/test/useTaxonomy.js
  packages/story-editor/src/app/taxonomy/useTaxonomy.ts
  packages/story-editor/src/app/taxonomy/utils/index.js
  packages/story-editor/src/app/taxonomy/utils/test/index.js
  packages/story-editor/src/components/panels/document/taxonomies/FlatTermSelector.js
  packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js
  packages/story-editor/src/components/panels/document/taxonomies/karma/taxonomies.karma.js
  packages/story-editor/src/karma/fixture/db/getTaxonomiesResponse.js
  packages/story-editor/src/karma/fixture/db/storyResponse.js
  packages/story-editor/src/karma/fixture/fixture.js
  packages/story-editor/src/types/apiProvider.ts
  packages/story-editor/src/types/configProvider.ts
  packages/story-editor/src/types/index.ts
  packages/story-editor/src/types/story.ts
  packages/story-editor/src/types/taxonomyProvider.ts
  packages/story-editor/tsconfig.json
  packages/wp-story-editor/src/api/utils/transformStoryResponse.js
Labels: Type: Code Quality, Pod: WP, Package: Design System

#12934 KSES: Adjust type for `post_parent` param
  includes/KSES.php
Labels: Type: Bug, Group: WordPress, Pod: WP

#12931 PHPCS: Enable cognitive complexity rule
  includes/AMP/Sanitization.php
  includes/Admin/Cross_Origin_Isolation.php
  includes/KSES.php
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Hotlinking_Controller.php
  includes/REST_API/Products_Controller.php
  includes/REST_API/Stories_Controller.php
  phpcs.xml.dist
Labels: Type: Infrastructure, Type: Code Quality, Pod: WP

#12930 PHPCS: better enforce parameter type hints
  includes/AMP/Tag_And_Attribute_Sanitizer.php
  includes/AMP/Traits/Sanitization_Utils.php
  includes/Admin/Activation_Notice.php
  includes/Admin/Admin.php
  includes/Admin/Cross_Origin_Isolation.php
  includes/Admin/Customizer.php
  includes/Admin/Dashboard.php
  includes/Admin/Editor.php
  includes/Admin/ImgAreaSelect_Patch.php
  includes/Admin/Meta_Boxes.php
  includes/Admin/PluginRowMeta.php
  includes/Admin/TinyMCE.php
  includes/Analytics.php
  includes/Database_Upgrader.php
  includes/Exception/FailedToMakeInstance.php
  includes/Exception/InvalidService.php
  includes/Infrastructure/Injector/FallbackInstantiator.php
  includes/Infrastructure/PluginActivationAware.php
  includes/Infrastructure/PluginDeactivationAware.php
  includes/Infrastructure/ServiceBasedPlugin.php
  includes/Integrations/AMP.php
  includes/Integrations/Conditional_Featured_Image.php
  includes/Integrations/Jetpack.php
  includes/Integrations/ShortPixel.php
  includes/KSES.php
  includes/Media/Image_Sizes.php
  includes/Media/Media_Source_Taxonomy.php
  includes/Media/SVG.php
  includes/Media/Video/Muting.php
  includes/Media/Video/Poster.php
  includes/Post_Type_Base.php
  includes/Shopping/Shopify_Query.php
  includes/Shopping/WooCommerce_Query.php
  includes/Story_Archive.php
  includes/Story_Post_Type.php
  includes/Taxonomy/Taxonomy_Base.php
  includes/User/Capabilities.php
  includes/User/Preferences.php
  includes/namespace.php
  phpcs.xml.dist
  tests/phpunit/integration/includes/Fixture/DummyClassWithDependency.php
  tests/phpunit/integration/tests/Admin/Admin.php
  tests/phpunit/integration/tests/Admin/Editor.php
  tests/phpunit/integration/tests/Integrations/Jetpack.php
  tests/phpunit/integration/tests/KSES.php
  tests/phpunit/integration/tests/Renderer/Archives.php
  tests/phpunit/integration/tests/Renderer/Feed.php
  tests/phpunit/integration/tests/Renderer/Oembed.php
  tests/phpunit/integration/tests/Renderer/Single.php
  tests/phpunit/integration/tests/Renderer/Story/HTML.php
  tests/phpunit/integration/tests/Settings.php
  tests/phpunit/integration/tests/Story_Archive.php
  tests/phpunit/integration/tests/Story_Post_Type.php
  tests/phpunit/shared/Private_Access.php
  tests/phpunit/unit/includes/ScriptHash.php
  tests/phpunit/unit/tests/AMP/Meta_Sanitizer.php
  tests/phpunit/unit/tests/AMP/Story_Sanitizer.php
  tests/phpunit/unit/tests/Decoder.php
  tests/phpunit/unit/tests/Shopping/Mock_Product.php
  tests/phpunit/unit/tests/Shopping/WooCommerce_Query.php
Labels: Type: Infrastructure, Type: Code Quality, Pod: WP

#12911 PHPCS: Enable `RequireNumericLiteralSeparator` rule
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Link_Controller.php
  phpcs.xml.dist
  tests/phpunit/integration/tests/Admin/Admin.php
  tests/phpunit/integration/tests/Analytics.php
  tests/phpunit/integration/tests/Integrations/Jetpack.php
  tests/phpunit/integration/tests/Shortcode/Stories_Shortcode.php
Labels: Type: Infrastructure, Type: Code Quality, Pod: WP

#12760 Code Quality: Force import of functions / classes
  includes/templates/admin/dashboard.php
  includes/templates/admin/edit-story.php
  includes/templates/admin/experiments.php
  phpcs.xml.dist
  tests/phpunit/integration/includes/Capabilities_Setup.php
  tests/phpunit/integration/includes/Kses_Setup.php
  tests/phpunit/integration/tests/AMP/Sanitization.php
  tests/phpunit/integration/tests/AdSense.php
  tests/phpunit/integration/tests/Ad_Manager.php
  tests/phpunit/integration/tests/Admin/Admin.php
  tests/phpunit/integration/tests/Admin/Cross_Origin_Isolation.php
  tests/phpunit/integration/tests/Admin/Customizer.php
  tests/phpunit/integration/tests/Admin/Dashboard.php
  tests/phpunit/integration/tests/Admin/Editor.php
  tests/phpunit/integration/tests/Admin/Meta_Boxes.php
  tests/phpunit/integration/tests/Admin/Site_Health.php
  tests/phpunit/integration/tests/Context.php
  tests/phpunit/integration/tests/Discovery.php
  tests/phpunit/integration/tests/Experiments.php
  tests/phpunit/integration/tests/Integrations/Conditional_Featured_Image.php
  tests/phpunit/integration/tests/Integrations/Jetpack.php
  tests/phpunit/integration/tests/Media/SVG.php
  tests/phpunit/integration/tests/Migrations/Remove_Broken_Text_Styles.php
  tests/phpunit/integration/tests/Migrations/Remove_Unneeded_Attachment_Meta.php
  tests/phpunit/integration/tests/Migrations/Replace_Conic_Style_Presets.php
  tests/phpunit/integration/tests/Migrations/Set_Legacy_Analytics_Usage_Flag.php
  tests/phpunit/integration/tests/Migrations/Unify_Color_Presets.php
  tests/phpunit/integration/tests/Migrations/Update_Publisher_Logos.php
  tests/phpunit/integration/tests/Model/Story.php
  tests/phpunit/integration/tests/REST_API/Embed_Controller.php
  tests/phpunit/integration/tests/Renderer/Stories/Generic_Renderer.php
  tests/phpunit/integration/tests/Renderer/Stories/Renderer.php
  tests/phpunit/integration/tests/Renderer/Story/Embed.php
  tests/phpunit/integration/tests/Renderer/Story/Image.php
  tests/phpunit/integration/tests/Shopping/Product_Meta.php
  tests/phpunit/integration/tests/Story_Post_Type.php
  tests/phpunit/integration/tests/Taxonomy/Taxonomy_Base.php
  tests/phpunit/integration/tests/Tracking.php
  tests/phpunit/integration/tests/User/Capabilities.php
  tests/phpunit/unit/tests/AMP/Meta_Sanitizer.php
  tests/phpunit/unit/tests/Shopping/WooCommerce_Query.php
  uninstall.php
  web-stories.php
Labels: Type: Code Quality

#12950 Fixed `*.tsx` tests
  packages/animation/src/components/test/WAAPIWrapper.tsx
  packages/animation/src/components/test/animationProvider.tsx
  packages/rich-text/src/formatters/test/color.tsx
  packages/rich-text/src/formatters/test/italic.tsx
  packages/rich-text/src/formatters/test/underline.tsx
  packages/rich-text/src/formatters/test/uppercase.tsx
  packages/rich-text/src/formatters/test/weight.tsx
  tests/js/jest.config.js
  tests/js/setup-globals.js
Labels: Type: Code Quality, Pod: Prometheus

#12935 E2E Tests: Disable access to remote block directory and patterns
  bin/local-env/docker-compose.yml
  bin/local-env/install-wordpress.sh
  includes/Media/SVG.php
  includes/namespace.php
  packages/e2e-tests/src/jest.config.js
  packages/e2e-tests/src/plugins/disable-block-directory.php
  packages/e2e-tests/src/specs/editor/backgroundAudio.js
  packages/e2e-tests/src/specs/editor/fontCheck.js
  packages/e2e-tests/src/specs/wordpress/blockWidget.js
Labels: Type: Infrastructure, Group: WordPress, Pod: WP, Package: E2E Tests

#12952 Fix issues with package bundling
  .eslintrc
  .gitignore
  package-lock.json
  packages/date/src/getOptions.ts
  packages/date/src/settings.ts
  packages/date/src/third_party/buildLocalizeFn.ts
  packages/date/src/typings/date-fns/index.d.ts
  packages/story-editor/package.json
  packages/story-editor/src/app/media/utils/useFFmpeg.ts
  packages/story-editor/src/components/colorPicker/currentColorPicker.js
  packages/story-editor/src/components/colorPicker/editablePreview.js
  packages/story-editor/src/components/form/color/colorInput.js
  rollup.config.js
Labels: Type: Infrastructure, Type: Code Quality, Pod: WP

#12949 Code Quality: Remove all `defaultProps` usage
  packages/design-system/src/components/circularProgress/index.js
  packages/design-system/src/components/contextMenu/styled.js
  packages/design-system/src/components/dialog/index.js
  packages/design-system/src/components/snackbar/snackbarContainer.js
  packages/design-system/src/components/snackbar/snackbarMessage.js
  packages/design-system/src/components/typography/display/index.js
  packages/design-system/src/components/typography/headline/index.js
  packages/design-system/src/components/typography/link/index.js
  packages/design-system/src/components/typography/text/index.js
  packages/stories-block/src/block/block-types/single-story/embedPlaceholder.js
  packages/story-editor/src/components/colorPicker/currentColorPicker.js
  packages/story-editor/src/components/colorPicker/editablePreview.js
  packages/story-editor/src/components/form/textArea.js
  packages/story-editor/src/components/library/panes/media/common/mediaElement.js
  packages/story-editor/src/components/library/panes/media/common/mediaGallery.js
  packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js
  packages/story-editor/src/components/library/panes/shared/virtualizedPanelGrid/components.js
  packages/story-editor/src/components/panels/panel/shared/content.js
  packages/story-editor/src/components/panels/panel/shared/handle.js
  packages/story-editor/src/components/panels/panel/shared/title.js
  packages/story-editor/src/components/uploadDropTarget/dropTarget.js
  packages/wp-dashboard/src/components/editorSettings/archive/index.js
Labels: P2, Type: Code Quality, Pod: WP, Fixit

#12868 Fixed template layer order
  packages/animation/src/components/provider.tsx
  packages/migration/src/migrate.ts
  packages/migration/src/migrations/test/v0047_fixBrokenTemplates.js
  packages/migration/src/migrations/v0047_fixBrokenTemplates.ts
  packages/templates/src/raw/a-day-in-the-life/template.json
  packages/templates/src/raw/ace-hotel-kyoto-review/template.json
  packages/templates/src/raw/all-about-cars/template.json
  packages/templates/src/raw/almodos-films/template.json
  packages/templates/src/raw/baking-bread-guide/template.json
  packages/templates/src/raw/belly-fat-workout/template.json
  packages/templates/src/raw/celebrity-q-and-a/template.json
  packages/templates/src/raw/doers-get-more-done/template.json
  packages/templates/src/raw/elegant-travel-itinerary/template.json
  packages/templates/src/raw/experience-thailand/template.json
  packages/templates/src/raw/fashion-inspiration/template.json
  packages/templates/src/raw/fashion-on-the-go/template.json
  packages/templates/src/raw/food-and-stuff/template.json
  packages/templates/src/raw/fresh-and-bright/template.json
  packages/templates/src/raw/how-video-calls-saved-the-day/template.json
  packages/templates/src/raw/indoor-garden-oasis/template.json
  packages/templates/src/raw/kitchen-stories/template.json
  packages/templates/src/raw/los-angeles-city-guide/template.json
  packages/templates/src/raw/no-days-off/template.json
  packages/templates/src/raw/plant-based-dyes/template.json
  packages/templates/src/raw/sangria-artichoke/template.json
  packages/templates/src/raw/self-care-guide/template.json
  packages/templates/src/raw/skin-care-at-home/template.json
  packages/templates/src/raw/sleep/template.json
  packages/templates/src/raw/street-style-on-the-go/template.json
  packages/templates/src/raw/summer-adventure-guide/template.json
  packages/templates/src/raw/summer-fashion-collection/template.json
  packages/templates/src/raw/tv-show-recap/template.json
  packages/templates/src/raw/ultimate-comparison/template.json
  packages/templates/src/raw/weekly-entertainment/template.json
  packages/templates/src/test/getTemplates.js
Labels: Type: Bug, Pod: Prometheus

#12974 PHP: Add some code comments for future reference
  includes/Admin/ImgAreaSelect_Patch.php
  includes/REST_API/Font_Controller.php
  includes/REST_API/Publisher_Logos_Controller.php
  includes/REST_API/Stories_Autosaves_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/REST_API/Stories_Lock_Controller.php
  includes/REST_API/Stories_Media_Controller.php
  includes/namespace.php
Labels: PHP, Type: Code Quality, Pod: WP

#12954 Code Quality: Dynamically import mediainfo.js
  includes/Admin/Editor.php
  packages/story-editor/src/app/media/utils/test/useMediaInfo.tsx
  packages/story-editor/src/app/media/utils/useMediaInfo.ts
  packages/story-editor/tsconfig.json
  webpack.config.cjs
Labels: Group: Media, Type: Performance, Type: Code Quality, Pod: WP, Package: Story Editor

#12981 Code quality: Refactor `useQuickActions`
  packages/story-editor/src/app/quickActions/index.js
  packages/story-editor/src/app/quickActions/mediaPicker.js
  packages/story-editor/src/app/quickActions/test/useQuickActions.js
  packages/story-editor/src/app/quickActions/useElementReset.js
  packages/story-editor/src/app/quickActions/useForegroundActions.js
  packages/story-editor/src/app/quickActions/useMediaActions.js
  packages/story-editor/src/app/quickActions/useQuickActions.js
  packages/story-editor/src/app/quickActions/useTextActions.js
Labels: Type: Code Quality, Pod: Prometheus
