Repository GoogleForCreators/web-stories-wp, pull requests merged in 2024-03, with the labels that each got.

#13602 Blocks: Fix box carousel layout on mobile devices
  packages/stories-block/src/css/views/carousel.css
  packages/stories-carousel/src/index.js
Labels: Type: Bug, Group: WordPress, Group: Blocks

#13601 Guide for enabling shopping in third party integration
  docs/third-party-integration/story-editor/integration-layer.md
Labels: Type: Documentation

#13566 Canvas: Fix broken zoom behaviour
  packages/story-editor/src/components/canvas/layout.js
Labels: Type: Bug, Group: Canvas, P3
