Repository GoogleForCreators/web-stories-wp, pull requests merged in 2024-06, with the labels that each got.

#13721 Env: Use `mariadb` executable instead of `mysql`
  bin/local-env/includes.sh
Labels: Type: Infrastructure

#13724 Remove manual AMP runtime check from tests
  packages/jest-amp/src/utils.js
Labels: Type: Infrastructure, Package: Jest AMP

#13725 Remove `rel="noopener"` from all links
  includes/Admin/PluginRowMeta.php
  packages/story-editor/src/components/helpCenter/quickTip/index.js
  packages/story-editor/src/components/hotlinkModal/utils.js
  packages/story-editor/src/components/panels/document/slug/slug.js
  packages/story-editor/src/components/panels/shared/linkRelations.js
  packages/wp-story-editor/src/components/corsCheck/corsCheckFailed.js
  packages/wp-story-editor/src/components/documentPane/publish/publish.js
  packages/wp-story-editor/src/components/postPublishDialog/index.js
  packages/wp-story-editor/src/components/statusCheck/statusCheckFailed.js
  tests/phpunit/integration/tests/Admin/PluginRowMeta.php
Labels: Type: Code Quality

#13728 Add blueprint for Live Preview on WordPress.org
  .wordpress-org/blueprints/blueprint.json
Labels: Type: Task

#13729 Consolidate AMP sanitization
  bin/install-wp-tests.sh
  includes/AMP/Sanitization.php
  includes/KSES.php
  tests/phpunit/integration/data/story_post_content_sanitized.html
  tests/phpunit/integration/tests/KSES.php
  tests/phpunit/integration/tests/REST_API/Stories_Autosaves_Controller.php
  tests/phpunit/integration/tests/REST_API/Stories_Controller.php
Labels: Type: Enhancement

#13731 Bump WP version requirement to 6.4
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit-php.yml
  includes/Settings.php
  includes/Shopping/Product_Meta.php
  includes/Story_Post_Type.php
  includes/Taxonomy/Category_Taxonomy.php
  phpcs.xml.dist
  readme.txt
  web-stories.php
Labels: Type: Task, Group: WordPress, Type: Code Quality

#13509 PHPStan: re-enable `bleedingEdge` option
  includes/Admin/Customizer.php
  includes/Infrastructure/Injector/SimpleInjector.php
  includes/Infrastructure/ServiceBasedPlugin.php
  includes/Integrations/AMP.php
  includes/Integrations/Jetpack.php
  includes/Integrations/Site_Kit.php
  includes/KSES.php
  includes/Media/Media_Source_Taxonomy.php
  includes/Media/Types.php
  includes/Plugin.php
  includes/REST_API/Embed_Controller.php
  includes/REST_API/Font_Controller.php
  includes/REST_API/Hotlinking_Controller.php
  includes/REST_API/Link_Controller.php
  includes/REST_API/Products_Controller.php
  includes/REST_API/Status_Check_Controller.php
  includes/REST_API/Stories_Autosaves_Controller.php
  includes/REST_API/Stories_Base_Controller.php
  includes/REST_API/Stories_Controller.php
  includes/REST_API/Stories_Lock_Controller.php
  includes/REST_API/Stories_Media_Controller.php
  includes/REST_API/Stories_Taxonomies_Controller.php
  includes/Tracking.php
  includes/User/Capabilities.php
  includes/templates/frontend/single-web-story.php
  phpstan.neon.dist
  tests/phpunit/integration/tests/Infrastructure/LazilyInstantiatedServiceTest.php
  tests/phpunit/integration/tests/Infrastructure/ServiceBasedPluginTest.php
  tests/phpunit/integration/tests/Infrastructure/SimpleInjectorTest.php
  tests/phpunit/integration/tests/REST_API/Stories_Controller.php
Labels: Type: Code Quality

#13732 WordPress 6.6 Compatibility
  .github/workflows/tests-e2e.yml
  packages/e2e-test-utils/src/publishPost.js
  packages/e2e-tests/src/config/bootstrap.js
  readme.txt
Labels: Type: Task, Group: WordPress, Type: Code Quality
