Repository GoogleForCreators/web-stories-wp, pull requests merged in 2024-05, with the labels that each got.

#13617 Require WordPress 6.3 or newer
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit-php.yml
  composer.lock
  phpcs.xml.dist
  readme.txt
  tests/phpstan/bootstrap.php
  web-stories.php
Labels: Type: Enhancement

#13700 Settings: Prime options to reduce database queries
  includes/Admin/Customizer.php
  includes/Admin/Dashboard.php
  includes/Integrations/Core_Themes_Support.php
  includes/Integrations/Site_Kit.php
  includes/Settings.php
  includes/Story_Post_Type.php
  includes/Tracking.php
  tests/phpunit/integration/tests/Integrations/Site_Kit.php
  tests/phpunit/integration/tests/Tracking.php
Labels: Type: Enhancement, Type: Performance

#13619 Add oxlint in addition to ESLint
  .eslintrc
  package-lock.json
  package.json
  packages/dashboard/src/components/cardGrid/stories/index.js
  packages/design-system/src/components/infiniteScroller/stories/index.js
  packages/design-system/src/components/loadingSpinner/loadingSpinner.tsx
  packages/design-system/src/theme/stories/index.js
  packages/output/src/components/withLink/index.tsx
  packages/story-editor/src/components/canvas/mediaCaptions/cue.js
  packages/story-editor/src/components/header/buttons/preview.js
  packages/story-editor/src/components/header/buttons/test/preview.js
  packages/story-editor/src/components/library/panes/media/media3p/karma/mediaFetching.karma.js
Labels: Type: Infrastructure, Type: Performance, Type: Code Quality
