Repository GoogleForCreators/web-stories-wp, pull requests merged in 2025-03, with the labels that each got.

#13704 Use Interactivity API for frontend functionality
  .phpstorm.config.js
  blocks/embed/block.json
  includes/Renderer/Stories/Carousel_Renderer.php
  includes/Renderer/Stories/Generic_Renderer.php
  includes/Renderer/Stories/Renderer.php
  includes/Renderer/Story/Embed.php
  includes/Renderer/Story/Singleton.php
  package-lock.json
  packages/stories-block/package.json
  packages/stories-block/src/css/singleton.css
  packages/stories-block/src/view.ts
  packages/stories-block/tsconfig.json
  packages/stories-lightbox/README.md
  packages/stories-lightbox/package.json
  packages/stories-lightbox/src/index.js
  packages/stories-lightbox/src/web-stories-lightbox.js
  tests/phpunit/integration/tests/Media/Types.php
  tests/phpunit/integration/tests/Renderer/Stories/Carousel_Renderer.php
  tests/phpunit/integration/tests/Renderer/Stories/Generic_Renderer.php
  tsconfig.json
  webpack.config.cjs
Labels: Type: Enhancement, Status: Blocked, Type: Performance, Group: Blocks

#14030 Block: Improve carousel UX
  .eslintrc
  babel.config.cjs
  includes/Assets.php
  includes/Renderer/Stories/Carousel_Renderer.php
  package-lock.json
  packages/glider/package.json
  packages/glider/src/index.ts
  packages/glider/tsconfig.json
  packages/stories-block/src/block/block-types/latest-stories/edit.js
  packages/stories-block/src/block/components/storiesInspectorControls.js
  packages/stories-block/src/block/components/storiesPreview.js
  packages/stories-block/src/block/components/storyPicker/selectStories.js
  packages/stories-block/src/css/views/carousel.css
  packages/stories-carousel/package.json
  packages/stories-carousel/src/@types/global.d.ts
  packages/stories-carousel/src/index.js
  packages/stories-carousel/src/index.ts
  packages/stories-carousel/tsconfig.json
  patches/@types+glider-js+1.7.11.patch
  tests/phpunit/integration/tests/Renderer/Stories/Carousel_Renderer.php
  tsconfig.json
  webpack.config.cjs
Labels: Type: Enhancement, Type: Performance, Group: Blocks

#14066 Block: minor bug fixes for WP 6.8
  packages/stories-block/src/block/block-types/single-story/embedControls.js
  packages/stories-block/src/block/block-types/single-story/embedControlsInLoop.js
  packages/stories-block/src/block/components/storiesInspectorControls.js
  packages/stories-block/src/block/components/storyPicker/selectStories.js
  patches/@types+glider-js+1.7.12.patch
Labels: Type: Bug, Group: WordPress, Group: Blocks

#14072 Patch `thecodingmachine/safe` for PHP 8.4
  composer.json
  composer.lock
  patches/thecodingmachine-safe-nullable.diff
Labels: Type: Infrastructure
